### ISSUE TITLE
SO_REUSEADDR and SO_REUSEPORT options can not work on linux

### ISSUE THREAD

**Issue by avriltank** [peachpiecompiler/peachpie#1005]
```php
<?php

function main()
{
    //this can  not work when linux open two progress
    $opts = [
        'socket'=>[
            'SO_REUSEPORT'=>1,
            'SO_REUSEADDR'=>1,
        ]
    ];
    $context = stream_context_create($opts);
    //stream_context_set_option($context, 'socket', 'SO_REUSEPORT', 1);
    //this can  not work when linux open two progress
    //stream_context_set_option($context, 'socket', 'SO_REUSEADDR', 1);
    //this can  not work when linux open two progress
    $socket = stream_socket_server("tcp://0.0.0.0:5004", $errno, $errstr,\STREAM_SERVER_BIND | \STREAM_SERVER_LISTEN,$context);
    //$socket1 = \socket_import_stream($socket);
    //socket_set_option($socket1,SOL_SOCKET,SO_REUSEADDR,1);
    //socket_set_option($socket1,SOL_SOCKET,SO_REUSEPORT,1);
    if (!$socket) {
      echo "$errstr ($errno)<br />\n";
    } else {
      while ($conn = stream_socket_accept($socket)) {
          echo 'zhou';
        fwrite($conn, 'The local time is ' . date('n/j/Y g:i a') . "\n");
        fclose($conn);
      }
      fclose($socket);
    }
}

main();

```

**Comment by jakubmisek** [comment]
thank you for the issue, do you have any comments on this?

what is the actual and expected result please?

**Comment by avriltank** [comment]
terminal report message:Address already in use (98)<br />,the c# code of SOCKET_REUSEADDR option can work on linux well.But peachpie code can not work well!
![reuse](https://user-images.githubusercontent.com/13652682/146770806-e9145caa-a025-48ef-8b53-dea95ab02257.png)

**Comment by avriltank** [comment]
When the SO_REUSEADDR or SO_REUSEPORT option is used, when two identical programs are opened in two terminals of the Linux system, they should work at the same time. When the socket client is connected to port 5004, the operating system allocates the process to handle the connection! This mode is a little similar to the working principle of nginx!

**Comment by jakubmisek** [comment]
thanks! you're right, the options weren't actually used at all;

`socket_set_option` should work tho?

**Comment by jakubmisek** [comment]
according to the docs, those should be the possible values
https://www.php.net/manual/en/context.socket.php

I'm not sure about the "SO_REUSEPORT" option?

**Comment by avriltank** [comment]
Yes,you are right they are lower case!

**Comment by avriltank** [comment]
I try all uppercase or lowercase code they don't work! The above code I forget to edit

**Comment by jakubmisek** [comment]
casing doesn't matter. 

I just cannot find a way of setting "SO_REUSEPORT" in C#;

**Comment by avriltank** [comment]
yes!c#  only has "SO_REUSEADDR”,but only this option can work on linux well

**Comment by jakubmisek** [comment]
alright then, thanks!

The https://github.com/peachpiecompiler/peachpie/commit/fd461dcb004df7d84be53252c300c4d882b81efd implements this, please feel free to try and let me know

**Comment by avriltank** [comment]
ok!Thanks very much!I will try it after the new Appveyvor version of peachpie builded!

**Comment by avriltank** [comment]
fix it well!

**Comment by jakubmisek** [comment]
thank you!
