### ISSUE TITLE
is there any plan to implement pcntl and posix extensions of php

### ISSUE THREAD

**Issue by avriltank** [peachpiecompiler/peachpie#1006]
Hello, do peachpie have any plans to implement pctl and POSIX extensions? I originally had an [amphp ](https://github.com/amphp/amp)project based on PHP libevent extension. I basically migrated all the code to peachpie, except pctl and POSIX extension If I use ["mono. POSIX"](https://github.com/mono/mono.posix), I find that I can quickly implement these two extensions in peachpie. I haven't tried to extend PHP with Csharp. If possible, I'm willing to try to implement it, but I haven't learned CSharp for a long time, and the code quality should be very poor!

**Comment by jakubmisek** [comment]
Hi,

PeachPie already implements some PHP functions using Mono.Posix. Pctl or other Posix functions were not needed yet; do you have a list of what is needed?

**Comment by avriltank** [comment]
I found that Mono.Posix has disabled fork. I guess his author should consider that many APIs are thread related, so we directly disable the fork function of libc. However, in the current ecosystem of PHP, there are many multi process + fiber schemes, and this architecture model is also more convenient for daemon + multiple worker processes

**Comment by jakubmisek** [comment]
But what specifically requires "Mono.Posix" to be used. .NET has intense threading API's included so we can use that.

Anyways; do you have a list of PHP extensions/functions/classes you miss in PeachPie?

**Comment by avriltank** [comment]
All functions of [pcntl](https://www.php.net/manual/en/book.pcntl.phpl) and all functions of [posix](https://www.php.net/manual/zh/book.posix.php),we can use llibuv instead of libevent.

**Comment by jakubmisek** [comment]
thanks! we don't have plans for that, but I can create a branch here on GitHub, create a few empty function stubs, and help with the implementation.

**Comment by avriltank** [comment]
Very  nice!thanks  for  your  reply
