### ISSUE TITLE
Why in Visual Studio WebProject Still Uses 1.0.6 version & Different Targateframework version on csproj and msbuildproj

### ISSUE THREAD

**Issue by BKSoftCraft** [peachpiecompiler/peachpie#1008]
```  C#
//   Server.csproj  //
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>                                        <--- Framework 5.0
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Peachpie.AspNetCore.Web" Version="1.0.6" />           <---Old Version
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test55\Test55.msbuildproj">
      <PrivateAssets>None</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

</Project>

//  msbuildproj //
<Project Sdk="Peachpie.NET.Sdk/1.0.6">                                               <---Old Version

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>                                <---Framework 2.1
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php;**/*.phar;" Exclude="$(DefaultExcludeItems)" />
  </ItemGroup>

</Project>
```

**Comment by BKSoftCraft** [comment]
- Is this problem on myside & I have to change it manually  to latest version

- Is this Due to Extension of Peachpie

**Comment by avriltank** [comment]
You can change the latest version!I use the latest version

**Comment by BKSoftCraft** [comment]
> You can change the latest version!I use the latest version

And What About TargetFramework,
Do I use net5.0 at both place

**Comment by avriltank** [comment]
yes,you can

**Comment by avriltank** [comment]
I use net6 and peachpie 1.0.9,they work well

**Comment by BKSoftCraft** [comment]
Ok, Thanks For Reply

**Comment by jakubmisek** [comment]
The `.msbuildproj` is a library assembly, hence it targets `.netstandard` which makes it usable as a reference to .NET Core 3 and 5 and 6 project, and also .NET Framework 4.7.2 projects.

The server project is an executable, hence it targets `net5`, and can be safely changed to `net6` as well.

The version `1.0.6` can be updated, it's just that the extension for Visual Studio has not yet been updated.

**Comment by jakubmisek** [comment]
we have updated the extension to create projects with peachpie v1.0.9 by default (https://marketplace.visualstudio.com/items?itemName=iolevel.peachpie-vs)

thanks!

**Comment by BKSoftCraft** [comment]
Thanks.
