### ISSUE TITLE
High CPU consumption when use fread<--PhpStream.GetValid(handle)

### ISSUE THREAD

**Issue by avriltank** [peachpiecompiler/peachpie#1013]
![highcpu](https://user-images.githubusercontent.com/13652682/148871408-b28b19e7-5944-4f0b-9682-12c53761ce4b.png)
the function 'fread' for socket stream make High CPU consumption when i use some Performance pressure test

**Comment by jakubmisek** [comment]
thank you for the issue;

This seems weird. This function basically does not do anything

https://github.com/peachpiecompiler/peachpie/blob/81e4cbe568dd7cc9d1df35e2e4a05fde654c1e48/src/Peachpie.Library/Streams/PhpStream.cs#L2017

**Comment by avriltank** [comment]
It happens only on windows.Any way peachpie can run my old project perfectly now,thanks!

**Comment by avriltank** [comment]
This error is because the function feof($socket) always return false!This behavior is diffrent from php,[the code](https://github.com/peachpiecompiler/peachpie/blob/d4ba61e3fdda019143af6a608ab31021b7cd1b1e/src/Peachpie.Library/Streams/SocketStream.cs#L176).

**Comment by avriltank** [comment]
j
