### ISSUE TITLE
Need help with ‍WPDOTNET_HOTPLUG_ENABLE‍‍ property

### ISSUE THREAD

**Issue by amira133** [peachpiecompiler/peachpie#1020]
The description of `WPDOTNET_HOTPLUG_ENABLE`  in this [address  ](https://docs.peachpie.io/scenarios/wordpress/configuration/#extra-settings) is ambiguous. You may explain more.
If `WPDOTNET_HOTPLUG_ENABLE ` is equal to 1 , effectively disallows downloading plugins from the dashboard Or if it is 0?
Also how do I set this utility in ConfigureServices?

thanks

**Comment by jakubmisek** [comment]
moved to https://github.com/iolevel/wpdotnet-sdk/issues/119
