### ISSUE TITLE
"freads fgets" are also blocked when the filehandle or socket has been seted to non blocked mode

### ISSUE THREAD

**Issue by avriltank** [peachpiecompiler/peachpie#1028]
when we set the non blocked mode of  socket or file,"freads fgets" function should return soon

**Comment by jakubmisek** [comment]
thanks,

this should be handled in https://github.com/peachpiecompiler/peachpie/blob/2e45f503bef5da4bbc87dc84f39d64c0ff212f65/src/Peachpie.Library/Streams/SocketStream.cs#L109 , if you see what may the problem?

**Comment by avriltank** [comment]
In my project,I use one csharp libary,that lib code change the block mode
