### ISSUE TITLE
FPDF image not printing

### ISSUE THREAD

**Issue by BKSoftCraft** [peachpiecompiler/peachpie#1032]
````php
<?php
require('fpdf/fpdf.php');

class PDF extends FPDF
{
// Page header
function Header()
{
    // Logo
    $this->Image('logo.png',10,6,30);       //  Use any file name with logo.png as logo file
    // Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(80);
    // Title
    $this->Cell(30,10,'Title',1,0,'C');
    // Line break
    $this->Ln(20);
}

// Page footer
function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Page number
    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
}
}

// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Times','',12);
for($i=1;$i<=40;$i++)
    $pdf->Cell(0,10,'Printing line number '.$i,0,1);
$pdf->Output();
?>

// Why Logo Not Printing ?

**Comment by BKSoftCraft** [comment]
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/ - -
warn: Microsoft.AspNetCore.Session.SessionMiddleware[7]
      Error unprotecting the session cookie.
      System.Security.Cryptography.CryptographicException: The payload was invalid.
         at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/ - - - 200 - application/pdf 1312.4480ms

**Comment by BKSoftCraft** [comment]
Above Comment is displayed in console while executing the script

> ```
> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
>       Request starting HTTP/2 GET https://localhost:5001/ - -
> warn: Microsoft.AspNetCore.Session.SessionMiddleware[7]
>       Error unprotecting the session cookie.
>       System.Security.Cryptography.CryptographicException: The payload was invalid.
>          at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
>          at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
>          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
>          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
>          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
>          at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished HTTP/2 GET https://localhost:5001/ - - - 200 - application/pdf 1312.4480ms
> ```

This is display in console while running project

**Comment by jakubmisek** [comment]
Thank you @BKSoftCraft !

May I ask for a .zip with the test project?

**Comment by BKSoftCraft** [comment]
yes definetly, i upload in few minutes

**Comment by jakubmisek** [comment]
from the stack trace:
```
warn: Microsoft.AspNetCore.Session.SessionMiddleware[7]
      Error unprotecting the session cookie.
      System.Security.Cryptography.CryptographicException: The payload was invalid.
```
I would guess it is more related to aspnet rather than PeachPie?

**Comment by BKSoftCraft** [comment]
this is test project data for fpdf image not printing issue
[fpdf_image.zip](https://github.com/peachpiecompiler/peachpie/files/9739477/fpdf_image.zip)

**Comment by jakubmisek** [comment]
do you have the .NET project that was failing ?

**Comment by BKSoftCraft** [comment]
Sorry, Right now i only have this data.
May be i can send it tomorrow !

**Comment by jakubmisek** [comment]
> Sorry, Right now i only have this data. May be i can send it tomorrow !

thank you :)

**Comment by BKSoftCraft** [comment]
this is test repo for issue
https://github.com/BKSoftCraft/imageTest

Sorry i forgot it :)

**Comment by jakubmisek** [comment]
there seem to be some issues with string encodings; the .png file is not read properly :/

**Comment by jakubmisek** [comment]
`.jpg` works though!
