### ISSUE TITLE
Function is_callable(string) always returns true

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#104]
`is_callable` does not check if the callback represents an existing callable at all. Always returns `true`.

Test case:
```php
<?php
echo (int)is_callable("foo");
```

Expected: 0
Actual: 1

**Comment by jakubmisek** [comment]
fixd in https://github.com/peachpiecompiler/peachpie/commit/ea475c6e77fb9882b0ba9fbc254b51673b963044
