### ISSUE TITLE
no matching .ctor

### ISSUE THREAD

**Issue by xiangyi-wang** [peachpiecompiler/peachpie#1046]
I compiled flarum core successfully before（Peachpie.NET.Sdk/1.0.12 ）[#1015 ](url), and now the following errors are reported in version 1.0.18 
![image](https://user-images.githubusercontent.com/22881957/155083407-92b15f1b-5645-4615-871b-f0fdbf529bf2.png)

**Comment by jakubmisek** [comment]
thanks, it seems like a totally different issue.

Looking at the source code: https://github.com/peachpiecompiler/peachpie/blob/54e8e0c600cc5c581b8f274c517a8002aa0d153c/src/Peachpie.CodeAnalysis/Symbols/Source/SourceCustomAttribute.cs#L63

there are probably two issues:

- [ ] the exception lacks more details
- [ ] there is a PHP 8 attribute in the Flarum source code which PeachPie can't match with its constructor arguments

We'll add more details into the exception.
