### ISSUE TITLE
Helping in currently-not-implemented libraries

### ISSUE THREAD

**Issue by hadi77ir** [peachpiecompiler/peachpie#107]
Hi, 
I want to help you in development, I saw your roadmap and saw that there are some libraries that haven't been implemented yet and decided to work on those.

May I use P/Invoke in implementation?
May I use external libraries in implementing these?
Or they must be pure C# and implemented totally by myself?

**Comment by jakubmisek** [comment]
Hi,

That's great! 

Libraries must be targeting `netstandard1.6` or `netstandard2.0` which means they have to be pure C#, without unsafe code and without P/Invoke.

External libraries in form of a NuGet package reference are allowed. We use for example `ImageSharp` or `HtmlAgilityPack`

**Comment by hadi77ir** [comment]
Great.
I've read your guidelines, so I "think" if I rewrite libmagic in C#, I have to make it a NuGet package in order to use it in Pchp as it states 

> The contribution is your own original work and does not infringe any copyrights.

and

> You license the contribution under the terms applied to the rest of the Peachpie project.

and since a rewrite is a derivative work, it can't be included directly in project. 😀 
I will rewrite those libraries (targeting `netstandard`) and publish them on NuGet.
Then write a wrapper for Pchp. I think this way I won't cross the red-lines.

**Comment by jakubmisek** [comment]
Yes. Also that is the correct approach I guess - create a C# library and then a lightweight wrapper for Peachpie that uses the library.

**Comment by hadi77ir** [comment]
So I close the issue, as the problem is solved. :)
