### ISSUE TITLE
Is peachpie-web ready for netcore 2.0?

### ISSUE THREAD

**Issue by dotChrisSharp** [peachpiecompiler/peachpie#108]
Hello Peachpie team, 

first of all want to thank you that you bring PHP to the .NET World. You did great work. I was very happy to read your blog https://www.peachpie.io/2017/11/php-netstandard-2-0.html and so I took my Fedora netbook and though "try it out.". I took one of my older peachpie project solution (bases on the 0.7 templates / which i tried under windows 10), bring it to my Fedora and changed the versions from ASP.NET Core 1.1.0 to 2.0 and the peachpie packages from 0.7.0 to 0.8.0.  The build worked fine but there was a runtime error when starting the ASP.NET Core server. Usual I use dotnet run -p ./XYZ.server/XYZ.server.csproj to start the peachpie app and before it always worked. 
- Error 
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
thrown at Pchp.Core.Context.get_GlobalServices() at peachpie.Library.PDO.PDODriver.RegisterAllDrivers()

- Guess 
Maybe I did some mistakes in project file. It seems I selected a wrong Version of package or bad combination. 
- question 
Is my guess correct theoretically and is peachpie-web ready for .NET Core 2.0? :) just curious because console application and lib seems to work fine with .NET Core 2.0 on Fedora. So it must be the C# Server. 
- desired Christmas gift / wish for future ;) 
peachpie Web example could be modified for net core 2.0 so we peachpie fans can enjoy ASP.NET Core 2.0 based webservers. ;)

This issue is just a question and wish - no bug detection. By the way : great work with wordpress on .NET. impressive. 👍

**Comment by zyxyL** [comment]
I'm trying it out on Ubuntu 17.10 (with .net core 2.0.3) and running into similar issues as well.

@dotChrisSharp  are you following this sample web project... ?  https://github.com/iolevel/peachpie-samples/tree/master/web-application
@jakubmisek just updated it to .netcore 2.0 around the time you posted this question.  I noticed that the targetframework has been upgraded to "netcoreapp2.0" but still references AspNetCore 1.1.x packages.  I'm still trying to wrap my head around netcore2 stuff so maybe that is expected?

If I reference the AspNetCore 2.x packages in the server.csproj then I get the same BuildServiceProvider runtime error you posted.  

If I reference the 1.1.x AspNetCore packages (like the sample project does), then it gives me a "Unable to load DLL 'libuv'" runtime error.  But I have Kestrel running fine from a different netcore2 project (non-PeachPie) so it's not *just* that it can't find libuv.

**Comment by dotChrisSharp** [comment]
@zyxyL actual what I did was about the following : 
- install .NET Core SDK 2.0.3 on Fedora 27 
- install template by "dotnet new -i Peachpie.Templates::*"
- mkdir ./myWebside
- cd ./myWebside 
- dotnet new peachpie-web 
- opened sln in Visual Studio Code 
- did changes in  the ASP.NET Core Project csproj file 
    1. upgrade "Microsoft.AspNetCore.Server.Kestrel" to 2.0.0
    2. upgrade "Microsoft.AspNetCore.Session" to 2.0.0
    3. upgrade "Microsoft.AspNetCore.StaticFiles" to 2.0.0
    4. upgrade "Peachpie.NETCore.Web" to 0.8.0-*
    5. removed "Microsoft.Extensions.Caching.Memory"
- did changes in PHP Project file (the msbuildproj) 
    1. upgrade "Peachpie.Compiler.Tools" to "0.8.0-*" 
    2. upgrade "Peachpie.NET.Sdk" to "0.8.0-*" 
- "dotnet build" in command line when at sln file level (in our folder system) --> works fine
-  "dotnet run -p ./myWebside.Server/myWebside.Server.csproj" in command line to run the server --> fail

**Comment by jakubmisek** [comment]
@dotChrisSharp Nice!

The `MissingMethodException` is the same as described at https://github.com/aspnet/EntityFrameworkCore/issues/8498 . We have to workaround it in `Peachpie.Runtime`.

The sample will be updated to reference the most recent version of Kestrel. For now, it runs on .NET Core 2.0, version of the Kestrel is not related to the version of .NET Core, that's another issue.

**Comment by jakubmisek** [comment]
In one of the dependency, they have changed signature of method from
`IServiceProvider BuildServiceProvider(this IServiceCollection services)` to
`ServiceProvider BuildServiceProvider(this IServiceCollection services)`

**Comment by jakubmisek** [comment]
Thanks again, closing the issue.

**Comment by dotChrisSharp** [comment]
@jakubmisek  thanks for this information. The funny thing is : this is exactly the URL I was looking yesterday but when saw it is in the Runtime - I was thinking "better tell developers and dont touch a running system". :D Awesome reaction. ;) Have a nice weekend. I will try it out on weekend.

**Comment by jakubmisek** [comment]
good! the latest preview `0.8.0-CI00500` fixes the issue, everything seems to work fine now (at least on Windows)

**Comment by zyxyL** [comment]
Things are good for Ubuntu Linux 17.10, .net core 2.0.3, thanks again for the recent updates.

**Comment by jakubmisek** [comment]
@zyxyL great! thanks : )
