### ISSUE TITLE
Addition of variable not giving perfect value () [Floating point error]

### ISSUE THREAD

**Issue by BKSoftCraft** [peachpiecompiler/peachpie#1096]
```php
<?php
$sum = 296.95 + 297.95 + 41.3;
echo $sum;      // Print Sum :636.1999999999999
// In Core PHP work fine
?>

**Comment by jakubmisek** [comment]
It's the exact opposite - PHP is not giving the exact value. It tries to hide the floating-point-number error implicitly.

If you use `debug_zval_dump($sum)` in PHP, you'd see the correct value.

We don't do this rounding inside `echo`.
