### ISSUE TITLE
Match parsing fails

### ISSUE THREAD

**Issue by feamsr00** [peachpiecompiler/peachpie#1098]
Hi There!

I'm exploring the port of an application to peachpie, but I'm seeing a lot of syntax error oddities, even though this supports PHP 8?

Example
``` php
		$ret = match ($number)
		{
			'10', #here
			'20'	=> 'another value'
		};
```
`(3,8): error PHP2014: Syntax error: unexpected token ','`

I believe I'm using the latest PP (whats the fastest way to double check the version?)

**Comment by jakubmisek** [comment]
Hi,

The version would be specified in your project file, and you'd see it as the first thing on the commandline when the build starts.

The unexpected "`,`" looks like a bug though

**Comment by jakubmisek** [comment]
the version is `1.0.6`, not sure why it installed an older version - I'll try that ..

Anyways, there is output with your version upon running `dotnet build`

**Comment by jakubmisek** [comment]
`match` syntax error fixed; new release will be prepared soon!
