### ISSUE TITLE
Help with solving the problem with the magic __get and __set

### ISSUE THREAD

**Issue by FibonacciFox** [peachpiecompiler/peachpie#1106]
There is a wrapper class, it is written to interact with Avalonia Ui components.
```cs
using System;
using System.Reflection;
using Pchp.Core;

namespace Peachpie.Avalonia.Experimental;

public class BaseWrapper<T> where T : new()
{
    public T GetWrappedObject()
    {
        return _wrappedObject;
    }
    
    public PhpValue __get(PhpValue propertyName)
    {
        return _getProperty(propertyName);
    }

    public void __set(PhpValue propertyName, PhpValue value)
    {
        _setProperty(propertyName, value);
    }
    
    private PropertyInfo GetWrappedProperty(PhpValue propertyName)
    {
        return _wrappedObject.GetType().GetProperty(propertyName.ToString());
    }

    private PhpValue _getProperty(PhpValue propertyName)
    {
        var property = GetWrappedProperty(propertyName);
        if (property != null) return PhpValue.FromClr(property.GetValue(_wrappedObject));

        throw new ArgumentException(
            $"Property '{propertyName}' not found on object of type '{_wrappedObject.GetType().Name}'");
    }

    private void _setProperty(PhpValue propertyName, PhpValue value)
    {
        var property = GetWrappedProperty(propertyName);
        if (property != null) 
            property.SetValue(_wrappedObject, value.ToClr());
        else
            throw new ArgumentException(
                $"Property '{propertyName}' not found on object of type '{_wrappedObject.GetType().Name}'");
    }

    private readonly T _wrappedObject = new();
}
```

```cs
using System;
using Avalonia;
using Pchp.Core;
using Peachpie.Avalonia.Experimental;

namespace Peachpie.Avalonia;

public class AvaloniaWrapper<T> : BaseWrapper<T> where T : AvaloniaObject, new()
{
    public void On(PhpValue eventName, Closure callback)
    {
        var eventInfo = GetWrappedObject().GetType().GetEvent(eventName.ToString());
        if (eventInfo != null)
        {
            eventInfo.AddEventHandler(GetWrappedObject(),
                CreateDelegate(eventInfo.EventHandlerType,
                    (_, e) => { callback.call(null, PhpValue.FromClass(GetWrappedObject()), PhpValue.FromClass(e)); }));
        }
        else
        {
            throw new ArgumentException(
                $"Event '{eventName}' not found on object of type '{GetWrappedObject().GetType().Name}'");
        }
    }
    
    static private Delegate CreateDelegate(Type type, EventHandler handler)
    {
        return (Delegate) type.GetConstructor(new[] {typeof(object), typeof(IntPtr)})
            ?.Invoke(new[] {handler.Target, handler.Method.MethodHandle.GetFunctionPointer()});
    }
}
```
Access to properties and fields using the wrapper is implemented via __get and __set!

![image](https://user-images.githubusercontent.com/61143434/223440318-b7ef2067-7a3a-4764-a14a-bb2930c2a849.png)

But in order for the magic methods to work, I have to create an heir class.

![image](https://user-images.githubusercontent.com/61143434/223441104-0845110e-dfc6-48bc-9d44-a0701698ee77.png)

![image](https://user-images.githubusercontent.com/61143434/223441168-91d98695-02e4-4730-a980-d34f1bbb6155.png)

![image](https://user-images.githubusercontent.com/61143434/223441286-ced92a20-04fa-4b16-90ff-b733e9e76ae6.png)

![image](https://user-images.githubusercontent.com/61143434/223441901-bbebc3c3-3f65-4d0d-99e3-2e734f2474e5.png)

**Comment by jakubmisek** [comment]
Currently, this PHP-specific feature can only be defined in the PHP language.

As a workaround, in C#, you can define
```c#
class MyDynamicClass {
  internal PhpArray __peach__runtimeFields;
}

```

so the class can have dynamic properties int PHP:

```php
$x = new MyDynamicClass();
echo $x->prop; // looks into "__peach__runtimeFields" array
```

**Comment by FibonacciFox** [comment]
> Currently, this PHP-specific feature can only be defined in the PHP language.
> 
> As a workaround, in C#, you can define
> 
> ```cs
> class MyDynamicClass {
>   internal PhpArray __peach__runtimeFields;
> }
> ```
> 
> so the class can have dynamic properties int PHP:
> 
> ```
> $x = new MyDynamicClass();
> echo $x->prop; // looks into "__peach__runtimeFields" array
> ```

> Unhandled exception. System.MethodAccessException: Attempt by method 'Application.Forms.MainWindow.__construct()' to access method 'Peachpie.Avalonia.Experimental.MyDynamicClass..ctor()' failed.
>    at Application.Forms.MainWindow.__construct() in C:\Users\shama\RiderProjects\Peachpie.Avalonia\src\Samples\Application\src\Application\Forms\MainWindow.php:line 67
>    at Application.Forms.MainWindow..ctor(Context <ctx>)
>    at <Root>.ApplicationDesktop_php.anonymous@function(Closure <closure>) in C:\Users\shama\RiderProjects\Peachpie.Avalonia\src\Samples\ApplicationDesktop\ApplicationDesktop.php:line 16
>    at anonymous@function#1(Closure, Context, PhpValue[])
>    at Pchp.Core.Reflection.RoutineInfo.Invoke(Context ctx, Object target, PhpValue[] arguments)
>    at Pchp.Core.Reflection.RoutineInfo.Pchp.Core.IPhpCallable.Invoke(Context ctx, PhpValue[] arguments)
>    at Closure.__invoke(PhpValue[] parameters)
>    at Peachpie.Avalonia.Platform.UxApplication.<>c__DisplayClass0_0.<.ctor>b__0(IClassicDesktopStyleApplicationLifetime desktop) in C:\Users\shama\RiderProjects\Peachpie.Avalonia\src\Peachpie.Avalonia\Platform\UxApplication.cs:l
> ine 34
>    at Peachpie.Avalonia.Platform.UxAppBuilderMinimalExtensions.StartWithClassicDesktopLifetime[T](T builder, Action`1 callback, String[] args, ShutdownMode shutdownMode) in C:\Users\shama\RiderProjects\Peachpie.Avalonia\src\Peac
> hpie.Avalonia\Platform\AppBuilderMinimalExtensions.cs:line 45
>    at Peachpie.Avalonia.Platform.UxApplication..ctor(Closure closure, String materialThemeMode, String[] args) in C:\Users\shama\RiderProjects\Peachpie.Avalonia\src\Peachpie.Avalonia\Platform\UxApplication.cs:line 32
>    at <Root>.ApplicationDesktop_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Users\shama\RiderProjects\Peachpie.Avalonia\src\Samples\ApplicationDesktop\ApplicationDesktop.php:line 15
>    at <Script>.Main(String[] args)

Unfortunately, there is a crash with an error.
```php
<?php

namespace Application\Forms;

use Peachpie\Avalonia\Controls\ {
    UxWindow,
    UxStackPanel,
    UxListBox,
    UxButton,
    UxCheckBox,
    UxCanvas
};
use Peachpie\Avalonia\Experimental\MyDynamicClass;
############Stub Classes#########

class StackPanel extends UxStackPanel {

}

class ListBox extends UxListBox {

}

class Button extends UxButton {

}

class CheckBox extends UxCheckBox {

}
#####################################

class MainWindow extends UxWindow {

    public function __construct()
    {
        $this->Title = "ApplicationDesktop";
        $this->Width = 400;
        $this->Height = 400;

        $UxStackPanel = new StackPanel();


        $ListBox = new ListBox();
        $ListBox->Items->Add('Hello World');


        $UxButton = new Button();
        $UxButton->Name = "button1";
        $UxButton->Content = "Button1";
        $UxButton->Width = $this->Width/2;

        $UxCheckBox = new CheckBox();

        $UxButton->on('Click', function($sender, $e) use ($UxCheckBox, $ListBox) {
            $IsChecked = $UxCheckBox->IsChecked ? 'AddToList - true' : 'AddToList - false';
            $ListBox->Items->Add($IsChecked);
            $sender->Content = $IsChecked;
        });

        $UxStackPanel->Children->Add($ListBox->GetWrappedObject());
        $UxStackPanel->Children->Add($UxButton->GetWrappedObject());
        $UxStackPanel->Children->Add($UxCheckBox->GetWrappedObject());

        $x = new MyDynamicClass();

        $this->Content = $UxStackPanel->GetWrappedObject();
    }
}
```

**Comment by FibonacciFox** [comment]
@jakubmisek ,Thanks, everything works fine. Closing the topic.
