### ISSUE TITLE
some syntax error 

### ISSUE THREAD

**Issue by xiangyi-wang** [peachpiecompiler/peachpie#1111]
Hi, the string is not recognized in this constructor.  I'm not sure whether it's a syntax error or whether it doesn't support this writing method

`	PHP2014	Syntax error: unexpected token 'Sort'	Flarum	D:\Flarum\vendor\ramsey\collection\src\Sort.php	20	
`
![image](https://user-images.githubusercontent.com/22881957/236408531-35603014-a750-4947-a6e4-46fa8f23dab5.png)
`	PHP2014	Syntax error: unexpected token 'string'	Flarum	D:\Flarum\vendor\ramsey\collection\src\Set.php	50	
`
![image](https://user-images.githubusercontent.com/22881957/236407780-0b481a06-f34b-44ee-a160-acf921499e10.png)

PHP4087	Argument 1 passed to is() must be of the type Pchp\Core\PhpValue, NULL given	
`} elseif ($def === null && !Nette\Utils\Validators::is(null, $type)) {`

**Comment by jakubmisek** [comment]
thank you for reporting that! It's a bug in the parser; for now you can workaround it by commenting `/*string*/` out.

**Comment by xiangyi-wang** [comment]
thanks! I also encountered a situation
`PHP4085	Property Ramsey\Uuid\Builder\FallbackBuilder::$builders cannot have type iterable	Flarum	D:\Flarum\vendor\ramsey\uuid\src\Builder\FallbackBuilder.php	33	
`
![image](https://user-images.githubusercontent.com/22881957/236723875-08a53bab-b544-4ad4-95aa-437d939c51d5.png)

**Comment by jakubmisek** [comment]
fixed, and updated PHP language level (syntax) to 8.2

Thank you @xiangyi-wang !
