### ISSUE TITLE
strange compiler behavior when modifier is "protected"

### ISSUE THREAD

**Issue by N0zzy** [peachpiecompiler/peachpie#1112]
Greetings. I observe strange behavior of the pie and reflection. when creating a class property using a php script with modifiers protected static - pie compiles in static as public and reflection points to this fact. is this a bug?

![1](https://user-images.githubusercontent.com/46209742/236680345-adbf7900-3569-41f1-b7e7-7d20373226b8.jpg)
![2](https://user-images.githubusercontent.com/46209742/236680350-ea12e5d0-61f0-435e-8f03-838f94b43c74.jpg)

**Comment by jakubmisek** [comment]
Hi,

This is by purpose; PHP `static` and .NET `static` behave differently. In PHP, a static property is static within the current request only. In .NET, static would be across all the requests.

To overcome this difference, PeachPie puts static properties into a nested class `_statics`, and creates a single instance for each request if needed.

Details at https://docs.peachpie.io/api/assembly/compiled-class/#additional-class-members

If it would be `static`, its value would be shared by all threads and all requests which would break the PHP behavior.

--

If you need a property, that is truly static (in a .NET manner), you can annotate it with Doc Comment `@appstatic`:

```php
/*
 * field
 * @appstatic
 */
protected static $dTest;
```

This will create a property which value is shared across all requests - you can use it as optimization for example.
