### ISSUE TITLE
program execution time

### ISSUE THREAD

**Issue by N0zzy** [peachpiecompiler/peachpie#1113]
![skFLJKoNo6k](https://github.com/peachpiecompiler/peachpie/assets/46209742/c7a56648-cb65-470d-b6df-f05b3b78419e)

this small code in original php runs in less than 1 second, and in pie from 5 to 10 seconds. how to fix it and is it possible? is it possible?

**Comment by jakubmisek** [comment]
Because it's in a global code which is unoptimized.

Try puting it into a function.

**Comment by N0zzy** [comment]
thanks for trying to help.
I thought I could solve this with a C Sharp thread.

**Comment by jakubmisek** [comment]
C# would be the same speed in this case:

```php
function test() {
  for ($i = 0; $i < 10000; $i++) {}
}
```
