### ISSUE TITLE
Problems when compiling a project using Avalonia UI. Help is needed

### ISSUE THREAD

**Issue by FibonacciFox** [peachpiecompiler/peachpie#1118]
Hello, [jakubmisek](https://github.com/peachpiecompiler/peachpie/commits?author=jakubmisek).
I can't solve the problem for a very long time. There is a library .Net, which builds the project and replaces the AvaloniaXaml.Load(this) call with !XamlIlPopulateTrampoline(this). (screenshots are attached). In PHP, is it compiled into
call_Load?0.Target(call_Load?0, this, <ctx>, this); Because of this, it is impossible to build the project because the library cannot find AvaloniaXaml.Load(this) in the class. Link to the code section: 
[XamlCompilerTaskExecutor.cs](https://github.com/AvaloniaUI/Avalonia/blob/ffaf02cf036cd92776367cef3c0290dec9c59b84/src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs#L441-L501)

Here is what happens in c# :
![image](https://github.com/peachpiecompiler/peachpie/assets/61143434/210e8911-a455-41b2-bd39-5deb59040378)
![image](https://github.com/peachpiecompiler/peachpie/assets/61143434/7703cf98-8767-4bed-8fdc-986ca67ae227)

Here's what's going on in php:

![image](https://github.com/peachpiecompiler/peachpie/assets/61143434/c613da2a-bc49-4343-a3ee-67dc38b6118f)
![image](https://github.com/peachpiecompiler/peachpie/assets/61143434/ef54b810-8792-4f72-89d5-70864e44d9c6)

But if you specify in php like this:

```php
public function Load(object $This){
      AvaloniaXamlLoader::Load($This)
}
```

Will compile to:

```c#
public virtual void Load(object This){
     AvaloniaXamlLoader.Load(This)
}
```

But that won't help in any way, because it's still waiting for AvaloniaXamlLoader.Load(this); when compiling.
I will be very grateful in finding a solution to this problem.

**Comment by FibonacciFox** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/ffaf02cf036cd92776367cef3c0290dec9c59b84/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs#L10C4-L25C10

**Comment by jakubmisek** [comment]
The compiler sees several `Load()` overloads, so it postpones the resolution to runtime using the callsite (`call_Load?0`).

The fix would be to improve the compiler so it resolves the `Load(object)` overload in compile time - I'm not sure, why it's not resolving it already, it should.

**Comment by kekekeks** [comment]
For a reference: [this](https://github.com/AvaloniaUI/Avalonia/blob/ffaf02cf036cd92776367cef3c0290dec9c59b84/src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.Helpers.cs#L129-L157) is how XAML compiler task tries to match `AvaloniaXamlLoader.Load(this)` call. 

It currently recognizes the normal
```
ldarg.0
call AvaloniaXamlLoader.Load(object)
```
pattern and the monstrosity generated by F# compiler.


The peachpie pattern won't be easily recognizable since it would require us to analyze the CallSite static variable initialization that happens elsewhere and looks like an internal implementation detail.

So the preferable solution would be for peachpie to just emit the simple ldarg.0+call sequence.

**Comment by jakubmisek** [comment]
@kekekeks the compiler mainly emits simple `.ldarg`+`.call`. Here it's probably an unimplemented optimization where due to more similar overloads, it falls back to runtime overload resolution.

**Comment by jakubmisek** [comment]
So in PHP, you have the following?

```php
AvaloniaXamlLoader::Load( $this );
```

**Comment by jakubmisek** [comment]
this has been fixed in the recent releases, and discussed on our [discord channel](https://discord.com/channels/1198334116182102177/1198335586222743594)

thanks!
