### ISSUE TITLE
Peachpie.Runtime uses outdated System.Data.SqlClient 4.6.0

### ISSUE THREAD

**Issue by mhoeper** [peachpiecompiler/peachpie#1126]
Hi, 

using Peachpie.Runtime, depending on Peachpie.App depending on, finally Peachpie.Library.MsSql is being used. I do not even need MsSql.... Nevertheless, this has dependency to System.Data.SqlClient 4.6.0, that is outdated. Can you please upgrade to the latest version?

I am using target framework net7.0 with Peachpie.Runtime 1.1.9

**Comment by jakubmisek** [comment]
Hi,

Thank you for the issue;

- the reference will be updated.
- you can disable the reference to `Peachpie.App` by setting `<DisableImplicitPeachpieReferences>true</..` MSBuild property

**Comment by mhoeper** [comment]
Thanks Jakub for the update. Turns out i am using` Peachpie.NET.Sdk`, too, so somehow even with `<DisableImplicitPeachpieReferences>true</..` the `System.Data.SqlClient` gets linked. 

Do you know this is going to be released this year?

**Comment by mhoeper** [comment]
Thank you, its working good now!

I was referencing Peachpie.NET.Sdk by package reference as below in msbuildproj file: 

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<DisableImplicitPeachpieReferences>true</DisableImplicitPeachpieReferences>  
  </PropertyGroup>  
  <ItemGroup>
    <PackageReference Include="Peachpie.NET.Sdk" Version="1.1.7" PrivateAssets="Build" />
  </ItemGroup>
</Project>`

This way its still adding System.Data.SqlClient. When changing to the below, System.Data.SqlClient no longer being included...

`<Project Sdk="Peachpie.NET.Sdk/1.1.9">
  <PropertyGroup>
	<DisableImplicitPeachpieReferences>true</DisableImplicitPeachpieReferences>
  </PropertyGroup>
</Project>`
