### ISSUE TITLE
PHP4034: Failure writing debug information: Value cannot be null. (Parameter 'type') 

### ISSUE THREAD

**Issue by Miatrix** [peachpiecompiler/peachpie#1128]
When doing a dotnet publish with the following options under GitHub actions:

dotnet publish Client/Client.csproj -c Release -o ${{env.DOTNET_ROOT}}/app/Client /p:RuntimeIdentifier=linux-x64 /p:PublishSingleFile=true /p:DebugType=None /p:DebugSymbols=false /p:PublishReferencesDocumentationFiles=false

I'm getting: BUILDTASK : error PHP4034: Failure writing debug information: Value cannot be null. (Parameter 'type') [/home/runner/work/PHPLib/PHPLib.msbuildproj]

When I run that same command locally it works fine.  Is there some option I should or should not pass to solve this issue?

The client includes several .net packages and 1 php package called PHPLib

**Comment by jakubmisek** [comment]
I guess, the .NET SDK version might be different.

What is the .NET version you use?

**Comment by jakubmisek** [comment]
currently, you need to specify
```
/p:DebugType=portable
```

and the compilation will proceed

**Comment by jakubmisek** [comment]
implemented! thanks for pointing this out
