### ISSUE TITLE
How to convert laravel to bitcode

### ISSUE THREAD

**Issue by vahidalvandi** [peachpiecompiler/peachpie#1129]
Hi. I want to concert my laravel app to dot net compiled

**Comment by jakubmisek** [comment]
@vahidalvandi thank you for the comment. There are a few related projects:

- https://github.com/calvinbaart/laravel-peachpie-sample
- https://github.com/calvinbaart/laravel-peachpie

Once it will be ready, we'll definitely publish some tutorials about running Laravel on .NET :)
