### ISSUE TITLE
Integrating Wordpress with ASP.NET MVC

### ISSUE THREAD

**Issue by KevinBurton** [peachpiecompiler/peachpie#113]
With the Peachpie compiler I can see how I can get an existing Wordpress site up an running in a .NET environment. My question is, how can a Wordpress site be integrated with an MVC application? I realize that this is probably aWordpress and/or an ASP.NET question but most of the solutions that I have see don't involve the Peachpie compiler and I was just wondering what your ideas were?

Thank you.

Kevin

**Comment by jakubmisek** [comment]
Good question. I can imagine several options

1. Routing may be implemented in .NET. Then requests to WordPress pages passed to compiled WordPress.
2. Implement a View which using Peachpie API "includes" specific WordPress scripts. Implement Model that sets C# model to WordPress-specific global variables in a way that WordPress understands. This would allow to setup environment in C# (like current page, authenticated user etc.) and pass it to WordPress.
3. Reuse WordPress widgets or plugins and render them into View.
