### ISSUE TITLE
PeachPie is not copying images into build

### ISSUE THREAD

**Issue by vitor93** [peachpiecompiler/peachpie#1130]
Pchp.Core.ScriptDiedException: '<strong>TCPDF ERROR: </strong>SVG file not found: /app/src/download/config/ciologo.svg'

![image](https://github.com/peachpiecompiler/peachpie/assets/13287512/fa03892e-2255-4f6d-a74b-9689533a1770)

You can see the image there in the image above.
Can you help me ?

**Comment by jakubmisek** [comment]
Shouldn't it be a wrong working directory?

**Comment by vitor93** [comment]
It was the right directory, as shown in the image above.

**Comment by vitor93** [comment]
The problem is when it tries to read, it does not have permissions.

PS: just to give a little context on the problem that happened.

By the way the project is a very nice iniciative :) keep up the good work.

**Comment by jakubmisek** [comment]
@vitor93 thank you for the update, and for the nice words!
