### ISSUE TITLE
Dynamicly compile the php script

### ISSUE THREAD

**Issue by HengzheLi** [peachpiecompiler/peachpie#1139]
I am a fresh of this project. Juost wonder is it possible to compile the php script on the fly when debugging the php?

Currently, it has to recompile the host project to apply the change in a php script file. I have to stop then start the VS to see the latest result when I make an update on a php script in debugging. Can it be like the razor view when I save then refrsh the browser, then the updated view is there.

**Comment by jakubmisek** [comment]
@HengzheLi Hi, Edit&Continue is not implemented yet. So it's necessary to restart your project after making changes.

**Comment by HengzheLi** [comment]
OK. Thanks for your replies
