### ISSUE TITLE
Closures inside classes cannot acces their private methods dynamically

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#114]
The reason for this is the missing type context of such call site (related to #96). See the following test case:
```php
<?php
class A {
  private function foo() {
    echo "foo";
  }

  public function bar($method) {
    $fn = function() use ($method) {
      $this->$method();
    };
    $fn();
  }
}

(new A)->bar('foo');
```
Expected result: ```foo```
Actual result: ```'foo' not found```

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/af3030400f90edc4c0d1bf212d042ab0ee87849a
