### ISSUE TITLE
Is Server project behave properly?

### ISSUE THREAD

**Issue by dotChris90** [peachpiecompiler/peachpie#127]
Hello peachpie team, 

I am very happy that peachpie develops so well and you made a great job. 
I just would like to ask if the asp.net core server behave properly. I know there is the php project which compiles it php data to CIL and there is the ASP.NET Core. 
I was playing little bit and detected that (in my opinion) the asp.net core does not behave like static webserver should do (maybe I did some wrong configurations).

I was expecting the following : there should be a rootfolder in "/projectname/Server" and if i put a static file like "hello.txt" and I hit the URL "localhost:5004/hello.txt" the server should anwser. But I just got a white page.      

First I was thinking "ok - they forgot app.UseStaticFiles();" but nope - its inside. ok - there is no rootfolder? added - no change. "have to add the rootfolder to csproj? nope the other templates like razor or MVC do not do too". -.- So .... "ok the most easy stuff was tried xD" 

It is not an too important issue - but I am curious what could be the problem. ;) 
I will also look little bit around - it must be a trivial stuff. 

Soo :D thanks for your time and wish you all a great christmas time!  
Merry christmas 
dotChris90 / Christian

**Comment by jakubmisek** [comment]
Hi! Thanks for trying peachpie.

In ASP.NET Core, it is important to setup web root and/or content root folders. This is where static files will be searched by the pipeline.

See for example our WordPress demo, where we setup both https://github.com/iolevel/peachpie-wordpress/blob/af79682304859ae55a9bf7e451e89559483c5d8f/app/Program.cs#L14

Otherwise the content folder is set to the current application directory, which is somewhere in `bin`

**Comment by dotChris90** [comment]
Hey Jakub, 

thanks again. :) and you solved my issue again so fast. ;) 
Yeah you are totally right with your anwser. I forgot this totally ^^' in asp.net core 1.* it was always written in every project but now with the asp.net core 2.0 there exist a "default" builder and .... I forgot that beside the static files you have to configure the webroot. 

Did it and it works perfectly! thanks ;) 

Wish you a merry christmas and a good time. 
greeting 
dotchris90 / Christian
