### ISSUE TITLE
Cannot install wordpress plugins in runtime?

### ISSUE THREAD

**Issue by chungvinhkhang** [peachpiecompiler/peachpie#130]
So peachpie wordpress can be installed wordpress plugins in runtime and we have to download the plugins outside and rebuild whole web?

**Comment by jakubmisek** [comment]
As of now (`0.8.0`), after source code changes you have to run build again.

You can use https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md to rebuild website automatically after the change.

In future, there will be an option to compile plugins and core separately.

**Comment by chungvinhkhang** [comment]
Hi, dotnet-watch is still watch from source code. When we installed wordpress plugins in runtime (I mean from wordpress hosted plugins repository https://wordpress.org/plugins/), the plugins is downloaded to the running production env. So I think the better solution in the future is to trigger the local or remote peachpie compiler to process after the plugins is activated.

**Comment by jakubmisek** [comment]
Currently the compilation has to be triggered manually if desirable (this can be automated using `dotnet-watch`).

**Comment by jakubmisek** [comment]
Closing for now - this feature is not supported.

We'll open new issue for compilation of modified files in runtime once it gets planned.
