### ISSUE TITLE
Disappearing '' in string with complex interpolation containing array access

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#133]
Consider the following test case:
```php
<?php
function test() {
  $arr = ['foo' => 'bar'];
  echo "{$arr['foo']}''";
}
test();
```
Expected result: ```bar''```
Actual result: ```bar```

```echo "{$arr['foo']}'"``` works properly - it returns ```bar'```

**Comment by jakubmisek** [comment]
https://github.com/DEVSENSE/Parsers/commit/3ec9c1f80b0495df8e9de24f85d005d81ea0e18e
