### ISSUE TITLE
Support accessing static trait members and methods from outside

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#135]
Test case:
```php
<?php
trait T {
  public static function foo() {
    echo "foo";
  }
  public static $bar = "bar";
}
T::foo();
echo T::$bar;
```
Expected result: ```foobar```

Actual result: ```Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)``` - this is probably caused by the unfilled type parameter ```T0```, because ```T::foo()``` is compiled as ```T<T0>.foo(ctx)```

**Comment by jakubmisek** [comment]
Nice test case, I wouldn't ever believe PHP allows using members of a trait directly.

Yes, implicit type parameter `TSelf` is not specified.

**Comment by roberthusak** [comment]
Thanks, well, I was surprised, too..

**Comment by jakubmisek** [comment]
more or less fixed in recent commits, still not handled in runtime binders
