### ISSUE TITLE
class 'SplFileInfo' not implemented

### ISSUE THREAD

**Issue by amigainc** [peachpiecompiler/peachpie#140]
Hello,
I have this warning when compiling a PHP Project.
I thought SplFileInfo was native PHP class.
Regards,

**Comment by jakubmisek** [comment]
Hi,
`SplFileInfo` is a part of PHP (since PHP 5.1.2), however, not implemented in Peachpie yet.

Do you work on an opensource that might benefit from this?

**Comment by amigainc** [comment]
Indeed, I have a PHP project I tru to convert as EXE, and developer uses this class.
May you have an idea if and when this function would be implemented?
Regards,

**Comment by jakubmisek** [comment]
We have no schedule so far - it depends on what project requires it, whether it is a blocking issue. If it is not an opensource or you'd like to keep it in private, please contact us on info@iolevel.com.

**Comment by amigainc** [comment]
Project is private, I'll rewrite it to exclude _SplFileInfo_, it'll be the most simple in a first time.
Thanks for your answers.

**Comment by jakubmisek** [comment]
`SplFileInfo` stubs have been added. Please add an issue for specific methods that are not implemented.
