### ISSUE TITLE
GD functions: imagefilledrectangle, imagettftext

### ISSUE THREAD

**Issue by TyKonKet** [peachpiecompiler/peachpie#156]
Hi @jakubmisek , I would need to use some GD functions such as **imagefilledrectangle** and  **imagettftext**, are them planned to being implemented?

**Comment by jakubmisek** [comment]
Yes, basically they are planned as they will be needed.

**Comment by jakubmisek** [comment]
`imagefilledrectangle` in https://github.com/peachpiecompiler/peachpie/commit/23bff8be212302ba2253902280c493a59663b901

**Comment by jakubmisek** [comment]
@TyKonKet - implemented
