### ISSUE TITLE
Web Application SEO URLs

### ISSUE THREAD

**Issue by Seimann91** [peachpiecompiler/peachpie#157]
How do i use SEO URLs in Peachpie Web Application .NET Core?
it does not work:
`app.UseRewriter(new RewriteOptions().AddRewrite(@"^rewrite-rule/(\d+)/(\d+)", "index.php?var1=$1&var2=$2", skipRemainingRules: true));`

How can I send all input to index.php?

**Comment by jakubmisek** [comment]
Using `Microsoft.AspNetCore.Rewrite` as you noted is the correct way to go.

You can check our sample on https://github.com/iolevel/peachpie-samples/blob/master/web-application/app/Startup.cs
