### ISSUE TITLE
PDO -- Sqlite

### ISSUE THREAD

**Issue by Wulfklaue** [peachpiecompiler/peachpie#158]
Is it possible that the Sqlite driver support is incomplete?

After following the source code examples and adding:

```
    <PackageReference Include="Peachpie.Library.PDO.Sqlite" Version="0.9.0-*" />
```

I keep getting Sqlite driver not found on Windows (.netCore 2.0). Despite that the Sqlite driver is in the Windows/System32 directory.

```
Unhandled Exception: Peachpie.Library.PDO.PDOException: Driver 'sqlite' not found
```

Also added the following to the Peachpie.msbuildproject:

```
    <PackageReference Include="Microsoft.Data.Sqlite" Version="1.1.0" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.106" />   
```
Both do not provide a solution.

Been back tracing your C# code but got stuck on the "PDODriver.RegisterAllDrivers();" as its unclear to what C# actually loads as driver strings at this point.

**Comment by jakubmisek** [comment]
You are right, the Sqlite driver was not loaded.

It should work now. Specifying `<PackageReference Include="Peachpie.Library.PDO.Sqlite" Version="0.9.0-*" />` is sufficient.
