### ISSUE TITLE
Doesn't build (strange error)

### ISSUE THREAD

**Issue by paragonie-scott** [peachpiecompiler/peachpie#160]
https://gist.github.com/paragonie-scott/87cd39d21301ac0658027b822ab53c32

Create a console project. Grab Composer (separately). Run `composer install`. Then try to build it with PeachPie.

**Comment by jakubmisek** [comment]
Can you post the strange error?

**Comment by paragonie-scott** [comment]
It's in the gist, but,

`C:\Users\Scott\.nuget\packages\peachpie.net.sdk\0.9.0-ci00687\build\Peachpie.NET.Core.Sdk.targets(148,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netcoreapp2.0\compile-php-args.rsp" exited with code -532462766. [D:\dotnet\dotnet.msbuildproj]`

**Comment by jakubmisek** [comment]
@paragonie-scott I see, isn't there any kind of stack trace? this is strange

**Comment by paragonie-scott** [comment]
Nothing of the sort. Just an exit code. I omitted 80 or so warnings about `RangeException` not being defined.

This was prompted by Reddit: https://www.reddit.com/r/PHP/comments/7smqw7/benchmarking_wordpress_on_php_vs_net/

**Comment by jakubmisek** [comment]
got it, somewhere in the middle I'm getting
```
  Unhandled Exception: System.NotImplementedException: Sub(Object,...)
     at Pchp.CodeAnalysis.Semantics.BoundBinaryEx.EmitSub(CodeGenerator cg, TypeSymbol xtype, BoundExpression right, TypeSymbol resultTypeOpt)
     at Pchp.CodeAnalysis.Semantics.BoundBinaryEx.Emit(CodeGenerator cg)
```
after this, there will be few more not implemented functions/classes I guess.

**Comment by jakubmisek** [comment]
note, there are several `Class 'Sodium\Error' not found` and `Class 'Sodium\Exception' not found` that is bug in sodium sources

**Comment by jakubmisek** [comment]
The build error was fixed with https://github.com/peachpiecompiler/peachpie/commit/cb65dd584dd53da36b755016b2cce9f79f8d88ed

These two commits implement missing RangeException and TypeError: https://github.com/peachpiecompiler/peachpie/commit/8442cf8891c253caf2324e9b0ee25e640f41becc,
 https://github.com/peachpiecompiler/peachpie/commit/ad144ecc6f85938596d0c3ccfdbdcc93b007c6b1

**Comment by jakubmisek** [comment]
@paragonie-scott it should compile now - I took a quick look, there is like hundreds of operations we can evaluate in compile time or otherwise optimize. Please open an issue if you'd like to discuss possible steps.
