### ISSUE TITLE
PHP String Operator crash

### ISSUE THREAD

**Issue by Seimann91** [peachpiecompiler/peachpie#167]
Hi,
When I use php string operators, I get a dotnet.exe APPCRASH (Peachpie WebApp)

```php
$a = "Hello ";
$b = $a . "World!";
// or
$a = "Hello ";
$a .= "World!";

**Comment by jakubmisek** [comment]
Do you have a stack trace?
It is possible it happened in a previous development version, we can't get it crash with provided test case.

**Comment by Seimann91** [comment]
OK I see there is another problem here,
`ERROR MSB3073 Command "dotnet compile-php @obj\Debug\netstandard2.0\compile-php-args.rsp" exit with code Code -532462766. Line num 154`

Code Line
`<Exec Command="dotnet compile-php @$(TempOutputDir)compile-php-args.rsp" />`

No idea how that comes about. But it is also on new peachpie-web projects.
I try a new installation VS / Peachpie and then write again

**Comment by Seimann91** [comment]
@jakubmisek 
Right!
I had a faulty VS2017 installation. (For whatever reason)
Thanks for looking, and thanks for the feedback!
best regards

**Comment by bfistein** [comment]
@Seimann91 glad you were able to find the culprit and happy it wasn't us :) closing this issue.
