### ISSUE TITLE
something about load_class,maybe it is time consuming。

### ISSUE THREAD

**Issue by smallcodelin** [peachpiecompiler/peachpie#174]
I test CI framwork and find one load_class method may reduce 200 qps by ab.

**Comment by jakubmisek** [comment]
CI `load_class` is a complex method doing an include and calling other handlers.

**Comment by smallcodelin** [comment]
thanks for answers.As a result of loading documents lead to performance degradation。
How to improve‘require_once’ or 'include' performance in peachpie. like php use opcache.

**Comment by jakubmisek** [comment]
`include` is already optimized. What I'm saying is, include leads to another code (inside that included file) to be executed and another and another ... in the result `load_class` does a lot of things, and a lot of them can be optimized.
