### ISSUE TITLE
Custom exception implementing __toString causes TypeLoadException

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#175]
Test case:
```php
class MyException extends Exception {
  public function __toString() { return "foo"; }
}
```
Result:
```
Unhandled Exception: System.TypeLoadException: Declaration referenced in a method implementation cannot be a final method.  Type: 'MyException'.  Assembly: 'console-application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Script>.Main(String[] args)
```
The problem is that ```MyException.ToString()``` attempts to override sealed ```Exception.ToString()```. I'm not sure whether to prevent the generation of the former (in ```EmitToString```) or to unseal the latter.

**Comment by jakubmisek** [comment]
you are right.
first, in general, the generation of ToString override should respect the base implementation. If it is sealed, we should not override it.
