### ISSUE TITLE
multi-threading resource trouble

### ISSUE THREAD

**Issue by laytondavis** [peachpiecompiler/peachpie#179]
I have written a postgres interface that is largely copied from the mysql interface. I am calling Peachpie from javascript through edge.js in electron. In one instance I am submitting 21 requests from javascript to Peachpie simultaneously. Since each process is calling the same function, the queries would be identical except for the parameters passed. Sometimes everything works correctly, and sometimes the Peachpie threads hang. in visual studio I can see that either one of two conditions is happening. Either there are multiple queries being sent on one connection or the database connection is null. When I investigate each of the threads, there are anywhere between 2 and 5 of them that have the same connection resource number. Just for comparison, there are often 3 to 5 threads stopped at the same statement number when visual studio breaks at the error message.
Getting the same resource on multiple threads would explain the issues I am having. What I can't figure out is why I am getting the same resource number.
here is the line of code that asks for the connection resource
`CreateConnection(connstring, true, -1, out success);`

I can see that the line that gives a new PHP resource is /or should be thread safe.  Just to be sure, I tried putting an explicit lock around that statement, and all that did was slow the process down without changing the results.

What do I need to do to guarantee that I will get a unique resource on each thread?

Hardware: AMD FX8350 8 core system with 32Gig of memory
Peachpie version: tried both the git version checked in Feb. 20 and March 1 with the same result.

**Comment by jakubmisek** [comment]
Hi, may I ask for link to the line that gives a new PHP resource, just for a reference.

**Comment by laytondavis** [comment]
it is line 71 in the file at [https://github.com/laytondavis/peachpie/blob/postgres/src/Peachpie.Library.PostgreSql/PostgresFunctions.cs](url)

**Comment by laytondavis** [comment]
oops. it was line 72. The PHP function never passes the optional parameter, so that will always have its default value.

**Comment by jakubmisek** [comment]
Thanks!

It does not seem to give me the same resource Id. Also the instance of resource and underlaying postgres connection is always freshly created.

You can try to put a breakpoint or a debug log into [PhpResource.RegisterInternalInstance](https://github.com/laytondavis/peachpie/blob/ac9fe1f85b79cd479163d7887c5ab0d4e17c016c/src/Peachpie.Runtime/PhpResource.cs#L34) which is thread safe and static and generates new Ids for every created resource.

**Comment by laytondavis** [comment]
This issue was caused by a null database connection. When PHP runs off the end of a script it automatically closes any resources that were allocated during the run. When a PHP function is called from C#, there is no reasonable way of knowing that the page has run all of its script. Therefore the user must close all connections. I had forgotten to close the database connection in one place, and it caused connection exhaustion on the database server. Why it looked like re-use of resources in the debugger, I don't know. Mark this one up to user error.
