### ISSUE TITLE
MySQL in binary mode contracts certain multibyte UTF characters to "?"

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#183]
This causes problems especially when storing a serialized string which contains such character - for example [en dash "–"](http://www.fileformat.info/info/unicode/char/2013/index.htm), see the test case of passing such string through a MySQL connection:
```php
function query(mysqli $db, string $sql) {
  echo $sql ."\n";
  $result = $db->query($sql);
  return $result->fetch_assoc()['val'];
}

function test($server, $user, $pwd, $dbname) {
  $db = mysqli_init();
  $db->options(MYSQLI_SET_CHARSET_NAME, 'binary');
  $db->real_connect($server, $user, $pwd, $dbname);

  $str = "–";  // Three characters in UTF-8: 0xE2 0x80 0x93s
  $val = query($db, "SELECT '". serialize($str) ."' AS val");
  echo $val ."\n";
  print_r(unserialize($val));

  $db->close();
}

test('localhost', 'user', 'pwd', 'db');
```
Expected result:
```
SELECT 's:3:"–";' AS val
s:3:"–";
–
```
Actual result:
```
SELECT 's:3:"-";' AS val
s:3:"?";
```
If the line ```$db->options(MYSQLI_SET_CHARSET_NAME, 'binary');``` is removed, it works as it should. If the ```string``` type hint of the ```string $sql``` parameter is removed (and thus the PhpString without the conversion to System.String is passed to ```$db->query```), the result is as follows:
```
SELECT 's:3:"ÔÇô";' AS val
s:3:"ÔÇô";
-
```
Notice that the en dash was changed to a hypen-minus "-".

**Comment by jakubmisek** [comment]
It's not just mysql, specifying `string` type hint corrupts single byte strings

```php
function query(mysqli $db, string $sql) {
```
causes `$sql` to be encoded into Unicode string.

Solution: internally we should use `PhpString` instead of `String` for these type hints ... once `PhpString` will be more efficient

**Comment by jakubmisek** [comment]
I duno why but the test case gives me the expected result now. Probably we accidentally already fixed this?

**Comment by roberthusak** [comment]
According to MediaWiki, the original problem with the characters seems to be solved 👍 However, when working with binary data, an error can still occur. E.g. in MediaWiki they compress the data cached to the DB:
```php
function query(mysqli $db, string $sql) {
  $result = $db->query($sql);
  return $result->fetch_assoc()['val'];
}

function test($server, $user, $pwd, $dbname) {
  $db = mysqli_init();
  $db->options(MYSQLI_SET_CHARSET_NAME, 'binary');
  $db->real_connect($server, $user, $pwd, $dbname);

  $val = 'Lorem Ipsum dolor sit amet';
  $compressed = gzdeflate($val);
  $compressed_result = query($db, "SELECT '". $db->real_escape_string($compressed) ."' AS val");
  $uncompressed_result = gzinflate($compressed_result);

  var_dump($uncompressed_result);

  $db->close();
}

test('localhost', 'user', 'pwd', 'db');
```
Expected output:
```
string(26) "Lorem Ipsum dolor sit amet"
```
Actual output:
```
bool(false)
```
Again, it works well when the ```string``` type hint is removed. Globally using ```PhpString``` instead of ```String``` would help in all these cases.

**Comment by jakubmisek** [comment]
seems to work now, closing
