### ISSUE TITLE
Responsive File Manager

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#185]
Thanks for your hard work on the cURL feature and on this project in general. Issue #121 was opened for cURL specifically, but with the aim of getting **Responsive File Manager** working in Peachpie. I'm having some more issues with it and decided it's probably better to open a new issue rather than add noise to the issue which is specific to cURL.

So, I am using 100% the same version of **Responsive File Manager** that I've been using for years with Phalanger, but I can't get it to work properly... and I believe it's probably due to some functions not being implemented yet and perhaps some other functions not implemented quite right. Jakub has already helped fix a couple of bugs (thanks). I would be very grateful if you guys could clone my test repo (here: [peachpie-responsive-file-manager](https://github.com/gordon-matt/peachpie-responsive-file-manager)) and get it working. There are various issue - most importantly I can't open folders that I just created and also thumbnails are not generated (I guess due to some graphics functions not yet implemented - maybe). As I don't know PHP, it's very hard for me to diagnose these issues. When you have some time, I would very much appreciate if you could please take a look and see if you can get it working. Thanks guys!

**Comment by gordon-matt** [comment]
Thanks to Jakub for helping fix various issues, I now have a partially working demo, which can be found here: [peachpie-responsive-file-manager](https://github.com/gordon-matt/peachpie-responsive-file-manager).

The file manager shows up fine and files can be uploaded fine as well. However, there are 3 remaining issues that I have yet to resolve before this can be considered a working project:

1. After creating a folder, I cannot browse to it.. I am not sure why this is - it worked perfectly fine with Phalanger.

2. Thumbnails are not generated. I believe this is due to various functions missing in the graphics library. See issue #190 for further info.

3. RFM is supposed to work with relative paths in the .config file... but I get error messages when trying to do so. Ideally, I would like to use the following:
	```
	'current_path' => '../Media/Uploads/',
	'thumbs_base_path' => '../Media/Thumbs/',
	```
	
	This is what I had when using Phalanger in MVC5 and it worked fine. However, with Peachpie I am forced to use the full path. In my case, as follows:
	
	```
	'current_path' => 'D:\\Source\\GitHub\\peachpie-responsive-file-manager\\WebApplication\\wwwroot\\Media\\Uploads\\',
	'thumbs_base_path' => 'D:\\Source\\GitHub\\peachpie-responsive-file-manager\\WebApplication\\wwwroot\\Media\\Thumbs\\',
	```

	Trying to use relative paths always produces an exception... and now more recently with moving the static files and upload files to **wwwroot** in the **WebApplication**, it's another problem as well, which is that using relative paths doesn't make it look in `WebApplication\wwwroot\Media\Uploads`, but instead it's trying to look in `Website\Media\Uploads`.

**Comment by jakubmisek** [comment]
can you please provide the exceptions you have?

Add 2. if you debug the project, you should see either exceptions or debug output in Output pane. Anything not implemented throws an exception. Anything not supported writes to Output pane.

**Comment by gordon-matt** [comment]
Hi @jakubmisek . I have updated the paths in my `config.php` file to the following:

```
'current_path' => '../../WebApplication/wwwroot/Media/Uploads/',
'thumbs_base_path' => '../../WebApplication/wwwroot/Media/Thumbs/',
```

I have good news and bad news... well, bad news is more of a question actually:

The good news is that relative paths do seem to be working in the latest version now (probably I was getting the `FileNotFoundException` before because of the confusion with `WebRoot/ContentRoot`. Now that you have provided the new `RootPath` property in the options, I think that has solved the problem.

The bad news is I just realized that with the **config.php** file like this, I would need to recompile the DLL for every project I use it in. This is not good. I need a way to provide the values to **config.php** without having to recompile (keep it outside of the DLL). I guess you have a simple solution for that, but I am not sure what. Can you please tell me how I would do that?

**Comment by gordon-matt** [comment]
@jakubmisek It seems I made a mistake - the issue with relative paths still exists.. it only happens when trying to upload. Here are the exception details, as requested:

**EXCEPTION**: `DirectoryNotFoundException`: Could not find a part of the path.

**STACK TRACE**
```
   at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Pchp.Library.Web.move_uploaded_file(Context ctx, String path, String destination)
   at <Root>filemanager.upload_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in D:\Source\GitHub\peachpie-responsive-file-manager\Website\filemanager\upload.php:line 86
   at <Root>filemanager.upload_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

Problem is with a variable called **$targetFile**, the value of which is:

`'..\..\WebApplication\wwwroot\Media\Uploads\grapesjs-logo-2.png'`

**Comment by jakubmisek** [comment]
seems like `move_uploaded_file` does not create destination directory first. Will be fixed.

**Comment by gordon-matt** [comment]
OK I figured out why I can't browse to my folders:

Take a look at this working **GET** Request from an **MVC5** site of mine that also uses this file manager:
`?editor=&type=0&lang=en_EN&popup=&crossdomain=&extensions=""&field_id=&relative_url=&akey=key&fldr=Folder1%2F&58D2D89945E2F`

Now compare that with what is generated by Peachpie:

`?editor=type=lang=en_ENpopup=crossdomain=field_id=relative_url=akey=keyfldr=Folder1%2F&58CD5BB1EA1F9`

For one, there are no ampersands and also the empty strings are missing as well. Is this a problem in **cURL** or somewhere else? Let me know and I can use the existing **cURL** issue #121 or open a separate issue if it's not **cURL** related.

**Comment by gordon-matt** [comment]
**UPDATE**: Now that issue #193 is closed, we can browse the folders and that means we are almost done here. All that's left really is #194 which I am looking into and trying to figure out why the thumbnails are not being generated. I have been trying like crazy to find the reason, but I just don't see it yet. If there's anyone here who could help me debug and find the reason, I would be very grateful.

**Comment by gordon-matt** [comment]
**UPDATE:** Regarding thumbnails not being generated, I believe I have found the reason and logged it as issue #196

**Comment by gordon-matt** [comment]
Good news: The first working version is now available! Thumbnails and everything, all working. The only issue left is #195. Without that, I cannot easily reuse the code against multiple projects. Almost there!

**Comment by jakubmisek** [comment]
#195 has been closed, closing this one, please open new issues if any

**Comment by AdwardNguyen** [comment]
Error: Method not found: Pchp.Core.PhpString Pchp.Library.PhpPath.file_get_contents

<img width="1373" alt="screen shot 2018-10-03 at 2 14 23 pm" src="https://user-images.githubusercontent.com/22392606/46398337-0ebd4a00-c71f-11e8-9079-a90175cdee3b.png">
<img width="294" alt="screen shot 2018-10-03 at 2 09 59 pm" src="https://user-images.githubusercontent.com/22392606/46398340-0ebd4a00-c71f-11e8-9cc6-00faf208f04d.png">

**Comment by jakubmisek** [comment]
Restore, consolidate dependencies version and rebuild
