### ISSUE TITLE
Missing functions in Graphics library?

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#190]
It would appear that many functions are still missing from the Graphics library. I received many **PHP3006** compiler warnings complaining of the following:

```
Call to undefined function: 'imagefilter'
Call to undefined function: 'imageconvolution'
Call to undefined function: 'imagecolorstotal'
Call to undefined function: 'imagecolorsforindex'
Call to undefined function: 'imagecolorset'
Call to undefined function: 'imageTrueColorToPalette'
Call to undefined function: 'imageColorsTotal'
Call to undefined function: 'imagecolortransparent'
Call to undefined function: 'imagefill'
Call to undefined function: 'imagefilledellipse'
Call to undefined function: 'imagepolygon'
Call to undefined function: 'imagefilledarc'
Call to undefined function: 'imageTTFBbox'
Call to undefined function: 'imageinterlace'
Call to undefined function: 'imagecolorexact'
Call to undefined function: 'ImageColorsForIndex'
Call to undefined function: 'imageColorSet'
```

About 80% of the warnings were for `imagefilter`. I searched the Peachpie repo for this term and found it in `PhpGd2.cs` and compared that with the same file in **Phalanger**. The only difference I could find is that each of the values in the `FilterTypes` enum had an `[ImplementsConstant]` attribute in Phalanger. Not sure if that's needed in Peachpie or not.

I also had 1 other compiler warning as follows:

`warning PHP3008: Class 'PhpPsdReader' not found`

**NOTE**: This is related to issue #185

**Comment by jakubmisek** [comment]
We can take a look on these functions. If you'd have a pull request with some of them, it would be great.

Most of them can be found in **Phalanger**, just note that underlaying graphics library was changed from Windows GDI+ to cross-platform ImageSharp. Constants and functions are declared differently in Peachpie (without these attributes, and using `PhpValue` instead of `object`). The specification of the library can be found on https://github.com/peachpiecompiler/peachpie/wiki/Libraries-Architecture#extension-library

`PhpPsdReader` seems to be a 3rd party package (this one? https://github.com/chisimba/chisimba/blob/master/app/core_modules/files/resources/imagecreatefrompsd.php)

**Comment by gordon-matt** [comment]
See pull request #192. Also, I see you've aalready added `imagefilter` earlier today.. didn't realize that until now. Please note, I simply copied over the missing functions and made slight changes to easy ones and simply commented the ones that are too difficult at the bottom of the file. ope someone here with more expertise can finish it off.

**Comment by gordon-matt** [comment]
I just noticed: I think I have accidentally overwritten your version of `imagefilter` with my own. I spent some time making these changes and then when I wanted to commit them, I noticed I was working on the main repo and not a fork. So I forked peachpie and then copied over the 2 files I was working on and checked in, assuming you guys hadn't made any changes to the graphics library in that short time.. but it seems you did. So please feel free to put your own version of `imagefilter` back there instead of mine.

**Comment by jakubmisek** [comment]
@gordon-matt I checked the PR and commented everything I could : )

**Comment by jakubmisek** [comment]
The PR has been merged. May I ask for the updated list of missing functions? : )

**Comment by gordon-matt** [comment]
I think you just need to find time to implement the few functions in my PR where I was throwing a `NotImplementedException`. Other than that, all good I think.

**Comment by jakubmisek** [comment]
closing, please open new issue for specific GD function if necessary.
