### ISSUE TITLE
How to exclude config.php from compilation properly

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#194]
Compiled **.php** is great, except when one of those **.php** files is supposed to serve as a configuration file, similar to an ASP.NET site's **web.config**. We need a way of either specifying that the config file should not be compiled into the DLL (but having **Peachpie** still able to use it) or else an alternative maybe is passing in something from the C# side to the PHP file.. but that is not very ideal. Do you already have a solution for this? If not, we need something.

**NOTE**: This is related to issue #185

**Comment by jakubmisek** [comment]
Currently there are several options:
- recompile project every time you change your config (e.g. before publish)
- in your project file (.msbuildproj), exclude the config PHP file (https://blogs.msdn.microsoft.com/msbuild/2006/03/08/how-to-exclude-multiple-files-from-a-wildcard/), hook into `PhpRequestOptions.BeforeRequest` and create the configuration global variable programically in C#
- like above but use PeachPie scripting API to compile PHP configuration code dynamically once your app starts, hook into `PhpRequestOptions.BeforeRequest` and invoke the dynamically compiled config.php code
- modify PHP config code to read values from .NET configuration (and cache it into an app-static variable)

**Comment by gordon-matt** [comment]
Thanks. The last option there is not a viable one for me, as I am not familiar with PHP and moreover I prefer not to change too much of the 3rd party code. I will look into one of the other options though and will close this issue asap if I find something suitable. Thanks again.

**Comment by jakubmisek** [comment]
`BeforeRequest` runs before request, but then `config.php` gets called and overwrites your value, probably.

**Comment by gordon-matt** [comment]
Yeah, I guessed that's what was happening too. OK, is there a way I can store my values in my **appsettings.json** in the .NET Core site and then pass those into Peachpie and read them from inside the **config.php** file? For example:

```
$config = array(
	'current_path' => [Pass value here from .NET Core],
	'thumbs_base_path' => [Pass value here from .NET Core],
	// etc
);
```

**Comment by jakubmisek** [comment]
first, your previous code stores into the global variable `$current_path`, not `$config["current_path"]`

#### [Pass value here from .NET Core] ?
several options, for now I would recommend to pass it from your global variable `$appsettings["config_path"]` which you will create in `BeforeRequest`
```csharp
ctx.Globals["appsettings"] = (PhpValue)new PhpArray(){ {"config_path", ".../.../..."} };
```
Then in PHP:
```php
$config = $appsettings;
```

**Comment by gordon-matt** [comment]
Well that certainly does the trick!

To anyone who might find this useful, my solution was as follows:

**Startup.cs:**
```
public void ConfigureServices(IServiceCollection services)
{
    // etc
    
    services.Configure<ResponsiveFileManagerConfig>(Configuration.GetSection("ResponsiveFileManagerConfig"));
    
    // etc
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    // etc

    var rfmOptions = app.ApplicationServices.GetRequiredService<IOptions<ResponsiveFileManagerConfig>>().Value;

    app.UsePhp(new PhpRequestOptions(scriptAssemblyName: "ResponsiveFileManager")
    {
        RootPath = Path.GetDirectoryName(Directory.GetCurrentDirectory()) + "\\Website",
        BeforeRequest = (Context ctx) =>
        {
            ctx.Globals["appsettings"] = (PhpValue)new PhpArray()
            {
                { "upload_dir", rfmOptions.UploadDirectory },
                { "current_path", rfmOptions.CurrentPath },
                { "thumbs_base_path", rfmOptions.ThumbsBasePath }
            };
        }
    }
    
    // etc
}
```

**config.php**
```
$config = array(
    // etc
    'current_path' => $appsettings['current_path'],
    'thumbs_base_path' => $appsettings['thumbs_base_path'],
    // etc
);
```

Thanks for that.

**Comment by kripper** [comment]
Hi @gordon-matt , I tried your code, but it gave me syntax errors.

```
    app.UsePhp(new PhpRequestOptions(scriptAssemblyName: "ResponsiveFileManager")
    {
        RootPath = Path.GetDirectoryName(Directory.GetCurrentDirectory()) + "\\Website",
        BeforeRequest = (Context ctx) =>
        {
            ctx.Globals["appsettings"] = (PhpValue)new PhpArray()
            {
                { "upload_dir", rfmOptions.UploadDirectory },
                { "current_path", rfmOptions.CurrentPath },
                { "thumbs_base_path", rfmOptions.ThumbsBasePath }
            };
        }
    }
```
