### ISSUE TITLE
PHP ini configuration not implemented.

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#196]
`ini_get('')`, `ini_set('', ...)` and other functions pertaining to PHP configuration are not implemented. In my case, the code is trying to **get** and/or **set** the following values:

`memory_limit`
`max_execution_time`
~~`post_max_size`~~
~~`allow_url_fopen`~~
~~`safe_mode`~~ // removed in PHP 5.4
~~`disable_functions`~~ // in https://github.com/peachpiecompiler/peachpie/commit/326aa52c09fd1dea46f939c1e7a250471b01c6d0
~~`upload_max_filesize`~~
~~`open_basedir`~~

The file manager I am trying to run needs these and is not generating thumbnails, at least in part due to `memory_limit` missing.

All of the above and more I found in Phalanger, here: [PhpIni.CLR.cs](https://github.com/DEVSENSE/Phalanger/blob/master/Source/ClassLibrary/PhpIni.CLR.cs).

Will this be a lot of effort?

**NOTE**: This is related to issue #185

**Comment by gordon-matt** [comment]
OK I looked into the Peachpie code a bit deeper and I can see you have actually done some of the ini configuration. I just noticed `static PhpValue GsrCore(static PhpValue GsrCore(Context ctx, IPhpConfigurationService config, string option, PhpValue value, IniAction action)` in **Options.cs**... but it's missing some functions like `memory_limit`.

**Comment by jakubmisek** [comment]
Good point. Few of them are already supported. Can you please make a list of options used within `ini_get` and `ini_set` separately? Because `ini_get` is easy to implement for all of them, `ini_set` might be tricky since it is mostly not possible in .NET (the configuration is somewhere else and we can't change it once the app starts)

**Comment by jakubmisek** [comment]
`memory_limit` cannot be set in .NET, however, there is a bug in Responsive File Manager.
 They should check for `$memory_limit` is `-1` (https://github.com/gordon-matt/peachpie-responsive-file-manager/blob/3fbb7a7e8467e48baa9e6985def53b5d87b7597e/Website/filemanager/include/utils.php#L587).

**Comment by jakubmisek** [comment]
`max_execution_time` will be implemented

**Comment by gordon-matt** [comment]
All of the ones I listed above are for `ini_get`. For `ini_set`, I can only see one of them, which is **memory_limit** and I think that can be ignored. I already checked in a PR for you for **memory_limit** which simply returns -1, which is what Phalanger seems to do, if I am not mistaken. I might not need to care too much about the other ones, I am not sure yet.. but I definitely need **memory_limit** which is in my latest pull request

**Comment by jakubmisek** [comment]
@gordon-matt PR was "merged" (I've added code that also registers the options to be actually used)

ini_get for `memory_limit` is supported, but it returns `-1` according to PHP manual and Responsive File Manager doesn't handle that

**Comment by gordon-matt** [comment]
Regarding the bug in RFM, I am actually using quite an old version (more than a year old).. because that's what I've been using in my old CMS for quite a long time now... I did actually try using the latest version with Peachpie, but it seems they are now using a lot more PHP functions that aren't implemented in Peachpie yet, and so I got a LOT more errors than just using this old version. I will work on trying to upgrade it later once I get the old one working first, which is my priority right now.

**Comment by jakubmisek** [comment]
In that case, just `return true;` in https://github.com/gordon-matt/peachpie-responsive-file-manager/blob/3fbb7a7e8467e48baa9e6985def53b5d87b7597e/Website/filemanager/include/utils.php#L567

**Comment by gordon-matt** [comment]
Very weird.. I see that's what I did before.. there's even a comment there saying why I ignored it for Phalanger... but for some reason I commented it out.. I think I remember now - I saw some warnings in Peachpie about "Unreachable code" and made that change thinking Peachpie would be different. Sorry, my stupid mistake.. Thanks for the help

**Comment by gordon-matt** [comment]
As `max_execution_time` will be implemented and all the others have been addressed, I will close this issue.
