### ISSUE TITLE
Feature: Please implement the `error_log` function.

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#198]
Please implement the `error_log` function. This will make it easier for me to write debug info when the code is in a NuGet package. Otherwise, there's no other way for me to check values of some variables.

**NOTE:** This is related to issues #185 and #195.

**Comment by jakubmisek** [comment]
just note: to watch values and debug your code, use Visual Studio

**Comment by gordon-matt** [comment]
Yes, but that can only be done when referencing the `.msbuildproj`. If I use a NuGet package instead, then I can't step into that code in the NuGet package, right? That's the problem I am having.

**Comment by jakubmisek** [comment]
you can create debug nuget package (it will have PDB file inside), the rest is the same

**Comment by gordon-matt** [comment]
Oh I see. I didn't realize NuGet packages came with PDBs. I will try that. In any case, it will still be good to have `error_log` implemented as well. If the PDB works though, then no rush I suppose. I will try that soon.

**Comment by gordon-matt** [comment]
My NuGet package didn't have the PDB in it and I read something about needing a `[package id].symbols.nupkg` file now instead.. anyway, I didn't need it in the end (See issue #195 - now closed). Still, please implement `error_log()` when you have time.

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/f6ee8e3cb50f06260d43b9b56fea35ed07175733
