### ISSUE TITLE
Support for a self-contained assembly

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#199]
While getting Responsive File Manager to work in Peachpie, I have come across another issue.. I keep receiving this error:

**"Language file is missing!"**

When I looked into it, I can see that it is trying to load some **.php** files from `/filemanager/lang/[iso_code].php`. I get that error every time I create a folder or delete a file, etc.

Now, the problem is... I believe it is looking in the `wwwroot` of the main **ASP.NET MVC** project (named **WebApplication**), but the language files are in the **Peachpie** lib project (named **Website**). So I moved these **.php** language files to `wwwroot/filemanager/lang`... since the other static files are already there (`wwwroot/filemanager/css`, `wwwroot/filemanager/js`, etc). However, when I do this, I get an error message because the files no longer exist where they are supposed to. So in order to get everything to work nicely, I have to duplicate the files (have them all in both locations). Because I guess what's happening is this:

1. For `include 'something.php'`, it requires the file to be in the **Peachpie** library

2. However, when the file manager uses `file_exists()` function, then it's looking in the `/wwwroot/` of my **MVC** app.

I hope I explained this properly. So, basically I don't have the error anymore, but it's an ugly workaround to have to duplicate the files. Is there anything you can do for future? Maybe you have a better idea, but I was thinking maybe some new option to tell peachpie to look for all **.php** files (or a specified collection of files?) in the Peachpie project and look for static files (js, css, etc) in the main **MVC** project. Is this possible?

**NOTE:** This is related to issue #185

**Comment by gordon-matt** [comment]
I was just thinking an even better solution to all of this is the following: Can there be an option to search for all files (including all static JS, CSS, images and other files) from embedded resources? Because one of the annoying issues I am having is I can only include php files into the NuGet package, but then I need to copy all the static files between each project, again and again... as the static files are in the main app's wwwroot folder while the php files are in the Peachpie NuGet package. It would be far better if I could have all the files together in 1 package and simply reference the NuGet and pass my options.

**Comment by jakubmisek** [comment]
NuGet package should contain these content files, and `RootPath` should be configured properly.

**Comment by gordon-matt** [comment]
I already tried that before - it didn't work, so I thought it wasn't supported - maybe I configured `RootPath` incorrectly. If using [peachpie-responsive-file-manager](https://github.com/gordon-matt/peachpie-responsive-file-manager), what should the `RootPath` be? I have tried the following but it doesn't work:

`RootPath = Path.GetDirectoryName(Directory.GetCurrentDirectory()) + "\\Website"`

Also, what would the `RootPath` be if I use it in a NuGet package (like this project: [peachpie-rfm-nuget-test](https://github.com/gordon-matt/peachpie-rfm-nuget-test))?

**Comment by jakubmisek** [comment]
`PhpRequestOptions.RootPath` is used internally by PHP (Peachpie) runtime so all the file operations (include, fread, is_file, ...) are relative to that path.

If you need to setup content files (.js, .css, ...) to be accessible from web browser, setup ASP.NET Core Middleware pipeline properly with `.UseStaticFiles(  {your folder} )`

**Comment by gordon-matt** [comment]
Thanks @jakubmisek , but please read the whole issue again, because I'm not sure that you are understanding the problem. Yes, I did mention CSS, JS and other static files... but that is not the main problem. There are some PHP files that are being requested in 2 different ways:

1. For `include 'something.php'`, it requires the file to be in the Peachpie library (embedded)

2. However, when the file manager uses `file_exists()` function, then it's looking in the '/wwwroot/' of my MVC app.

So I can't have these PHP files in only one place - they must be in both...

Anyway, that's why I suggested an option for not only php files, but any static files to be able to be embedded inside the peachpie library, so that when `file_exists()` or other file system methods are called, it can look in the php assembly instead of external files in my wwwroot. Is this possible? If not, I will have 2 problems:

1. Anyone who downloads my NuGet package has to separately go and find the static files for the file manager and place them in the wwwroot directory manually (that sucks).

2. And secondly, the PHP language files I mentioned will HAVE TO be duplicated both in the assembly (for `include`) and in the wwwroot (for `file_exists()`)

Maybe we can have an option like `PhpRequestOptions.StaticFilesAreEmbedded = true/false` ? Then for any JS, CSS, or even PHP files that are loaded from the file system, it will load from embedded resources in the assembly instead.

**Comment by gordon-matt** [comment]
Basically, I think it's a good idea to have a way to create a "self contained" assembly/NuGet package, so all resources are there without needing to go find the static files. Perhaps a `PhpRequestOptions.IsSelfConatined = true/false` option

**Comment by jakubmisek** [comment]
as noted - file_exists and other functions in PHP code use PhpRequestOptions.RootPath to resolve relative paths.

**Comment by jakubmisek** [comment]
with later update of Peachpie you don't have to have .php files as content anymore.

**Comment by jakubmisek** [comment]
You don't have to (should not) copy or duplicate anything anywhere. This is a manner of web servers pipeline; in this case, just add `UseStaticFiles( another path )` to your Configure() method.

You can of course compile content files (css, js, ...) as resources and implement your own RequestDelegate middleware which will pass corresponding resource to response stream ... anyway; you should be able to achive this with a two-line configuration, and no copying or duplicating is necessary.

**Comment by gordon-matt** [comment]
Are you suggesting to somehow add some `IEmbeddedFileManager` in the pipeline and pass the embedded path to `UseStaticFiles`? Maybe something like:

```
var responsiveFileManagerAssembly = typeof(Something).GetTypeInfo().Assembly;

app.UseStaticFiles();
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new EmbeddedFileProvider(responsiveFileManagerAssembly, "ResponsiveFileManager.wwwroot");
});
```

Is this what you are suggesting? I suppose I could try that. Will do tomorrow and let you know how it goes.

**Comment by gordon-matt** [comment]
Unfortunately, that didn't work. When I tried to set some files' **Build Action** to **Embedded Resource**, then I got an error as follows:

**"Resources are not allowed in PHP projects compiled by Peachpie"**

But I guessed maybe **Peachpie** sets them as embedded anyway, and so I tried the following:

```
string assemblyPath = Path.GetDirectoryName(Assembly.GetEntryAssembly().CodeBase.Substring(8)) + "\\ResponsiveFileManager.dll";
var responsiveFileManagerAssembly = Assembly.LoadFile(assemblyPath);

app.UseStaticFiles();
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new EmbeddedFileProvider(responsiveFileManagerAssembly, "ResponsiveFileManager")
});
```

This did not work.

FYI - I am going to change the title of this issue from "**Having to duplicate files to prevent errors**" to "**Support for a self-contained mode**"

**Comment by jakubmisek** [comment]
PeachPie compiler does not support embedded resources yet (you can create an issue for that).

The typical approach is to specify content files within your PHP project (NuGet package) and use content files.

**Comment by gordon-matt** [comment]
When you say, "Content" files, I can only guess that you mean files inside the main app (not in the NuGet package).. Otherwise, if you mean content files INSIDE the NuGet package, then how would that even work? Even if the Build Action is set to "Content" and they are somehow content files inside the NuGet package, then how do I configure my app to use those files inside that package? Can you give me an example? I know you said before to use `app.UseStaticFiles()` and I honestly don't see any other way to do that unless the files are embedded (as per my example that I tried above). If they are not embedded, how do I get my app to reference them? A code example would be appreciated, because I am just confused here.

**Comment by jakubmisek** [comment]
@gordon-matt 
This is how you define content files https://github.com/iolevel/peachpie-wordpress/blob/a5284a5cbcfe31bafcf8f680818028460858550c/WordPress/WordPress.msbuildproj#L16
They get copied into NuGet.
When you reference the NuGet, content files get copied to your project.
In your web app, add static files middleware pointing to the content files https://github.com/iolevel/peachpie-wordpress/blob/a5284a5cbcfe31bafcf8f680818028460858550c/Peachpie.WordPress.AspNetCore/RequestDelegateExtension.cs#L83

**Comment by gordon-matt** [comment]
Okay, I see. I appreciate the example and will give it a try, thanks.

**Comment by gordon-matt** [comment]
Could you please explain this part to me?:
`<PackagePath>contentFiles/any/netcoreapp2.0/wordpress/</PackagePath>`

It looks like an output path (for where the content files should go?) I guess "any" means it can be both Debug and Release mode, right? And what does the "contentFiles" prefix mean? Is it some variable or what? It doesn't look like a variable though, just plain text (part of the path).. Would be great if you could clarify, thanks.

**Comment by jakubmisek** [comment]
@gordon-matt it is according to NuGet specs; `contentFiles/any/netcoreapp2.0` means the files are provided as content files, for any language and netcoreapp2.0 target framework. `wordpress` is a path relative to target project root.

**Comment by gordon-matt** [comment]
Good news... I'm almost there!

I have the following in my **PHP** project:

`<ContentFiles>**/*.as;**/*.css;**/*.fla;**/*.gif;**/*.html;**/*.jpg;**/*.js;**/*.json;**/*.png;**/*.svg;**/*.swf;**/*.txt;</ContentFiles>`

and this:

```
<Content Include="$(ContentFiles)" Exclude="obj/**;bin/**">
    <PackagePath>contentFiles/any/netcoreapp2.0/wwwroot/</PackagePath>
    <PackageCopyToOutput>true</PackageCopyToOutput>
</Content>
```

It works nicely and has all the files show up as follows:

![rfm_1](https://user-images.githubusercontent.com/2860937/40238332-0735c314-5af2-11e8-865f-5625158004f6.PNG)

However, when I run it, it complains about the language PHP files missing (see original post in this issue). Obviously this is because I didn't add all php files like the other content files. So, I tried to add only the php files from the **lang** folder, like so:

`<ContentFiles>**/*.as;**/*.css;**/*.fla;**/*.gif;**/*.html;**/*.jpg;**/*.js;**/*.json;**/*.png;**/*.svg;**/*.swf;**/*.txt;lang/*.php</ContentFiles>`
> Notice the last part there...

But when I try to build it, I get this error:
`MSB3073 The command "dotnet compile-php @obj\Release\netstandard2.0\compile-php-args.rsp" exited with code 1.`

Did I use the wrong syntax for adding the **lang/*.php** files or is this an expected error because of Peachpie thinking that NO php files can be content files? In this case, we actually want those few lang files as both handled by Peachpie and also as content files (for reasons already mentioned in first few posts).

**Comment by gordon-matt** [comment]
OK never mind that problem; I restarted Visual Studio and now there is no such error when building. However, the **lang/*.php** files do not show up in my project when I reference the new NuGet package.

**Comment by jakubmisek** [comment]
@gordon-matt  yes, none of this is handled by peachpie, it is completely under the Microsoft's MSBuild tool.

**Comment by gordon-matt** [comment]
Hey, I finally figured it out! I added a new `<Content Include=...` entry, as follows:

```
<ItemGroup>
	<Compile Include="**/*.php" />
	<Content Include="$(ContentFiles)" Exclude="obj/**;bin/**">
		<PackagePath>contentFiles/any/netcoreapp2.0/wwwroot/</PackagePath>
		<PackageCopyToOutput>true</PackageCopyToOutput>
	</Content>
	<Content Include="filemanager/lang/*.php;">
		<PackagePath>contentFiles/any/netcoreapp2.0/wwwroot/filemanager/lang/</PackagePath>
		<PackageCopyToOutput>true</PackageCopyToOutput>
	</Content>
</ItemGroup>
```
Thanks for your help!
