### ISSUE TITLE
MissingMethodException for mysql_insert_id

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#202]
I just updated my packages from version **0.9.0-CI00872** to version **0.9.0-CI00880** and I am getting a **MissingMethodException**, as follows:

``System.MissingMethodException: Method not found: 'Int32 Peachpie.Library.MySql.MySql.mysql_insert_id(Pchp.Core.Context, Pchp.Core.PhpResource)'.
    at <Script>.BuiltinFunctions(Action`2 callback)``

Stack Trace:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Int32 Peachpie.Library.MySql.MySql.mysql_insert_id(Pchp.Core.Context, Pchp.Core.PhpResource)'.
   at <Script>.BuiltinFunctions(Action`2 callback)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Pchp.Core.Context.AddScriptReference(Type tscript)
   at Peachpie.Web.PhpHandlerMiddleware.LoadScriptAssemblies(PhpRequestOptions options)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

I can only assume this is due to the last [commit](https://github.com/peachpiecompiler/peachpie/commit/3ecb00ccb2e85313d5c199a1d4d66ea3d7803bc6).

**Comment by jakubmisek** [comment]
restore & rebuild

**Comment by gordon-matt** [comment]
@jakubmisek I already have and it didn't work. Just did a rebuild now again to make sure.. no difference.

**Comment by jakubmisek** [comment]
you definitely not consolidated your package references

**Comment by gordon-matt** [comment]
@jakubmisek Oh but I most definitely did... I've just checked my .csproj as well. See before and after (I'm using TortoiseGit's file compare tool):

**BEFORE:**

```
<PackageReference Include="Peachpie.Library" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.Library.Graphics" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.Library.MsSql" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.Library.MySql" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.Library.Network" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.Library.PDO" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.Library.Scripting" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.Library.XmlDom" Version="0.9.0-CI00872" />
<PackageReference Include="Peachpie.NETCore.Web" Version="0.9.0-CI00872" />
```

**AFTER:**
```
<PackageReference Include="Peachpie.Library" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.Library.Graphics" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.Library.MsSql" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.Library.MySql" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.Library.Network" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.Library.PDO" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.Library.Scripting" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.Library.XmlDom" Version="0.9.0-CI00880" />
<PackageReference Include="Peachpie.NETCore.Web" Version="0.9.0-CI00880" />
```
And I know this is not necessary, but JUST to make sure... I also deleted the `bin` and `obj` folders, then reopened Visual Studio and did a rebuild again... no difference.

**Comment by jakubmisek** [comment]
Have you checked all the projects - msbuildproj, csproj, ...

**Comment by gordon-matt** [comment]
Hold on.. sorry.. I see the problem. Look here: https://ibb.co/nvix2H

**Comment by gordon-matt** [comment]
SDK is the only lib not referenced directly by main project. I will fix. Thanks for your time anyway

**Comment by jakubmisek** [comment]
good, once we stop making changes to API, this would not be necessary

**Comment by jakubmisek** [comment]
Yes you have to re-release it for every peachpie version. Usually you would make releases for every major version (like once in 6 months) but if you wish to update daily you have to update daily everything.

**Comment by gordon-matt** [comment]
Ouch, that's a pain. OK I guess we can't do anything about it. Thanks anyway. When are you guys planning to release the stable version?

**Comment by jakubmisek** [comment]
there are few major features to do before `1.0` version, see https://github.com/peachpiecompiler/peachpie/wiki/Peachpie-Roadmap for more information. But I think we are getting closer : )
