### ISSUE TITLE
Create and Access SQLite3 File Database with PHP?

### ISSUE THREAD

**Issue by SanduRajapakse** [peachpiecompiler/peachpie#203]
Hi all,
I am new to Peachpie and am looking to make an app that runs locally and therefore needs a database to be stored locally on the users PC (ex. local.db.sqlite or something).

I tried my best look through the Docs and Tuts, but I can't figure out how to get it to work.

Can someone please inform me on how to create and use a that is not running on an external server?

Thank you in advance!

**Comment by bfistein** [comment]
Hi @SanduRajapakse, apologies for the late reaction due to many other commitments. We will get to your issue momentarily.

**Comment by jakubmisek** [comment]
installing sqlite locally is out of scope of this project, closing
