### ISSUE TITLE
Cannot get the new 0.9-template to publish correctly

### ISSUE THREAD

**Issue by itssimple** [peachpiecompiler/peachpie#205]
We're trying to use `dotnet publish` and `octo pack` on a project with Peachpie.

But when we try to use either a local IIS with the published version (or via Octopus Deploy), we can't get the server/website to work.

But if we run `dotnet run` manually it works.

**Comment by jakubmisek** [comment]
@itssimple do you have more information? An exception or a comparison of files published using `dotnet publish`? Maybe you need content files to be published together with binaries (`<Content Include="**/*.php" />`)

**Comment by jakubmisek** [comment]
closed for inactiveness
