### ISSUE TITLE
Error establishing database connection

### ISSUE THREAD

**Issue by djacobsmeyer** [peachpiecompiler/peachpie#206]
I didn't have the ability to submit an issue on the Wordpress repo itself, but that is the codebase which I've run into an issue. 

I download the zipped project (and extracted the contents), ran the provided docker command to start a mysql instance, ran dotnet restore, ran dotnet run, and while I didn't get any actual errors returned for any of those commands, I do get loads of warnings about unreachable code and calls to undefined functions. When I go to localhost:5004 I get a 500 error saying 'Error establishing database connection'.

I noticed that the repo has changed a bit recently and that the documentation has not. Am I missing something? I've tried this on 3 different user accounts across 2 different macOS machines.

**Comment by jakubmisek** [comment]
`Error establishing database connection` is a WordPress regular message simply saying - it couldn't connect to your MySQL database. Check `wp-config.php` that your credentials are correct.

**Comment by iwhp** [comment]
I do have the same issues as djacobsmeyer.
I have checked wp-config.php and everything seems fine.

**Comment by bfistein** [comment]
@djacobsmeyer @iwhp still having this issue after double checking that your credentials are correct?

**Comment by djacobsmeyer** [comment]
Yes, I tried the whole process many times following instructions to the letter.

**Comment by jakubmisek** [comment]
@djacobsmeyer Hi, this can be caused by a bunch of reasons (usually when using latest mysql server, there are some new restrictions and limitations when not using secure connection).

Sadly WordPress does not tell you details of the failure. Anyway; start the project from within a VS or V S Code or attach to the `dotnet` process from your VS or VS Code. You will see the detailed error message in `Output` window.

**Comment by mammadkoma** [comment]
I had this problem on VS 2019 and windows 10. I saw the output that said : "Access denied for user 'root'@'localhost' (using password: YES)" 
I solved by edit my.ini file : https://www.youtube.com/watch?v=LKE1G4sinBM
