### ISSUE TITLE
does stdio supported?

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#207]
i try to use STDOUT to echo something, but nothing happened.
```php
fwrite(STDOUT,'hello');
```

**Comment by bfistein** [comment]
Hi @liesauer, `STDOUT` is indeed not yet supported by PeachPie. We can implement it fairly soon. Are you trying to use it in a bigger project or just playing around?

**Comment by jakubmisek** [comment]
latest commit https://github.com/peachpiecompiler/peachpie/commit/15221055e3dc71abc4f154054a9cfeb2eb2ad107 just adds support for STDIN,STDOUT,STDERR. It only works when targeting console application.

**Comment by liesauer** [comment]
@bfistein i am going to write a spider using c# and php, i am used to using STDIO for my little php spider, when i run my simple hybird demo, i found that it seems to be not support STDIO.

**Comment by bfistein** [comment]
It is now supported since commit [1522105](https://github.com/peachpiecompiler/peachpie/commit/15221055e3dc71abc4f154054a9cfeb2eb2ad107), but only for console applications.

**Comment by liesauer** [comment]
@bfistein the best way to run a spider obviously is the cli environment.
