### ISSUE TITLE
Cross target .NETSTANDARD 2.0

### ISSUE THREAD

**Issue by iamcarbon** [peachpiecompiler/peachpie#208]
Are there plans to cross target .NETSTANDARD 2.0? This would minimize the dependencies when used in a .NETCOREAPP project.

**Comment by bfistein** [comment]
Hi @iamcarbon, we have been targeting netstandard2.0 for a while now. More info [here](https://www.peachpie.io/2017/11/php-netstandard-2-0.html). Can I close this issue or do you have additional questions about this?
