### ISSUE TITLE
need help on hybird programming

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#211]
is there any fully manual about hybird programming using c# and php? those samples is not enough. it will take a lots of learning time by reading the peachpie codes

**Comment by bfistein** [comment]
Of course. There are plenty on our [blog](https://www.peachpie.io/blog), like [this one](https://www.peachpie.io/2017/10/wordpress-plugin-csharp.html) or [this one](https://www.peachpie.io/2017/01/csharp-php-interop.html) or [this article](https://www.peachpie.io/2018/01/peachpie-php-code-together.html). We try to make detailed tutotials as often as possible.

**Comment by bfistein** [comment]
Hope it helps, feel free to let us know what problrms you run into on Gitter.
