### ISSUE TITLE
Discuss PHP/MySQL vs ADO.NET

### ISSUE THREAD

**Issue by bgrainger** [peachpiecompiler/peachpie#217]
I'm knowledgeable about the MySQL protocol and ADO.NET conventions for exposing it. I don't know a lot about PHP, mysql, mysqli, or PDO.

If you're interested, I'm open to meeting with someone who _does_ know about those topics to discuss how PHP's MySQL APIs can be mapped safely and correctly onto an ADO.NET MySQL driver's connection string options and .NET API.

I expect that this discussion would result in a document (or possibly a list of GitHub issues) that outline how to adapt ADO.NET to PHP.

**Comment by bgrainger** [comment]
Additional discussion topic: exposing async APIs to PHP.

**Comment by jakubmisek** [comment]
This is already done and tested. We can only add something to the connection string.

And there is no async API in PHP (every function gets the result immediately).

**Comment by bgrainger** [comment]
I was referring to things like `mysql_connect` vs `mysql_pconnect` (this would control `Pooling=true/false`), the `p:` prefix to the hostname in `mysqli_connect`, `PDO::ATTR_PERSISTENT`, whether PeachPie should pretend it was compiled with `MYSQLI_NO_CHANGE_USER_ON_PCONNECT` or not (this would control `ConnectionReset=true/false`).

> Prepending host by p: opens a persistent connection. mysqli_change_user() is automatically called on connections opened from the connection pool.

From [here](http://docs.php.net/manual/en/mysqli.construct.php). This makes it sound like `ConnectionReset=true` _should_ be on for PHP/MySQL compatibility.

**Comment by jakubmisek** [comment]
Good point, you are right. Maybe if the polling is smart enough and takes into account the entire connection string (including the user), you don't have to enable `ConnectionReset`?

Otherwise as you said.

Also we can remember what user and database is selected for the connection and do not re-select it if not necessary. `PeachPie` manages its own set of polled connections anyway; I assume it could be removed if polling in `MySqlConnector` works fine.

**Comment by jakubmisek** [comment]
@bgrainger since we didn't know much about mysql polling, there is already implemented very naive polling in PeachPie; as I understand we can get rid of it and rely on `Polling` property?

**Comment by bgrainger** [comment]
Yes, you should be able to remove any pooling code you have and rely on MySqlConnector's built-in connection pool.

`Pooling=True` (which is on by default) will cause MySqlConnector to retrieve an existing connection from the pool (whenever possible); `Pooling=False` will force a new connection to the server every time.

**Comment by jakubmisek** [comment]
ok, so I may close the issue for now. Please open a new one if there would be more.

Basically PHP just forwards calls to some native mysql lib, so MySqlConnector should be able to do the same. Additionally there will be performance concerns and possible improvements.

**Comment by jakubmisek** [comment]
@bgrainger quick question - is it realistic to accept PR to MySqlConnector with a new connection string option `"dbname"` (alias to `"Database"`) ?
