### ISSUE TITLE
simplexml_load_string is throwing CLR/System.NullReferenceException if second parameter is given

### ISSUE THREAD

**Issue by tobihille** [peachpiecompiler/peachpie#219]
Hi there!

Sadly simplexml_load_string is throwing **CLR/System.NullReferenceException** An exception of type 'System.NullReferenceException' occurred in Peachpie.Library.XmlDom.dll but was not handled in user code: 'Object reference not set to an instance of an object.' if the second parameter of this function is used.

I can reproduce it with the following code:
<pre>
class FooBarBaz extends SimpleXMLElement {
  //dummy
}

$string = &lt;&lt;&lt;XML
&lt;?xml version='1.0'?&gt;
&lt;document&gt;
 &lt;body&gt;
  Some text
 &lt;/body&gt;
&lt;/document&gt;
XML;

$xml = simplexml_load_string($string, 'FooBarBaz');

print_r($xml);
</pre>

We tried to use peachpie to compile Magento 1 and encountered the error there. If you need context, the line inside the project is https://github.com/tobihille/magento-peachpie/blob/master/website/lib/Varien/Simplexml/Config.php#L510.

If we (https://github.com/Sdfendor or me) can help tracking this down we would be happy to help.

Also: Thank you for this exciting technology and the good samples!

Kind regards

- Tobi

**Comment by jakubmisek** [comment]
Hi @tobihille, great test case! the nullref should be fixed now, please just note `print_r` on `SimpleXmlElement` gets weird results which is expected.
