### ISSUE TITLE
Issue with some date_ functions

### ISSUE THREAD

**Issue by tobihille** [peachpiecompiler/peachpie#221]
Hi,

first: thank you for your last and fast fix. After recompiling and updating peachpie i now get an error in some date functions, maybe they are related (or I compiled it wrong and that's just the tip of the iceberg).

The first function throwing an exception is date_default_timezone_get() and the error is **CLR/System.TypeInitializationException**
<pre>
An exception of type 'System.TypeInitializationException' occurred in Peachpie.Library.dll but was not handled in user code: 'The type initializer for 'Pchp.Library.DateTime.PhpTimeZone' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Xml.XmlException : Data at the root level is invalid. Line 1, position 1.
</pre>

The second function throwing an exception is date_default_timezone_set(). I tried setting "UTC" or "Europe/Berlin", both resulted in the above exception, too.

After encountering these two errors I wanted to check for available timezones and got error number three and four:
* http://php.net/manual/en/function.timezone-abbreviations-list.php is not available and 
* calling http://php.net/manual/en/datetimezone.listabbreviations.php even breaks the compiler.

Again for context, the call inside Magento that's failing is the following: https://github.com/tobihille/magento-peachpie/blob/master/website/app/code/core/Mage/Core/Model/App.php#L378
I encountered the other errors while trying to correct the issue on the php-side.

Kind regards 

- Tobi

**Comment by jakubmisek** [comment]
`TypeInitializationException` probably only happening on Linux (will be fixed)

Compilation error will be fixed, the method was incorrectly declared as non-static.

However; we do't know where to collect abbrevations yet.

**Comment by jakubmisek** [comment]
Nice, can you check please the `TypeInitializationException` again? It does not happen on our environments.

We are actually using a combination of up-to-date time zones from OS through .NET API (which also gets updated through windows update) and this feed http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml ... however it misses the abbreviations. We might add them separately using the script you've noted.

**Comment by tobihille** [comment]
Sorry, totally forgot to check if your commit works. Have checked it now, everything is fine. Thanks a lot!

**Comment by jakubmisek** [comment]
@tobihille thanks! so the only remaining issue is the abbreviations.

**Comment by jakubmisek** [comment]
status: the only thing remaining are the abbreviations.

**Comment by jakubmisek** [comment]
@tobihille timezone_abbreviations_list now lists available abbreviations as in PHP

closing
