### ISSUE TITLE
System.InvalidOperationException when calling unset in class inheriting from SimpleXMLElement on class member

### ISSUE THREAD

**Issue by tobihille** [peachpiecompiler/peachpie#222]
Hi,

I think I found a rather exotic issue. The following code throws an exception
<pre>
class Foo extends SimpleXMLElement {
    public function bar() {
        $var = 'date';
        unset($this->$var);
    }
}
$foo = new Foo();
$foo->bar();
</pre> while this code runs as expected 
<pre>
class Foo {
    public function bar() {
        $var = 'date';
        unset($this->$var);
    }
}
$foo = new Foo();
$foo->bar();</pre>.

The exception thrown is **CLR/System.InvalidOperationException**
An exception of type 'System.InvalidOperationException' occurred in System.Linq.Expressions.dll but was not handled in user code: 'The unary operator IsFalse is not defined for the type 'System.Void'.'

Kind regards

- Tobi

**Comment by tobihille** [comment]
Oops, totally forgot to mention the location where it happens inside magento: https://github.com/tobihille/magento-peachpie/blob/master/website/lib/Varien/Simplexml/Element.php#L423
I hope this is of use.

**Comment by jakubmisek** [comment]
Thanks!
