### ISSUE TITLE
DBNAME option in datasource of MySQL PDO Driver

### ISSUE THREAD

**Issue by tobihille** [peachpiecompiler/peachpie#227]
Hi,

sadly I can not create a connection to MySQL. The following sample code only echoes "FOO" and then dies.
<pre>
echo "FOO";
$dsn = 'mysql:dbname=dt;host=localhost';
$pdo = new PDO($dsn, "user", "password", []);
echo "BAR";
$result = $pdo->query('select * from admin_user');
echo "BAZ";
</pre>

When debugging in VS Code (by the way: this is amazing!) I see the following lines in the debugging-console after calling `new PDO(...)`:
<pre>
Exception thrown: 'System.ArgumentException' in MySqlConnector.dll
Exception thrown: 'System.ArgumentException' in System.Data.Common.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
</pre>

Just for reference: Magento uses (in my case) the following Data Source Name: `mysql:host=127.0.0.1;dbname=hackathon_m1;initStatements=SET NAMES utf8;model=mysql4;type=pdo_mysql;pdoType=;active=1`

I wish I could provide more data but every try (I stripped the $dsn - String down to the example mentioned in the example code) resulted in the same error.
Scince wordpress runs already on peachpie and does basically the same thing (https://github.com/WordPress/WordPress/search?q=new+PDO%28&unscoped_q=new+PDO%28) I assume at the moment I'm doing something wrong but I have no idea what this might be.

Kind regards
- Tobi

**Comment by jakubmisek** [comment]
actually wordpress uses `mysqli` and `mysql` functions. It does not make use of `PDO`.

**Comment by jakubmisek** [comment]
note: `PDO` is not tested at all, so we might try that first. Does it throw another exception? In VSCode, Debugging pane at the bottom, you can tick "All Exceptions" and it might give you detailed information about exceptions.

**Comment by tobihille** [comment]
Thanks for the hint. By checking "All Exceptions" VS Code stopped with the following exception:
**CLR/System.ArgumentException**
<pre>
Exception thrown: 'System.ArgumentException' in MySqlConnector.dll: 'Option 'dbname' not supported.'
   at MySql.Data.MySqlClient.MySqlConnectionStringOption.GetOptionForKey(String key) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnectionStringBuilder.cs:line 354
</pre>
Please note: the path C:\projects does not exist on my machine. When hovering the tab VS Code says the opened file is this: https://github.com/mysql-net/MySqlConnector/blob/fe426352f29a7087d700e99d2550ceb4d0305ee9/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnectionStringBuilder.cs#L354

I guess what is misssing is a map to mysql-connector-names like they are mentioned here: https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html

**Comment by jakubmisek** [comment]
@tobihille thats it, if [MySqlConnector](https://github.com/mysql-net/MySqlConnector/) would support `dbname` option directly, it would be perfect. Otherwise PeachPie has to convert these names to valid option names.
