### ISSUE TITLE
Performance problem : Invoking a PHP file will get slower and slower

### ISSUE THREAD

**Issue by ghominejad** [peachpiecompiler/peachpie#232]
We have a `PHP` page and we want to call it from c#.  (it uses wordpress libraries)
After compiling, the size of compiled library became about 10mb.

The first call took only 18ms but next calls got slower and slower.
After only 200 times of invocation, each calls took 200ms!

```CSHARP
public static void LoadAssembly()
{
            Assembly asm = LoadAssembly();
            Context.AddScriptReference(asm);
            TypeInfo mainPage = FindMainPage(asm);
            string ScriptPath = "index.php";
            indexScript = new ScriptInfo(0, ScriptPath, mainPage);

            ctx = Context.CreateEmpty();
            ctx.RootPath = targetFolder;
            ctx.WorkingDirectory = targetFolder;
}

public static string RunPage()
{
            var result = indexScript.Evaluate(ctx, ctx.Globals, null);
            return result.String;
}

public static void Test()
{          
           LoadAssembly();

            for (var i= 0; i <= 200; i++) {
                     RunPage();
            }
}
```

**Comment by jakubmisek** [comment]
10MB is a lot, assuming it can does a lot of things .. have you tried a profiler? Diagnostic Tools in Visual Studio will tell you how much CPU is consumed by what function. If there is something taking more and more time, feel free to make an issue so we can optimize it. Note when debugging there is a lot of overhead in case there are some runtime PHP warnings (see Debug Output)

**Comment by ghominejad** [comment]
Thanks for quick response,

I've checked and seems the problem comes from my internal libraries.
I'll look more closely and inform you the result.

Thanks for the great job you do

**Comment by jakubmisek** [comment]
Thanks! please let us know if you'll find any issue in the project.

We're glad you've found PeachPie useful!
