### ISSUE TITLE
The command dotnet compile-php exited with code -532462766

### ISSUE THREAD

**Issue by genifycom** [peachpiecompiler/peachpie#233]
When I use this in Visual Studio 15.7.4 with .NET Core 2.1 and csproj settings of

  <ItemGroup>
    <Compile Include="**/*.php" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Peachpie.Compiler.Tools" Version="0.7.0-*" />
    <PackageReference Include="Peachpie.NET.Sdk" Version="0.7.0-*" PrivateAssets="Build" />
  </ItemGroup>
  <PropertyGroup>
    <CSharpDesignTimeTargetsPath Condition="'$(CSharpDesignTimeTargetsPath)'==''">$(MSBuildExtensionsPath)MicrosoftVisualStudioManagedMicrosoft.CSharp.DesignTime.targets</CSharpDesignTimeTargetsPath>
  </PropertyGroup>
  <Import Project="$(CSharpDesignTimeTargetsPath)" Condition="'$(CSharpDesignTimeTargetsPath)' != '' and Exists('$(CSharpDesignTimeTargetsPath)')" />

and I try to build index.php, I get the following error:

C:\Users\Test\.nuget\packages\peachpie.net.sdk\0.7.0-ci00318\build\Peachpie.NET.Core.Sdk.targets(148,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netcoreapp2.1\compile-php-args.rsp" exited with code -532462766.

**Comment by jakubmisek** [comment]
please check the output for errors and exceptions, there must be some more information like `Exception ... `

**Comment by genifycom** [comment]
1>Target CoreCompile:
1>  Peachpie PHP Compiler.
1>
1>  Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: ambiguity
1>
1>     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
1>     at System.Environment.get_StackTrace()
1>     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
1>     at System.Diagnostics.Debug.Assert(Boolean condition, String message)
1>     at Pchp.CodeAnalysis.Symbols.AssemblySymbol.GetTypeByMetadataName(String metadataName, Boolean includeReferences, Boolean isWellKnownType, Boolean useCLSCompliantNameArityEncoding, DiagnosticBag warnings)
1>     at Pchp.CodeAnalysis.PhpCompilation.GetWellKnownType(WellKnownType type)
1>     at Pchp.CodeAnalysis.Symbols.SynthesizedScriptTypeSymbol.CreateEnumerateReferencedFunctionsSymbol()
1>     at Pchp.CodeAnalysis.Symbols.SynthesizedScriptTypeSymbol.get_EnumerateReferencedFunctionsSymbol()
1>     at Pchp.CodeAnalysis.Emit.PEModuleBuilder.CreateEnumerateReferencedFunctions(DiagnosticBag diagnostic)
1>     at Pchp.CodeAnalysis.SourceCompiler.CompileReflectionEnumerators()
1>     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
1>     at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1350
1>     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1714
1>     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 437
1>     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 295
1>     at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output)
1>     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
1>     at System.Diagnostics.Debug.WindowsDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
1>     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
1>     at System.Diagnostics.Debug.Assert(Boolean condition, String message)
1>     at Pchp.CodeAnalysis.Symbols.AssemblySymbol.GetTypeByMetadataName(String metadataName, Boolean includeReferences, Boolean isWellKnownType, Boolean useCLSCompliantNameArityEncoding, DiagnosticBag warnings)
1>     at Pchp.CodeAnalysis.PhpCompilation.GetWellKnownType(WellKnownType type)
1>     at Pchp.CodeAnalysis.Symbols.SynthesizedScriptTypeSymbol.CreateEnumerateReferencedFunctionsSymbol()
1>     at Pchp.CodeAnalysis.Symbols.SynthesizedScriptTypeSymbol.get_EnumerateReferencedFunctionsSymbol()
1>     at Pchp.CodeAnalysis.Emit.PEModuleBuilder.CreateEnumerateReferencedFunctions(DiagnosticBag diagnostic)
1>     at Pchp.CodeAnalysis.SourceCompiler.CompileReflectionEnumerators()
1>     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
1>     at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
1>     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>     at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output)
1>     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)

**Comment by genifycom** [comment]
Project file is:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="index.php" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Peachpie.Compiler.Tools" Version="0.7.0-*" />
    <PackageReference Include="Peachpie.NET.Sdk" Version="0.7.0-*" PrivateAssets="Build" />
  </ItemGroup>

  <ItemGroup>
    <None Include="index.php" />
  </ItemGroup>

  
  <PropertyGroup>
    <CSharpDesignTimeTargetsPath Condition="'$(CSharpDesignTimeTargetsPath)'==''">$(MSBuildExtensionsPath)MicrosoftVisualStudioManagedMicrosoft.CSharp.DesignTime.targets</CSharpDesignTimeTargetsPath>
  </PropertyGroup>
  <Import Project="$(CSharpDesignTimeTargetsPath)" Condition="'$(CSharpDesignTimeTargetsPath)' != '' and Exists('$(CSharpDesignTimeTargetsPath)')" />

</Project>

**Comment by genifycom** [comment]
Php is as per the example

<?php
$a = array("a" => "apple", "b" => "banana");
$b = array("a" => "pear", "b" => "strawberry", "c" => "cherry");
$c = $a + $b; // Union of $a and $b
echo "Union of \$a and \$b: \n";
var_dump($c);
$c = $b + $a; // Union of $b and $a
echo "Union of \$b and \$a: \n";
var_dump($c);
$a += $b; // Union of $a += $b is $a and $b
echo "Union of \$a += \$b: \n";
var_dump($a);
?>

**Comment by jakubmisek** [comment]
Can you attach your project file (`.msbiuildproj` file)

**Comment by jakubmisek** [comment]
Thanks, I see. Please update Peachpie dependencies from `0.7.0` to `0.9.0`. `0.7` is something about 2 years old and not working at all. Also you can remove the end section of the project file.

You should have something like:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php" Exclude="index.php" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Peachpie.Compiler.Tools" Version="0.9.0-*" />
    <PackageReference Include="Peachpie.NET.Sdk" Version="0.9.0-*" PrivateAssets="Build" />
  </ItemGroup>
</Project>
```

**Comment by genifycom** [comment]
Thank you for the help.
The following libraries were loaded:

C:\Dev\SourceControl\Development\AITC\PeachPie\TestPHP\TestPHP>dotnet restore
  Restoring packages for C:\Dev\SourceControl\Development\AITC\PeachPie\TestPHP\TestPHP\TestPHP.csproj...
  Restoring packages for C:\Dev\SourceControl\Development\AITC\PeachPie\TestPHP\TestPHP\TestPHP.csproj...
  Installing Peachpie.CodeAnalysis 0.9.0-CI00996.
  Installing Peachpie.Compiler.Tools 0.9.0-CI00996.
  Installing Peachpie.Runtime 0.9.0-CI00996.
  Installing Peachpie.Library 0.9.0-CI00996.
  Installing Peachpie.Library.XmlDom 0.9.0-CI00996.
  Installing Peachpie.Library.Scripting 0.9.0-CI00996.
  Installing Peachpie.Library.MySql 0.9.0-CI00996.
  Installing Peachpie.Library.PDO 0.9.0-CI00996.
  Installing Peachpie.Library.Network 0.9.0-CI00996.
  Installing Peachpie.Library.MsSql 0.9.0-CI00996.
  Installing Peachpie.NET.Sdk 0.9.0-CI00996.
  Installing Peachpie.App 0.9.0-CI00996.

But I get a conflict:

1>------ Rebuild All started: Project: TestPHP, Configuration: Debug Any CPU ------
1>Build started 6/28/2018 15:50:33.
1>Target CoreClean:
1>  Deleting file "C:\Dev\SourceControl\Development\AITC\PeachPie\TestPHP\TestPHP\obj\Debug\netcoreapp2.1\TestPHP.csproj.CoreCompileInputs.cache".
1>  Deleting file "C:\Dev\SourceControl\Development\AITC\PeachPie\TestPHP\TestPHP\obj\Debug\netcoreapp2.1\TestPHP.csprojAssemblyReference.cache".
1>Target _HandlePackageFileConflicts:
1>  Encountered conflict between 'Reference:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Http.dll' and 'Reference:C:\Users\DAnderson\.nuget\packages\system.net.http\4.3.2\ref\netstandard1.3\System.Net.Http.dll'.  Choosing 'Reference:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Http.dll' because AssemblyVersion '4.2.1.0' is greater than '4.1.1.1'.
1>  Encountered conflict between 'Platform:Microsoft.DiaSymReader.Native.amd64.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\microsoft.diasymreader.native\1.3.3\runtimes\win-x64\native\Microsoft.DiaSymReader.Native.amd64.dll'.  Choosing 'Platform:Microsoft.DiaSymReader.Native.amd64.dll' because file version '14.0.24210.0' is greater than '14.0.23431.0'.
1>  Encountered conflict between 'Platform:Microsoft.DiaSymReader.Native.x86.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\microsoft.diasymreader.native\1.3.3\runtimes\win-x86\native\Microsoft.DiaSymReader.Native.x86.dll'.  Choosing 'Platform:Microsoft.DiaSymReader.Native.x86.dll' because file version '14.0.24210.0' is greater than '14.0.23431.0'.
1>  Encountered conflict between 'Platform:Microsoft.DiaSymReader.Native.amd64.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\microsoft.diasymreader.native\1.3.3\runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll'.  Choosing 'Platform:Microsoft.DiaSymReader.Native.amd64.dll' because file version '14.0.24210.0' is greater than '14.0.23431.0'.
1>  Encountered conflict between 'Platform:Microsoft.DiaSymReader.Native.arm.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\microsoft.diasymreader.native\1.3.3\runtimes\win\native\Microsoft.DiaSymReader.Native.arm.dll'.  Choosing 'Platform:Microsoft.DiaSymReader.Native.arm.dll' because file version '14.0.24210.0' is greater than '14.0.23431.0'.
1>  Encountered conflict between 'Platform:Microsoft.DiaSymReader.Native.x86.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\microsoft.diasymreader.native\1.3.3\runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll'.  Choosing 'Platform:Microsoft.DiaSymReader.Native.x86.dll' because file version '14.0.24210.0' is greater than '14.0.23431.0'.
1>  Encountered conflict between 'Platform:Microsoft.DiaSymReader.Native.arm.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\microsoft.diasymreader.native\1.3.3\runtimes\win8-arm\native\Microsoft.DiaSymReader.Native.arm.dll'.  Choosing 'Platform:Microsoft.DiaSymReader.Native.arm.dll' because file version '14.0.24210.0' is greater than '14.0.23431.0'.
1>  Encountered conflict between 'Platform:System.Net.Http.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\system.net.http\4.3.2\runtimes\unix\lib\netstandard1.6\System.Net.Http.dll'.  Choosing 'Platform:System.Net.Http.dll' because AssemblyVersion '4.2.1.0' is greater than '4.1.1.1'.
1>  Encountered conflict between 'Platform:System.Net.Http.dll' and 'Runtime:C:\Users\DAnderson\.nuget\packages\system.net.http\4.3.2\runtimes\win\lib\netstandard1.3\System.Net.Http.dll'.  Choosing 'Platform:System.Net.Http.dll' because AssemblyVersion '4.2.1.0' is greater than '4.1.1.1'.
1>Target CoreCompile:
1>  PeachPie PHP Compiler version 0.9.0-CI00996
1>  EXEC : error PHP2016: Source file 'C:\Dev\SourceControl\Development\AITC\PeachPie\TestPHP\TestPHP\1702' could not be found.
1>  C:\Users\DAnderson\.nuget\packages\peachpie.net.sdk\0.9.0-ci00996\build\Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netcoreapp2.1\compile-php-args.rsp" exited with code 1.
1>Done building target "CoreCompile" in project "TestPHP.csproj" -- FAILED.
1>
1>Done building project "TestPHP.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>EXEC : error PHP2016: Source file 'C:\Dev\SourceControl\Development\AITC\PeachPie\TestPHP\TestPHP\1702' could not be found.
1>C:\Users\DAnderson\.nuget\packages\peachpie.net.sdk\0.9.0-ci00996\build\Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netcoreapp2.1\compile-php-args.rsp" exited with code 1.
1>    0 Warning(s)
1>    2 Error(s)
1>
1>Time Elapsed 00:00:02.02
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by jakubmisek** [comment]
There must be something else in your project you didn't tell.

Is there another project?
The actual error is that you somewhere specify `1702` as a source file (???)
`.csproj` is usually reserved for C# projects, recommending to use `.msbuildproj` file extension instead.

**Comment by genifycom** [comment]
[TestPHP.zip](https://github.com/peachpiecompiler/peachpie/files/2149641/TestPHP.zip)

Ok I am confused. The project (included) consists of TestPHP.sln, TestPHP.csproj, Program.cs and index.php

Visual Studio 2017 will not open a .msbuildproj file.

Are you saying that this will not work in Visual Studio 2017?

To try this out, open the .sln with Visual Studio 2017 (Version 15.7.4) Community Edition (download is here https://visualstudio.microsoft.com/downloads/).

Then try a build. 

The error 1702 could not be found is labelled PHP2016

**Comment by jakubmisek** [comment]
compiling both .cs and .php with a single project file cannot work ... you need two projects, look on our https://www.peachpie.io/getstarted

**Comment by jakubmisek** [comment]
`PHP2016` means there are no source files (because you excluded index.php, there are no php files to be compiled ....)

**Comment by jakubmisek** [comment]
`error PHP2016` is fixed in latest development build, for now add following into your project
`<NoWarn></NoWarn>`
