### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by Remo** [peachpiecompiler/peachpie#236]
According to this Peachpie should support all of PHP 7.2 https://github.com/peachpiecompiler/peachpie/wiki/Peachpie-Roadmap

So far I've found two things that don't work. I'm using 0.9.0-CI01014 which is the version support PHP 7.2. Am I missing something?

Optional return types or arguments:

```php
public function getParent(): ?self
{
    return $this->parent;
}
```

Array destructuring 
```php
[$class, $method] = \explode('::', $methodName);
```

**Comment by jakubmisek** [comment]
Both constructs seem to work fine, see https://try.peachpie.io/#v2:DYLgDgFmA0AmIGoA+AeA/JMBYAULgxsAIYDOJABABq4Deu5D5YArgEbACW+5AZswHb4ALhwD2/cgHMApkIAKRAE7T+QgBQBKEOTQlpwHvUZ0cjM+QAkAW1kRRsAHJEb5ALzkAREVb4QIWNI8HgDcRubkANoWhKQk0JY2QnawALpu5AA60gAeYMD20moA5H5F8da29k42GqF4puHkykLMihL80gDuVHVmAL64A/XS+Hbkah3dlBoAtAB8MvJKKuq1QA== how it compiles to IL (and de-compiles do C#)

**Comment by Remo** [comment]
I think I got confused. It seems like the language server analysing the code doesn't support it. This is what I see when I try to run the project in VS Code:

![image](https://user-images.githubusercontent.com/129864/42369380-0c80a13e-810a-11e8-95aa-f0a937180149.png)

**Comment by jakubmisek** [comment]
This seams like an error from vscode builtin syntax checker; which does not support 7.2 syntax I guess. Peachpie does, try building the project and check the build output instead. Also you can disable vscode builtin php checks in settings.json and install official peachpie for vscode extension which gives proper diagnostics.

**Comment by bfistein** [comment]
@Remo can we close this issue or was the problem solved? Just in case, [this](https://marketplace.visualstudio.com/items?itemName=iolevel.peachpie-vscode) is the official PeachPie extension for VS Code that Jakub was referring to.

**Comment by Remo** [comment]
sure
