### ISSUE TITLE
namespace resolution problem

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#240]
when try to resolve class/function inside current namespace failed, it should try to find in the global namespace.

```
O:\project\NULASpider\NULASpider\src\Container\Exceptions\ContainerException.php(5,56): error PHP2044: Type name 'nulastudio\Spider\Container\Exceptions\Psr\Container\ContainerExceptionInterface' could not be resolved. [O:\project\NULASpider\NULASpider\NULASpider.msbuildproj]
```
this is my code:
```php
<?php

namespace nulastudio\Spider\Container\Exceptions;

class ContainerException extends \Exception implements Psr\Container\ContainerExceptionInterface
{
}

```

the following are what php manual saying:
Names are resolved following these resolution rules: 
1.  Calls to fully qualified functions, classes or constants are resolved at compile-time. For instance new \A\B resolves to class A\B.  
2.  All unqualified and qualified names (not fully qualified names) are translated during compilation according to current import rules. For example, if the namespace A\B\C is imported as C, a call to C\D\e() is translated to A\B\C\D\e().  
3.  Inside a namespace, all qualified names not translated according to import rules have the current namespace prepended. For example, if a call to C\D\e() is performed within namespace A\B, it is translated to A\B\C\D\e().  
4.  Unqualified class names are translated during compilation according to current import rules (full name substituted for short imported name). In example, if the namespace A\B\C is imported as C, new C() is translated to new A\B\C().  
5.  Inside namespace (say A\B), calls to unqualified functions are resolved at run-time. Here is how a call to function foo() is resolved:
    1.  It looks for a function from the current namespace: A\B\foo().  
    2.  It tries to find and call the global function foo().  

6.  Inside namespace (say A\B), calls to unqualified or qualified class names (not fully qualified class names) are resolved at run-time. Here is how a call to new C() or new D\E() is resolved. For  new C():
    1.  It looks for a class from the current namespace: A\B\C.  
    2.  It attempts to autoload A\B\C.  
For  new D\E():
    1.  It looks for a class by prepending the current namespace: A\B\D\E.  
    2.  It attempts to autoload A\B\D\E.  
 To reference any global class in the global namespace, its fully qualified name new \C() must be used.

**Comment by liesauer** [comment]
i found the following code is ok:
```php
<?php

namespace nulastudio\Spider\Container\Exceptions;

use Psr\Container\ContainerExceptionInterface;

class ContainerException extends \Exception implements ContainerExceptionInterface
{
}

```

**Comment by jakubmisek** [comment]
Nope, not fully qualified class names are resolved relatively to current namespace, or using alising only. Please read the note from php manual carefuly and please try it on php before posting an issue.

**Comment by jakubmisek** [comment]
Btw: the compiler just resolved you an error in the code. The qualified name should be prepended with \.

**Comment by liesauer** [comment]
@jakubmisek that code works properly on php, that is why i posted this issue.

**Comment by jakubmisek** [comment]
Even in php, there is missing \\ before `Psr`. Isn't it possible the issue is somewhere else?

**Comment by liesauer** [comment]
@jakubmisek the only possibility is that the problem about composer autoload that a couple of weeks ago i said

**Comment by jakubmisek** [comment]
@liesauer it is possible something in specific autoload code makes class aliasing, anyway to be clear:
```php
namespace nulastudio\Spider\Container\Exceptions;
class X implements Psr\Container\ContainerExceptionInterface
```
in PHP, the name `Psr\Container\ContainerExceptionInterface` resolves to `nulastudio\Spider\Container\Exceptions\Psr\Container\ContainerExceptionInterface` in **parse time**.

It is treated like that. Once the file is actually included, the autoload kicks in and tries to resolve that name.

My guess is, in your code it is actually never used in run time, BUT, PeachPie performs these checks in compile time so it reveals those issues before you actually run them.
