### ISSUE TITLE
peachpie error with .net framework 

### ISSUE THREAD

**Issue by thakurankesh** [peachpiecompiler/peachpie#246]
Hi Team,

I am trying to integrate peachpie with asp.net (Not Core) and finding attached error while trying to add peachpie from nuget. 

![peachpie](https://user-images.githubusercontent.com/16999287/43240453-2f27b204-90b4-11e8-89ca-dc836379bea0.PNG)

Could you please suggest ?

**Comment by jakubmisek** [comment]
Hi, `.Net Standard 2.0` is compatible with full .NET Framework version 4.7.1 or newer (https://docs.microsoft.com/en-us/dotnet/standard/net-standard). Target either `netcoreapp2.0` or `net461`. Backward compatibility with `net45` has been dropped.
