### ISSUE TITLE
Missing installation instructions for IIS 10

### ISSUE THREAD

**Issue by BananaAcid** [peachpiecompiler/peachpie#251]
The Readme, wiki, homepage - none seem to have install instructions for Windows Server 2016 + IIS or related.

**Comment by jakubmisek** [comment]
The instructions are not finished yet and not officially supported (most preferred way is to run an ASP.NET Core app).

There are two approaches:
- run the request handler for `.php` files inside your ASP.NET (not Core) app domain (https://github.com/peachpiecompiler/peachpie/blob/8896e98737ad2810a0b8381511d25f657a8265d8/src/Runtime/Peachpie.RequestHandler/readme.md)
- run ASP.NET Core app (Kestrel; most of our samples) inside your IIS 10 server (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x)
