### ISSUE TITLE
PDO does not throw exceptions

### ISSUE THREAD

**Issue by ErstaunlichUnsterblicherBussard** [peachpiecompiler/peachpie#255]
If i try the following code the screen just stays white. If i try this code normally under PHP i get the catched error message (Unable to connect: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)). could it be that i missed someting to get this working in Peachpie?

``<?php
try {
$pdo = new PDO('mysql:host=localhost;dbname=sakila', 'user', 'wrong_password'); 
$statement = $pdo->prepare("SELECT actor_id, first_name, last_name FROM actor");
} catch (Exception $e) {
    echo "Unable to connect: ".$e->getMessage();
    exit;
}``

**Comment by jakubmisek** [comment]
It is possible this particular code (`new PDO` or `PDO->prepare`) does not throw an exception.

In general try/catch works as expected.

**Comment by ErstaunlichUnsterblicherBussard** [comment]
Thank you for pointing this out. Clearly my mistake.

**Comment by jan-pavlovsky** [comment]
The exception throwing from PDO should be fixed now.
