### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by cruelbob** [peachpiecompiler/peachpie#256]
```php
<?php

{
?>
<?php}

echo 'test';
```
Error:
`example.php(7,13): error PHPX2014: Syntax error: unexpected token ''`
PeachPie PHP Compiler version 0.9.0-CI01042

**Comment by jakubmisek** [comment]
Thanks for posting.
```php
<?php
{
?>
<?php}
```
is a syntax error in regular PHP as well -> closing

We might improve the error message in future.
