### ISSUE TITLE
Configuring wordpress with .net core

### ISSUE THREAD

**Issue by thakurankesh** [peachpiecompiler/peachpie#258]
I have downloaded the wordpress and copied it to website folder, I commenetd the code as suggested by article 
wp-includes/class-json.php:
Commented condition if (!class_exists(...))
Commented first class Services_JSON_Error (we don’t have PEAR_Error yet), keeping the second one

but when I am building the app I am getting follwoing error 

![image](https://user-images.githubusercontent.com/16999287/43760691-7c7d934e-9a40-11e8-8c28-f5aacba24231.png)

**Comment by bfistein** [comment]
The file `class-akismet-cli.php` is there in case you are using the WP CLI plugin. If you aren't using it, I suggest deleting that file and the error will be resolved that way.

Another solution is to use our [WP.NET SDK](https://github.com/iolevel/wpdotnet-sdk), which includes a dummy `WP_CLI_Command`, so you also wouldn't be getting this error.

**Comment by jakubmisek** [comment]
there is also a sample project that runs already compiled WordPress on https://github.com/iolevel/peachpie-wordpress

**Comment by thakurankesh** [comment]
After deleting the class-akismet-cli.php I got the following error - 
![image](https://user-images.githubusercontent.com/16999287/43769691-f222ca08-9a57-11e8-8493-80248167fb47.png)


Error message is not user friendly, could you please let me know what is the error and how I can fix this

**Comment by jakubmisek** [comment]
Press `f5`. This is by design exception caused by php' `die()`. Not an error.

**Comment by thakurankesh** [comment]
After that I am getting System.NotSupportedException: 'The given path's format is not supported.'

Do I need to change any setting/permissions ?

**Comment by jakubmisek** [comment]
It would help to provide the stack trace. Is the exception handled or unhandled? Handled exceptions occur in .NET, that's how it works. If you don't want to see such advanced .NET effects then turn off `Just My Code` in VS Debug Options.

**Comment by thakurankesh** [comment]
Hi Team,

Its still not working, If i disable just my code I got the following 
![image](https://user-images.githubusercontent.com/16999287/43970127-2623fdc4-9cea-11e8-9314-e83432dee99d.png)

It seems there is still some error? Do you have any sample project which have WP integration, the one you provided in documentation don't have full WP site

**Comment by jakubmisek** [comment]
Please note, [Just My Code](https://msdn.microsoft.com/en-us/library/dn457346.aspx) just hides exceptions that happens inside referenced libraries and that are handled.

Yes there is a sample we use in production on https://github.com/iolevel/peachpie-wordpress .

It would really help if you could provide the stack trace of the exception. Maybe this may help https://msdn.microsoft.com/en-us/library/x85tt0dd.aspx

**Comment by jakubmisek** [comment]
well, can you at least provide the exceprtion type and message of the first stack trace?

The second stack trace corresponds to an exception that is handled (it means it happens internally but program handles it and continues)

**Comment by thakurankesh** [comment]
Please find as asked for first stack trace
![image](https://user-images.githubusercontent.com/16999287/44003185-553a0666-9e6c-11e8-9ab8-f0ead5beecb9.png)

**Comment by jakubmisek** [comment]
Already answered - `ScriptDiedException` is caused by PHP' `die` construct (https://github.com/peachpiecompiler/peachpie/issues/258#issuecomment-411006040) - it does not cause crash since it is handled by the framework.

**Comment by thakurankesh** [comment]
So how I can get to know that why its not working. I means when I run the application its not showing the WP login page as its not installing the setup.

**Comment by thakurankesh** [comment]
@jakubmisek could you please let me know how I proceed further

**Comment by jakubmisek** [comment]
Sure - please tell me what exception it throws, also your setup, peachpie version, and content of the output window. Also as noted before, there is the entire solution ready for use on github.com/iolevel/peachpie-wordpress . Please note you need at least basic knowledge on asp.net core and exception handling.

**Comment by thakurankesh** [comment]
Hi I have following settings (Exception already attached above)
VS 2017 15.5.6
.NET Framework 4.7.03056

Please find attached output windows message.

Just to update you that connection string to database is correct and it paas the connection check.


[output window error.txt](https://github.com/peachpiecompiler/peachpie/files/2283816/output.window.error.txt)

**Comment by bfistein** [comment]
What version of PeachPie?

Also, please consider just running the [ready-for-use solution](github.com/iolevel/peachpie-wordpress) Jakub mentioned.

**Comment by thakurankesh** [comment]
yes I tried ready to use solution but there was issues related with .net core version, did that sample project not supported for version 2.0?

Also, please find the peachpie version details below:

![image](https://user-images.githubusercontent.com/16999287/44070214-29aba308-9fa0-11e8-9e3f-934847931b4d.png)

**Comment by bfistein** [comment]
Yes, please update your .NET Core SDK to version 2.1.301 (https://www.microsoft.com/net/download) and run `dotnet restore` once before opening in VS.

**Comment by thakurankesh** [comment]
Thanks for your help team, Its working now with the sample complied code (.net core) for wordpress but still getting the error while I am trying to setup using my wordpress code. Do you have any suggestion why Its not working while I am trying to setup wordpress from scratch?

Will it work with ASP.net also i.e. with .NET Framework 4.7.2? If yes do I need to change some settings. 

Also while integrating it with current application, how can I proceed.

**Comment by thakurankesh** [comment]
Hi @bfistein

Any suggestion for ASP.net integration for peachpie and integration with current application ?

**Comment by erinmester** [comment]
Hi @bfistein and @jakubmisek.. Did you see the comments above? We would love a response! Thanks!

**Comment by jakubmisek** [comment]
@thakurankesh Please, in order to report an issue, provide the exception. "Does not work" is not helpful.

I'm suggesting to handle the exception you are having (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1) and post the screenshot of what you see in your web browser.

@thakurankesh yes there is a way but it is not a goal of this project. Also it is out of the scope of this thread.

**Comment by jakubmisek** [comment]
@thakurankesh @erinmester ASP.NET has a different life cycle than ASP.NET Core. The integration depends on many scenarios - are you running MVC with custom route paths? do you have just .aspx files? do you have custom configuration in `web.config` ?

There are general steps you have to achieve (documented well on microsoft docs site or our docs)
- compile your PHP website for `net471` (https://docs.peachpie.io/php/msbuild/ with TargetFramework net471)
- reference the PHP project from your ASP.NET project
- take a look on request handler - https://github.com/peachpiecompiler/peachpie/blob/e143573e9084fdcc0aadc666b4f947ffe1cdf9d4/src/Runtime/Peachpie.RequestHandler/RequestHandler.cs#L21 - use this handler to handle requests to `.php` request paths - from your MVC router for example

Marking this as offtopic.

**Comment by jakubmisek** [comment]
@erinmester @thakurankesh do we have any progress? thanks!

**Comment by bfistein** [comment]
@thakurankesh @erinmester 

FYI [here is the documentation page](https://docs.peachpie.io/scenarios/beginner/full-net-framework/) describing your scenario. @thakurankesh should be able to get it done following those instructions. 

If you run into additional issues, please contact us via email for support or submit a separate Github issue with a description of the problem and the exception you get.
