### ISSUE TITLE
set_exception_handler does no supported yet

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#262]
```php
<?php

function exception_handler($e) {
    var_dump($e);
}

set_exception_handler('exception_handler');

throw new \Exception('my exception');
```
will cause
```
Unhandled Exception: Pchp.Library.Spl.Exception: my exception
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in O:\project\pchptest\set_exception_handler\main.php:line 9
   at <Script>.Main(String[] args)
```

**Comment by jakubmisek** [comment]
What is your use case? To handle errors without crashing the app?

**Comment by liesauer** [comment]
@jakubmisek right!

**Comment by liesauer** [comment]
my spider dynamic loads user's php script, it is important to handle the user's unhandled exceptions in order to save the data and the progress.

**Comment by jakubmisek** [comment]
Usually an exception means there problem in the code and the page should not be displayed to the user. In asp.net core, I would suggest to use middleware to handle and log exceptions https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1

Anyway; `set_exception_handler` will be implemented, there is just not a specific timeframe.

**Comment by liesauer** [comment]
i am working on netcore console

**Comment by jakubmisek** [comment]
for now you can just run the code within a `try/catch` block

**Comment by liesauer** [comment]
ok
