### ISSUE TITLE
Error while following Get Started guide

### ISSUE THREAD

**Issue by matheuszabin** [peachpiecompiler/peachpie#263]
I'm trying to use Peachpie following the [Get Started page](https://www.peachpie.io/getstarted).

> dotnet new -i Peachpie.Templates::*
> dotnet new web -lang PHP
> cd Server
> dotnet run

Then I receiving

> Program.cs(5,16): error CS0234:  The type or namespace 'Web' does not exist in the namespace 'Peachpie' (are you missing an assembly reference?)

Anyone know how to solve this?

**Comment by jakubmisek** [comment]
Thanks for letting us know - the templates have been updated

`dotnet new -i Peachpie.Templates::*` should give you updated templates (in few minutes).

For the already created project, update `program.cs`, line `5` to `use Peachpie.AspNetCore.Web;`
