### ISSUE TITLE
relative include path resolution issue

### ISSUE THREAD

**Issue by stweb** [peachpiecompiler/peachpie#264]
A circular dependency (base class includes file with derived class) causes:
System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'
instead of showing a proper error message.

**Comment by jakubmisek** [comment]
do you have a test case?

for now I found 
```php

class Y extends X {}
class X extends Y {}
```
causes `StackOverflowException`

**Comment by stweb** [comment]
The pattern is something like this (with another intermediary include so that the circle wasn't obvious')

In BaseClass.php
```
<?php
include_once('Other.php');
class Base { ....
```

In Other.php
```
<?php
include_once('Derived/DerivedClass.php');
```

In DerivedClass.php:
```
<?php
include_once('BaseClass.php');
class DerivedClass extends BaseClass{
```

**Comment by stweb** [comment]
This exception is thrown in `EnsureTypeDelared`

**Comment by jakubmisek** [comment]
I see, the exception should be more descriptive ..
`EnsureTypeDeclared` checks the `BaseClass` has been declared, otherwise it throws the exception (even tho the class was resolved in compile time, runtime checks `class BaseClass` was actually reached)

**Comment by stweb** [comment]
Would be good to show such errors in the VS Code plugin,

Btw. is there a way to debug the VS Code plugin, it seems to choke on my project. which compiles with some 150 warnings? 

Thanks for the quick reply and for the great work on Peachpie!

**Comment by jakubmisek** [comment]
@stweb the plugin is somehow a work in progress, it is opensourced on https://github.com/iolevel/peachpie-vscode/tree/master/src/Peachpie.VSCode

I suppose, the language server project `Peachpie.LanguageServer` writes response JSONs one over another, there should be a lock or something

**Comment by stweb** [comment]
ah ok, didn't find it there because https://marketplace.visualstudio.com/items?itemName=iolevel.peachpie-vscode links to here

**Comment by jakubmisek** [comment]
@stweb good point, we'll add some info in there

**Comment by jakubmisek** [comment]
I have tried the pattern but seems to work fine, requesting any of three files does not cause the exception.
![image](https://user-images.githubusercontent.com/842150/44121331-d20a0330-a01f-11e8-8920-fc2b78b4980c.png)
Do you have another sample?

**Comment by stweb** [comment]
Hmm, Ii'm trying to come up with a minimal reproduction of the issue, sorry for the wrong example.

**Comment by stweb** [comment]
It turned out to be indeed an issue with include/require, but not an obvious one (in my more complex real world app). I was mislead by the cyclic includes that were not the root cause. I've now created an example which compiles without errors, yet throws a runtime exception. 

I think the issue should be renamed to 'relative include path resolution issue'. It appears the path is not resolved relative to the referencing file, but rather to the root script, which I believe is different from PHP per http://php.net/manual/en/function.include.php

From debug output it seems the include paths are resolved at runtime, although the script had already been compiled. Shouldn't Peachpie resolve includes at compile time and identify when the same file is referenced so that these can be mapped to the same .NET class?
[repro.zip](https://github.com/peachpiecompiler/peachpie/files/2291515/repro.zip)

**Comment by jakubmisek** [comment]
@stweb good we found the actual reason. Yes, Peachpie resolves the inclusion in compile time if it can - As I understand; according to the manual, the path is relative to current directory if it starts with `.` or `..`. Otherwise it follows the include paths (which is `.` by default, but configurable in runtime) with respect to `cwd` (which is the project root if not changed by `chdir`)?

**Comment by stweb** [comment]
In my real world project there are 100's of files and classes in a complex directory structure and the includes that work in PHP 5.6 don't run in Peachpie out of the box: Depending on where the starting script is located, the includes are resolved in a different order and I don't know how to make it work.

Also, I wonder how to deal with php-includes vs public entry points. Can I move the php-includes to a separate DLL and reference them from there?

**Comment by stweb** [comment]
Yup, I can give it a try. Thanks for pointing to the source location.
What's the best way to debug it? I assume debugging peach.exe with my code?

**Comment by stweb** [comment]
HIt close by accident ;-)

**Comment by jakubmisek** [comment]
This is the runtime, so you need to debug your compiled app, "Just My Code" disabled, with debug build of `Peachpie.Runtime.dll`.

Anyway it would be better to specify how it should work - there are a lot of cases when the same file exists in `current working directory`, `current scripts directory` and in one of include_path's directory ...

**Comment by jakubmisek** [comment]
@stweb Hi, do you have the test case that resolves include path incorrectly? It would be something like
`include "a.php";` whene `a.php` exists in all include_path, current dir and working dir.
Thanks

**Comment by stweb** [comment]
I installed a real PHP and realized that I was mistaken about how ../ paths should be resolved. I thought these were relative to the script location, but indeed they seem relative to the entry point script. I haven't testes include paths - how are these configured in Peachpie? My problem may be related to combining files into my peachpie project that were separated in php-include paths originally, because I didn't know how to setup include paths.

What remains is that actual reason for a failed include / missing class is not shown in the exception, but only printed to debug output which doesn't show e.g. in the ASP.NET core developer error page.

I'm closing this issue for now as not reproducible.
