### ISSUE TITLE
404 on .css, .js and other subfolder files

### ISSUE THREAD

**Issue by matheuszabin** [peachpiecompiler/peachpie#267]
Hi,
I've followed the Getting Started Guide and copied my project folders/files (including index.php) to Website folder, but all files the isn't index.php aren't being loaded (404).
I don't know if I've to specify some config or what... No compile/run errors are show.

**Comment by jakubmisek** [comment]
Hi, I suppose in the app project, you have to add app.UseStaticFiles() with path to the website. For more info check the asp.net core UseStaticFiles docs pls.
We'll take a look and update the get started templates if necessary.
Thanks!
