### ISSUE TITLE
unwrap __call magic method params list

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#268]
![tim 20180826234617](https://user-images.githubusercontent.com/8676741/44630040-66cb9880-a98a-11e8-88e5-01a491780918.png)
![tim 20180826234638](https://user-images.githubusercontent.com/8676741/44630043-70550080-a98a-11e8-8cc9-8855b0318e63.png)
it should be
```
[
    'test1',
    'test2'
]
```
not
```
[
    [
        'test1',
        'test2'
    ]
]
```
testcase
[paramsListTestCase.zip](https://github.com/peachpiecompiler/peachpie/files/2321644/paramsListTestCase.zip)

**Comment by jakubmisek** [comment]
Actually in PHP, you get the arguments in a second parameter as array.

However in C# it would be nice to get it unpacked (if `params` is specified).

**Comment by jakubmisek** [comment]
closing as it behaves according to PHP semantics. `params` makes it just a little confusing. May be re-opened in a future after consideration.

**Comment by liesauer** [comment]
alright, but it should be a braking change in future, not just a little commit. actually, every class which is written in c# and declares `__call` method need unpack once now so that make `params` totally behaves the same as `...` (in php), no matter it is a single class or super class or subclass.

**Comment by jakubmisek** [comment]
PHP does not allow `...` in `__call`. If it would, the behavior would be as weird as in your case with `params`.

**Comment by jakubmisek** [comment]
the latest commit allows for non-PHP classes to implement `__call` and `__callStatic` using unwrapped arguments unlike PHP. If the magic method will have two arguments, the PHP's behavior is still used.
