### ISSUE TITLE
If Class Exists Implementation

### ISSUE THREAD

**Issue by deinok** [peachpiecompiler/peachpie#276]
Seems like this kind of construction dont work well:
```php
if (class_exists("A")){
    class B extends A{
        ...
    }
} else {
    class B{
        ...
    }
}
```

**Comment by deinok** [comment]
related to the PEAR_Error of Wordpress

**Comment by jakubmisek** [comment]
Please add expected behavior and actual behavior. For me it is working fine.

**Comment by jakubmisek** [comment]
*Expected:* if class `A` does not exist, the compilation fails with error code `PHP4044` documented on https://docs.peachpie.io/php/diagnostics/. It is important to be aware that the compiler is not an interpreter.

**Comment by jakubmisek** [comment]
`class_exists` is not a precate but regular condition. The compiler cannot be sure, thass won't exist in runtime (it can be dynamically added)

**Comment by jakubmisek** [comment]
There is no interpreter, the closes to intepreter is https://github.com/peachpiecompiler/peachpie/tree/master/src/Tests/Peachpie.Test which lets you to execute code from a C# variable.
