### ISSUE TITLE
"self" not supported as argument type in interface methods

### ISSUE THREAD

**Issue by jan-pavlovsky** [peachpiecompiler/peachpie#281]
When trying to create a method signature inside interface, that accepts an argument of type self, the following exception is thrown during compilation:

System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=Peachpie.CodeAnalysis
  StackTrace:
   at Pchp.CodeAnalysis.PhpCompilation.GetTypeFromTypeRef(TypeRef tref) in C:\Users\jan\OneDrive\Dokumenty\GitHub\peachpie\src\Peachpie.CodeAnalysis\Compilation\PhpCompilation.Types.cs:line 205

Test case
To reproduce the issue, it is sufficient to try to compile following fragment of PHP code:

```php
interface AInterface {
    public function foo(self $a);
}
```

**Comment by jakubmisek** [comment]
thanks!
