### ISSUE TITLE
Local variables in function unavailable in included file

### ISSUE THREAD

**Issue by diddledan** [peachpiecompiler/peachpie#283]
In PHP when a file is pulled with `require` or `include` (or their `_once` equivalents) it is inserted into the local scope of the calling location. If that happens to be within a function then any function-local variables should be exposed to the included script. This is not the case with PeachPie.

Consider the following:

test.php:
```php
<?php

function test() {
    $variable = '$variable is set!';

    include 'include-me.php';
}

test();
```

include-me.php:
```php
<?php

if ($variable) {
    echo $variable; // This is the branch taken in PHP
} else {
    echo '$variable is NOT set :-('; // This is the incorrect branch which PeachPie takes
}
```

**Comment by jakubmisek** [comment]
This behavior is tested and works.

The only "confusing" to you might be the `Locals` in Visual Studio which does not show you variables from outer scopes.

**Comment by diddledan** [comment]
I beg to differ from your statement that it "works" - using the above two files:

```bash
$ php test.php 
It Works!

$ dotnet run test.php
It does not work :-(
```

**Comment by jakubmisek** [comment]
I'm just running the same and it works (the same dotnet and peachpie versions)
![image](https://user-images.githubusercontent.com/842150/46263426-5077a600-c50f-11e8-8ece-a3d4e4156c2d.png)
Isn't it possible you are running `include-me.php` as the main script ?
