### ISSUE TITLE
set_error_handler is not implemented

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#285]
testcase:
[set_error_handler_Test.zip](https://github.com/peachpiecompiler/peachpie/files/2436805/set_error_handler_Test.zip)

**Comment by liesauer** [comment]
`trigger_error` as well

**Comment by jakubmisek** [comment]
Update: PeachPie **will** treat most errors strictly - so it will throw exceptions instead of reporting the error. Error handler will be probably an unused feature.

**Comment by surfmuggle** [comment]
@jakubmisek what does it mean that   [set_error_handler](https://www.php.net/manual/en/function.set-error-handler.php)  `will be an unused feature`?

1. Do you expect that few people will have it in their code?
2. Do you mean that peachpie will not support / not implement it?


The code from the zip file
```
set_error_handler(function ($errno, $errmsg, $errfile, $errline, $errcontent = []) {
    var_dump("{$errmsg} on {$errfile}:{$errline}");
});
$t = $a;
trigger_error('user error');
```

**Comment by jakubmisek** [comment]
@surfmuggle internal errors will result in an exception - which might be handled using `set_exception_handler`

`set_error_handler` will be probably only used in combination with `trigger_error`

**Comment by jakubmisek** [comment]
current status:
- internal warnings/notices cannot be handled using `set_error_handler`
- `trigger_error` can be handled
- fatal errors will raise exception which can be handled using `set_exception_handler`

**Comment by jakubmisek** [comment]
Closing since `set_error_handler ` is implemented.

Please open an issue if internal warnings/notices need to be handled by the handler.
