### ISSUE TITLE
`PDO` and `eval` on .NET Framework cause `ReflectionTypeLoadException`

### ISSUE THREAD

**Issue by DaveMagrathSmith** [peachpiecompiler/peachpie#286]
I'm having trouble using PDO with SQL Server.  I've referenced the Peachpie.Library.PDO.SqlSrv (0.9.9) nuget package, and the project (a php class library) compiles successfully.  But when I execute the code, the following exception is throw when constructing the PDO object:

`System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Peachpie.Library.PDO.PDOEngine.CollectPdoDrivers()
   at Peachpie.Library.PDO.PDOEngine.GetDrivers()
   at Peachpie.Library.PDO.PDO.__construct(String dsn, String username, String password, PhpArray options)`

Any suggestions about what I might be doing wrong?

Thanks!

**Comment by jakubmisek** [comment]
It does not happen on test environments with 0.9.9.

This error might be caused when there are mismatching versions (any NuGet restore warning?) Ensure all the `Peachpie.***` package versions are the same and there are no warnings during the `restore`.

**Comment by jakubmisek** [comment]
@DaveMagrathSmith did consolidating package versions help?

**Comment by DaveMagrathSmith** [comment]
It looks like all my package versions are the same.  Here's what I have...

In my class library:
Peachpie.App (0.9.9)
Peachpie.Compiler.Tools (0.9.9)
Peachpie.Library.PDO.SqlSrv (0.9.9)

And in my ASP.NET Core app:
Peachpie.AspNetCore.Mvc (0.9.9)

Doing a dotnet restore on both projects runs successfully without any warnings.

I did notice there are two files being pulled in by those nuget packages that have different versions:
Peachpie.Microsoft.CodeAnalysis.dll (42.42.42.42424)
Peachpie.Compiler.Diagnostics (1.0.1.0)

Not sure if those could be causing an issue - I'm working on figuring out what exactly is pulling those in.

Thanks,
Dave

**Comment by jakubmisek** [comment]
Those two files are compiler dependencies and the version is alright.

**Comment by jakubmisek** [comment]
@DaveMagrathSmith Can you dig into that exception details? There should be the exact file name that is missing or which version is mismatching.

**Comment by DaveMagrathSmith** [comment]
Will do - I just downloaded the source so I can debug into it...

**Comment by jakubmisek** [comment]
Sources are not needed I guess, the exception details should reveal the troublesome dependency.

**Comment by DaveMagrathSmith** [comment]
For some reason I couldn't catch the exception from my PHP code (the process seems to terminate before returning to my code).  With the source though, I added a try/catch to the CollectPdoDrivers() method, and it looks like this is the troublesome dependency:

Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by DaveMagrathSmith** [comment]
Here the "FusionLog" from within the exception:

=== Pre-bind state information ===
LOG: DisplayName = System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Projects/peachpie-master/Intranet-Core/bin/Debug/net461/
LOG: Initial PrivatePath = NULL
Calling assembly : Peachpie.Library.Scripting, Version=0.9.9.0, Culture=neutral, PublicKeyToken=5b4bee2bf1f98593.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Projects\peachpie-master\Intranet-Core\bin\Debug\net461\Intranet-Core.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Projects/peachpie-master/Intranet-Core/bin/Debug/net461/System.Runtime.Loader.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by jakubmisek** [comment]
I see, it happens when targeting `net461`. Targeting `netcoreapp2.1` works fine.

**Comment by DaveMagrathSmith** [comment]
Yes, I just tested targeting netcoreapp2.1, and it does work fine.

I was hoping to target the full framework since I still have 4.6 class libraries I need to reference.  I know that you can now reference 4.6 libraries from .NET Core 2.1, so I'll have to experiment with that.

Thanks for your help.

**Comment by jakubmisek** [comment]
Thanks for the info. There is an issue with referencing "System.Runtime.Loader" under `net461`, just looking into that.

**Comment by DaveMagrathSmith** [comment]
Thank you Jakub!  This is now working on 0.9.11 for me.
