### ISSUE TITLE
PhpStream.ResolvePath always returns false when Context.WorkingDirectory is null

### ISSUE THREAD

**Issue by DaveMagrathSmith** [peachpiecompiler/peachpie#288]
I'm trying to use the file_exists function with a network path:

$path = '\\\\server\\share\\filename.ext'
$result = file_exists($path);

This makes a call to PhpStream.ResolvePath, which attempts a Path.Combine(ctx.WorkingDirectory, path).  But the working directory is null, resulting in an ArgumentNullException, which is caught and swallowed, returning false.  This causes file_exists to always return false even if the file does exist.

Perhaps I am doing something wrong with my environment - should WorkingDirectory have a value?

Thanks,
Dave

**Comment by DaveMagrathSmith** [comment]
@jakubmisek Actually, I'm not creating the context myself - This is an ASP.NET Core app, referencing a PHP class library, running in IIS Express.

**Comment by jakubmisek** [comment]
So the ctx is of type `RequestContextCore` ?

Its `WorkingDirectory` is always initialized to a non-null value right after optional `PhpRequestOptions.BeforeRequest` gets invoked.

**Comment by DaveMagrathSmith** [comment]
Yeah, the type is:  Peachpie.AspNetCore.Web.RequestContextCore

When RequestContextCore is created, it does have a rootPath.  But for some reason, it doesn't look like the WorkingDirectory is ever set from that, nor is BeforeRequest is ever called on the options.  (In fact, I don't see the PhpHandlerMiddleware involved at all).  Here's the call stack when the context is created:

`Peachpie.AspNetCore.Web.RequestContextCore.RequestContextCore(Microsoft.AspNetCore.Http.HttpContext httpcontext, string rootPath, System.Text.Encoding encoding) Line 303	C#
Peachpie.AspNetCore.Web.HttpContextExtension.CreateNewContext(Microsoft.AspNetCore.Http.HttpContext httpctx) Line 52	C#
Peachpie.AspNetCore.Web.HttpContextExtension.GetOrCreateContext(Microsoft.AspNetCore.Http.HttpContext httpctx) Line 45	C#
Peachpie.AspNetCore.Mvc.HtmlHelperExtension.Php(Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper htmlHelper, string relativePath, object this) Line 70	C#
AspNetCoreApp.Views.dll!AspNetCore.Views_Php_Page.ExecuteAsync() Line 11	C#`

**Comment by jakubmisek** [comment]
I see! the Razor page does not initialize that ... will be fixed

**Comment by DaveMagrathSmith** [comment]
Appreciate it - Thanks Jakub!
