### ISSUE TITLE
Assembly Peachpie.Microsoft.CodeAnalysis not found when using Peachpie.RequestHandler and .NET Framework

### ISSUE THREAD

**Issue by dlob** [peachpiecompiler/peachpie#292]
When I use the Peachpie.RequestHandler to run a site in iisexpress, I get the following error:

```
Could not load file or assembly 'Peachpie.Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

My project file:
```xml
<Project Sdk="Peachpie.NET.Sdk/0.9.11">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net461</TargetFramework>
    <AssemblyName>PeachpieTest</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Peachpie.RequestHandler" Version="0.9.11" />
  </ItemGroup>
</Project>
```

web.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.5" />
    <httpRuntime targetFramework="4.5" />
  </system.web>
  <system.webServer>
    <handlers>
      <add name="PeachpieHandler" path="*.php" verb="*" type="Peachpie.RequestHandler.RequestHandler, Peachpie.RequestHandler, Version=0.9.0.0, Culture=neutral, PublicKeyToken=5b4bee2bf1f98593" resourceType="Unspecified" preCondition="integratedMode" />
    </handlers>
  </system.webServer>
</configuration>
```

index.php
```php
<?php
	phpinfo();
?>
```

The installed .NET Framework version is 4.7.2. The file Peachpie.Microsoft.CodeAnalysis.dll is present in the bin directory.

**Comment by jakubmisek** [comment]
The full error?

```
Parser Error Message: Could not load file or assembly 'Peachpie.Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

at

```
Source File: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config    Line: 97
```

Is it correct?

**Comment by dlob** [comment]
Not exactly. The full stacktrace:
```
[FileLoadException: Could not load file or assembly 'Peachpie.Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +225
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +110
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +22
   System.Reflection.Assembly.Load(String assemblyString) +34
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +48
```

My workflow:
* First I publish the project `dotnet publish -o %wwwroot%\bin`
* Then `copy Web.config %wwwroot%\Web.config`

I get the exception with iisexpress and also with the docker image `microsoft/asp.net:4.7.2`.

**Comment by jakubmisek** [comment]
It seams `Peachpie.Microsoft.CodeAnalysis` reference has troubles loading on .NET Framework. It has nothing to do with `Peachpie.RequestHandler`.

**Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]**

**Comment by dlob** [comment]
I'm not sure that is has nothing to do with Peachpie.Requesthandler. When I use the dll in an ASP.NET Core project and then run this project with `dotnet run` it works (both projects target net461). Possibly there is a difference in assembly loading.

**Comment by jakubmisek** [comment]
For me it says that loading of Peachpie.Microsoft.CodeAnalysis errored on .NET 4.6.1 with **Strong name signature could not be verified**.  It is possible the DLL is compiled incorrectly (https://github.com/peachpiecompiler/Peachpie.Microsoft.CodeAnalysis) @roberthusak ?

**Comment by roberthusak** [comment]
@jakubmisek Yes, it seems that the assembly was only delay signed due to the usage of a wrong key in the [key directory](https://github.com/peachpiecompiler/Peachpie.Microsoft.CodeAnalysis/tree/master/build/Strong%20Name%20Keys) (35MSSharedLib1024.snk - without the private part in the repository). We can either revert to RoslynInternalKey.Private.snk (which was used till the version 0.6.0) or put the Peachpie key there.

**Comment by jakubmisek** [comment]
@roberthusak can you please rebuild the assembly with the key from peachpie project and incremented minor version. I'll put it on nuget.org and update deps asap.

**Comment by roberthusak** [comment]
@jakubmisek After some problems with MSBuild I've updated the repository and uploaded the new package to the relevant item in trello.

**Comment by jakubmisek** [comment]
@roberthusak thanks! updating right now. 

BTW this property is really important when building on non-windows platform
```xml
          <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
              <PublicSign>true</PublicSign>
          </PropertyGroup>
```

**Comment by roberthusak** [comment]
@jakubmisek Ah, I see. I've added that to the repository. The package was built on Windows.
