### ISSUE TITLE
I uploaded mp4 and found that '/thumbs' has nothing, but uploading other files is fine.

### ISSUE THREAD

**Issue by zivhsiao** [peachpiecompiler/peachpie#302]
When I upload mp4, when I upload it, the file in '/upload' is actually uploaded successfully, but '/thumbs' does not generate its file.

No problem except image upload

How can I solve this?

**Comment by bfistein** [comment]
Hi @zivhsiao, which application are you trying to run - WordPress? What version of PeachPie are you running? If you could start off by posting a screenshot and letting me know the above answers please, we'll try to take it from there.

**Comment by zivhsiao** [comment]
i got it, because used the 'filemanager/dialog.php?type=1', should be 'filemanager/dialog.php?type=0'

thanks.
