### ISSUE TITLE
eval() causes request to hang on asp.net/net461

### ISSUE THREAD

**Issue by dlob** [peachpiecompiler/peachpie#304]
When requesting the following sample php file (compiled with peachpie 0.9.12) with `Peachpie.RequestHandler.RequestHandler` on target framework `net461` it hangs and doesn't return anything:

```php
<?php
    eval("echo \"test\";");
?>
```

**Comment by jakubmisek** [comment]
Would you have more details? It probably fails by .NET runtime with an assembly load exception. If you'd enable some kind of detailed logging of the ASP.NET app on your IIS/IIS Express.

**Comment by dlob** [comment]
There isn't an exception. The request never returns any content. Since IISExpress musst be killed after a request, I assume there is something like an endless loop.

**Comment by jakubmisek** [comment]
Thank you! We were not able to find this out.

**Comment by jakubmisek** [comment]
If the PR #315 is confirmed, closing the issue. Thank you @dlob for finding out.
