### ISSUE TITLE
CallSite not reused when making a dynamic call to the same function

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#305]
```php
if(!function_exists('foo')) {
	function foo($v) {
		echo 'foo: ', $v, PHP_EOL;
	}
}

foo('v1');
foo('v2');
```
Each call to `foo()` gets its own static field of type `CallSite<<>A{00000004}<CallSite, Context, PhpValue>>` that gets bound to the same function in the static constructor in the generated .net code.

In WordPress (4.9.8) some of the core functions are defined a second time in wp-admin/includes/noop.php which leads to dynamic calls to all those functions. For example, only in the code generated for wp-include/post.php there are around 90 callsites for dynamic calls to the same `__()` function.

**Comment by jakubmisek** [comment]
This piece of code actually reuses existing callsites. There are two fields indeed but initialized with the same instance of the `CallSite` object.

What we can improve is not declaring the field more than once to make the resulting assembly little bit more clean and smaller.

**Comment by jakubmisek** [comment]
Right, this is a kind of optimization that will definitely take a place in a future. For now there are much bigger areas to look at. Future optimizations will probably remove the duplicit callsites and unnecessary function declarations in general.

Let's close it for now.
