### ISSUE TITLE
Trouble compiling with a System.AggregateException: Pchp.Core.Context not implemented

### ISSUE THREAD

**Issue by Valks** [peachpiecompiler/peachpie#306]
I've just recently attempted to use Peachpie again and I noticed the project definition has changed a bit.
When I compiled what I originally had I got a lot of errors but updating to (roughly):
```
<Project Sdk="Peachpie.NET.Sdk/1.0.0-CI01233">
...
<ItemGroup>
    <!-- <PackageReference Include="PeachPied.WordPress" Version="$(WordPressVersion)" /> -->
    <PackageReference Include="PeachPied.WordPress" Version="$(WordpressPackageVersion)" /><!-- Need the CI version until it becomes stable. -->
  </ItemGroup>
</Project>
```
With the changes above I managed to compile my Patch project (fixes for missing functions) but when I went to compile a plugin library I get the following error:
```Unhandled Exception: System.AggregateException: One or more errors occurred. (Pchp.Core.Context not implemented at```

Any thoughts on what might be causing it?
Only differences I can see are I specify what is compiled, and copied, i.e.
```
<ItemGroup>
    <Compile Include="**/*.php"
             Exclude="obj/**;bin/**" />
    <Content Include="**"
             Exclude="**/*.php;obj/**;bin/**;*.msbuildproj"
             CopyToOutputDirectory="PreserveNewest">
      <PackagePath>contentFiles/any/netcoreapp2.0/wordpress/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="wp-content/plugins/electro-extensions/electro-extensions.php" CopyToOutputDirectory="PreserveNewest">
      <PackagePath>contentFiles/any/netcoreapp2.0/wordpress/wp-content/plugins/electro-extensions/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
```

Also it seems msbuild has been updated and I've had to add the following property to get the old behaviour
```
<PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
```

**Comment by Valks** [comment]
Downgrading the Project SDK reference to 0.9.13 fixed the compiling issue so there's a regression.

**Comment by jakubmisek** [comment]
0.9.13 is much newer than the latest CI build.
