### ISSUE TITLE
Do While Continue is improperly compiled when there is a lot of logic

### ISSUE THREAD

**Issue by jondmcelroy** [peachpiecompiler/peachpie#321]
Found this issue when trying to compile a project using symfony's Yaml library.
You can reproduce this by compiling this class: https://github.com/symfony/yaml/blob/master/Parser.php#L152-L154
Errors come from the continue in the doParse function's doWhile loop. The c# compiled code translates the continue to another doWhile and causes an infinite loop.

```php
// PHP
do {
    if ($this->isCurrentLineEmpty()) {
        continue;
    }
    ....
 } while ($this->moveToNextLine()); 
```
This is the compiled version:
```c#
// C#
do
{
    do
     ;   
     while (this.isCurrentLineEmpty());
     ....
}
while (this.moveToNextLine());
```

I was not able to reproduce it with a smaller set of logic. It could be just because there is so much if/else logic and thrown exceptions

**Comment by jakubmisek** [comment]
Nice test case. First it seems call to function `getNextEmbedBlock` generates an invalid IL. That might cause other issues.
```php
$this->getNextEmbedBlock();
```
where `getNextEmbedBlock` has nullable optional value type:
```php
function getNextEmbedBlock(int $indentation = null) { }
```

**Comment by jondmcelroy** [comment]
That seems like it might be a different issue, I removed that function and was able to make the doWhile problem happen again.

That other issue does seem like a problem though since:
```php
// PHP
private function getNextEmbedBlock(int $indentation = null, bool $inSequence = false)
```
Makes
```c#
// C#
private virtual string getNextEmbedBlock(long indentation = default (long), bool inSequence = false)
```
When:
```php
// PHP
 private function getNextEmbedBlock(?int $indentation = null, bool $inSequence = false)
```
```c#
private virtual string getNextEmbedBlock(PhpValue indentation = default (PhpValue), bool inSequence = false)
```

Both ?int and $variable = null, should probably be PhpValues.

**Comment by jakubmisek** [comment]
Yes, or Nullable<long>

**Comment by jakubmisek** [comment]
update: `continue;` in `do { ... } while (condition);` was compiled totally wrong!
