### ISSUE TITLE
Directory->read() does not contain directory actully

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#323]
directory struct
```
dir/
    dir2/
    r.txt
a.txt
b.txt
```
code
```php
<?php

$dir = dir(__DIR__);
while ($file = $dir->read()) {
    var_dump($file);
}
$dir->close();

```
expect
```
.
..
dir
a.txt
b.txt
```
actully
```
.
..
a.txt
b.txt
```

**Comment by jakubmisek** [comment]
It should, the test gives me the directories as well.

Isn't it possible `__DIR__` is a .NET output folder without the `dir` directory?

**Comment by jakubmisek** [comment]
It seems like an issue with `cwd` (current working directory). `dir()` lists all the file system entries.

Closing for now, if you'd have any more details, please comment : ) Thank you

**Comment by liesauer** [comment]
@jakubmisek  you are right, i misunderstand something before, but things are going intersting. it lists all of the php source scripts(only php scripts)  in the project with the same level directory struct of the running script both. check this out.
[readdirTest.zip](https://github.com/peachpiecompiler/peachpie/files/2634143/readdirTest.zip)

**Comment by jakubmisek** [comment]
It works as expected for me, it is getting me files in the directory and compiled scripts (which is needed for compatibility with PHP behavior in case you distribute your app without source files)

**Comment by liesauer** [comment]
so is there any ways to get the real stuff and compiled scripts separately?

**Comment by jakubmisek** [comment]
you can use `dir()` and filter files that are readable, maybe `stat()` function is the fastest way.

**Comment by liesauer** [comment]
i see, thanks!
