### ISSUE TITLE
Getting a dll when trying to build an exe

### ISSUE THREAD

**Issue by louismrose** [peachpiecompiler/peachpie#328]
Hi there,

I'm trying to build an exe from the sample console application, but I always seem to get a dll. Should it be possible to build an exe on a Mac?

I've followed these steps based on the [getting started](https://docs.peachpie.io/get-started/) guide:

1. Installed .NET Core 2.2 from https://dotnet.microsoft.com/download
2. Installed the PeachPie template: `dotnet new -i Peachpie.Templates::*`
3. Created the console app: `dotnet new console -lang PHP`
4. Verified that the console app works: `dotnet run`. I see `tmp says "Hello .NET World!"`
5. Edited `tmp.msbuildproj` to have the contents shown below.
6. Ran `dotnet build`. I see that a DLL is built, but no exe (`tmp -> /my/local/path/tmp/bin/Debug/netcoreapp2.0/tmp.dll`)

```xml
<Project Sdk="Peachpie.NET.Sdk/0.9.20">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <StartupObject>program.php</StartupObject>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php" />
  </ItemGroup>
  
</Project>
```

I've tried using `exe`, `Exe` and `winexe` as the value for `OutputType`, but I always get a dll in the output from the build.

I'm pretty sure that my `tmp.msbuildproj` file is being read correctly, as setting other properties to invalid values (such as a non-existent file for `StartupObject` and `8.2` for `LangVersion`) cause an error to be raised during the build.

I'm on macOS Mojave 10.14.1 and `dotnet --version` emits `2.2.100`

The contents of my `program.php` file is:

```php
<?php

function main()
{
    echo "tmp says \"Hello .NET World!\"";    
}

main();
```

**Comment by jakubmisek** [comment]
Hi, great question.

This is how .NET Core works in general, It always creates .dll, and you can either "publish" it for a specific platform to get the .exe, or you run the dll using .NET Core Runtime like `dotnet yourapp.dll`

You can take a look on a quick tutorial I randomly found https://neelbhatt.com/2018/08/21/generate-an-exe-for-the-net-core-console-apps-net-core-quick-posts-part-5/

or search for ".net core exe".

**Comment by louismrose** [comment]
Thanks a lot @jakubmisek -- I didn't realise I'd need to run `publish` too. For anyone who finds this in the future, I was able to run:

`dotnet publish -c Release -r osx-x64` to build a binary for my Mac
`dotnet publish -c Release -r win81-x64` to build a binary for a Windows Server 2012 R2 box.

Further possible release IDs are listed here: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids.

One further issue I'm now encountering is that when running the exe on my Windows box, I get the following error:

```
Error:
  An assembly specified in the application dependencies manifest (tmp.deps.json)
 was not found:
    package: 'Devsense.PHP.Parser', version: '1.4.82'
    path: 'lib/netstandard2.0/Devsense.PHP.Parser.dll'
```

Any idea what might be causing that @jakubmisek?

**Comment by louismrose** [comment]
> One further issue I'm now encountering is that when running the exe on my Windows box, I get the following error:
> 
> ```
> Error:
>   An assembly specified in the application dependencies manifest (tmp.deps.json)
>  was not found:
>     package: 'Devsense.PHP.Parser', version: '1.4.82'
>     path: 'lib/netstandard2.0/Devsense.PHP.Parser.dll'
> ```
> Any idea what might be causing that @jakubmisek?

Aha -- it turns out this also isn't a PeachPie issue. Sorry!

I was running the exe at `tmp/bin/Release/netcoreapp2.0/win81-x64` and should have been running the exe at `tmp/bin/Release/netcoreapp2.0/win81-x64/publish`! Thanks go to [Martin Ullrich on StackOverflow](https://stackoverflow.com/a/50292039/9902857).
