### ISSUE TITLE
Problems with stream_get_line

### ISSUE THREAD

**Issue by DaveMagrathSmith** [peachpiecompiler/peachpie#329]
I'm trying to use stream_get_line, as follows:

$line = stream_get_line($handle, 8192, '~');

However, I'm running into two issues.  The first seems easy to fix.  The function is supposed to remove the ending from the returned string.  Instead, it returns only the ending.  Here is the code from stream_get_line, on line 717 of Stream.cs:

            rv = rv.Substring(rv.Length - ending.Length);

I think the substring function should read, in order to start at position 0:

            rv = rv.Substring(0, rv.Length - ending.Length);

Secondly, while looping and calling stream_get_line repeatedly to read the entire file, it eventually fails in the ReadBinaryBuffer function, on line 852 of PhpStream.cs:

            Debug.Assert(peek.Length >= readPosition);

Somehow, the buffer length becomes less than the read position, but I'm struggling to figure out how (I can provide a copy of the file being read if that would be helpful).

Thanks,
Dave

**Comment by jakubmisek** [comment]
thank you @DaveMagrathSmith !

**Comment by DaveMagrathSmith** [comment]
Of course - thank you!

**Comment by DaveMagrathSmith** [comment]
I'm just getting around to testing this out, and see two remaining issues:

1.  The first time stream_get_line() is called, it returns the second line of the file.  It seems to skip the first line (everything prior to the first ending).

2.  Subsequent calls to stream_get_line() are missing the first character of the line, so "Third Line" gets returned as "hird Line".  This occurs the second time stream_get_line() is called, and every time thereafter.

Thanks,
Dave

**Comment by DaveMagrathSmith** [comment]
Thank you!  The first issue was a bug on my end - sorry about that.  Thanks for fixing the other problem!

**Comment by bfistein** [comment]
Thank you for reporting it and for the donation :)

**Comment by jakubmisek** [comment]
thanks @DaveMagrathSmith ! closing, if you'd find anything else, let us know
