### ISSUE TITLE
Plugin require wordpress upgrade?

### ISSUE THREAD

**Issue by garthig** [peachpiecompiler/peachpie#333]
Hi 
I have installed the plugin "ULTIMATE TABLES by Extendyourweb.com"  on both wordpres PHP source which is wordpress 5.0 version and the compiled version of c#. On the PHP site I see it's works properly after activating but on the c# compiled version it was activated but missing create edit function.
Insted its says An updated version of WordPress is available.
You can update to WordPress 5.0 automatically:
I don't know how to upgrade it since wordpress is already compiled is there any guide lines how to upgrade the compiled version ? I could only see the guidelines for installing new plugins 
Regards
Garthig

**Comment by jakubmisek** [comment]
Hi,

please move the issue to https://github.com/iolevel/wpdotnet-sdk. It was just updated to wp5.0 and all the related issues should be answered there.

Updating the wordpress is also discussed in there.
