### ISSUE TITLE
Support for nested generics

### ISSUE THREAD

**Issue by DevJohnC** [peachpiecompiler/peachpie#337]
Compiling PHP that contains nested generics will fail with a syntax error, Peachpie is missing support for nested generics like so:

`$wordpressOptions = $_SERVICES->GetRequiredService<IOptions<WordpressOptions>>()->Value;`

Currently the compiler reports an error: `unexpected ')'`.

**Comment by jakubmisek** [comment]
thank you @DevJohnC , nested generics are now supported
