### ISSUE TITLE
'Operation is not valid due to the current state of the object.'

### ISSUE THREAD

**Issue by petrsvihlik** [peachpiecompiler/peachpie#340]
Following up on #335.

I tried providing all arguments to the `DeliveryClient` constructor as suggested

https://github.com/petrsvihlik/PeachPieTests/blob/a61adb21de5c279344399986ac0a3e527154b925/kc-peachpie-console/Program.cs#L35

 but I'm getting 

> 'Operation is not valid due to the current state of the object.'

when the `UrlBuilder` is being instantiated. 

When I try to create an instance of the `UrlBuilder` myself, it works fine.

https://github.com/petrsvihlik/PeachPieTests/blob/a61adb21de5c279344399986ac0a3e527154b925/kc-peachpie-console/Program.cs#L31

Could you please suggest what I am doing wrong?

**Comment by jakubmisek** [comment]
`UrlBuilder` is not "declared" yet, but used from the PHP code resulting in "InvalidOperationException". 

This is how we decided to behave for now. There are few options tho:

- include your autoloading script file first so UriBuilder will be declared lazily when used
- call `ctx.Include("file where UriBuilder is declared");` first
- lets discuss how to handle the situation - PeachPie runtime should be careful so it requires depending scripts to be included. Not including a file and just using contained declarations may result in side effects. We can for example autoinclude a file if some of its contained declarations is used for the first time (but it is not respecting PHP's behavior).

**Comment by petrsvihlik** [comment]
For those running into similar issues, we solved it by adding: `Context.AddScriptReference(<assembly_with_php_code>);` 

in front of the following block:

```csharp 
using (var ctx = Context.CreateConsole(string.Empty, args))
{
   ctx.Include(string.Empty, @"vendor\autoload.php", true, true);               
   YourWhateverMethod(ctx);
}
```


Docs:
- https://docs.peachpie.io/api/ref/context/#methods
