### ISSUE TITLE
PDO support for FETCH_UNIQUE

### ISSUE THREAD

**Issue by DaveMagrathSmith** [peachpiecompiler/peachpie#341]
Are there any plans to support FETCH_UNIQUE? (an associative fetch, where the resulting array is indexed by the value of the first column). Would be nice, but I can work around if necessary.

Thanks,
Dave

**Comment by bfistein** [comment]
Hi @DaveMagrathSmith, we will definitely support this, but it isn't on the immediate roadmap to be honest. If you can work around it for now, that would be the preferred option, but we'll get to it once it's immediately required. 

Cc @jan-pavlovsky who implemented PDO for us just FYI for future reference.

**Comment by DaveMagrathSmith** [comment]
Thank so much @bfistein and @jan-pavlovsky, appreciate it.  I can work around for now.

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/550d0ebc3888e6b8402f340dc47d647220283f28

**Comment by DaveMagrathSmith** [comment]
Thanks for implementing this!  I'm testing it out now, but it's not behaving as expected.

Here are results for a FETCH_ASSOC:

![image](https://user-images.githubusercontent.com/42848571/52005505-db55b680-2497-11e9-803a-28eeb94bec41.png)

And here is the same query, using FETCH_UNIQUE:

![image](https://user-images.githubusercontent.com/42848571/52005869-bd3c8600-2498-11e9-87ee-e2c1cfdd90af.png)

I'm expecting the key to be the value of the first column returned (00001.BK.06 in this case).  Something like this:

items
    ["00001.BK.06"]
        ["style"]    ….    '00001'
        ["color"]    ….    'BK'
        ["class"]    ….    '06'
        ["qtyBux"]    ….    0
    ["00001.BK.12"]
        ...
    ["00001.BR.06"]
        …
    etc

**Comment by jakubmisek** [comment]
thanks!

more fixes in https://github.com/peachpiecompiler/peachpie/commit/d80a1fae1bdb90c276d170d701e4af764b220269

PDO fetch modes will be reimplemented since there are much more combinations we didn't think of.

**Comment by jakubmisek** [comment]
`FETCH_UNIQUE` fixed

we'll close the issue for now, the compatibility with PDO FETCH flags will be improved in upcoming commits. If wou'd find any more issues, please start a new issue - the screenshot help a lot. Thanks!

**Comment by DaveMagrathSmith** [comment]
Thanks so much @jakubmisek !

I'll test again at the next release.
