### ISSUE TITLE
ReflectionFunction does not support Closure

### ISSUE THREAD

**Issue by hz86** [peachpiecompiler/peachpie#342]
An unhandled exception occurred while processing the request.
NotImplementedException: The method or operation is not implemented.
Pchp.Library.Reflection.ReflectionFunction.__construct(Context ctx, PhpValue name)

```
<?php

$fun = function ():string {
    return '';
};

$reflection = new ReflectionFunction($fun); //exception 
```

**Comment by jakubmisek** [comment]
known unsupported features: getting parameters number, export, getExtensionName, hasReturnType, isGenerator, isVariadic

please post issues if needed
