### ISSUE TITLE
difficulty including/using php library

### ISSUE THREAD

**Issue by xaviercarmo** [peachpiecompiler/peachpie#344]
Hi, as a bit of context this is what I'm trying to achieve:
Implement a Beider-Morse Phonetic Algorithm in C#. I can only find implementations written in PHP, so I am trying to use your PeachPie compiler to create a PHP library that I can use from C# (In Visual Studio 2017). I've looked through your blog posts and documentation, and found some conflicting info about how to include (ctx.include) and use files, and I'm a bit lost about what is curently implemented, what is outdated etc. etc.

Alright, so the problem I'm facing at the moment is that I have the following C# file in a C# console project:
![image](https://user-images.githubusercontent.com/13409392/50938559-dc18af80-14cc-11e9-9594-45b7bdb63677.png)

This project is in the same solution as my php project, which contains the php library (that I have compiled into a .Net dll successfully I believe).

When I run my C# console application, it gets to the point of creating the new type, and (I think) fails to find the "BMDM" class, giving this error:
![image](https://user-images.githubusercontent.com/13409392/50938656-50535300-14cd-11e9-8dbd-c96bb7735a61.png)

After looking through your github I think I found the tinfo it's referring to, and I believe it's throwing the ArgumentNullException because the Include for BMDM.php has failed, and so the class is not defined.

Some extra notes about things I've tried/noticed:
I have a separate console project (using the peachpie console Visual Studio extension) where i tested the functionality of the library on its own and managed to get it working fine, instantiating that same class (BMDM) and then using its methods. The only quirk is that my require_once() calls were playing up. Originally (before i made changes) the BMDM class file had `require_once("library/Core.php")` and `use dautkom\bmdm\library\Core` at the top, so that BMDM could extend the Core class (`BMDM extends Core {}`). Then, in a different file called program.php i had `require_once("BMDM.php")` and could continue to use the class BMDM and its methods. This worked fine in Xampp. When I used PeachPie however i was forced to move the `require_once("library/Core.php")` from the BMDM.php file, to the program.php file _before_ the require for the BMDM.php file. If i did not do this, then upon instantiating the BMDM class in program.php i would get an error at the `extends` part of the BMDM class declaration information me "the operation is invalid due to the current state of the object".
I'm not sure if that's helpful or relevant, but included just in case.

Also, if I (instead of side-loading the assembly), add `using dautkom.bmdm` (as you can see commented out at the top of my first picture), then I can access all the classes successfully (statements like var test = new BMDM() work) but still cannot use the methods without other strange errors, if this sounds relevant i can try and include some screenshots and stuff and elaborate.

Finally, I've just noticed in the output log that side-loading the assembly results in this error (no matter what combination of obscure relative paths I throw at it...):
![image](https://user-images.githubusercontent.com/13409392/50946693-b8666100-14ee-11e9-9f6e-bd552d84d2f2.png)

Thanks for any help you can give, sorry if anything was unclear/if I've forgotten to include anything important. Happy to clarify/give more info if needed :)

**Comment by xaviercarmo** [comment]
Ok, so I realise now after reading a different issue that i should have been using createConsole, not createEmpty (my working directory was null). However my issue concerning the extension (under extra notes) still stands, and is now preventing me from moving forward, so if you have any insight on that topic that would still be greatly appreciated!

**Comment by jakubmisek** [comment]
Hi,

Do you have the project somewhere opensourced ? 

I see a possible issue in performing the `include` - using ctx.Include( ... ); This call should pass and its purpose is only to "simulate" what would happen in native PHP. It virtually declares contained PHP classes and functions as it does in PHP. When you use a PHP class, the runtime has to check it was properly declared (just to make sure the containing file was included and any additional global code next to the class declaration executed).

When including a file like "BMDM.php", it is important to specify full relative path. In this case I guess the file is located in the project's root directory?

The `PHP (Warning)` might give a clue, something is trying to include 'index.php' but the file is not compiled? the working directory is invalid? does the `ctx.RootPath` match current working directory?

Once we find out, we'll definitely summarize this into docs, and maybe improve the warning messages.

**Comment by jakubmisek** [comment]
@xaviercarmo Have you made any progress?

In short, it is important to "include" (`ctx.Include(...)`) everything that you would have to include in regular PHP. Check `ctx.RootPath` whether it is not `null` or empty.

**Comment by xaviercarmo** [comment]
Hi Jakub, thanks a tonne for that super speedy reply! Unfortunately i posted this issue at work on thursday and i only work mon-thurs, so i dont actually have access to the files right now...ill try and answer your questions best i can though.

Unfortunately i can't opensource it due to it being a work-related task haha. ctx.include(...) is now working fine after i starting using Context.createconsole(null), instead of createEmpty() - i was only using createEmpty() because in one of the tutorials createConsole has a no-parameter implementation and i erroneously assumed createEmpty had possible superseded that implementation or something, big mistake on my part!!

the main issue/question now (ignoring the crossover functionality between c# and php) is that in my php files, for some reason those includes/requires are behaving oddly, which i don't think i expressed very well above. This is the file structure:

library          -> Core.php (+ some other files)

BMPM.php
Program.php (I added this one)

And BMPM.php requires core, as the BMPM class extends the core class. If i run it on xampp, my program.php file needs to only `require('BMPM.php')` and then everything runs fine, i can call all functions, class methods etc.
If i compile it into a .net console application using PeachPie, I must change program.php to first `require('core.php')` and then `require('BMPM.php')`, otherwise when BMPM.php attempts to `require('Core.php')` it fails, with the error message being "the operation is invalid due to the current state of the object"

Hopefully i made that a little bit clearer this time? if not ill try and just get a few of the files to you on monday, im sure my manager wont mind since this has been a bit of a blocking issue for my work item haha

Thanks again for your help!

**Comment by jakubmisek** [comment]
Got it. First the exception `The operation is invalid due to the current state of the object` corresponds to `extends Core` piece of code (seems like Visual Studio debugger highlights the line above instead).

When debugging, go to a stack frame where there is an instance of `Context` and check following:
- `RootPath` and `WorkingDirectory` are both non empty.
- `GetDeclaredTypes()` returns list of declared classes and interfaces. Check it contains `Core` class (including the namespace)

**Comment by xaviercarmo** [comment]
yeah it was highlighting the `extends Core` bit, just didnt make that clear my bad. And it was definitely accompanied by that error in the output window.

While making the crossover version i did debug and have a look at context + used GetDeclaredTypes as well as some of the other functions like the included files ones (i think, sorry, like i said this is all from memory haha) and before changing from createEmpty() to createConsole() the RootPath, WorkingDirectory, and pretty much anything related to the magic constants from PHP were null. After changing to createConsole i assume this fixed since my includes started working but ill check tomorrow.

However while only working with the PHP the only thing i noticed is that the magic constants are wrong, they are initialising from the .net dll that is generated by the compiler, rather than the file of execution itself (had to make some changes in the library to account for this). Could this possibly be the issue? Is PHP using an erroneous "root path" or something? (sorry, am still fairly new to PHP)

**Comment by jakubmisek** [comment]
@xaviercarmo this is set from process's `CurrentWorkingDirectory` which is set by Visual Studio when you start your project (see projects `Properties` and `Working Directory` option).

PHP's  `__DIR__`, `__FILE__` and scripts path do all correspond to `Context.RootPath` which is set to "CurrentWorkingDirectory", so it can be the DLL's path and it will work.

By other words,

Everything is relative to `Context.RootPath` = `CurrentWorkingDirectory`. By default it is your DLL's path and it is ok. 
`__DIR__` = RootPath
`__FILE__` = RootPath + "script's relative path"
`include "./script's relative path";` // should work
`include __DIR__ . "/script's relative path";` // should work

**Comment by jakubmisek** [comment]
What usually happens:
The exception on `extends Core` means `Core` is not declared. I guess in PHP it gets "autoloaded", so it is important to include something like `ctx.Include("","vendor/autoload.php");`

**Comment by jakubmisek** [comment]
Lets close it for now. We can continue discussing in here : )
