### ISSUE TITLE
require not finding path

### ISSUE THREAD

**Issue by favamaker** [peachpiecompiler/peachpie#347]
When I try to include a php file from another folder, the script is not found:
require __DIR__ . 'vendor/autoload.php';

Script 'vendor/autoload.php' inclusion failed. Cause: Script file 'vendor/autoload.php' not found. Search paths: include_path is '.', working directory is ''

**Comment by jakubmisek** [comment]
Check the `Context.RootPath` property is set. This value is usually passed from the `Context` constructor.

It seems like `WorkingDirectory` and `RootPath` are both not set.

**Comment by favamaker** [comment]
oh thats it, thanks a lot, do you have an example? I cant find any in
google.

Em sáb, 12 de jan de 2019 às 15:57, Jakub Míšek <notifications@github.com>
escreveu:

**Comment by jakubmisek** [comment]
We have some samples on https://github.com/iolevel/peachpie-samples

Do you have a specific scenario?

**Comment by favamaker** [comment]
Please help me, I cant find this anywhere, in the following code, the
compiler doesnt allow me to rebuild:

namespace InstagramAPILibrary;

require __DIR__ . '/vendor/autoload.php';

/**
 * A sample class.
 */
class StartClass extends Instagram
{

It says typename Instagram could not be resolved, even it exists in the
folder.

Em sáb, 12 de jan de 2019 às 17:29, Benjamin Fistein <
notifications@github.com> escreveu:
