### ISSUE TITLE
Unable to parse response code from HTTP response due to malformed response

### ISSUE THREAD

**Issue by petrsvihlik** [peachpiecompiler/peachpie#350]
The [HTTP client library](http://phphttpclient.com/) that I use in [my project](https://github.com/petrsvihlik/PeachPieTests) (and that internally uses `curl_exec`) expects the value part of a header [to be numeric](https://github.com/nategood/httpful/blob/master/src/Httpful/Response.php#L126) while it's string:
![image](https://user-images.githubusercontent.com/9810625/51633589-4829f780-1f52-11e9-9ac8-5116b3395a9c.png)

That causes the following exception:

> Pchp.Library.Spl.Exception: 'Unable to parse response code from HTTP response due to malformed response'

Stack trace:
>C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\vendor\nategood\httpful\src\Httpful\Response.php(143,12)
#0 C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\vendor\nategood\httpful\src\Httpful\Response.php(40,8): Response->_parseCode($headers)
#1 C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\vendor\nategood\httpful\src\Httpful\Request.php(1047,8): Response->__construct($body, $headers, $request, $meta_data)
#2 C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\vendor\nategood\httpful\src\Httpful\Request.php(203,8): Request->buildResponse($result)
#3 C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\src\KenticoCloud\Delivery\DeliveryClient.php(299,12): Request->send()
#4 C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\src\KenticoCloud\Delivery\DeliveryClient.php(208,8): DeliveryClient->sendRequest($uri, $attemptNumber)
#5 C:\Users\rocky\Documents\GitHub\peachpie_web\kc-peachpie-console\Program.cs(47,12): DeliveryClient->getType($codename)
#6 C:\Users\rocky\Documents\GitHub\peachpie_web\kc-peachpie-console\Program.cs(19,16): Program::TestInterop2()
#7 : Program::Main($args)

**Comment by jakubmisek** [comment]
Thanks @petrsvihlik !

**Comment by jakubmisek** [comment]
I have an update :)

- no more necessary to call `AddScriptReference`
