### ISSUE TITLE
Strict comparison with null fails for a parameter with default value and class type hint

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#355]
```php
function test(DateTime $v = null) {
	if(null === $v) {
		echo 'null';
	} else {
		echo 'something';
	}	
}

test();
```
Version 0.9.31 gives a compiler warning `warning PHP5011: Unreachable code detected` on line 3. At runtime the output is `something`. Running the same code with PHP 7.2.7 outputs `null`.

**Comment by jakubmisek** [comment]
Great test case - compiler thinks `$v` cannot be `null` and optimizes out the condition. Will be fixed.

**Comment by bfistein** [comment]
@crbrz awesome issues, thanks a lot!

**Comment by crbrz** [comment]
I use WordPress and its plugins as source of "inspiration" 😃. This one is a simplified version of what Woocommerce 3.5.4 uses in one of its background tasks.
