### ISSUE TITLE
Unable to parse response code from HTTP response due to malformed response - II.

### ISSUE THREAD

**Issue by petrsvihlik** [peachpiecompiler/peachpie#357]
Following up on #350 

![image](https://user-images.githubusercontent.com/9810625/52089798-ce2beb00-25af-11e9-8b12-e730b4f47406.png)

Now the problem seems to be that the second part is not numeric.

**Comment by jakubmisek** [comment]
Thank you!

This seems however to work well for me:
```php
    $parts = ['HTTP/1.2', '200', 'OK'];
    if (count($parts) < 2 || !is_numeric($parts[1]))
    {
        echo "Fails!";
    }
    else
    {
        echo "Success";
    }
```
Is the value of `'200'` correct? Doesn't it contain some whitespaces that can't be seen on your screenshot?

**Comment by petrsvihlik** [comment]
I was just about to test it but I updated to 0.9.34 (from 0.9.31) and it seems to be working fine now...interesting.
Thanks so far!
