### ISSUE TITLE
How  can I direct run a complex php website ?

### ISSUE THREAD

**Issue by RockNHawk** [peachpiecompiler/peachpie#359]
Hi,
I have follow Peachpie for a long time,

Today I try run nextcloud (an open source, self-hosted file share and communication platform)

But get many compile error , 
Does Peachpie possible to direct run any complex php web site without any modify in the future ?

Thanks,
Thanks Peachpie developer's great work, It's cool !

Here some compile error message, Hope it can help for Peachpie:

`
nextcloud.peachpie/Website/nextcloud/3rdparty/aws/aws-sdk-php/src/S3/S3MultiRegionClient.php(243,25): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git
`

`/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/psr/log/Psr/Log/Test/LoggerInterfaceTest.php(14,44): error PHP4044: Type name 'PHPUnit_Framework_TestCase' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/console/DependencyInjection/AddConsoleCommandPass.php(27,40): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(25,40): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/DependencyInjection/RoutingResolverPass.php(24,38): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/DependencyInjection/RoutingResolverPass.php(26,9): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\PriorityTaggedServiceTrait' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/AnnotationClassLoader.php(58,49): error PHP4044: Type name 'Symfony\Component\Config\Loader\LoaderInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/AnnotationFileLoader.php(25,36): error PHP4044: Type name 'Symfony\Component\Config\Loader\FileLoader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/ClosureLoader.php(24,29): error PHP4044: Type name 'Symfony\Component\Config\Loader\Loader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/ObjectRouteLoader.php(23,42): error PHP4044: Type name 'Symfony\Component\Config\Loader\Loader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/DirectoryLoader.php(18,31): error PHP4044: Type name 'Symfony\Component\Config\Loader\FileLoader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/GlobFileLoader.php(22,30): error PHP4044: Type name 'Symfony\Component\Config\Loader\FileLoader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/PhpFileLoader.php(26,29): error PHP4044: Type name 'Symfony\Component\Config\Loader\FileLoader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/XmlFileLoader.php(26,29): error PHP4044: Type name 'Symfony\Component\Config\Loader\FileLoader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/routing/Loader/YamlFileLoader.php(27,30): error PHP4044: Type name 'Symfony\Component\Config\Loader\FileLoader' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/translation/DataCollector/TranslationDataCollector.php(23,40): error PHP4044: Type name 'Symfony\Component\HttpKernel\DataCollector\DataCollector' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/translation/DataCollector/TranslationDataCollector.php(23,65): error PHP4044: Type name 'Symfony\Component\HttpKernel\DataCollector\LateDataCollectorInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/translation/DependencyInjection/TranslationDumperPass.php(21,40): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/translation/DependencyInjection/TranslationExtractorPass.php(22,43): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
/home/s/git/nextcloud.peachpie/Website/nextcloud/3rdparty/symfony/translation/DependencyInjection/TranslatorPass.php(19,33): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface' could not be resolved. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]
`

The last error:
`/home/s/.nuget/packages/peachpie.net.sdk/0.9.31/build/Peachpie.NET.Core.Sdk.targets(166,5): error MSB3073: The command "dotnet "/home/s/.nuget/packages/peachpie.compiler.tools/0.9.31/build/../tools/dotnet-compile-php.dll" @obj/Debug/netstandard2.0/compile-php-args.rsp" exited with code 1. [/home/s/git/nextcloud.peachpie/Website/Website.msbuildproj]

The build failed. Please fix the build errors and run again.
`

**Comment by jakubmisek** [comment]
Thank you!

**Comment by jakubmisek** [comment]
Basically you have two types of error (see https://docs.peachpie.io/php/diagnostics/ for details):
- `PHP4042` - yield from try/catch is not supported - and you have to modify the source to fix this
- `PHP4044` - the compiler needs to know the class to be able to compile the code. This can be fixed without modification to the source:
  - using `PHPUnit_Framework_TestCase` and any PHPUnit** classes means you are compiling TESTS together with your website. Solution is to Exclude any test files from your compilation https://blogs.msdn.microsoft.com/msbuild/2006/03/08/how-to-exclude-multiple-files-from-a-wildcard/ E.g. `<Compile Include="**/*.php" Exclude="**/tests/**" />`
  - other unresolved classes means you are probably missing some source files. Copy the missing files or __Exclude__ the files that you don't need from a project.

**Comment by RockNHawk** [comment]
> https://docs.peachpie.io/php/diagnostics/

Thank you!

I just remove the test file, and another compile error is some  PHP file could not found, I think Peachpie can **lazy compile** some PHP file (maybe have an option to switch lazy compile ) and **just throw an Exception when the lazy compile failed at runtime**, although some PHP file is missing, it just  effect some page or a little feature not all feature, but now a little missing file will cause the whole build fail , and could not got work easily.

Finally, I think more and more open source PHP project will be targeting to Peachpie (first by some personal developer, then the official author inherit it), and Peachpie can calling people to initiate the work or collect work results .

**Comment by jakubmisek** [comment]
closing for now; we can continue discussing the progress in here.
