### ISSUE TITLE
tinfo cannot be null

### ISSUE THREAD

**Issue by petrsvihlik** [peachpiecompiler/peachpie#360]
Hi guys,
I'm slowly working towards my goal. 

Now I'm getting the following exception:
>Message: System.ArgumentNullException : Value cannot be null.
Parameter name: tinfo

When I run this test

https://github.com/petrsvihlik/PeachPieTests/blob/master/kc-peachpie-test/PeachPieTests.cs#L48

which internally calls this PHP code: 

https://github.com/petrsvihlik/PeachPieTests/blob/master/kc-sdk/src/KenticoCloud/Delivery/Example.php#L8

I compared my code to your [sample code](https://github.com/iolevel/peachpie-samples/tree/master/using-csharp-from-php) and can't really tell what's causing the issue. The code is basically the same.

Any idea?

**Comment by jakubmisek** [comment]
This exception happens if PHP expects some class to be declared but it isn't.

```php
<?php
new X;
```
where `X` has not been declared (included) in the PHP context.

Do you have a callstack for that ?

**Comment by petrsvihlik** [comment]
Sure.

>   at Pchp.Core.Context.Create(RuntimeTypeHandle caller, PhpTypeInfo tinfo, PhpValue[] arguments)
   at KenticoCloud.Delivery.Example.TestInstantiation() in C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\src\KenticoCloud\Delivery\Example.php:line 10
   at kc_peachpie_test.PeachPieTests.TestInteropInstantiation() in C:\Users\rocky\Documents\GitHub\peachpie_web\kc-peachpie-test\PeachPieTests.cs:line 51

To test it out, just clone the mentioned repo and run the `TestInteropInstantiation()` test.

**Comment by jakubmisek** [comment]
It means `Models\Article` (https://github.com/petrsvihlik/PeachPieTests/blob/b85a6baefc2dd9744edb75b38a2fdf85a27a6bb5/kc-sdk/src/KenticoCloud/Delivery/Example.php#L10) is not a known class. We'll fix the exception message.

You have to make sure the file that declares `Article` is included. Either provide autoload or `include_once` manually. If you have an autoload, just include it once whenj you're creating the Context.

**Comment by jakubmisek** [comment]
Closing for now; the class `Article` must be declared first.
