### ISSUE TITLE
EmitAdd on void and smth.

### ISSUE THREAD

**Issue by petrroll** [peachpiecompiler/peachpie#361]
```
<?php
function a(){
}

function b(){
	return 3;
}
echo(a() + b());
```

Expected: 3
Actual: Exception

**Comment by petrroll** [comment]
Two issues: 
1) No conversion Void->PhpNumber 
2) EmitAdd, ..., doesn't even try to convert Void->PhpNumber

**Comment by petrroll** [comment]
Some operators have branches that - for some combinations - convert to PhpValue (which can also handle Void type) and then do said operation. E.g. `a() - b()` works. It's heavily inconsistent, however.

**Comment by jakubmisek** [comment]
This will be resolved in future - planning to implement all the operators in general by looking for best fitting `operator` method with given parameters (like in C#). So all this code that checks Left/Right type will be gone.
