### ISSUE TITLE
Specified value does not have a ':' separator.

### ISSUE THREAD

**Issue by petrsvihlik** [peachpiecompiler/peachpie#363]
After upgrading to 0.9.35, I started getting:

>Message: System.ArgumentException : Specified value does not have a ':' separator.
Parameter name: header

Stack trace:
>   at System.Net.WebHeaderCollection.Add(String header)
   at Peachpie.Library.Network.CurlOption_Headers.Apply(HttpWebRequest request)
   at Peachpie.Library.Network.CURLFunctions.ExecHttpRequestInternalAsync(Context ctx, CURLResource ch, Uri uri)
   at Peachpie.Library.Network.CURLFunctions.StartRequestExecution(Context ctx, CURLResource ch)
   at Peachpie.Library.Network.CURLFunctions.curl_exec(Context ctx, CURLResource ch)
   at Httpful.Request.send() in C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\vendor\nategood\httpful\src\Httpful\Request.php:line 202
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at KenticoCloud.Delivery.DeliveryClient.sendRequest(String uri, Int64 attemptNumber) in C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\src\KenticoCloud\Delivery\DeliveryClient.php:line 300
   at KenticoCloud.Delivery.DeliveryClient.getType(PhpValue codename) in C:\Users\rocky\Documents\GitHub\peachpie_web\kc-sdk\src\KenticoCloud\Delivery\DeliveryClient.php:line 209
   at kc_peachpie_test.PeachPieTests.TestInteropGetType() in C:\Users\rocky\Documents\GitHub\peachpie_web\kc-peachpie-test\PeachPieTests.cs:line 64

You can try it out if you run the following test:
- https://github.com/petrsvihlik/PeachPieTests/blob/master/kc-peachpie-test/PeachPieTests.cs#L59

It used to work in 0.9.34. Could you please have a look into it?

It blocks me from wrapping up #360.

**Comment by jakubmisek** [comment]
Thanks, this hasn't been changed; can you take a look on stack frame `CurlOption_Headers.Apply`, value of `this.OptionValue`? There is probably a header value without `:` which might be allowed in PHP but not in .NET.

**Comment by petrsvihlik** [comment]
It takes quite a lot of effort debugging the `Peachpie.Library.Network`. Don't you want to enable [SourceLink](https://github.com/dotnet/sourcelink) & [symbol publishing](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) on those NuGets?

- Can you have a look at #365?

In the meantime, this is what I've collected from `Httpful.Request.send()` so far:

  | Name | Value | Type
-- | -- | -- | --
◢ | this | {Httpful.Request} | Httpful.Request
  | ▶ _ch | Peachpie\Library\Network\CURLResource#12F0C86 | resource
  | ▶ _debug | NULL | NULL
  | ▶ additional_curl_opts | array(length = 0) | array
  | ▶ auto_parse | true | boolean
  | ▶ content_type | 'application/json' | string
  | ▶ error_callback | NULL | NULL
  | ▶ expected_type | 'application/json' | string
  | ▶ follow_redirects | false | boolean
  | ◢ headers | array(length = 2) | array
  | ▶ ["X-KC-SDKID"] | 'packagist.org;kentico-cloud/delivery-sdk-php;2.0.0' | string => string
  | ▶ ["Content-Length"] | 0 | string => integer
  | ◢ Raw View |   |  
  | Count | 2 | int
  | ▶ IntrinsicEnumerator | array(length = 2) | array
  | IsFixedSize | false | bool
  | IsReadOnly | false | bool
  | IsSynchronized | false | bool
  | ▶ Keys | {Pchp.Core.OrderedDictionary.KeysCollection} | System.Collections.Generic.ICollection<Pchp.Core.IntStringKey> {Pchp.Core.OrderedDictionary.KeysCollection}
  | Pchp.Core.IPhpEnumerator.AtEnd | false | bool
  | ▶ Pchp.Core.IPhpEnumerator.CurrentKey | 'X-KC-SDKID' | string
  | ▶ Pchp.Core.IPhpEnumerator.CurrentValue | 'packagist.org;kentico-cloud/delivery-sdk-php;2.0.0' | string
  | ▶ Pchp.Core.IPhpEnumerator.CurrentValueAliased | 'packagist.org;kentico-cloud/delivery-sdk-php;2.0.0', Refs#error CS0103: The name '_refcount' does not exist in the current context | &string
  | ▶ SyncRoot | array(length = 2) | array
  | ▶ System.Collections.Generic.IEnumerator<System.Collections.Generic.KeyValuePair<Pchp.Core.PhpValue, Pchp.Core.PhpValue>>.Current | {[X-KC-SDKID, packagist.org;kentico-cloud/delivery-sdk-php;2.0.0]} | System.Collections.Generic.KeyValuePair<Pchp.Core.PhpValue, Pchp.Core.PhpValue>
  | System.Collections.IEnumerator.Current | "packagist.org;kentico-cloud/delivery-sdk-php;2.0.0" | object {string}
  | TypeCode | PhpArray | Pchp.Core.PhpTypeCode
  | ▶ Values | {Pchp.Core.OrderedDictionary.ValuesCollection} | System.Collections.Generic.ICollection<Pchp.Core.PhpValue> {Pchp.Core.OrderedDictionary.ValuesCollection}
  | _intrinsicEnumerator | 0 | int
  | _visited | 0 | int
  | ▶ table | dictionary (count = 2) | Pchp.Core.OrderedDictionary
  | ▶ Static members |   |  
  | ◢ Raw View |   |  
  | ▶ Alias | 'this.headers.Alias' threw an exception of type 'System.InvalidCastException' | Pchp.Core.PhpAlias {System.InvalidCastException}
  | ▶ Array | array(length = 2) | array
  | Boolean | false | bool
  | DebugTypeName | "array" | string
  | DisplayString | "array(length = 2)" | string
  | Double | 0 | double
  | IsAlias | false | bool
  | IsArray | true | bool
  | IsBoolean | false | bool
  | IsDefault | false | bool
  | IsEmpty | false | bool
  | IsNull | false | bool
  | IsObject | false | bool
  | IsScalar | false | bool
  | IsSet | true | bool
  | Long | 0 | long
  | ◢ MutableString | 'this.headers.MutableString' threw an exception of type 'System.InvalidCastException' | Pchp.Core.PhpString {System.InvalidCastException}
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2147467262 | int
  | HelpLink | null | string
  | ▶ IPForWatsonBuckets | {140734233426660} | System.UIntPtr
  | ▶ InnerException | null | System.Exception
  | IsTransient | false | bool
  | Message | "Unable to cast object of type 'Pchp.Core.PhpArray' to type 'Blob'." | string
  | RemoteStackTrace | null | string
  | Source | "Peachpie.Runtime" | string
  | StackTrace | "   at Pchp.Core.PhpValue.get_MutableString()" | string
  | ▶ TargetSite | {Pchp.Core.PhpString get_MutableString()} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | WatsonBuckets | null | object
  | _HResult | -2147467262 | int
  | _className | null | string
  | ▶ _data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | _dynamicMethods | null | object
  | ▶ _exceptionMethod | {Pchp.Core.PhpString get_MutableString()} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | _helpURL | null | string
  | ▶ _innerException | null | System.Exception
  | ▶ _ipForWatsonBuckets | {140734233426660} | System.UIntPtr
  | _message | "Unable to cast object of type 'Pchp.Core.PhpArray' to type 'Blob'." | string
  | _remoteStackIndex | 0 | int
  | _remoteStackTraceString | null | string
  | _source | "Peachpie.Runtime" | string
  | ▶ _stackTrace | {sbyte[48]} | object {sbyte[]}
  | _stackTraceString | null | string
  | _watsonBuckets | null | object
  | _xcode | -532462766 | int
  | ▶ _xptrs | {0} | System.IntPtr
  | ▶ Static members |   |  
  | ▶ MutableStringBlob | 'this.headers.MutableStringBlob' threw an exception of type 'System.InvalidCastException' | Pchp.Core.PhpString.Blob {System.InvalidCastException}
  | ▶ Object | array(length = 2) | array
  | ▶ String | 'this.headers.String' threw an exception of type 'System.InvalidCastException' | string {System.InvalidCastException}
  | TypeCode | PhpArray | Pchp.Core.PhpTypeCode
  | ▶ _obj | array(length = 2) | array
  | ▶ _type | {Pchp.Core.PhpValue.ArrayTable} | Pchp.Core.PhpValue.TypeTable {Pchp.Core.PhpValue.ArrayTable}
  | ▶ _value | {Pchp.Core.PhpValue.ValueField} | Pchp.Core.PhpValue.ValueField
  | ▶ Static members |   |

**Comment by jakubmisek** [comment]
thanks, it was a typo in the latest version affecting cURL headers and PDO. Following looks reasonable I guess (send was successful)

![image](https://user-images.githubusercontent.com/842150/53736370-d23a7980-3e89-11e9-91fd-f29c6d315bf6.png)

**Comment by petrsvihlik** [comment]
cool, looking forward to trying it out with the next release ;)

**Comment by petrsvihlik** [comment]
works fine in 0.9.36
👍
