### ISSUE TITLE
Push symbols to NuGet

### ISSUE THREAD

**Issue by petrsvihlik** [peachpiecompiler/peachpie#368]
Follow up to: #365

I noticed that `.snupkg`s are not being pushed to NuGet... e.g. https://www.nuget.org/packages/Peachpie.Library/0.9.36 still doesn't have its symbols.

Could you please adjust the publishing process? 

Docs:
- https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#nugetorg-symbol-server

**Comment by jakubmisek** [comment]
MyGet.org seems to ignore `.snupkg` files and does not allow pushing them to NuGet.org yet.

We'll try to run the process on DevOps next time.

**Comment by jakubmisek** [comment]
just introduced NuGet feed:
>> https://ci.appveyor.com/nuget/peachpie <<

- Always built from latest source code
- Always have corresponding .snupkg

Please use this one for development : )

**Comment by petrsvihlik** [comment]
cool, thx
