### ISSUE TITLE
PDO error with FETCH_UNIQUE

### ISSUE THREAD

**Issue by DaveMagrathSmith** [peachpiecompiler/peachpie#370]
I'm testing out support for FETCH_UNIQUE on v0.9.36, with a simple select statement, just pulling two columns:

`SELECT [No_] AS itemNo, Description FROM Item ORDER BY [No_]`

And I get this error:

![error](https://user-images.githubusercontent.com/42848571/53906570-4a837500-4019-11e9-96ce-d34cad3c4d2d.png)

The fetch works fine when using FETCH_ASSOC.

Thanks,
Dave

**Comment by jakubmisek** [comment]
May I ask for a test case? sample PHP code and a DB scheme. Thank you : )

**Comment by DaveMagrathSmith** [comment]
Sure :)

Here's a script to create a table and insert test data in a SQL Server database:

`CREATE TABLE [dbo].[PDOTest](
	[ID] [varchar](20) NOT NULL,
	[Value1] [varchar](20) NULL,
	[Value2] [varchar](20) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[PDOTest] ([ID], [Value1], [Value2]) VALUES (N'Item1', N'aaaa', N'bbbb')
GO
INSERT [dbo].[PDOTest] ([ID], [Value1], [Value2]) VALUES (N'Item2', N'1111', N'2222')
GO`

And here's PHP code to query it (obviously you'll need to reference Peachpie.Library.PDO.SqlSrv and change the connection string for your server/database):

`$conn = new PDO('sqlsrv:Server=ServerName;Database=DatabaseName', 'User', 'Password');
$sql = "SELECT ID, Value1, Value2 FROM PDOTest";
$query = $conn->prepare($sql);
$query->execute();
$items = $query->fetchAll(PDO::FETCH_UNIQUE);`

**Comment by DaveMagrathSmith** [comment]
This is working perfectly now in the latest release (0.9.38).  Thank you!  :)
