### ISSUE TITLE
EXEC : error PHP4041: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#371]
The following error is shown. No PHP reference is given.

```
EXEC : error PHP4041: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.
[path]\.nuget\packages\peachpie.net.sdk\1.0.0-appv2300\build\Peachpie.NET.Core.Sdk.targets(167,5): error MSB3073: The command "dotnet "[path]\.nuget\packages\peachpie.compiler.tools\1.0.0-appv2300\build\../tools/dotnet-compile-php.dll" @obj\Debug\netstandard2.0\compile-php-args.rsp" exited with code 1.
```

Error msg points to line 167  in file .nuget\packages\peachpie.net.sdk\1.0.0-appv2300\build\Peachpie.NET.Core.Sdk.targets: 

`
<Exec Command="dotnet &quot;$(PeachpieToolFullPath)&quot; @$(TempOutputDir)compile-php-args.rsp" />`

**Comment by jakubmisek** [comment]
https://docs.peachpie.io/php/diagnostics/
see PHP4041 and the error message.

**Comment by menturion** [comment]
Thanks for the link. 
Got it. However, it will be difficult and time-consuming to split up the project.

**Comment by jakubmisek** [comment]
This is limitation of .NET DLL.
Every piece of HTML text within PHP files and every echo together must not exceed certain limit.

We're aware of this limitation and will put HTML text into resources which do not have the limit, but it is a future feature, not planned for now.

**Comment by jakubmisek** [comment]
@menturion  what framework/project do you compile ?

**Comment by menturion** [comment]
@jakubmisek this project isn't based on one of the common (PHP) frameworks. 
It contains about 12,000 PHP files, referencing a minimum set of vendor libs. 

Would you mind when I file an official feature request with reference to the solution of this limitation you mentioned above?

**Comment by jakubmisek** [comment]
I'm pretty sure we cannot do much about this limitation. The only workaround for now is to split the project into two.

**Comment by menturion** [comment]
I ran into this problem again. 
Is there a way to identify the affected code maybe by adding further information into the error message (PHP4041)?

**Comment by jakubmisek** [comment]
This is caused by ALL the strings within the project combined.

The simplest solution is to split the project into two. In future compiler might be more effective when allocating strings.
