### ISSUE TITLE
Declare construct will be ignored, because it is currently not supported by Peachpie.

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#372]
The following PHP5012 warning is displayed multiple times while compiling e.g. "vendor\phpfastcache":
`
Declare construct will be ignored, because it is currently not supported by Peachpie.`

Example: 
https://github.com/PHPSocialNetwork/phpfastcache/blob/64638b27f473aa26603e84288d91a2b80a4aa388/lib/Phpfastcache/Drivers/Memcache/Driver.php#L14

Will ignoring "declare" constructs lead to issues at runtime?

**Comment by jakubmisek** [comment]
Yes, the compiler and runtime are both very strict about types so this construct has no effect.

Currently (version 0.9) the compiler does not allow type mismatches and runtime throws an exception in case types do not match.

You can disable reporting of such warning in case you are aware of them (https://docs.peachpie.io/php/msbuild/#nowarn)

**Comment by menturion** [comment]
Ok, thanks (for the link).
