### ISSUE TITLE
[Discussion] How to deal with templates?

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#374]
Many PHP web apps are using template systems like Twig, Smarty etc. 
At runtime the template system compiles template specific tags to PHP and dumps these templates to a certain folder if a user requests a controller for the first time. 

Does this dynamic mechanism still work if the app would have been compiled by PeachPie without any changes?

To my current understanding this won't work(?).

-- So do I have to compile all templates to PHP templates in advance?

-- Or is there any mechanism that supports creating C# templates dynamically?

**Comment by jakubmisek** [comment]
currently (as of planned for `1.0` version) we don't allow dynamic compilation and the project is more focused on precompiling PHP packages/components into statically compiled DLL's (WordPress, PhpUnit, plugins, certain libraries, ...)

What is very possible we'll implement twig and blade compilers and somehow do the dirty job during compilation of itself. (we're already planning compilation of regular expressions during compile time)

Workaround for now: generate twig or blade php files and rebuild the project

**Comment by menturion** [comment]
Again, many thanks for your help!

So as supposed I will have to code a script that compiles and dumps all templates to "PHP templates" before (re)building the app through PeachPie.

**Comment by jakubmisek** [comment]
probably yes, for now : )
