### ISSUE TITLE
ArgumentException: Function 'password_verify' not found

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#379]
Function "password_verify" (http://php.net/manual/function.password-verify.php) not found:

```
An unhandled exception occurred while processing the request.
ArgumentException: Function 'password_verify' not found!
Pchp.Core.Dynamic.CallBinder.BindMissingMethod(CallSiteContext bound)
```

**Comment by jakubmisek** [comment]
confirming - `password_verify` is not impl in peachpie

**Comment by menturion** [comment]
Although implemented, "password_verify" is not able to verify PWDs.
PWDs are hashed (-> "password_hash") with algo "PASSWORD_DEFAULT" (bcrypt) and option ['cost' => 12].
Any idea? What might be wrong?

**Comment by jakubmisek** [comment]
Yes, the function is not implemented. There are no sorted supported algorithms enabled.
