### ISSUE TITLE
imagefill is too slow

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#380]
Test case:
```php
$time_before = microtime(true);

$img = imagecreatetruecolor(1000, 1000);
$red = imagecolorallocate($img, 255, 0, 0);
imagefill($img, 0, 0, $red);

$time_after = microtime(true);
echo $time_after - $time_before;
```
Approximate results:
- PHP: ```0.013078927993774```
- Peachpie: ```41.0942230224609```

It seems that the main problem is with accessing the individual pixels by ```Image[x, y]```, because each of these calls is quite complex. It would be better to use a more low-level API for this task.

**Comment by jakubmisek** [comment]
we have to update to newest ImageSharp so we can make use of `AdvancedImageExtensions` (they've made few APIs public). Then we can access the raw picture memory buffer and implement own `IImageProcessor<TPixel>` with superfast flood fill :)

@roberthusak can you update to the latest `SixLabors.ImageSharp,1.0.0-beta6` please ? :)

**Comment by roberthusak** [comment]
@jakubmisek Updated in e23e25247ef0bded24da8eb939f1856c8a7925f6 and changed it to use ```Span<TPixel>``` in b430b3066162f85ea5e9fd32401f8615d427f881. It's now 25% faster (about 30s for the sample above), but that's still too slow. I'll try and revide the algorithm itself, maybe there's another inefficiency I haven't found yet.

**Comment by jakubmisek** [comment]
This is way to go! suggesting to fill rows by rows - find `fromX, toX` and then `Span<TPixel>.Fill( rowStart + fromX, toX - fromX, _fillColor)` :))

**Comment by roberthusak** [comment]
Each pixel used to added to the queue more that once (too many times), the latest commit resolves that. ```Span<TPixel>.Fill``` speeded that up as well, thanks 👍

**Comment by jakubmisek** [comment]
@roberthusak how is the speed in comparison to PHP ?

**Comment by roberthusak** [comment]
After the latest commit we are about 25% faster. At least if we measure just the duration of ```imagefill``` (i.e. not ```imagecreatetruecolor```) itself and use the simple fill of a monochromatic (black by default) image 1000x1000.
