### ISSUE TITLE
System.InvalidOperationException: Arg_InvalidOperationException

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#387]
PeachPie PHP Compiler version 1.0.0-appv2359+0847dc256a49b9dd69639e321e6a34907240acda

The below error is shown as return value of a method. 

The method should simply return (the values of) an array that has been set within a class. The debugger indicates that the array contains correct values within the called method. However, returning the array does not succeed.  

```
System.InvalidOperationException: Arg_InvalidOperationException
   at System.Runtime.CompilerServices.JitHelpers.GetRawSzArrayData(Array array)
   at System.Span`1[[System.Char, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Char[] array, Int32 start, Int32 length)
   at System.Text.StringBuilder.get_RemainingCurrentChunk()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at Pchp.Core.PhpValue.ArrayTable.DisplayString(PhpValue& me)
   at Pchp.Core.PhpValue.get_DisplayString()}	array
```
Error	Cannot evaluate expression because a thread is stopped at a point where garbage collection is impossible, possibly because the code is optimized.

**Comment by jakubmisek** [comment]
seems like some kind of CLR debugger issue, we'll fix it by not using `StringBuilder`

**Comment by menturion** [comment]
Thanks.
Tested it in appv2363.
Error "`Cannot evaluate expression because a thread is stopped at a point where garbage collection is impossible, possibly because the code is optimized.`" is still shown.

However, return value is now "`array(length = 10)	array`" witout any values.

**Comment by menturion** [comment]
Error still active in appv2364, pls find a screenshot attached.

![2019-03-21_185347](https://user-images.githubusercontent.com/41576848/54774128-4c4d5b00-4c0b-11e9-9854-9b28439b869e.jpg)

**Comment by jakubmisek** [comment]
Do you have the full call stack of the new `InvalidOperationException`? I'm not sure what causes this behavior (maybe we put sequence points in PDB in wrong locations ... ) Maybe we should not use `StringBuilder` for debug watches

**Comment by menturion** [comment]
Call stack:
```
testapp.dll!testapp_class.getArray() Line 449	Unknown
[External Code]	
testapp.dll!testapp_mod.cache() Line 1773	Unknown
testapp.dll!testapp_mod.load() Line 271	Unknown
[External Code]	
testapp.dll!testapp.start(Pchp.Core.Context <ctx>) Line 1481	Unknown
testapp.dll!<Root>.index_php.<Main>(Pchp.Core.Context <ctx>, Pchp.Core.PhpArray <locals>, object this, System.RuntimeTypeHandle <self>) Line 189	Unknown
[External Code]	

```
    
Class: 
```
class testapp_class
{    
    private $anArray = [];
    
    ...
    
    public function getArray()
    {
        return $this->anArray;
    }
    
    ...
}
```

**Comment by jakubmisek** [comment]
Do you have call stack of the exception?

I can't repro the issue with the sample, the code runs fine and I can watch values on every line of the code of every variable.

**Comment by menturion** [comment]
I noticed that after several further steps of debugging the error msg suddenly disappears and the correct array values are shown. The debugger seems to be extremely slow.

**Comment by jakubmisek** [comment]
You are right. I cannot see the error but I've noticed 'Cannot evaluate expression because a thread stopped ...`

The lag is caused by .NET debugger evaluating all the local variables when you have "Locals" pane opened. To improve the debugging speed (for now) I recommend to not have opened "Call Stack" and "Locals" panes. Switch for example to "Watch" and "Output".

**Comment by menturion** [comment]
Many thanks for the tip.
I adapted the debugger panes. Way faster now.
