### ISSUE TITLE
[Question] Exception User-Unhandled: Pchp.Core.ScriptDiedException

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#388]
Debugger throws the following exception `Exception User-Unhandled: Pchp.Core.ScriptDiedException` (s. screenshot below) when executing an "exit" statement (after sending to a new location):
```
header('Location: ' . $url);
exit;
```
![2019-03-22_175302](https://user-images.githubusercontent.com/41576848/54840203-bd087c00-4ccc-11e9-87b8-967748cc2445.jpg)

Is this the correct resp. intended behavior?

**Comment by liesauer** [comment]
use `\System\Environment::Exit($exit_code)` instead.

**Comment by jakubmisek** [comment]
Described on https://docs.peachpie.io/api/ref/scriptdiedexception/

Can be ignored. Currently it is the only way we can "exit" from the request.

**Comment by menturion** [comment]
Is there a way to check whether the code is currently executed as PHP or C#, e.g. by testing the existence of a certain class?

**Comment by liesauer** [comment]
> Is there a way to check whether the code is currently executed as PHP or C#, e.g. by testing the existence of a certain class?

check `PHP_VERSION` and `PHP_EXTRA_VERSION` constants if contains `peachpie`, but i don't know if this will be changed in the future.
```
array(1138) {
  ["PHP_VERSION"]=>
  string(14) "7.2.0-peachpie"
  ["PHP_EXTRA_VERSION"]=>
  string(9) "-peachpie"
}
```

@jakubmisek  btw, i think adding a `PEACHPIE_VERSION` constant is a nice idea. so we can do some compatibility works to let our application works on native php and peachpie.

**Comment by jakubmisek** [comment]
@menturion liersauer is right - you can check whether the code runs under PeachPie by checking `PEACHPIE` global constant:
```php
if (defined('PEACHPIE')) { /*..*/. }
```

**Comment by jakubmisek** [comment]
@liesauer `PEACHPIE_VERSION` is there since beginning.

**Comment by menturion** [comment]
Many thanks! This is very helpful.
