### ISSUE TITLE
implicit autoloading breaks class_exists

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#389]
This code is not working after [5fb15da1](https://github.com/peachpiecompiler/peachpie/commit/5fb15da1):
```php
<?php

// Foo is defined in another file in project
if(class_exists('Foo')) { // default value for autoload is true
	echo 'Foo exists';
} else {
	echo "Foo doesn't exist";
}
```
It should output `Foo doesn't exist` because the script where `Foo` is defined wasn't included and there is no autoloader registered for it.

In WordPress [wp-includes\class-http.php](https://github.com/WordPress/WordPress/blob/8ea4da0826124c9ce809929d4a6efa37cb89ea10/wp-includes/class-http.php#L10) it breaks loading dependencies for `Requests` class.

**Comment by jakubmisek** [comment]
you are right, this implicit autoloading expects that modern apps would use SPL autoload
