### ISSUE TITLE
Curl issue with wpdotnet

### ISSUE THREAD

**Issue by diddledan** [peachpiecompiler/peachpie#394]
The dashboard in a new wpdotnet installation has an error in the news feed section that reads:

```plain
RSS Error: A feed could not be found at
https://wordpress.org/news/feed/. A feed with an invalid mime type may
fall victim to this error, or SimplePie was unable to auto-discover it..
Use force_feed() if you are certain this URL is a real feed.

RSS Error: A feed could not be found at
https://planet.wordpress.org/feed/. A feed with an invalid mime type may
fall victim to this error, or SimplePie was unable to auto-discover it..
Use force_feed() if you are certain this URL is a real feed.
```

This appears to be a problem with Peachpie's CURL module.

**Comment by jakubmisek** [comment]
can you please post it on https://github.com/iolevel/wpdotnet-sdk/issues 
otherwise we would need a test case here :)) thanks!

**Comment by diddledan** [comment]
that'll teach me to second guess which repo it should be in :-p I was going to pop it over there but then considered it is a bug in peachpie itself so changed my mind and put it here. Sorry about the mixup :-)
