### ISSUE TITLE
TypeLoadException: Method 'get_IsClientConnected' in type 'Peachpie.AspNetCore.Web.RequestContextCore' from assembly 'Peachpie.AspNetCore.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5b4bee2bf1f98593' does not have an implementation.

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#397]
PeachPie PHP Compiler version 1.0.0-appv2391+4cbd4275fe41a086122569210e6bf7922afcf944

Got this exception:

```
TypeLoadException: Method 'get_IsClientConnected' in type 'Peachpie.AspNetCore.Web.RequestContextCore' from assembly 'Peachpie.AspNetCore.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5b4bee2bf1f98593' does not have an implementation.

Peachpie.AspNetCore.Web.PhpHandlerMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jakubmisek** [comment]
Seems like your references are not consolidated. Ensure you reference the same versions for all `Peachpie.*` packages.

**Comment by menturion** [comment]
As every time, I simply reference the PeachPie SDK within the .msbuildproj file like this ...

```
<Project Sdk="Peachpie.NET.Sdk/1.0.0-appv2392">
...
</Project>
```

The rest is done by VS2017 resp. provided by PeachPie. If this approach is wrong, pls let me know how to overcome this issue, which also occurs in "appv2392".

**Comment by jakubmisek** [comment]
In your C# app, there is usually a reference to `Peachpie.AspNetCore.Web`. This version has to match as well.

**Comment by menturion** [comment]
Now I directly reference Peachpie.AspNetCore.Web the latest version the NuGet package manager is offering:

```
<Project Sdk="Peachpie.NET.Sdk/1.0.0-appv2393">
  <ItemGroup>
    <PackageReference Include="Peachpie.AspNetCore.Web" Version="1.0.0-appv2393" />
  </ItemGroup>
</Project>
```

Compiling works fine. However, debugging fails with the following error msg:

```
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Build started: Project: Server, Configuration: Debug Any CPU ------
1>C:\dotnet\test\test\Server\Server.csproj : error NU1605: Detected package downgrade: Peachpie.AspNetCore.Web from 1.0.0-appv2393 to 1.0.0-appv2300. Reference the package directly from the project to select a different version. 
1>C:\dotnet\test\test\Server\Server.csproj : error NU1605:  Server -> test -> Peachpie.AspNetCore.Web (>= 1.0.0-appv2393) 
1>C:\dotnet\test\test\Server\Server.csproj : error NU1605:  Server -> Peachpie.AspNetCore.Web (>= 1.0.0-appv2300)
1>Done building project "Server.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by jakubmisek** [comment]
that's compilation error

**Comment by menturion** [comment]
Yes, that's right. What I was trying to say is that the rebuild finished successfully, starting IIS failed.

My underlying question is: Why do I have to set these references (Peachpie.AspNetCore.Web) by hand now which wasn't required before?

**Comment by jakubmisek** [comment]
It hasn't changed. Also it is not related to PeachPie itself but NuGets (and dotnet package resolution). Maybe the project `Server` changed?

Note, the rebuild couldn't finish successfuly, because
> Build: 0 succeeded, 1 failed
