### ISSUE TITLE
Laravel config and RecursiveDirectoryIterator

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#399]
Hi there,

I'm trying to run Laravel using PeachPie and while trying that I needed to work around a few issues. I'll try to make a ticket for each of them so they can be tracked.

Suppose we have a directory structure like this:
- config
  - a.php
  - b.php
- public
  - index.php

and index.php has this code:

```php
$directory = new \RecursiveDirectoryIterator(__DIR__ . "/../config");
$iterator = new \RecursiveIteratorIterator($directory);
$regex = new \RegexIterator($iterator, "/^.+\.php$/i", \RecursiveRegexIterator::GET_MATCH);

foreach ( $regex as $entry) {
    echo $entry[0] . "\r\n";
}
```

Using php7 the output of public.php will be:

```
/Users/calvinbaart/dev/laravel_peachpie/website/public/../config/a.php
/Users/calvinbaart/dev/laravel_peachpie/website/public/../config/b.php
```

on PeachPie this script errors out because the ../config directory doesn't exist relative to the output directory. Laravel does alot of dynamic loading like this and needs to be able to require the config files even when they are compiled.

The php files in the config folder are included in the Compiled files.

Shouldn't the (Recursive)DirectoryIterator also traverse the compiled files tree to allow these situations?

**Comment by menturion** [comment]
I have no particular experience with Laravel and @jakubmisek will correct me if I'm wrong.
 
In general, all PHP files must be present at compile time. This applies to both configuration files and template files (see https://github.com/peachpiecompiler/peachpie/issues/374). So you need to generate them before compiling your project. 

Regarding the dynamic config you mentioned, it might be a valid idea to generate all PHP config files of a default configuration in advance and dump all these settings into a Json file at runtime. Once this Json file exists load these settings instead of the (PHP) config files. This way you still have the ability to configure your app without recompiling it.

**Comment by calvinbaart** [comment]
Well in this example the configuration files are present at compile time (and even compiled in). (Will be fun with Blade Templating though, that needs to be pre-generated indeed).

What laravel does is it uses the filesystem to determine which config files are available, for now I have hardcoded this list in so that it does actually load the files but it would be ideal if the code could detect which config files are compiled in.

I'll look into switching the configuration loader to use json files instead of php files to bypass this. Its pretty core though so that will mean that regular Laravel won't be able to run correctly without modifications.

**Comment by jakubmisek** [comment]
The configuration files (as any other .php files) are compiled and their compiled version is present in compiled `.dll` file.

However; `RecursiveDirectoryIterator` works with file system. We could either "trick" `RecursiveDirectoryIterator` to list compiled scripts as well (but it may have weird side effects) or you can include the config files into your project `Content` in your project file:

```xml
<ItemGroup>
  <Content Include="config/**.php" />
</ItemGroup>
```

If you'd like to "anonymize" your configuration, you can create empty dummy config files and include them as the `Content`.

**Comment by calvinbaart** [comment]
That seems to work. It seems that a few more changes were needed to the LoadConfiguration provider of Laravel. It seems that the default version of the load function:
`
        $files = [];
        $configPath = realpath($app->configPath());
        foreach (Finder::create()->files()->name('*.php')->in($configPath) as $file) {
            $directory = $this->getNestedDirectory($file, $configPath);
            $files[$directory.basename($file->getRealPath(), '.php')] = $file->getRealPath();
        }
        ksort($files, SORT_NATURAL);
        return $files;
`

I needed to change it to:
`
        $files = [];

        $configPath = realpath($app->configPath());

        $directory = new \RecursiveDirectoryIterator($configPath);
        $iterator = new \RecursiveIteratorIterator($directory);
        $iterator = new \RegexIterator($iterator, "/^.+\.php$/i", \RecursiveRegexIterator::GET_MATCH);

        foreach ($iterator as $file) {
            $files[basename($file[0], '.php')] = "../config/" . basename($file[0]);
        }

        ksort($files, SORT_NATURAL);

        return $files;
`

to get it to work. I'll try to figure out which part of the default code doesn't work. After a few more stubs and unimplemented extensions (openssl for example) I'm able to get to the laravel homescreen!

I'll make some tickets for the other issues I faced. Thanks for the help!

**Comment by calvinbaart** [comment]
Turns out that the last issue with the original LoadConfiguration code was caused by myself. During compilation I needed to fix a few errors due to:

`Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie`

and the changes I made caused the code to stop working.

**Comment by jakubmisek** [comment]
Closing for now, it seams to be related to other issues.
