### ISSUE TITLE
Carbon fails with missing abstract method

### ISSUE THREAD

**Issue by Remo** [peachpiecompiler/peachpie#401]
I've got a project failing with this error:

```
Website\vendor\nesbot\carbon\src\Carbon\Carbon.php(491,1): error PHP1018: Class 'Carbon\Carbon' doesn't implement abstract method Carbon\CarbonInterface::setISODate()
```

From what I understand, the problem is caused by https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/CarbonInterface.php#L3111

The actual class doesn't implement the method, but I'm not sure it has to because `Carbon\Carbon` is derived from `DateTime`: https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php

**Comment by jakubmisek** [comment]
PeachPie does not implement `DateTime::setISODate`, will be added
