### ISSUE TITLE
Laravel: Missing DateTime methods

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#404]
Hi,

It seems that the following methods are missing:

- [x] `DateTime::getLastErrors`
- [x] `DateTime::setTimestamp`

These are used by Carbon during initialization of Laravel

Off-topic for a bit: Is there a development guide or something somewhere? I can't seem to get PeachPie to build otherwise I would attempt to implement this myself.

**Comment by jakubmisek** [comment]
both declarations have been added, thanks!

We'll prepare a proper development guide, possibly improve the developer experience as possible in future!
