### ISSUE TITLE
The "BuildTask" task failed unexpectedly (NullReferenceException)

### ISSUE THREAD

**Issue by DaveMagrathSmith** [peachpiecompiler/peachpie#405]
When building a PHP class library in Release mode, either from the command line (dotnet build --configuration Release), or within Visual Studio 2017, I get the following error:

![image](https://user-images.githubusercontent.com/42848571/55581954-3b611700-56ec-11e9-8944-7995834386db.png)

This happens even in a newly created, otherwise empty, "Hello World" project.

The build works fine in Debug mode.

**Comment by jakubmisek** [comment]
fixed with https://github.com/peachpiecompiler/peachpie/pull/407
thanks @DaveMagrathSmith and @crbrz

**Comment by DaveMagrathSmith** [comment]
Thanks! :)
