### ISSUE TITLE
Array default value is lost when function is called implicitly

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#409]
Hi,

I'm having some issues with the Eloquent ORM in Laravel. It mostly seems to work now but a few
parts of the code use a construction similar to this:
```php
function test(int $a, $b = ['*'])
{
    echo $a . ", " . count($b) . "\r\n";
}

$func = "test";
$args = [10];

$func(...$args);
```

In PHP this outputs `10,1`. In PeachPie this outputs `10,0`. 
The debugger shows that $b is a Void type when inside the test function

**Comment by jakubmisek** [comment]
thanks! fixed and your test case added to repo
