### ISSUE TITLE
Multiple set-cookie headers overwrite each other

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#413]
Hi,

Laravel calls the header function with set-cookie for each cookie. The way PeachPie handles this causes it to only pick-up the latest set-cookie.

```php
header("set-cookie: test1=a;");
header("set-cookie: test2=b;");
header("set-cookie: test3=c;");
```

In the above code only the test3 cookie is send back. PHP sends them all back.

**Comment by jakubmisek** [comment]
fixed with https://github.com/peachpiecompiler/peachpie/pull/414

thanks!
