### ISSUE TITLE
[laravel/framework] - "Process is terminating due to StackOverflowException."

### ISSUE THREAD

**Issue by atrauzzi** [peachpiecompiler/peachpie#418]
I'm tinkering with the idea of building [laravel/framework](https://github.com/laravel/framework) as a library which I can then integrate more tightly with a base ASP.net project (rather than relying on the more verbose laravel project skeleton).

My setup is quite simple.  I have a Peachpie project folder with `laravel/framework` extracted into the root directory.  I've done a `composer install` on the side to get all the dependencies.  My `msbuildproj` is as follows:

```xml
<Project Sdk="Peachpie.NET.Sdk/0.9.38">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.php" />
    <Compile Remove="vendor/mockery/mockery/library/Mockery/Mock.php" />
    <Compile Remove="vendor/phpunit/php-code-coverage/tests/_files/Crash.php" />
  </ItemGroup>
</Project>
```

Builds fails with the message _"Process is terminating due to StackOverflowException."_

**Comment by calvinbaart** [comment]
Can you get a more complete stacktrace? I have done exactly that and haven't encountered the issues you are facing: https://github.com/calvinbaart/laravel-peachpie-sample/tree/feature/laravel-sdk/Laravel

**Comment by jakubmisek** [comment]
The `msbuildproj` is ok (just suggestion to remove all tests from the compilation `<Compile Remove='**/tests/**' />`)

As @calvinbaart said, the stack trace or link to a sample project would be great :)

**Comment by jakubmisek** [comment]
we're able to repro the issue

**Comment by jakubmisek** [comment]
caused by following code in `vendor\symfony\var-dumper\Tests\Fixtures\NotLoadableClass.php`
```php
namespace Symfony\Component\VarDumper\Tests\Fixtures;

class NotLoadableClass extends NotLoadableClass
{
}
```

**Comment by atrauzzi** [comment]
That's great!  Apologies, I have been a bit busy, I'm hoping to come back to trying some Laravel projects with peachpie in a couple of months.  Rest assured, I'm watching closely.  😉
