### ISSUE TITLE
using a .net lib

### ISSUE THREAD

**Issue by huanent** [peachpiecompiler/peachpie#430]
Hi 
can I use a .net nuget package in peachpie , like Newtonsoft.Json ?

for example

<？php
require('Newtonsoft.Json');
$json= JsonConvert->SerializeObject("{}");

**Comment by huanent** [comment]
I saw https://www.peachpie.io/2019/02/using-c-in-php-and-vice-versa.html

**Comment by jakubmisek** [comment]
thank you for the question and for the answer :)

In short you can add references to other .NET projects, packages and DLL files in the same format as in C# project, either using Visual Studio (the link above) or by editing the project file:
```xml
<PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
```
