### ISSUE TITLE
Function call ignored in return statement if the function doesn't return a value

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#434]
```php
function test1() {
	echo 'test1';
}

function test2() {
	return test1();
}

test2();
```

With `Peachpie 0.9.41` (same result with `1.0.0-appv2481`) the code above doesn't output anything, with `PHP 7.3.3` it outputs `test1`.

**Comment by jakubmisek** [comment]
thank you @crbrz . Compiler incorrectly ignored expressions which value was not read, and it only did it in release mode.
