### ISSUE TITLE
type convert error

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#438]
recently i want to build my own peachpie for my special project, and i did compile successfully without any errors. but when i tried to compile my project, it failed.

```text
C:\Users\LiesAuer\.nuget\packages\peachpie.net.sdk\0.9.25-devv\build\Peachpie.NET.Core.Sdk.targets(190,5): error : Cannot implicitly convert 'PhpValue' to 'IntStringKey'. not implemented at O:\Projects\x\src\Util\Functions.php(66, 13) [O:\Projects\x\x.msbuildproj]
C:\Users\LiesAuer\.nuget\packages\peachpie.net.sdk\0.9.25-devv\build\Peachpie.NET.Core.Sdk.targets(190,5): error : PhpNumber -> PhpValue not implemented at O:\Projects\x\src\Util\Functions.php(163, 4) [O:\Projects\x\x.msbuildproj]
C:\Users\LiesAuer\.nuget\packages\peachpie.net.sdk\0.9.25-devv\build\Peachpie.NET.Core.Sdk.targets(190,5): error : PhpString -> PhpValue not implemented at O:\Projects\x\vendor\ezsql\ezsql\ez_sql_loader.php(4, 4) [O:\Projects\x\x.msbuildproj]
```

i tried to switch back the original peachpie compiler and it compiled successfully. i can not figure out why.

**Comment by jakubmisek** [comment]
Compiler lookups for implicit/explicit conversion operators and it seams it did not find them in your build of PeachPie.

In your case, it lookups `implicit operator` method in `PhpValue`, `IntStringKey`, `PhpNumber` and static operators in the special `Operators.cs`  file.

- https://github.com/peachpiecompiler/peachpie/blob/4b53bbbe7811a2f60be049fed2f3a3d94f0ab70f/src/Peachpie.Runtime/OrderedDictionary.cs#L97
- https://github.com/peachpiecompiler/peachpie/blob/4b53bbbe7811a2f60be049fed2f3a3d94f0ab70f/src/Peachpie.Runtime/PhpValue.cs#L247
- https://github.com/peachpiecompiler/peachpie/blob/4b53bbbe7811a2f60be049fed2f3a3d94f0ab70f/src/Peachpie.Runtime/PhpString.cs#L1596

**Comment by liesauer** [comment]
i found the problem, one of my dependencies project was compiled by the very old peachpie, and i update to the lastest version, and now every thing works fine!
