### ISSUE TITLE
PHP function 'libxml_disable_entity_loader' is not supported

### ISSUE THREAD

**Issue by tmewes** [peachpiecompiler/peachpie#440]
Currently it looks like the PHP function `libxml_disable_entity_loader` is not supported.
As Magento 1 uses this function, it would be great if PeachPie would support it too. :)

**Comment by jakubmisek** [comment]
added in https://github.com/peachpiecompiler/peachpie/commit/2272f1d262bf71a341729ba73d47ebb3a7b21ee8
