### ISSUE TITLE
Magento: Error when running 2 commands on PDO-Statement: "Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first."

### ISSUE THREAD

**Issue by tobihille** [peachpiecompiler/peachpie#441]
Hi,

the above mentioned error occured again. I managed to create a minimal sample to reproduce this issue. It happens on 0.9.42 as well as the current master.

```php
<?php
$dsn = 'mysql:host=localhost;dbname=magento_peachpie';
$username = 'root';
$password = 'password';

$dbh = new PDO($dsn, $username, $password, $options);
/** @link http://bugs.mysql.com/bug.php?id=18551 */
$dbh->query("SET SQL_MODE=''"); //sadly magento uses this hacky workaround. I don't know if it's needed anymore
$result = $dbh->exec("set names UTF-8");
```
The above queries are exactly the ones that are executed at first in magento.

**Comment by Sdfendor** [comment]
@tobihille changed calls from query to exec to fix his problem as a workaround. 
Even with the workaround I still encountered this problem though, when building against target framework 'netcoreapp2.0' but didn't anymore when changing/updating to 'netcoreapp2.2'. 
Maybe this info can help the investigation of this error.

**Comment by tobihille** [comment]
I tried to delete my workaround (use query instead of exec in the first call) but this still does not work on 2.2

**Comment by jakubmisek** [comment]
thank you @tobihille and @Sdfendor 

issues has been fixed.

BTW `$dbh->exec("set names UTF-8");` should result in error "Unknown character set: 'UTF'"
