### ISSUE TITLE
Package name conflict with composer.json

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#446]
when i am trying to make a composer package with a different package name for some reasons(shorter name, more meaningful name or something), the compiler takes the package name from `composer.json` and generates a wrong dependencies manifest `deps.json`.
```
Error:
  An assembly specified in the application dependencies manifest (packageNameConflict.deps.json) was not found:
    package: 'my.package', version: '1.0.0'
    path: 'my.package.dll'
```

i think it is pretty nice to add a `<PackageNameOverride>Company.Vendor.Package</PackageNameOverride>` or something like that to control what package nam i need exactly.

now i am using this `fixEPS.php` post build script to fix this problem temporarily.
```php
<?php

$searchPath = __DIR__ . '/bin';
$projects   = [
    'Vendor.CorrectPackageName' => 'Vendor.WrongPackageName',
];

foreach (getDEPSFiles($searchPath) as $deps) {
    foreach ($projects as $project => $fix) {
        if (strpos($deps, "{$project}.deps.json")) {
            fixDEPS($deps, $fix, $project);
            echo "{$deps} fixed." . PHP_EOL;
        }
    }
}

function getDEPSFiles($basePath)
{
    $deps = [];
    foreach (glob("{$basePath}/*") as $config) {
        foreach (glob("{$config}/*") as $framework) {
            foreach (glob("{$framework}/*.deps.json") as $file) {
                if (strpos($file, '.deps.json')) {
                    $deps[] = $file;
                }
            }
        }
    }
    return $deps;
}

function fixDEPS($depsFile, $search, $replace)
{
    $content = file_get_contents($depsFile);
    $content = str_replace($search, $replace, $content);
    file_put_contents($depsFile, $content);
}

```

add the following code to `csproj` or `*proj`
```
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="php $(ProjectDir)fixDEPS.php" />
  </Target>
```

testcase
[packageNameConflict.zip](https://github.com/peachpiecompiler/peachpie/files/3279929/packageNameConflict.zip)

**Comment by jakubmisek** [comment]
the compiler gets all the properties from `composer.json` and sets Version, AssemblyName, PackageId, Description, Author etc. .. you can disable this behavior by setting property
```xml
<PropertyGroup>
  <ComposerJsonPath>false</ComposerJsonPath>
</PropertyGroup>
```

**Comment by liesauer** [comment]
got it

**Comment by jakubmisek** [comment]
will be documented :)
