### ISSUE TITLE
PHP exec function not implemented

### ISSUE THREAD

**Issue by tazishere** [peachpiecompiler/peachpie#448]
Hello, I'm trying to build a web app which will be working on local server. In my code, I have some command-lines that I start with "exec" function:  https://www.php.net/manual/en/function.exec.php

It works normal when the code is served with Apache webserver. But when I compile it with PeachPie, the command lines doesn't run. I couldn't figure out why it's happening. I wonder if the reason might be the code runs on the another webserver included in your example codes? (http://localhost:5004/)

I don't know if the problem is because of peachpie or webserver configurations which doesn't let exec function. It also can be I'm doing something wrong when I'm compiling the code. (I'm new to C#)

The code:
```
<?php
exec('magick picture.png -crop 100x100+50+50 picture2.png 2>&1', $a, $b);
?>
```

Thanks for your help.

**Comment by bfistein** [comment]
Hey @tazishere, fantastic that you're trying our little project and welcome to the world of .NET. Thanks for your question!

**Comment by bfistein** [comment]
Scheduling this for 0.9.44, but it will be available on our AppVeyor immediately after we close this.

FYI this function is a bit of a security issue potentially, so we will add a warning diagnostic. This is why we haven't implemented it yet.

**Comment by tazishere** [comment]
Thanks very much for your fast action. Appreciate your passion.

When are you planning to release version 0.9.44? Can I use AppVeyor and download the code right now? Is there any tutorial how we can use AppVeyor? Or should I wait for 0.9.44 to be released?

**Comment by jakubmisek** [comment]
@tazishere you can use AppVeyor where you always have the latest build available.

NuGet source feed is `https://ci.appveyor.com/nuget/peachpie`
Then just update Peachpie.*** packages version to the latest available.

**Comment by tazishere** [comment]
Sorry but I couldn't download the latest build. I installed Visual Studio and it finds the default nuget packages. When I set the package source as "https://ci.appveyor.com/nuget/peachpie", it doesn't find any packages.

What could be the reason I cannot reach your AppVeyor releases? It looked like an authorization issue to me. Is it something like I need to join your AppVeyor page?

**Comment by jakubmisek** [comment]
@tazishere most probably you have to look for `PreRelease` packages. They are hidden by default. Or just take a look on the versions on https://ci.appveyor.com/project/dotnetfoundation/peachpie/build/artifacts and replace the version in your project file.
