### ISSUE TITLE
PHP Session State in an ASP.NET Core app

### ISSUE THREAD

**Issue by DaveMagrathSmith** [peachpiecompiler/peachpie#451]
I'm executing PHP in a .NET Core web app via the Html.Php() helper method, as such:

Pchp.Core.Context c = Context.GetOrCreateContext();
Microsoft.AspNetCore.Html.IHtmlContent content = Html.Php("Filename.php");

The PHP code sets session variables, which I want to be available on subsequent page requests.  But a new PHP Context seems to be created for each request, so the session is lost.  Should I manually copy variables from Pchp.Core.Context to HttpContext, and back again on the next request?  Or is there a simpler way to maintain session state?

**Comment by jakubmisek** [comment]
`Pchp.Core.Context` represents a single request - so it is expected to be destroyed when request ends.

In PHP there is global variable `$_SESSION` (you can get it in `Pchp.Core.Context.Session`) which is filled with session variables upon call to `session_start()` and which content is stored into ASP.NET `ISession` (`HttpContext.Session`) upon `session_commit()`.

So PHP session variables are stored in your `HttpContext.Session`, but for compatibility reasons they are serialized using PHP serializer.

`filename.php`:
```php
<?php
session_start();
echo $_SESSION['a'];
$_SESSION['a'] ++;
session_commit();
```

`page.cshtml`:
```html
@Html.Php("filename.php");

Option1 from ISession: @( Context.Session.TryGetValue("a", out byte[] bytes) ? PhpSerialization.PhpSerializer.Instance.Deserialize(c, bytes, default) : null )

Option2 from Pchp.Core.Context: @( c.Session["a"] )
```

If you'd like to pass your C# session data into PHP `$_SESSION`, you have to copy them by yourself into `Pchp.Core.Context.Session` or save them into `ISession` using PHP serializer.

**Comment by jakubmisek** [comment]
closing as answered, if you;d have any other questions or suggestions, please continue in this thread :) thanks

**Comment by jackflyer** [comment]
Should I expect this script to produce incremental result in next request? If so, Is there something that we need to configure?
```
<?php
session_start();
if(!isset($_SESSION['a']) $_SESSION['a'] = 0;
$_SESSION['a'] ++;
session_commit();
```

**Comment by jakubmisek** [comment]
@jackflyer the result as in PHP should be expected. Sessions have to be enabled in the app (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-5.0#configure-session-state). Check Debug's Output pane for eventual warnings.
