### ISSUE TITLE
Strict comparison handles nullable strings wrongly

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#459]
Test case:
```php
function test(string $s = null) {
  echo (int)($s === null);
  echo (int)($s !== null);
}

test(null);
```
Expected output:
```
10
```
Actual output:
```
01
```
It's probably caused by the optimization in cae3e3f1.

**Comment by jakubmisek** [comment]
thanks! can you please add the test to the repo :)

**Comment by roberthusak** [comment]
Sure, added in 06e6f03aeaecdc601a3706f306ce0ad62ceb299d. Thanks for the quick fix!
