### ISSUE TITLE
mb_convert_variables() undefined

### ISSUE THREAD

**Issue by feamsr00** [peachpiecompiler/peachpie#461]
Hi There!

Seems like [`mb_convert_variables()`](https://www.php.net/manual/en/function.mb-convert-variables.php) Is missing. Is this on the roadmap or an oversight?

Using `Peachpie.Library/0.9.45`

**Comment by jakubmisek** [comment]
will be added, thank you!

Do you have a sample code how you use it?

**Comment by feamsr00** [comment]
Hi @jakubmisek thanks for the fix! It was code used inside of Symfony\Console:
https://github.com/symfony/console/blob/v4.3.3/Application.php#L1154

Considering the fix, was this just code that was overlooked?

**Comment by jakubmisek** [comment]
There is a few other missing functions for sure. We or the community implement them subsequently based on what is needed.

Compiler will report you the full list of diagnostics what other called functions are not implemented yet.

**Comment by feamsr00** [comment]
While its nice that missing functions are emitted, have you considered running and keeping the output of the php-src test suite? That way there would be an auto updated (perhaps on every build) list of missing functions or other incompatibilities.

**Comment by jakubmisek** [comment]
It's a good suggestion, and it was considered. We are defnitely open to PR that runs php-src tests on .NET. Currently our main goal was to run few specific frameworks which are tested continuously already)

**Comment by feamsr00** [comment]
I'm glad you considered it. That tells me i'm not crazy for suggesting it! I am vaguely curious however. How far did you get down that thought process? Did you consider using functional test suit from php-src[1] or something else? What was the biggest reason why you "punted"; was it simply time, or some apparent complexity?

[1] http://www.phpinternalsbook.com/tests/overview.html

**Comment by jakubmisek** [comment]
haha we actually implemented it few years ago at https://github.com/DEVSENSE/Phalanger/tree/master/Testing/Tests

PeachPie, however, is more strict than PHP, so most of the tests will fail by purpose. Also faulty tests won't even get compiled. We might probably run the tests once a day to monitor if we don't break something that worked a day before? :)) and make a nice table with green checks and red crosses ..

**Comment by feamsr00** [comment]
Neat!

That would totally make sense and was exactly what I had in mind. Embarking on the endeavor that PP is, it's important to have regression testing and clear language parity reports. Perhaps **more** important is that needs to be painless for you guys to update, so if you already have even *part* of an automated test suite, that's fantastic. Now, I'm not saying a sea of green isn't a goal, but even if you pull that out now, and a lot of it is red (on purpose like you said), its still great to have a list that anyone can check in two seconds to see whats up, even before waiting for a compile.

Sometimes the documentation is just a important as the code :)

**Comment by jakubmisek** [comment]
You are right, currently we're still "forming" the compiler - for example it's still not clear how we treat PHP errors, should we always throw a CLR exception instead? Also type strictness is not specified yet..

Running PHP test suite would definitely give us better overview of the compatibility status.
