### ISSUE TITLE
DOMDocument node issues

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#462]
Hi There,

I was working on PHPUnit when I noticed it wouldn't load any testsuites. After some investigation I discovered that there is a difference between the number of nodes in the same xml between PHP and PeachPie. I created the following test case:

```php
$document = new DOMDocument();
$document->load("test.xml");

echo $document->childNodes->length . ", " . $document->firstChild->nodeName . "\r\n";
```

where test.xml is this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<RootNode />
```

PHP output:
```
➜  Laravel.Tests git:(feature/laravel-sdk) ✗ php main.php
1, RootNode
```

PeachPie output:
```
➜  Laravel.Tests git:(feature/laravel-sdk) ✗ dotnet run
2,
```

It seems that PeachPie includes the <?xml meta info as a tag, while PHP doesn't.

I tested this with the released version of PeachPie 0.9.45.

**Comment by jakubmisek** [comment]
behaves completely differently for me, but incorrectly as well. I have following output:

```
2, and NullReferenceException
```

**Comment by jakubmisek** [comment]
PeachPie (.NET) includes `#text` element (which is a whitespace between xml declaration and root node)
