### ISSUE TITLE
class_alias doesn't seem to work for Traits

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#465]
Hi There,

Finally figured out why Mockery fails to compile. It seems that the following sample:

```php
trait Foo
{
    function testFunc()
    {
        echo "Foo";
    }
}

class_alias(Foo::class, Bar::class);

class Test
{
    use Bar;
}

$obj = new Test();
$obj->testFunc();
```

fails on PeachPie with the following error:
```
➜  laravel-peachpie-sample git:(feature/laravel-sdk) ✗ dotnet run --project Laravel.Tests
/Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php(40,9): error PHP4044: Type name 'Bar' could not be resolved. [/Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/Laravel.Tests.msbuildproj]
```

In PHP it correctly prints "Foo"

**Comment by jakubmisek** [comment]
That's because `Bar` cannot be resolved in compile-time. We have to dynamically compile the class `Test` in run time. This feature is not planned for `1.0` release yet. The quick workaround is to add `use` statement in the file `use Foo as Bar;`

**Comment by calvinbaart** [comment]
Thanks, I have worked around it for now:
https://github.com/calvinbaart/laravel-peachpie-sample/blob/feature/laravel-sdk/Laravel.Tests/patches/mockery_peachpie_issue_465_001.patch
and
https://github.com/calvinbaart/laravel-peachpie-sample/blob/feature/laravel-sdk/Laravel.Tests/patches/mockery_peachpie_issue_465_002.patch

Hopefully in the future these patches aren't necessary anymore :)

**Comment by jakubmisek** [comment]
good, closing for now because the real issue is class_alias() and dynamic code in general - currently we're not going to fix it
