### ISSUE TITLE
Variadic parameters have the wrong class in Reflection

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#480]
After #472 hasType and getType have been fixed, but it seems the same error occurs with getClass.

See the following sample:
```php
function testFunction(...$parameters)
{
}

$func = new ReflectionFunction("testFunction");
$parameter = $func->getParameters()[0];

if ($parameter->allowsNull()) {
    echo "?";
}

if ($parameter->getClass()) {
    echo (string) $parameter->getClass()->getName();
}

if ($parameter->isVariadic()) {
    echo "...";
}

echo "$" . $parameter->getName();
```

PeachPie output:
```
?Pchp\Core\PhpValue[]...$parameters
```

PHP output:
```
?...$parameters
```

**Comment by jakubmisek** [comment]
right, PeachPie weirdly mixes CLR and PHP ... although `Pchp\Core\PhpValue[]` is absolutely correct, it is not expected to see it in PHP and causes incompatibilities. Will be fixed.
