### ISSUE TITLE
How does PeachPie approach exceptions?

### ISSUE THREAD

**Issue by aschwin** [peachpiecompiler/peachpie#488]
*Edited for brevity*

Does PeachPie adhere to strict PHP exceptions or has the PHP exception family been derived from the .NET exception family? In other words, if I want to make use of the deeper levels of the framework, do I need to extend PHP exceptions from .NET exceptions or has that already been done under the hood?

I can imagine (haven’t looked into this) that .NET makes use of checked vs. unchecked exceptions like Java does. In my opinion (which should be regarded as humble), using PeachPie should follow the .NET approach of using exceptions instead of mere PHP approach. Here, the distinction between checked vs. unchecked  exceptions should weigh more. Following two different approaches to handling exceptions would cause a lot of confusion and thus bugs.

Thank you so much for the answers!

**Comment by jakubmisek** [comment]
All the exceptions in .NET have to be derived from the `System.Exception` class, so PHP `Exception` class is no difference. Additionally, PHP `Exception` implements interface `Throwable`.

In short PHP exception looks like:
```C#
public class Exception : System.Exception, Throwable { ... }
```
(Note all PHP exception classes are all implemented in regular C# - e.g. https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library/Exceptions/Exception.cs#L11)

Then everything works out of the box:
- custom PHP exceptions (always derived from `Exception` class) are .NET `System.Exception` as well
- PHP exceptions can be caught in C#
- C# exceptions can be also caught in PHP

There is one remark - PHP developers in PHP code like to catch exceptions by the type `Throwable` (which is not implemented by regular C# exceptions). Also the PHP code might expect that exception is of type PHP `Exception` which does not have to be true.
```php
try { ... } // do some call to .NET
catch (Throwable $t) { ... } // this might not be caught, C# exceptions don't impl Throwable
```

To achieve full interoperability and to avoid unexpected behavior of the PHP code, exception thrown from C# and catch by PHP code should inherit PHP `Exception` (`Pchp.Library.Spl.Exception` class).

**Comment by aschwin** [comment]
Awesome! Thanks, Jakub. That is EXACTLY (as in exactly) what I was looking for. This is very important to know and you helped be a lot not having to go to the deep code of PeachPie myself.

Great stuff!

I actually expected just what you described to be true, since it makes so much sense. And no, checking for Throwable is awful. But I understand you warn for this.

**Comment by jakubmisek** [comment]
Good, please if there would be anything else, please ask. We'll extend the documentation continuously.

**Comment by bfistein** [comment]
@aschwin just added this to our [docs](https://docs.peachpie.io/net/exceptions/), we'll eventually expand on this. Thanks for the question!

**Comment by bfistein** [comment]
Hi again @aschwin - actually updated the [docs](https://docs.peachpie.io/net/exceptions/) on exception handling with some more detailed instructions, feel free to take a look :)

**Comment by aschwin** [comment]
Hi Benjamin,

Thank you so much for reaching out to me about this topic once again!

Yes, I've reviewed the documentation and it looks very straightforward.
Exactly the points that are important to a developer looking into this is
mentioned and clear and concise.

Keep up the good work!

Kind regards,

Aschwin Wesselius
