### ISSUE TITLE
[Feature] IsScriptDeclared method in Pchp.Core.Context

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#496]
Hi There,

I would like to be able to do something like this from PHP:
```php
function requireOrEval(string $path) {
    if (!class_exists("\Pchp\Core\Context") || \Pchp\Core\Context::IsScriptDeclared($path)) {
        return require $path;
    }

    return eval("?>" . file_get_contents($path));
}
```

That way I can compile all the generated blade files using eval unless they are declared in (which is better, but not always available in Laravel)

**Comment by jakubmisek** [comment]
There already is `Context::TryResolveScript( root, path )` which returns `ScriptInfo` that has property `IsValid`.
Usage (C#):
```C#
Pchp.Core.Context.TryResolveScript(Root, FullPath).IsValid 
```
Usage (PHP):
```php
if (\Pchp\Core\Context::TryResolveScript(APP_ROOT, $absolute_path)->IsValid) {
}
```

**Comment by jakubmisek** [comment]
If you have the script path relative to the app root, use `Context::TryGetDeclaredScript( $relpath )`

**Comment by jakubmisek** [comment]
Note: lazy eval of non-compiled scripts is going to be implemented in https://github.com/peachpiecompiler/peachpie/blob/47f765b5717e84262f410525bcfafa178a0eeeb0/src/Peachpie.Runtime/Context.cs#L524

**Comment by calvinbaart** [comment]
APP_ROOT define was empty here so I changed it to this:
```php
    public static function isScriptCompiled(string $script): bool
    {
        // Retrieve root path
        $root = realpath(__DIR__ . "/../");

        // Check if path is relative or absolute
        if (stripos($script, $root) === 0) {
            // Strip root path if absolute
            $script = substr($script, strlen($root) + 1);
        }

        // Check if relative path is declared as script
        return \Pchp\Core\Context::TryGetDeclaredScript($script)->IsValid;
    }
```

(This file is in a sub-directory relative to root)

This seems to work correctly for now, thanks!

**Comment by jakubmisek** [comment]
@calvinbaart yes, `APP_ROOT` was just a dummy constant that should refer to your application root directory.

**Comment by jakubmisek** [comment]
@calvinbaart  `TryResolveScript` does the dirty work with absolute paths for you.
```php
\Pchp\Core\Context::TryResolveScript( realpath(__DIR__ . "/../"), $script )
```
