### ISSUE TITLE
ReflectionMethod::setAccessible is not implemented

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#514]
Sample:
```php
class Foo
{
    private function myPrivateMethod()
    {
        return 7;
    }
}

$method = new ReflectionMethod("Foo", "myPrivateMethod");
$method->setAccessible(true);

echo $method->invoke(new Foo());
```

PeachPie output:
```
System.NotImplementedException: The method or operation is not implemented.
   at Pchp.Library.Reflection.ReflectionMethod.setAccessible(Boolean accessible)
```

PHP output:
```
7
```

**Comment by jakubmisek** [comment]
We'll probably throw a warning instead of exception. Anyways; this feature can't be implemented properly on .NET besides some nasty workarounds.

Do you have some real-world example? Or the sample above is real enough? :))

**Comment by calvinbaart** [comment]
Laravel uses it in their Macro system:

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/Traits/Macroable.php

See the mixin method. This method fails the tests now (and ofc the functionality of Macroable doesn't work)

**Comment by calvinbaart** [comment]
After some thinking I can probably comment out the setAccessible call from mixin, this would make it work with public methods in classes (but not protected, not sure if thats going to be an issue). I'll try this later.

**Comment by jakubmisek** [comment]
we'll change the exception to a warning, so the code will work

**Comment by calvinbaart** [comment]
Just noticed that the ReflectionProperty variant of this method is also used:

https://github.com/laravel/framework/blob/master/src/Illuminate/Queue/SerializesModels.php#L58

**Comment by jakubmisek** [comment]
we already silently ignore `ReflectionProperty::setAccessible` but good to know!
