### ISSUE TITLE
preg_replace: System.ArgumentException '[^\pL\d]+' thrown

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#516]
While executing the below statement an exception is thrown: 

`$str = preg_replace('/[^\\pL\d]+/u', '-', $str);`

Exception: 
![2019-08-29_141603](https://user-images.githubusercontent.com/41576848/63940116-21dcb500-ca69-11e9-807c-209c3f1a8cc8.jpg)

**Comment by jakubmisek** [comment]
thanks, fixed in https://github.com/peachpiecompiler/peachpie-perlregex/commit/7d8b6197f9fdcee61ce4662c3da10cbb8129ca41
