### ISSUE TITLE
operate two different encoding will cause garbage characters

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#527]
```php
// "你好" in chinese gbk
$text = urldecode('%c4%e3%ba%c3');
$text2 = urlencode($text);

// unable to restore
var_dump($text2);
```

the current `Context.StringEncoding` is `UTF8` which is default encoding, Peachpie uses current encoding to decode it, it actually breaks the text, thus it is unable to restore. not only `urldecode` `urlencode` but also others functions like `serialize` `unserialize`.

**Comment by jakubmisek** [comment]
Internally PeachPie calls to `System.Net.WebUtility.UrlDecode(string)` which returns the invalid Unicode characters (???). Looking for solution...

**Comment by jakubmisek** [comment]
I'm actually getting the same in C#
```c#
System.Web.HttpUtility.UrlDecode("%C4%E3%BA%C3", Encoding.Default)
```
Result: `"���"`

Is the string encoded in a Chinese code page?

**Comment by jakubmisek** [comment]
`urldecode()` now respects `Context.StringEncoding` which can be set in `PhpRequestOptions` (see https://github.com/iolevel/peachpie-samples/blob/11eeb017d023359671abddb713231f3722002079/web-application/app/Program.cs#L54)

**Comment by liesauer** [comment]
actually this doesn't solve the problem in some cases, for example, web crawler, we cannot preset the encoding, because different site has different encoding. `serialize` `unserialize` have the same problem, if i try to serialize my `Response` class which contains the raw html, it produces the invalid unicode characters as well.

**Comment by jakubmisek** [comment]
I see. Most of the functions are string-safe and avoids using single-byte strings as it is in PHP. The only way is to report particular issues with a small test case so it can be fixed.
