### ISSUE TITLE
Cannot use with .NET Framework

### ISSUE THREAD

**Issue by smx-smx** [peachpiecompiler/peachpie#536]
Changing the target of a PeachPie project from .NET Core to .NET Framework causes the following problems

1 - The exe won't run due to 'SixLabors.Core' not meeting the Strong Name requirements (other PeachPie libraries use a strong name)

Workaround for 1:
```
snremove.exe -r *.dll
```

2 - The exe still won't run: `System.BadImageFormatException: The module was expected to contain an assembly manifest.` on PeachPie.Runtime.dll

UPDATE:
I got it working by taking the PeachPie snk, https://github.com/brutaldev/StrongNameSigner
and resigning the following assemblies

- PeachPie.Library.Graphics.dll
- SixLabors.Core.dll
- SixLabors.ImageSharp.dll

So the issue is about SixLabors not being signed, and PeachPie.Library.Graphics requiring it

PeachPie version: 0.9.46
.NET Framework version targeted: 4.7.2

**Comment by jakubmisek** [comment]
There is a nuget that solves the issue before we make the dependencies strongly signed by ourselves
https://www.nuget.org/packages/strongnamer

You have to add packagereference to your main dotnet app

**Comment by jakubmisek** [comment]
update - waiting for ImageSharp to strongly sign their release - https://github.com/SixLabors/ImageSharp/issues/738. Since we are providing ImageSharp as a dependency to other libraries, **strongnamer** is not always an option.

**Comment by jakubmisek** [comment]
update - also waiting for https://github.com/keimpema/Mvp.Xml.NetStandard/issues/3
