### ISSUE TITLE
System.ArgumentException: '^[\x{9}\x{A}\x{D}\x{20}-\x{7E}\x{A0}-\x{D7FF}\x{E000}-\x{FFFD}\x{10000}-\x{10FFFF}]*$'

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#537]
While executing the following code (which is part of HTMLpurifier standalone, line #3961) an exception is thrown. I left the comments inside the code block to understand the purpose of this code, 

```
// UTF-8 validity is checked since PHP 4.3.5
// This is an optimization: if the string is already valid UTF-8, no
// need to do PHP stuff. 99% of the time, this will be the case.
if (preg_match(
    '/^[\x{9}\x{A}\x{D}\x{20}-\x{7E}\x{A0}-\x{D7FF}\x{E000}-\x{FFFD}\x{10000}-\x{10FFFF}]*$/Du',
    $str
)) {
    return $str;
}
```

Exception: 
![2019-09-16_095816](https://user-images.githubusercontent.com/41576848/64942378-2bd42580-d869-11e9-87ce-f9942a7c2fe6.jpg)

**Comment by jakubmisek** [comment]
thank you, we have to do two things:
- recognize the well known pattern and return `TRUE` instantly
- fix the regexp parser to not crash

**Comment by jakubmisek** [comment]
Fixed in the library, will be updated soon.

For ref used at https://github.com/ezyang/htmlpurifier/blob/b88fcd180c1d358baa2cf2346d0bb7e02fded20a/library/HTMLPurifier/Encoder.php#L139

Note: 6-digit hex codes are usually not supported by regex parsers, but PHP's PCRE does it.

**Comment by jakubmisek** [comment]
Note for me, following is another Unicode check that can be ignored (from WordPress)
```
/(
	(?: [\x00-\x7F]                  # single-byte sequences   0xxxxxxx
	|   [\xC2-\xDF][\x80-\xBF]       # double-byte sequences   110xxxxx 10xxxxxx
	|   \xE0[\xA0-\xBF][\x80-\xBF]   # triple-byte sequences   1110xxxx 10xxxxxx * 2
	|   [\xE1-\xEC][\x80-\xBF]{2}
	|   \xED[\x80-\x9F][\x80-\xBF]
	|   [\xEE-\xEF][\x80-\xBF]{2}
	|    \xF0[\x90-\xBF][\x80-\xBF]{2} # four-byte sequences   11110xxx 10xxxxxx * 3
	|    [\xF1-\xF3][\x80-\xBF]{3}
	|    \xF4[\x80-\x8F][\x80-\xBF]{2}
){1,40}                          # ...one or more times
)
| .                                  # anything else
/xl
```

**Comment by menturion** [comment]
> 
> 
> Fixed in the library, will be updated soon.
> 
> For ref used at https://github.com/ezyang/htmlpurifier/blob/b88fcd180c1d358baa2cf2346d0bb7e02fded20a/library/HTMLPurifier/Encoder.php#L139
> 
> Note: 6-digit hex codes are usually not supported by regex parsers, but PHP's PCRE does it.

Great, many thanks!
