### ISSUE TITLE
peach /target:web support

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#540]
Is phalanger's "target:web" supported?
How do we build dll's for Mono Linux with peach?

**Comment by jakubmisek** [comment]
`peach.exe` is just an internal tool for development; everything is managed through msbuild. Example of an **asp.net core** web project can be found on https://github.com/iolevel/peachpie-samples/tree/master/web-application/website

The targets are now the same as for the C# (https://docs.peachpie.io/php/msbuild/#outputtype), for web and class libraries use the `library` output type (which is the default).

```xml
<OutputType>library</OutputType>
```

For **asp.net (not core)** see https://docs.peachpie.io/scenarios/beginner/full-net-framework/#aspnet-application
