### ISSUE TITLE
Cannot run webapp

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#541]
When running web app sample [1] with "dotnet run, I get:

> Unable to run your project.
> Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
> A runnable project should target a runnable TFM (for instance, netcoreapp2.0) and have OutputType 'Exe'.
> The current OutputType is 'Library'.

Before trying this command, I synced lastest peachpie version from github and compiled with VS 2017.

[1] : https://github.com/iolevel/peachpie-samples/tree/master/web-application

**Comment by kripper** [comment]
I believe I'm not running the latest peachpie version when running "dotnet run".
How do I install the new compiled assemplies?

**Comment by liesauer** [comment]
use `dotnet run -p app`, that's becasuse this solution contains two projects so u need to specify which to  be startup.

**Comment by liesauer** [comment]
or u can just
```shell
cd /path/to/startup_project
dotnet run
```

**Comment by kripper** [comment]
I'm using "dotnet run" inside the project folder, but I believe dotnet is not using the latests compiled assemblies. I'm trying to find out how to install those assemblies.

**Comment by liesauer** [comment]
`web-application` folder or `web-application/app` folder? it's not the compiled assemblies issue.

**Comment by jakubmisek** [comment]
Please refer to the readme right on the link you've posted

**Comment by kripper** [comment]
Thanks!. Webapp is now running, but giving HTTP 500 ERROR.
How can we enable/see the PHP errors?

**Comment by jakubmisek** [comment]
all the errors and exceptions are written into the console or into your IDE debug output

**Comment by kripper** [comment]
Ok. When running "dotnet run" from command line, no errors are shown (the error is caused by referencing a undefined function).
I'm researching to find out how to run the .msbuildproj from VS 2017 to see the debug output.
I'm sorry for asking basic stuff, I'm just still completely new to the whole dev environment.

**Comment by jakubmisek** [comment]
![image](https://user-images.githubusercontent.com/842150/65391202-bf748d00-dd66-11e9-8234-e831b80b5cb4.png)

**Comment by jakubmisek** [comment]
or open the folder in VSCode, note you need the C# plugin installed

**Comment by jakubmisek** [comment]
Also, you can attach to the `dotnet` process from Visual Studio (select CLR Debug Engine when you do)

**Comment by kripper** [comment]
Working! I created a solution with my website.msbuildproj and the sample app.csproj and am now able to see/debug errors in VS 2017.

1) When building the project, I see "PeachPie PHP Compiler version 0.9.46+92daf0f5043a80a36bc511ab6826ab3cedb59760". Is that the latest version?
or should I replace the version string in my website.msbuildproj?
Is there any trick to always use the latests version?

2) Going further (and before starting to post as separate issues)...when compiling "$callBack($data)" I get "PHP4056	Function name must be a string, null given".
Should we rewrite "$callBack($data)" to something like:

```
$tmp = create_function('$data', "return $callBack(\$data)");
$tmp($data);
```

Or is/will this be supported directly in peachpie?

**Comment by jakubmisek** [comment]
1. no trick yet, we are changing versions and they might be not backward compatible so it is safer to use the version you specify

2. `$callBack` is null, that's error. Suppressing the error by using `eval()` is barbaric and you'll endup with the same error in runtime.

**Comment by kripper** [comment]
Ok, I thought the error was during compilation time.
We are on track now and will start testing and posting issues.
Thanks for this fast intro.

**Comment by jakubmisek** [comment]
The error is in compilation time. The compiler diagnoses the code and gives you errors before you run the code. (there are some of them described https://docs.peachpie.io/php/diagnostics/)

Thanks for the questions, we'll address them in the documentation.

**Comment by kripper** [comment]
Ok. the compiler was right.
I have another question regarding migration from Phalanger:

My app failed to compile because it references a class that is not included in the .msbuildproj file. In Phalanger, the class was included during runtime with require_once. The reason it is not included in .msbuildproj, is because this is third party code that references many other external resources that should not be included/compiled.

Does peachpie support referencing classes and functions that will not be compiled but included during runtime with require_once?

Use case is: we need to include a third party code (we don't want to modify) which references other third party code that are not used by our project.

**Comment by jakubmisek** [comment]
If the class is not included and compiled, you cannot require it in runtime either. See https://docs.peachpie.io/php/diagnostics/ **PHP4044**

All the code that you are going to run must be compiled. You can however break your project into several projects and reference each other so it won't get recompiled every time you change the source code.

This is a breaking change from Phalanger - as of PeachPie 1.0 - code won't be compiled dynamically during runtime.

**Comment by kripper** [comment]
Yep, I also found this discussion:
https://github.com/peachpiecompiler/peachpie/issues/289

Using "Exclude" and some minor modificatins should be fine I guess.

**Comment by kripper** [comment]
Is there any directive to ignore some PHP code block when using peachpie compiler?

**Comment by jakubmisek** [comment]
This is getting little bit off-topic. I would suggest to ask questions on https://gitter.im/iolevel/peachpie where other might help as well.

**Comment by kripper** [comment]
Ok, I'll do.
Regarding my last question, I will just move conflicting code to separate files and exclude them for peachpie.
Thanks again!

**Comment by jakubmisek** [comment]
I hope it helps!
