### ISSUE TITLE
v1.0.0-appv2863: mysqli connect/update does not work anymore

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#544]
v1.0.0-appv2863: mysqli connect/update does not work anymore.

**Comment by jakubmisek** [comment]
what does it mean - does not work? :)

**Comment by menturion** [comment]
Unable to update a field in the DB. 
No changes have been made to the code. Just updated to the above PeachPie version.

**Comment by jakubmisek** [comment]
what is the sequence of function calls? it is not `mysqli_connect`, `mysqli_query()` maybe ? we have changed how field names are mapped

**Comment by menturion** [comment]
The sequence didn't change and worked in previous PeachPie versions.

**Comment by jakubmisek** [comment]
Understand, but that doesn't help to find the issue.

**Comment by jakubmisek** [comment]
Are you using `mysqli_fetch_field` ?

**Comment by jakubmisek** [comment]
Ok, I see a warning `PHP (Warning): Command execution failed: There is no current result set`

**Comment by menturion** [comment]
It happens while mysqli_query UPDATE.

**Comment by jakubmisek** [comment]
thanks! found it
