### ISSUE TITLE
how to run peachpie on apache?

### ISSUE THREAD

**Issue by aidin0181** [peachpiecompiler/peachpie#547]
hi.i don't know if there is really need to use a web server or not.but if there is,could it be run in apache?the main reason for the usage of webserver is it's configurations.i need it a lot.
thanks

**Comment by jakubmisek** [comment]
thanks for the question

sample web application: https://github.com/iolevel/peachpie-samples/tree/master/web-application

to run the asp.net core website on apache: please see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.0
