### ISSUE TITLE
function myfunction(string $id = null) {...}: Different default values in PHP vs PeachPie

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#552]
Different behaviour for default value $id when calling `myfunction($param, string $id = null) {...}`

PHP:
Default value of $id is NULL.

PeachPie:
Default value of $id is 'null'.

Example: https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L122

**Comment by jakubmisek** [comment]
do you have a test case? I don't know where you got the `'null'` :)

**Comment by menturion** [comment]
@jakubmisek 
Get phpfastcache v7.1.0 via composer (see https://packagist.org/packages/phpfastcache/phpfastcache).

Instantiate it:
```
use Phpfastcache\CacheManager;
use Phpfastcache\Config\ConfigurationOption;

try {
    CacheManager::setDefaultConfig(new ConfigurationOption([
            'path' => $yourpathtocache,
    ]));
    $cache = CacheManager::getInstance('files');
} catch (\Exception $e) {
    // Something went wrong
}
```

Set a breakpoint here https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L122
and check whether the false clause of the "Elvis" operator is executed, i.e. whether the hash is generated.

Tested with PeachPie v1.0.0-appv2882 (-> I didn't get any updates from the PeachPie NuGet stream anymore).

**Comment by jakubmisek** [comment]
closing as not replicable - we don't have a test case.

**Comment by jakubmisek** [comment]
Please try to provide us with a test case that we can run. I don't know where you got NULL and 'null', what it means, etc. Some inspection of variables in Watch window might help, at least a screenshot a local variables?

**Comment by menturion** [comment]
Above, I gave you the detailed description of the test case and how to reproduce this issue.

**Comment by jakubmisek** [comment]
there is no code that outputs following text:
```
Default value of $id is NULL
```
therefore we were not able to replicate the test case, we were really trying hard. So please clarify what does it mean, what do you mean by NULL and 'null', how did you get this output from the line you're refering to.

**Comment by menturion** [comment]
@jakubmisek 
This is the test case: https://github.com/peachpiecompiler/peachpie/issues/552#issuecomment-540920622

Further explanantion:
If you instantiate the cache manager by this `$cache = CacheManager::getInstance('files');` the default value of `string $instanceId = null` should be NULL, see https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L113

However, `$instanceId` becomes a string with value 'null', in PeachPie with the consequence that the condition of the statement `$instanceId = $instanceId ?: \md5($driver . \serialize($config->toArray()));` in line #122 (see https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L122) is true and the hash `\md5($driver . \serialize($config->toArray()))` will not be generated. 

As a consequence, an exception is thrown.

**Comment by jakubmisek** [comment]
@menturion now I get it!

**Comment by jakubmisek** [comment]
It seams that the Visual Studio debugger just shows the value incorrectly. Internally there is the correct `null` at the beginning, and after the line with `md5` the hash is generated (but VS keeps showing `null`). If I double click it in watch, it gets updated correctly :/

![watch-string](https://user-images.githubusercontent.com/842150/66718156-fcb9c100-ede0-11e9-8c04-54e1984277f6.gif)

**Comment by menturion** [comment]
If so, I would expect the hash `\md5($driver . \serialize($config->toArray()))` be generated at line # 122. Instead, it won't and an exception will be thrown.
(?)

**Comment by jakubmisek** [comment]
please see the gif above ... it is generated but it shows as `null` in watch window ... 

if you are referring to some exception, you have totell me what exception ... please post us pictures and short test cases, because most of the discussion is very confusing

**Comment by menturion** [comment]
> please see the gif above ... it is generated but it shows as null in watch window ...

Ok, I see. So you suppose that this is an issue of VS's debugger and it would work as intended when running as release. 

The exception will be thrown if you proceed stepping through the code.

**Comment by jakubmisek** [comment]
Yes, seems like just incorrectly displayed value in the debug watch.

Please at least name of the exception :) sreenshot, anything, ...

**Comment by menturion** [comment]
> Please at least name of the exception :) sreenshot, anything, ...

Not today :)

**Comment by menturion** [comment]
Still doesn't work. Tested with latest PeachPie and latest VS 2019.

It works fine at this place if you remove the typehint `string`, i.e. changing `public static function getInstance(string $driver = self::AUTOMATIC_DRIVER_CLASS, $config = null, string $instanceId = null): ExtendedCacheItemPoolInterface` to `public static function getInstance(string $driver = self::AUTOMATIC_DRIVER_CLASS, $config = null, $instanceId = null): ExtendedCacheItemPoolInterface` at line # 113, see https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L113.

**Comment by jakubmisek** [comment]
please can you specify "doesn't work."? :)

You mean the value in Watch Window? because it will be always showing `null` even it is actually not null

**Comment by menturion** [comment]
It means that the code simply does not work correctly due to this issue. 
It is not just an issue of showing the wrong values in debug mode. Just test the code by stepping forward through the code.

**Comment by menturion** [comment]
... Did you verify your assumption that the code works correctly as Release? Otherwise all libraries that are using `myfunc(..., string $var = null, ...)` would not work correctly.

**Comment by jakubmisek** [comment]
I really need a simply test case, we don't have resources to get the whole framework compiled and working as a test case.

According to what you told me, following is **the test case**:

---
```php
class X {
    static function foo(string $s = null) {
        $s = $s ?: \md5("xxx");
        var_dump($s);
    }
}

X::foo();
```

Expected result: `string(32) "f561aaf6ef0bf14d4208bb46a4ccb3ad"`
Actual result: `string(32) "f561aaf6ef0bf14d4208bb46a4ccb3ad"`

---
so it works for me. If the test case is not valid according to what you test, please correct me.

**Comment by menturion** [comment]
You are right. It seems to work. 
It is something different and to be honest, currently, I don't know what is preventing the "files" driver to be instantiated, see above https://github.com/peachpiecompiler/peachpie/issues/552#issuecomment-540920622. 

Btw, I am getting the below popup message at this line of code https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L125

![2019-10-18_184608](https://user-images.githubusercontent.com/41576848/67112800-5dc60800-f1d8-11e9-80ad-18933892a3c2.png)

And the code fails at this line of code https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L131.


So, if you want to get PeachPie bug free, take a look at it :)
