### ISSUE TITLE
$sig = md5(print_r($data, true)); / System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#553]
While executing the statement `$sig = md5(print_r($data, true));` the following exception is thrown:

```
NullReferenceException: Object reference not set to an instance of an object.
Pchp.Core.OrderedDictionary+ReadonlyEnumerator.get_CurrentValue()

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)

Stack Query Cookies Headers
NullReferenceException: Object reference not set to an instance of an object.
Pchp.Core.OrderedDictionary+ReadonlyEnumerator.get_CurrentValue()

Show raw exception details
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
System.Reflection.RuntimePropertyInfo.GetValue(object obj, object[] index)
Pchp.Core.Reflection.TypeMembersUtils.EnumerateInstanceFields<TKey>(object instance, Func<MemberInfo, PhpTypeInfo, TKey> keyFormatter, Func<IntStringKey, TKey> keyFormatter2, Func<MemberInfo, bool> predicate, bool ignoreRuntimeFields)+MoveNext()
Pchp.Library.Variables+PrintFormatter.AcceptObject(object obj)
Pchp.Core.PhpVariableVisitor.Accept(PhpValue obj)
Pchp.Library.Variables+PrintFormatter.AcceptObject(object obj)
Pchp.Core.PhpVariableVisitor.Accept(PhpValue obj)
Pchp.Library.Variables+FormatterVisitor.Serialize(PhpValue value)
```

**Comment by jakubmisek** [comment]
Thank you for the issue, but in order to replicate the issue, we need the `$data` value. I'm just asusming it contains the object instance.

Closing for as not replicable

**Comment by menturion** [comment]
Please find below an excerpt of the $data array. The array obviously references non-public members, see screenshot below:

![2019-10-15_092128](https://user-images.githubusercontent.com/41576848/66809672-1ae10780-ef2e-11e9-8c9d-93520ef50dfd.png)

NOTE: There is no issue in PHP.

**Comment by jakubmisek** [comment]
But this is the object contained IN `$data` right ... I can only guess, the $data references an instance of `IteratorIterator`? Menturion you have a special gift showing me only the last pieces of the puzzle :))

**Comment by menturion** [comment]
I'm trying hard to give my best to do so :) Hopefully, here is the final piece of this puzzle: 

```
-		data	Expose\DataCollection#1779951	object
+		_ctx	request.php	Pchp.Core.Context {Peachpie.AspNetCore.Web.RequestContextCore}
+		_enumerator	{Pchp.Core.OrderedDictionary.ReadonlyEnumerator}	Pchp.Core.IPhpEnumerator {Pchp.Core.OrderedDictionary.ReadonlyEnumerator}
+		Non-Public members	
```

**Comment by jakubmisek** [comment]
Thanks! What is the parent class of `Expose\DataCollection` ? :)

**Comment by menturion** [comment]
@jakubmisek 
This is the library "enygma/expose" (https://github.com/enygma/expose). The affected line can be examined here ...
https://github.com/enygma/expose/blob/07ee1ebe5af6a23029d4d30147463141df724fc5/src/Expose/Manager.php#L172

**Comment by jakubmisek** [comment]
ok thanks so the parent class of `Expose\DataCollection` is `\ArrayIterator` :)

**Comment by jakubmisek** [comment]
fixed in https://github.com/peachpiecompiler/peachpie/commit/179b18b88e06043580abcda1e593f694114077b4
