### ISSUE TITLE
Instruction of publish on IIS

### ISSUE THREAD

**Issue by karthik0608** [peachpiecompiler/peachpie#554]
Hai, i had tried published the project into IIS. Unfortunately, there is sufficient of information on deployment of it. Is there any information that i'm missing it?

Error that occurred : 
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

0x80070005
--
Cannot read configuration file due to insufficient permissions

**Comment by jakubmisek** [comment]
The process of publish is not different to any other asp.net core application.

You can find much more resources on Internet than I'm able to give you here by searching for `500.19 0x80070005 Cannot read configuration file due to insufficient permissions` :)
