### ISSUE TITLE
Method call with parameter by reference -> Value/data not updated

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#555]
@jakubmisek here is another gift.

Found this issue in HTMLpurifier (standalone, also valid for HTMLpurifier.auto).
Please view the following code you can find here https://github.com/moodle/moodle/blob/8111abc33113e3c60f87aefea2cce28d25e5c9c3/lib/htmlpurifier/HTMLPurifier/Strategy/ValidateAttributes.php#L16:

```php
    public function execute($tokens, $config, $context)
    {
        // setup validator
        $validator = new HTMLPurifier_AttrValidator();
        $token = false;
        $context->register('CurrentToken', $token);
        foreach ($tokens as $key => $token) {
            // only process tokens that have attributes,
            //   namely start and empty tags
            if (!$token instanceof HTMLPurifier_Token_Start && !$token instanceof HTMLPurifier_Token_Empty) {
                continue;
            }
            // skip tokens that are armored
            if (!empty($token->armor['ValidateAttributes'])) {
                continue;
            }
            // note that we have no facilities here for removing tokens
            $validator->validateToken($token, $config, $context);
        }
        $context->destroy('CurrentToken');
        return $tokens;
    }
}
```

At line # 22 (https://github.com/moodle/moodle/blob/8111abc33113e3c60f87aefea2cce28d25e5c9c3/lib/htmlpurifier/HTMLPurifier/Strategy/ValidateAttributes.php#L22) the `$token` gets initialized by reference, calling `$context->register('CurrentToken', $token);`, see `$this->_storage[$name] =& $ref;` here https://github.com/ezyang/htmlpurifier/blob/c6ca293eab531add17726609a6a783c66611001a/library/HTMLPurifier/Context.php#L24  .

After this the data of `$token` gets altered by means of the loop` foreach ($tokens as $key => $token)` within "execute()" (by assigning an array), and thus altering `$context->_storage['CurrentToken']`. 

In PeachPie, however, the data of `$context->_storage['CurrentToken']` does not get altered through reference.

**Comment by jakubmisek** [comment]
thank you! we're already on it (ref https://github.com/peachpiecompiler/peachpie/issues/252)

to workaround it for now, you can add typehint to the function signature:
```php
    public function execute($tokens, $config, HTMLPurifier_Context $context)
```

**Comment by jakubmisek** [comment]
closing as duplicate to #252

**Comment by jakubmisek** [comment]
this should be fixed now! thanks @menturion

**Comment by menturion** [comment]
@jakubmisek 
Just tested. It - i.e. HTMLPurifier - seems to work now.

**Comment by jakubmisek** [comment]
thank you!
