### ISSUE TITLE
disable warning messages for files

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#556]
peachpie disable specific warning messages by their IDs currently. 
 see https://docs.peachpie.io/php/msbuild/#nowarn
but it would be nice if we can disable by specify php scripts or any files, such as
```xml
<NoWarnPattern Remove="vendor/**/*.php" />
<NoWarnPattern Remove="**/test/**/*.php;**/tests/**/*.php" />
```

**Comment by jakubmisek** [comment]
that's a good suggestion but we are not planning to support such setting in the future updates

- it is non-standard and undocumented
- it would be unnecessarily complex to implement
- it can be solved by spliting the solution into projects each with its own `<NoWarn>` property

However we'll keep it in mind!

**Comment by liesauer** [comment]
alright, but if implements, it would be pretty convenient, for example, disable all the third-party components warnings or all the composer stuff under `vendor/`, so it won't give us tons of warnings, we just need to focus on our warnings, most of time, the third-party warnings are useless.

**Comment by jakubmisek** [comment]
I agree, it makes sense. For now recommending to separate `/vendor` into a separate project anyways.
