### ISSUE TITLE
extend abstract constructor issues

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#557]
test case:
```php
<?php

interface ClassContract
{
    public function __construct();
}

abstract class AbstructClass implements ClassContract
{
    abstract public function __construct();
}

class BaseClass extends AbstructClass
{
    public function __construct()
    {
        // parent::__construct();
        echo "BaseClass";
    }
}

new BaseClass;

```

1. `BaseClass` no need to call `parent::__construct`, so should be no warning `warning PHP5026: Missing the call of parent::__construct from BaseClass::__construct.`
2. after adding `parent::__construct`, i should get a fatal error `PHP Fatal error:  Uncaught Error: Cannot call abstract method AbstructClass::__construct()`, but peachpie generates bad IL program

```
PeachPie PHP Compiler version 0.9.42+e52b08cc4a9ecf5c22794f19f168d2e779a3e9bf
/Users/imac/Projects/extendAbstractConstructor/program.php(15,32): warning PHP5026: Missing the call of parent::__construct from BaseClass::__construct. [/Users/imac/Projects/extendAbstractConstructor/extendAbstractConstructor.msbuildproj]
  extendAbstractConstructor -> /Users/imac/Projects/extendAbstractConstructor/bin/Debug/netcoreapp2.0/extendAbstractConstructor.dll
```

after adding `parent::__construct()`
![image](https://user-images.githubusercontent.com/8676741/67074881-9952d900-f1bc-11e9-8c69-8ca949a00796.png)

**Comment by jakubmisek** [comment]
thank you, fixed diagnostic and checked abstract methods cannot be called
