### ISSUE TITLE
RuntimeBinderException when passing the right object to PHP(with class type declaration) from C#

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#559]
![image](https://user-images.githubusercontent.com/8676741/67139520-c0281280-f283-11e9-90b8-1df32c49e44b.png)

my `fetchUrl` method signature
![image](https://user-images.githubusercontent.com/8676741/67139533-ecdc2a00-f283-11e9-8ae1-4ac5ed3bbbda.png)

**Comment by jakubmisek** [comment]
seems `o` is actually a boxed `Pchp.Core.PhpValue` which does not implement `IDynamicMetaObjectProvider` **yet** , so the CSharp runtime binder does not know what to do with it. 

We have it planned for `1.1` at https://docs.peachpie.io/roadmap/

For now, the `Action<object>` is not properly getting `object` converted from the PHP's world and gets boxed PhpValue instead. PhpValue should be "unwrapped" using e.g. `PhpValue.AsObject()` operator

**Comment by jakubmisek** [comment]
Sidenote - what an ugly tooltips you have in VSCode :) grab this extension instead! https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode

**Comment by jakubmisek** [comment]
`spider` is not `System.Object` but `PhpValue` - convert it from PhpValue to object first.

**Comment by liesauer** [comment]
![image](https://user-images.githubusercontent.com/8676741/67171046-c3d4aa00-f3e7-11e9-969c-e507b6e73d30.png)
i try lots of ways, still the same. may be is an IL issue? i will try to reproduce with a simple test case later.

**Comment by liesauer** [comment]
explicit cast `Request` to `dynamic` works! but i have no idea why.

**Comment by jakubmisek** [comment]
Yes, once you convert it using `ToClr()`, you can cast to `dynamic` or cast to `(Request)`. Not an IL issue.

Also I would recommend to review, how did you get the value into your Action in the first place, because it should get `object` already (not `PhpValue`)

**Comment by liesauer** [comment]
i have done lots of code refactoring. now no any `ToClr()` more. but i still need to cast to `dynamic` otherwise still `RuntimeBinderException `, this doesn't make any sense.

**Comment by jakubmisek** [comment]
if you'll find out what's the problem, we'll be happy to know :)
