### ISSUE TITLE
'Method not found: 'PhpValue.GetArray()'.' from array functions using class variables

### ISSUE THREAD

**Issue by siggi90** [peachpiecompiler/peachpie#572]
System.MissingMethodException: 'Method not found: 'Pchp.Core.PhpArray Pchp.Core.PhpValue.GetArray()'.' This error appears from this code when using class variables:

	public $test_array = [1,2,3];
	function test_function($value) {
		return in_array($value, $this->test_array);
	}

But it works fine like this:

	public $test_array = [1,2,3];
	function test_function($value) {
		$test_array = [1,2,3];
		return in_array($value, $test_array);
	}

and the error seems to appera with other array functions as well.

**Comment by jakubmisek** [comment]
This usually happens when referenced peachpie assemblies versions are mismatching. Ensure Sdk version and all references to PeachPie.*** have the same version.
