### ISSUE TITLE
call_user_func_array doesn't pass value to parameter with default array value

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#576]
```php
function test_args($p1 = 0, $args = array()) {
	echo 'p1: ', $p1, PHP_EOL;
	echo 'args:', PHP_EOL;
	print_r($args);
}

call_user_func_array('test_args', array(2, array('a' => 100, 'b' => 200)));
```
The code above shows an empty array for `$args` parameter instead of the passed array to `call_user_func_array`. It happens with the latest build (1.0.0-appv3013 - ce546023) but it worked in 0.9.46. With 1.0.0-appv3013 works only if `$args` doesn't have a default value.

**Comment by jakubmisek** [comment]
thank you @crbrz fixed

**Comment by jakubmisek** [comment]
fixed in https://github.com/peachpiecompiler/peachpie/commit/8fec7622534aed959f232cf42d289cf772b9111d
