### ISSUE TITLE
diff on DateTime is returning wrong information

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#577]
Using Peachpie 0.9.500 and 0.9.600 the following code 

	$y = '2018' 
	$m = '11'
	$d = '13'
	$tz_utc = new DateTimeZone("UTC");
	$today = new DateTime();
	$today = new DateTime($today->format("Y-m-d"), $tz_utc);
	$after = clone($today);
	$sdate = new DateTime($y . "-" . $m . "-" . $d, $tz_utc);
	$diff = $sdate->diff($after);

results the following $diff structure 

  | Name | Wert | Typ
-- | -- | -- | --
◢ | diff | {Pchp.Library.DateTime.DateInterval} | Pchp.Library.DateTime.DateInterval
  | d | -365 | int
  | ▶ days | -365 | integer
  | f | 0 | double
  | h | 0 | int
  | i | 0 | int
  | invert | 1 | int
  | m | 0 | int
  | s | 0 | int
  | y | 0 | int

**expected behaviour:**

Acording to php documentation (and our test with php) "Invert" should be set to zero and days should be positiv in this case, as the difference is a positive time span (from 13th Nomveber 2018 until today (13th November 2019)). Also y should be set to 1 and d should be set to 0.

```
DateInterval Object
(
    [y] => 1
    [m] => 0
    [d] => 0
    [h] => 0
    [i] => 0
    [s] => 0
    [f] => 0
    [weekday] => 0
    [weekday_behavior] => 0
    [first_last_day_of] => 0
    [invert] => 0
    [days] => 365
    [special_type] => 0
    [special_amount] => 0
    [have_weekday_relative] => 0
    [have_special_relative] => 0
)
```

**Comment by jakubmisek** [comment]
thank you, first update fixes the inverted results https://github.com/peachpiecompiler/peachpie/commit/31985cb804883e94061dd2f68de6e272bcda633d

**Comment by jakubmisek** [comment]
closing the issue since it now returns correct information

**Comment by jan-ai** [comment]
While invert and days seems to be correct now, other values seem to be always 0. As an example d should be in the range of 0 to 30, but not 56 as shown below. Taking the example from below m should be set to 1 and d to something between 25 and 28 (depending on input parameters).

see https://www.php.net/manual/en/class.dateinterval.php

  | Name | Wert | Typ
-- | -- | -- | --
◢ | diff | DateInterval | object
  | ▶ _span | {56.00:00:00} | System.TimeSpan
  | d | 56 | int
  | days | 56 | int
  | f | 0 | double
  | h | 0 | int
  | i | 0 | int
  | invert | 0 | int
  | m | 0 | int
  | s | 0 | int
  | y | 0 | int

**Comment by jakubmisek** [comment]
Thank you, you are right - this comes from the .NET which returns intervals in days (`TimeSpan`)

We should probably normalize the DateInterval ... (will create an issue for it)
