### ISSUE TITLE
DateTime ignores the time zone parameter

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#578]
```php
function test() {	
	$dt = new DateTime('2019-11-13 18:00:00', new DateTimeZone('America/Los_Angeles'));

	echo $dt->getTimestamp(), PHP_EOL;
}

test();
```
Parsing a date with `DateTime` and a timezone other than the current timezone gives a different result compared to PHP. Tested with 1.0.0-appv3028 (2a1650c7).

**Comment by jakubmisek** [comment]
fixed in https://github.com/peachpiecompiler/peachpie/pull/579
