### ISSUE TITLE
String concatenation doesn't work in release build

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#581]
```php
function test() {
	$a = array('a' => 1, 'b' => 2);

	$result = 'a(';
	foreach($a as $k => $v) {
		$result .= " $k=" . '"' . $v . '"';
	}
	$result .= ')';

	echo $result;
}

test();
```
Tested with 1.0.0-appv3041 (e0d70e73). The output from release build is ` b="2")` instead of `a( a="1" b="2")`

**Comment by jakubmisek** [comment]
https://github.com/peachpiecompiler/peachpie/commit/e0d70e732e526e7bed4b889b37b170a735e04df6 is not a master branch and is a work in progress, the issue does not occure in the master branch nor any of releases

**Comment by jakubmisek** [comment]
@roberthusak seems there is an issue with your last changes ;) in dev/semantic-transformations branch

**Comment by crbrz** [comment]
Sorry, I didn't noticed e0d70e7 wasn't from master branch. I checked with 1.0.0-appv3040 (ae23e94d) and I get the same result.

**Comment by jakubmisek** [comment]
ok, reopening, thanks!

**Comment by jakubmisek** [comment]
thanks @crbrz !
