### ISSUE TITLE
inaccessible get_Item method in 0.9.500

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#582]
before `0.9.500` we can access an object that has implemented .net indexer via `get_Item` method, but in `0.9.500` this method is inaccessible.

[indexer-testcase.zip](https://github.com/peachpiecompiler/peachpie/files/3853872/indexer-testcase.zip)
ps: downgrade this testcase's Peachpie version to `0.9.44` will work.

**Comment by jakubmisek** [comment]
we have to implement .NET indexers properly

**Comment by jakubmisek** [comment]
since now it is possible to use normal array item operator `[]` to call get_Item/set_Item
