### ISSUE TITLE
Unable to override certain methods, e.g. wpdb->get_results

### ISSUE THREAD

**Issue by jdluzen** [peachpiecompiler/peachpie#583]
Using the wpdotnet-sdk repo, I am attempting to override everything in the wpdb class.

While most methods override correctly, some do not. `wpdb->get_results` overridden via 
```c#
public override PhpValue get_results(PhpValue query = default, [DefaultValue("<get_results.output>_DefaultValue")] PhpValue output = default)
```
does not get called.

**Comment by jakubmisek** [comment]
This might "fail" because of use of the '[DefaultValueAttribute]` which should be always compiler-generated. Please try to remove the attribute if it helps.

**Comment by jdluzen** [comment]
I have removed the attribute, however it still calls the base method. I am currently working around it with your fix in #584, as that approach seems cleaner too.
I can leave this open if you'd like to investigate further.
For reference, the following are overridden successfully:
- db_connect
- set_prefix
- get_var
- get_blog_prefix
- query

**Comment by jakubmisek** [comment]
Can you check `$wpdb` is really an instance of your C# object? It's the only thing that comes to my mind now.

Where is the function call? Or does it happen for every function call?

**Comment by jakubmisek** [comment]
@jdluzen any updates on this? Overriding is something that works out of the box and we don't do much about it, maybe overriding a different overload?

Meantime I'm closing it as it works in our tests. If you'd have more information, please open a new issue.
