### ISSUE TITLE
stream_select() throws NotImplementedException

### ISSUE THREAD

**Issue by OsaPL** [peachpiecompiler/peachpie#590]
Hi,
I tried using select_streams() and it throws NotImplementedException.
Looked into repo and its works as it should, though I see code commented there:

https://github.com/peachpiecompiler/peachpie/blob/72568a227aba0b7f5e9fdd4671551c5be1eee523/src/Peachpie.Library/Streams/Streams.cs#L956-L1006

I really dont know anything about PHP (just trying to adapt some PHP libraries to work with our backend), but are there any plans to make it work?

In meantime, I'm gonna try and uncomment this, build from repo, and test if this even works (once I get it to build).

**Comment by jakubmisek** [comment]
thank you @OsaPL 
we have not tested it yet, but it should be working as specified
