### ISSUE TITLE
responsive file manager error 302

### ISSUE THREAD

**Issue by bahmansh** [peachpiecompiler/peachpie#592]
I'm using dotnet core 3, tinymce 5, and responsive file manager 9.
So when I want open file manager I get error 302 (Found) and redirect to 404 page.

![image](https://user-images.githubusercontent.com/19801131/69520640-731a1900-0f72-11ea-988f-2eda7a4914d4.png)

Here is error:

![image](https://user-images.githubusercontent.com/19801131/69520704-9218ab00-0f72-11ea-9d7e-2d313b98a0bc.png)

**Comment by jakubmisek** [comment]
Thank you for the issue. There is not much we can help with, I would suggest to move the issue to https://github.com/gordon-matt/peachpie-responsive-file-manager/issues :)
