### ISSUE TITLE
dotnet new -i 'Peachpie.Templates::*'  - can't download peachpie templates

### ISSUE THREAD

**Issue by 6umpukc-uHKBu3umop** [peachpiecompiler/peachpie#603]
`dotnet new -i 'Peachpie.Templates::*'`
```
                    
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error : Не удалось загрузить индекс службы для источника https://api.nuget.org/v3/index.json. [/home/user/.templateengine/dotnetcli/v3.1.100/scratch/restore.csproj]
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/home/user/.templateengine/dotnetcli/v3.1.100/scratch/restore.csproj]
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/home/user/.templateengine/dotnetcli/v3.1.100/scratch/restore.csproj]

```
`
dotnet --info                        `
```

Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Среда выполнения:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/var/lib/snapd/snap/dotnet-sdk/57/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/var/lib/snapd/snap/dotnet-sdk/57/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/var/lib/snapd/snap/dotnet-sdk/57/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by jakubmisek** [comment]
thank you, the correct command is
```shell
dotnet new -i Peachpie.Templates
```

**Comment by jakubmisek** [comment]
try the command without the quotes please

**Comment by 6umpukc-uHKBu3umop** [comment]
i have same error 

`dotnet new -i Peachpie.Templates     `

```

maybe its some problem of nuget packages service?
```
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error : Не удалось загрузить индекс службы для источника https://api.nuget.org/v3/index.json. [/home/user/.templateengine/dotnetcli/v3.1.100/scratch/restore.csproj]
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/home/user/.templateengine/dotnetcli/v3.1.100/scratch/restore.csproj]
/var/lib/snapd/snap/dotnet-sdk/57/sdk/3.1.100/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/home/user/.templateengine/dotnetcli/v3.1.100/scratch/restore.csproj]
```

**Comment by jakubmisek** [comment]
I see; this seems to be related to NuGet restore on MacOs (there are sometimes a weird issues with SSL), have you tried updating your local certificates?

maybe related?
- https://github.com/dotnet/core/issues/1668
- https://github.com/NuGet/Home/issues/8169
- https://github.com/dotnet/dotnet-docker/issues/1031
- https://github.com/dotnet/dotnet-docker/issues/1341

**Comment by jakubmisek** [comment]
> meanwhile you can create a project file by yourself using the template at https://docs.peachpie.io/php/msbuild/#sample-project-file
