### ISSUE TITLE
error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie.

### ISSUE THREAD

**Issue by iWangJiaxiang** [peachpiecompiler/peachpie#604]
Hi, developers.

Thank you for such an amazing `peachpie`. I have resolved many `Type name could not be resolved.` issue in my peachpie project and it all most works.

But finally the remaning issues are all `error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not
supported by PeachPie.`. Such as

>/root/projects/PeachPie.Test/Website/3rdparty/symfony/cache/Adapter/FilesystemTagAwareAdapter.php(161,21): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not
supported by PeachPie. [/root/projects/PeachPie.Test/Website/Website.msbuildproj]
···

It seems like these php packages use the grammar unsupported by peachpie. Do you have any plan to do this? Or, is there anything I could do to help you. (I write .Net)

**Comment by jakubmisek** [comment]
Hi, thank you! we have plans to support `yield` in try/catch, but currently it is too complicated (.NET does not allow jumping into try/catch blocks, or jumping out of try/catch without invoking `finally` ... we'll keep you updated here
