### ISSUE TITLE
curl_getinfo() before curl_exec()

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#613]
I also found another issue with the way PeachPie implements `curl_getinfo()`, specifically here:

https://github.com/peachpiecompiler/peachpie/blob/bb0116bdfa124b772ea1c2779e3cc8cd91f431dc/src/Peachpie.Library.Network/CURLFunctions.cs#L141

### Example
```php
// Set a URL
curl_setopt($ch, CURLOPT_URL, "http://example.com/");

// Get the URL _before_ the request is executed
$e_url = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
var_dump($e_url);

// Never executed:
// $response  = curl_exec($ch);
```

### PHP Runtime
`string(19) "http://example.com/"`

### Peach Pie Runtime
`bool(false)` - This is not correct

Unless I'm mistaken, the `Result` is initially set to `null`, which results in this incompatibility between the original and Peach Pie implementation:
https://github.com/peachpiecompiler/peachpie/blob/bb0116bdfa124b772ea1c2779e3cc8cd91f431dc/src/Peachpie.Library.Network/CURLFunctions.cs#L603

Is this assumption correct?

**Comment by jakubmisek** [comment]
I see, before `curl_exec()` PeachPie always returns `FALSE` ..

```php
    $ch = curl_init('http://www.example.com/');
    print_r( curl_getinfo($ch) ); // <-- always false
```

**Comment by jakubmisek** [comment]
thank you David, please let us know if there would be something else (curl has a lot of missing pieces, so we'll try to make it working for practical cases at least). 

Any pull request with fixes or new features is welcomed.

**Comment by DRSDavidSoft** [comment]
@jakubmisek Thank you again for the quick resolve, the df7429b0386eb4e91834613ca71200ebf62cd616 has been nicely done!

There are at the moment so many issues with the cURL implementation, although I'd say it's somewhat functional. I'll try to point out the ones that might be an obstacle for building practical projects. Thank for prioritizing!

I might create some PRs if I'd be able to write the required patch in C#.
