### ISSUE TITLE
Invalid implementation for CURLOPT_ENCODING

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#614]
### Description
This issue causes an invalid header to be sent when using the `CURLOPT_ENCODING` option.  
(**Expected:** `Accept-Encoding`, **Actual:** `Accept` )

### Example code
```php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://httpbin.org/get");
curl_setopt($ch, CURLOPT_ENCODING, "gzip, deflate"); // ← here
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$ret = curl_exec($ch);
var_dump($ret);
```

### php.exe
The request header set will be:
```
Accept-Encoding: gzip, deflate
```
which is correct.

### Peach Pie
The request header set will be:
```
Accept: gzip, deflate
```
which is not correct, and may cause the request to fail.

### Remarks
- e.g. IIS servers return HTTP 406 if the received `Accept` header from the client does not match the expected MIME
- This also causes the original `Accept` header to be reset from the default `*/*` value.

I was not able to find the cause of this in either [CURLFunctions.cs](https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library.Network/CURLFunctions.cs) or [CURLFunctions.cs](https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library.Network/CURLFunctions.cs).

**Comment by jakubmisek** [comment]
thanks, we've been setting a wrong header there!
