### ISSUE TITLE
cURL default `Accept` header missing

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#616]
## Description
All cURL requests by default _should_ have a default header of `Accept: */*`, unless a blank value for the accept header (i.e. `"Accept:"`) is passed to cURL.  

Please note the following examples:

### Example 1
<details><summary>Missing the default "Accept: */*" in Peach Pie, click to show</summary>

```php
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_exec($ch);
```

#### Received request headers from `php.exe`
```
GET http://httpbin.org/get HTTP/1.1
Host: httpbin.org
Accept: */*
```

#### Received request headers from Peach Pie
```
GET http://httpbin.org/get HTTP/1.1
Host: httpbin.org
Connection: Keep-Alive
```

**Note the missing `Accept: */*` in Peach Pie**

</details>

### Example 2
<details><summary>When setting "Accept:" header, click to show</summary>

```php
$ch = curl_init();

$headers  =  array( "Accept:" );  // passing a blank value for the Accept header

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_exec($ch);
```

#### Received request headers from `php.exe`
```
GET http://httpbin.org/get HTTP/1.1
Host: httpbin.org
```

#### Received request headers from Peach Pie
```
GET http://httpbin.org/get HTTP/1.1
Host: httpbin.org
Connection: Keep-Alive
```

**In this case, Peach Pie's behavior is correct.**
</details>

n.b. Peach Pie's cURL implementation also sets the `Connection: Keep-Alive`, which is unrelated here

**Comment by jakubmisek** [comment]
thank you! 

the seconds sample is probably wrong for php.exe, but I get the point :)

**Comment by DRSDavidSoft** [comment]
@jakubmisek It actually is intended:

- https://stackoverflow.com/q/18183467/1454514
- https://stackoverflow.com/a/7640101/1454514
- https://stackoverflow.com/a/12131993/1454514

**Comment by jakubmisek** [comment]
please check it behaves correctly now :)

**Comment by DRSDavidSoft** [comment]
@jakubmisek Nicely done, it works as expected! 👍
