### ISSUE TITLE
cURL cookies not working

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#617]
### Example code
```php
$ch = curl_init();

function cURL_test( $url ) {
	GLOBAL $ch;

	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_COOKIEFILE, true);

	$result = curl_exec($ch);

	$URL = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
	$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

	var_dump($code, $URL, "\n", $result);
}

// Performing the request for the first time
cURL_test( "http://ip.of.a.server:port/generate_some_cookie" );

// Performing the request for the second time
cURL_test( "http://ip.of.a.server:port/checking_the_cookie" );

curl_close( $ch );

```

### Expected results
1. The cookies from the first request (`http://ip.of.a.server:port/generate_some_cookie`) will be saved
2. The second request should contain cookies from the first request

### Actual results
The cookies from the first request is not sent when performing the second request

n.b. Confirmed that `php.exe` handles this correctly, while Peach Pie has this issue

**Comment by DRSDavidSoft** [comment]
@jakubmisek can you also take a look at this, please?

**Comment by jakubmisek** [comment]
thank you David, can you please verify the above fix works?

**Comment by DRSDavidSoft** [comment]
@jakubmisek Yes, it works perfectly; thank you!
