### ISSUE TITLE
Unexpected DOMDocument node result

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#622]
I'm not sure if this is intended behavior in Peach Pie (or .NET), but it seems that `DOMNode->nodeValue` returns the node's value in HTML entity encoded format; whereas `php.exe` doesn't.

Please have a look at the following example:

### Test case
```php
$html = <<<END
<!doctype html>
<html lang="en">
	<head>
		<script>
		  var test = "something";
		</script>
	</head>
</html>	
END;

// ----------------------------------------

$dom = new DOMDocument;
$dom->loadHTML($html);

$els = $dom->getElementsByTagName('script');
foreach ($els as $node) {
	$text = trim($node->nodeValue);
	var_dump($text);
}
```

### php.exe, i.e. expected results
```
string(23) "var test = "something";"
```

### Peach Pie, i.e. actual results
```
string(49) "//

                  var test = &quot;something&quot;;

////"
```

**Comment by jakubmisek** [comment]
looks like `HtmlAgilityPack.HtmlDocument` does it when converting HTML dom to XML dom

**Comment by DRSDavidSoft** [comment]
- So HtmlAgilityPack doesn't provide a method to get the inner text without having it encoded?
- Also, what if something like `html_entity_decode()` is applied to the returned string, before it's passed to php?
- How much effort would implementing an alternative to `HtmlNode.WriteTo` would take, as an estimate?

**Comment by jakubmisek** [comment]
It does provide the original string, but PeachPie calls `WriteTo` which internally performs the encoding (https://github.com/zzzprojects/html-agility-pack/blob/5f82294ea08802aac90d53074f6eef6f934634eb/src/HtmlAgilityPack.Shared/HtmlNode.cs#L1786). There is no option to save it without encoding the XML entities, hence, we have to implement our own `WriteTo` method.

**Comment by jakubmisek** [comment]
correct implementation would be to convert HTML DOM to XML DOM without saving it to string and parsing it back as XML :)
