### ISSUE TITLE
Console color issue (VT mode)

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#633]
### Test case
```php
echo "\033[31m" . "Hello, world" . "\033[0m\n";
```

### Result
**Command prompt terminal (conhost.exe)**

<img src="https://user-images.githubusercontent.com/4673812/73132964-a8f18180-4037-11ea-8437-6b0e8293b3f9.png" width="383" height="342" alt="Peach Pie PHP Console Color ANSI code" />

### Notes
This is the same case if I run the following `.cs` code:
```c#
Console.Write("\x1b[31m" + "Hello, world" + "\x1b[0m\n");
```

However, this works fine in `.cs`:
```c#
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Hello, World!");
Console.ResetColor();
```

I'm not sure how I can achieve the same thing in `.php`.

### Version information
- **PHP 7.2.9 cli**
- **.NET Core 3.1.100**
- **Windows 10 1903**

**Comment by jakubmisek** [comment]
thank you, a very nice test case.

In .NET we have Unicode console, without magic characters :) but this is implementable.

Just in order to get some priority to this - is it used as a part of some project? maybe an opensource?

**Comment by DRSDavidSoft** [comment]
@jakubmisek Thanks for the quick response! I hope the amount of effort required to implement this will be minimal.

I believe the console colors are used by open-source projects like [psysh](https://psysh.org/), [Kint](https://kint-php.github.io/kint/), [WP-CLI](https://wp-cli.org/), and many more that use the the [helper packages](https://packagist.org/?query=color+ansi).  In general, the [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) are actually quite useful when developing any kind of console application, be it Python, Node.js, PHP, and even Peach Pie (`dotnet new console -lang PHP`).

(Hopefully, Peach Pie will be able to support them!)

Although that .NET makes coloring the console output easier by using properties such as `Console.ForegroundColor` and/or `Console.BackgroundColor`, I believe in the end the mechanism is the same as outputting the magic characters, as you put it 😃 

I should also mention that this is only an issue with `conhost.exe`, and other terminal emulators such as [ConEmu](https://conemu.github.io/) (part of [Cmder](https://github.com/cmderdev/cmder)), or any [xterm.js](https://xtermjs.org/)-based terminal (such as [Hyper](https://hyper.is/), [Terminus](https://eugeny.github.io/terminus/) and VS Code's terminal work fine with Peach Pie generated escape codes.

One way to implement this is to parse the escape codes, and re-implement them via the `Console.*` properties.  Or somehow make the generated `.exe` behave in a way that Windows accepts the ANSI codes?  I believe the former method would be unnecessary if the latter is possible.

Personally, I am using the color codes in a PHP project I've written in the past that now I'm trying to run with Peach Pie, and the color codes are one of the aspect that are not working quite yet.

I have a `-peachpie` branch of my project with some patches in order to solve inconsistencies and make it work with Peach Pie. I'm open to using or calling any methods in the php source code at the moment, if there's anything I can do.

But hopefully Peach Pie will be able to display the ANSI escape codes correctly within conhost.exe, if that's possible.

**Comment by jakubmisek** [comment]
I see! So far I have tried powershell, vscode and VS, and color codes work for me, in C#, in PHP, in PeachPie.

![image](https://user-images.githubusercontent.com/842150/73136300-64bcac00-404c-11ea-8f1d-95be4d1fbfd7.png)

powershell, vscode:
![image](https://user-images.githubusercontent.com/842150/73136299-5f5f6180-404c-11ea-94b9-c88aaba5ef4c.png)

It turns out the only problem is `cmd.exe` where it is not properly supported

- https://www.jerriepelser.com/blog/using-ansi-color-codes-in-net-console-apps/

According to https://en.wikipedia.org/wiki/ANSI_escape_code#Platform_support this can be enabled in registry, or an API function and soon to be enabled by default maybe

**Comment by DRSDavidSoft** [comment]
@jakubmisek Is it possible by Peach Pie to call that API, or is it up to Core runtime?

**Comment by jakubmisek** [comment]
probably PeachPie should do it within its `ConsoleContext`  class.

PHP does it as well: https://github.com/php/php-src/blob/2fe86669c94354dbbfcdf98baef31674835fd4c0/win32/console.c#L83

**Comment by DRSDavidSoft** [comment]
I applied the registry option for now. There is [a SO post](https://stackoverflow.com/a/51681675/1454514) that explains a couple of bullet points:

> **PowerShell automatically activates VT (virtual terminal) support *for itself*** when it starts (in recent releases of Windows 10 this applies to both Windows PowerShell and PowerShell Core). 

also:

> Calling the `SetConsoleMode()` Windows API function *from inside the program (process)*, as described [here](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences), is cumbersome even in C# (due to requiring a P/Invoke declaration)

I remember before PHP 7, it didn't call `SetConsoleMode()` and thus VT100 mode was disabled.

If Peach Pie can call `SetConsoleMode()` before script execution in order to behave like `php.exe`, it'd be awesome.
