### ISSUE TITLE
How to detect Peach Pie from PHP

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#636]
This is a quick question, but is there a way to query Peach Pie's version from inside `.php`?

Also, aside from `PHP_EXTRA_VERSION === "-peachpie"` (defined in [here](https://github.com/peachpiecompiler/peachpie/blob/1748defa3d18b9608411a848fdda2b58588a8b39/src/Peachpie.Library/Environment.cs#L24)), how do I check if the project was build by Peach Pie?

**Comment by jakubmisek** [comment]
there is a global constant defined `PEACHPIE_VERSION`

```php
if (defined("PEACHPIE_VERSION")) {  }
```

**Comment by jakubmisek** [comment]
I'm adding this into the documentation, a few people asked already :)
