### ISSUE TITLE
Issue with CURLINFO_EFFECTIVE_URL

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#644]
### Description
Getting `CURLINFO_EFFECTIVE_URL` will not work correctly if the handle (e.g. `$ch`) has been previously used before.  

_Note:_ This only happens if the first request is executed successfully,  
in other words, if the first `curl_exec($ch);` is removed in the example below, the issue does not occur.

### Test case
```php
// initialize curl
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

// set first url
curl_setopt($ch, CURLOPT_URL, "https://example.com/?test=first");
$url_before = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL); // get the current url, works correctly

// execute first request
curl_exec($ch);

// set second url
curl_setopt($ch, CURLOPT_URL, "https://example.com/?test=second");
$url_after = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL); // get the current url, does not work, returns the previous url

// execute second request
curl_exec($ch);

// dump the results
print_r([$url_before, $url_after]);
```

### Expected results / `php.exe`
```
Array
(
    [0] => https://example.com/?test=first
    [1] => https://example.com/?test=second
)
```

### Actual results / PeachPie
```
Array
(
    [0] => https://example.com/?test=first
    [1] => https://example.com/?test=first
)
```

**Comment by DRSDavidSoft** [comment]
@jakubmisek I believe the issue lies here:
https://github.com/peachpiecompiler/peachpie/blob/256536174a4e693609ff208f934e039885d6a888/src/Peachpie.Library.Network/CURLFunctions.cs#L194-L195

It should be the other way around, i.e. `ch.Url` should be preferred over `ch.Result.ResponseUri.AbsoluteUri`.

Maybe only check for `ch.Url`, and after the request finishes set `ch.Url = ch.Result.ResponseUri.AbsoluteUri` would solve this?

**Comment by jakubmisek** [comment]
you are right, that's the php's behavior, it only looks into `ch.Url`

**Comment by DRSDavidSoft** [comment]
@jakubmisek interesting!

So, would my suggestion (regarding implementing `ch.Url = ch.Result.ResponseUri.AbsoluteUri` after the request has finished) be the correct approach, here?

**Comment by jakubmisek** [comment]
yes, it was correct. Now the URL is updated after the exec, behaving the same as in PHP.
thanks!
