### ISSUE TITLE
DOMDocument->loadHTML(false)

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#646]
### Description
- `DOMDocument`  
   There's an issue when calling [`DOMDocument::loadHTML()`](https://www.php.net/manual/en/domdocument.loadhtml.php) with an argument value of `false` instead of a string:

```php
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Peachpie.Library.XmlDom.DOMXPath.__construct(DOMDocument document)
   at Peachpie.Library.XmlDom.DOMXPath..ctor(DOMDocument document)
```

This is a problem with the code since `loadHTML()` should _never_ accept an argument of type boolean, but since PHP accepts it, I thought to mention this problem.

**Comment by jakubmisek** [comment]
the exception seems to be in `DOMXPath` - do you have a test case where DOMXPath is used please?

**Comment by DRSDavidSoft** [comment]
@jakubmisek oops, I didn't notice the stack trace. Sure, here's an example:

```php
// ... somewhere `false` is assigned to this variable, instead of the expected string
$html = false;

$dom = new DOMDocument;
@$dom->loadHTML($html);
$finder = new DOMXPath($dom);
```
