### ISSUE TITLE
Missing default DTD when working with DOMDocument

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#652]
## Description
The `getElementById` method does not work if the `XmlDocument` does not contain a valid DTD that defines the ID attribute.

From [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldocument.getelementbyid):
> The DOM implementation must have information which defines which attributes are of type ID. Although attributes of type ID can be defined in either XSD schemas or DTDs, this version of the product only supports those defined in DTDs. **Attributes with the name "ID" are not of type ID unless so defined in the DTD**. Implementations where it is unknown whether the attributes are of type ID are expected to return `null`.

In other words, since XmlDocument knows nothing about what an id means, we need a DTD to establish which attribute on elements would constitute the unique id. 

### Test case
```php
$dom = new DOMDocument;
@$dom->loadHTML( "<html> <div id='some_id'> foo <span>bar</span> baz <i class='icon'></i> </div> </html>"); // example html
	
$domElement = $dom->getElementById("some_id");
if ( $domElement == null ) die("FAULT: null detected");
print_r("id: " . $domElement->getAttribute('id'));
```

### PHP results
```
id: some_id
```

### Peach Pie results
```
FAULT: null detected
```

## Possible solutions

1. Attach some sorts of a default DTD to the XmlDocument before/while it's validated

2. Use hacks, such as:  
      ```cs
      public virtual DOMElement getElementById(string elementId)
      {
          // XmlElement element = XmlDocument.GetElementById(elementId);
          // return element != null ? new DOMElement(element) : null;
          foreach (XmlNode node in XmlDocument.GetElementsByTagName("*"))
          {
              if (node != null && node is XmlElement)
              {
                  string id = ((XmlElement)node).GetAttribute("id");
                  if ( id == elementId ) return new DOMElement((XmlElement)node);
              }
          }
          return null;
      }
      ```

   (This works, however, it's unnecessary reducing performance, and it works only if the `id` attribute is written in all lower-case - e.g. this will not work: `<div Id='some_id'>`)

   **── or ──**

   Using XPath (although it may need to be [escaped](https://stackoverflow.com/a/1352556/1454514)):

   ```cs
   XmlNode node = XmlDocument.SelectSingleNode($"//*[@id='{elementId}']");
   ```

3. Since we already have an `HtmlAgilityPack.HtmlDocument`, we can assign it to as a property of the class, so it could be later used like this:

   ```cs
   HtmlAgilityPack.HtmlNode element = htmlDoc.GetElementbyId(elementId);
   ```

   Although, I'm not sure if the `HtmlAgilityPack`'s method differs from `XmlDocument`, at all.

---

@jakubmisek I would appreciate your input on this subject.

**Comment by jakubmisek** [comment]
I would attach a default DTD if none is explicitly provided - the same behavior as PHP does. Maybe this should be created in `loadHtml` method.

`HtmlAgilityPack` is only used for loading HTML documents, nothing else.

**Comment by DRSDavidSoft** [comment]
@jakubmisek awesome, option 1 it is. I didn't know this is the same behavior as PHP.

**Comment by jakubmisek** [comment]
it's in the documentation you've posted :)

**Comment by jakubmisek** [comment]
so, it seems `loadHtml` should provide a default `systemId` (as a part of DOCTYPE) if not specified, and also `XmlDocument` must have XmlResolver set: 
```c#
XmlDocument.XmlResolver = new XmlPreloadedResolver();
```
so the DTD gets parsed and map of IDs populated into the XmlDocument!

Then `GetElementById` works

**Comment by jakubmisek** [comment]
the approach above would cause unnecessary DTD validation (which is veyr expensive and might fail and throw on invalid HTML fragments) ...

anyways; even .NET in the end creates a simple dictionary with { id -> element } ... we can simply override `GetElementById` and create and use this map by ourselves ..

working on it

**Comment by DRSDavidSoft** [comment]
@jakubmisek Thanks for the update, hopefully it'll be solved
