### ISSUE TITLE
curl_error() duplicated message

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#653]
### Test case
```php
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_URL, "http://test.test/test");
curl_exec($ch);
print_r(curl_error($ch));
curl_close($ch);
```

### Result
```
No such host is known. No such host is known.
```

As you can see, the message "No such host is known." is repeated two times. Any reason why this might happen?

**Comment by jakubmisek** [comment]
seems like an issue in WebException, it concatenates two inner exceptions which are both the same
