### ISSUE TITLE
Referenced array member not working

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#654]
### Description
This is a really weird case; this only causes an issue if the key "response" is used twice, and `$ref` is referenced to `$json`.

### Test case
```php
$str  = '{ "response": { "items": [ { "response": "OK" } ] } }';
$json = json_decode($str, true);
$ref  = &$json['response']['items']['0']['response'];
var_dump($ref, strlen($str)); exit;
```

### PHP
```
string(2) "OK"
int(53)
```

### PeachPie
```
NULL
int(53)
```

**Comment by jakubmisek** [comment]
Oh, I see - `['0']` is not converted to integer key `[0]`, it's a abug in runtime ... so PeachPie is looking for a non-existing array item, returning NULL.

**Comment by DRSDavidSoft** [comment]
Interesting, why does this issue happen only when it's `&`'ed? Hopefully, it's possible for the runtime to convert the key to integer this way, so this issue could be fixed?

**Comment by jakubmisek** [comment]
yes, it's a small typo in the compiler, thank you for finding out!!
