### ISSUE TITLE
is_numeric skipped on else branch

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#659]
```php
function test($v) {
	if(is_a($v, 'DateTime')) {
		echo 'a DateTime';
	} elseif(is_numeric($v)) {
		echo 'a number';
	} else {
		echo 'unknown';
	}
}

test(1);
```
On `1.0.0-appv3388` the code above outputs `unknown`. From IL it looks like `is_numeric` is skipped entirely. In release configuration `warning PHP5011: Unreachable code detected` is issued for line 5.

**Comment by jakubmisek** [comment]
seems that call to `is_a` breaks type information of `$v` (it is treated as `$v: null|object`) 

@roberthusak can you take a look on it please?
