### ISSUE TITLE
Request stubs for implementation

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#663]
### Description
I would like to ask for some stubs in order to implement some missing standard calls.  
The stubs should either
- throw a `NotImplementedException()`, or
- contain a `// TODO:` with a one-liner description of the method/function

preferably, both.

### List of requested stubs
- [x] `cli_get_process_title()`
- [x] `cli_set_process_title()`
- [x] `dns_get_record()`
- [x] `dns_check_record()` / `checkdnsrr()`
- [ ] _TBA_

**Comment by jakubmisek** [comment]
done, please let me know if you'd need any more stubs or help implementing them :)

**Comment by DRSDavidSoft** [comment]
@jakubmisek Thanks, I will let you know as soon as possible. :D
