### ISSUE TITLE
$argv[0] should contain script name

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#665]
Per [$argv documentation](https://www.php.net/manual/en/reserved.variables.argv.php):
> **Note:** The first argument `$argv[0]` is always the name that was used to run the script.

However, PeachPie is [missing](https://github.com/peachpiecompiler/peachpie/blob/1e07f03426a03304039efcb3df41363b93cafe5d/src/Peachpie.Runtime/Context.Console.cs#L46-L80) this argument.

This should not be omitted, as some apps/libraries simply `array_unshift()` it, so this causes the first argument (e.g. `arg1`) to be lost.

### PHP Example
```bash
php program.php arg1 arg2 arg3
```

```php
var_dump($argv);
```

```php
array(4) {
  [0]=>
  string(10) "script.php"
  [1]=>
  string(4) "arg1"
  [2]=>
  string(4) "arg2"
  [3]=>
  string(4) "arg3"
}
```

**Note:** `$argc === count($argv)` => 4

### PeachPie
```bash
dotnet run arg1 arg2 arg3
# or
.\bin\Debug\netcoreapp3.0\myApp-CLI.exe arg1 arg2 arg3
```

```php
var_dump($argv);
```

```php
array(4) {
  [0]=>
  string(4) "arg1"
  [1]=>
  string(4) "arg2"
  [2]=>
  string(4) "arg3"
}
```

**Note:** `$argc === count($argv)` => 3

### Suggestions for `$argv[0]`
- part of `mainscript`
- name of the executable

**Comment by jakubmisek** [comment]
thanks!
