### ISSUE TITLE
Implement remaining SPL features

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#668]
- [x] `function CachingIterator::__toString`
- [x] `const RegexIterator::INVERT_MATCH`
- [x] `const ArrayIterator::STD_PROP_LIST`
- [x] `const ArrayIterator::ARRAY_AS_PROPS`
- [x] `const RecursiveArrayIterator::CHILD_ARRAYS_ONLY`
- [x] `const FilesystemIterator::OTHER_MODE_MASK`
- [x] `function SplFileObject::getCurrentLine`
- [ ] `__serialize`/`__unserialize`

**Comment by roberthusak** [comment]
I have some notes regarding the stuff I didn't fully implement:

1. `ArrayIterator` cannot properly handle the assignment of aliases to properties, as the second argument of `__set` is always dealiased (which is the right behavior for `__set` implemented in PHP code).
2. `__serialize` and `__unserialize` are used for the [new serialization mechanism added in PHP 7.4](https://wiki.php.net/rfc/custom_object_serialization). I skipped them as we don't have it in Peachpie yet.
3. I skipped `_bad_state_ex`, as it seems to be just a helper method to raise an exception when the `SplFileInfo` object's constructor wasn't called. I haven't seen it used explicitly anywhere.

@jakubmisek Is that OK?

**Comment by jakubmisek** [comment]
1. so `ArrayIterator` behaves the same like in PHP ?
2. PeachPie has the new `Serializable` interface and supports its methods. The issue is, PHP reflection reveals the `ArrayIterator` (and others) have magic methods `__serialize`/`__unserialize` which are not documented and should not be there!
3. ok

**Comment by roberthusak** [comment]
1. It does if its properties are assigned by value, but not if it's by reference, e.g. `$it->prop =& $value`. Currently, the callsite is compiled so that it gets dereferenced before being passed to `__set`. Not sure if anyone uses this, though.
2. I'm afraid that `__serialize` and `__unserialize` are the newest way how to implement serialization in PHP (in addition to `Serializable` and `__sleep`/`__wakeup`), see this [RFC](https://wiki.php.net/rfc/custom_object_serialization) (implemented in PHP 7.4). But they're indeed not documented (yet), so maybe we can wait until they are.

**Comment by jakubmisek** [comment]
I see!

1. I think the callsite gets the value aliased, but inside it dereferences it?
2. ok! please implement __serialize/__unserialize in SPL :) and make me an issue to support it in serialization functions

**Comment by roberthusak** [comment]
1. Yes, exactly.
2. OK 👍
