### ISSUE TITLE
PDO SqlSrv: LastInsertId is empty

### ISSUE THREAD

**Issue by dlob** [peachpiecompiler/peachpie#674]
The last inserted ID returned is empty:
```php
<?php
$handle = new PDO("sqlsrv:server=(localdb)\MSSQLLocalDB; Database=test", null, null);
$handle->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$sql = "INSERT INTO table1 (field1) VALUES (?)";
$sth = $handle->prepare($sql);
$sth->execute(array(1234));
$lastId = $handle->lastInsertId();
var_dump($lastId);
?>
```
Output:
```
string(0) ""
```

Maybe replacing SCOPE_IDENTITY() (works in local scope only) with @@IDENTITY (global scope) would resolve the problem.

**Comment by jakubmisek** [comment]
Thank you! according to MS's sources https://github.com/microsoft/msphpsql/blob/7458a6c1c6389d9ad0eeb9670f5203c6c344d432/source/pdo_sqlsrv/pdo_dbh.cpp#L35 : `@@IDENTITY` should be correct
