### ISSUE TITLE
strrev() is not byte safe, string gets encoded using Encoding

### ISSUE THREAD

**Issue by aayushchachan** [peachpiecompiler/peachpie#687]
```
<?php
$hexStr = "7583B05800000000";

$up = unpack("H*", strrev(pack("H*", $hexStr)));

echo $up[1];

?> 
```
Output of above Php code in php compiler gives **0000000058b08375**

Whereas output of the same code snippet in PeachPie in my Visual Studio 2019 gives different output as below:
**0000000058EFBFBDEFBFBD75**

**Comment by jakubmisek** [comment]
Thank you. I'm not sure why, but I'm getting the same result with PeachPie: `0000000058B08375`
Using peachpie 0.9.800 and the latest development build as well.

May I ask for your project file?

**Comment by jakubmisek** [comment]
OK, the problem is not `pack`, but `strrev`.

Internally, PeachPie converts the argument for `strrev` to Unicode string using local culture which corrupts the byte array from `pack`.
