### ISSUE TITLE
better diagnostic for PHP5009: Call to undefined method: xxxxx

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#689]
if a class contains `__callstatic` or `__call` method, any undefined method call to this class should be ignored.
if contains `__callstatic`, ignore undefined static method call.
if contains `__call`, ignore undefined instance method call.

considering this or something like this
```
/**
 * @method static Router get(string $route, Callable $callback)
 * @method static Router post(string $route, Callable $callback)
 * @method static Router put(string $route, Callable $callback)
 * @method static Router delete(string $route, Callable $callback)
 * @method static Router options(string $route, Callable $callback)
 * @method static Router head(string $route, Callable $callback)
 */
class Router
{
    public static function __callstatic($method, $params)
    {
        // do something
    }
}
```
calling `Router::get()` or `Router::post()` will get a `PHP5009` warning now.

**Comment by jakubmisek** [comment]
thanks, the problem was the diagnostic was looking for `__callStatic` (case sensitively). Fixed in the upcoming commit.
