### ISSUE TITLE
pcre issue - Unrecognized grouping construct

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#694]
following code gives different results in PHP / PeachPie
```php
$pattern = "~\\{\\s* ([a-zA-Z_][a-zA-Z0-9_-]*) \\s*(?:    : \\s* ([^{}]*(?:\\{(?-1)\\}[^{}]*)*))?\\}(*SKIP)(*F) | \\[~x";
$routeWithoutClosingOptionals = "/";
$segments = preg_split($pattern, $routeWithoutClosingOptionals);

print_r($segments);
```

PHP: `Array(  [0] => "/" )`

PeachPie: `PHP (Warning): Unrecognized grouping construct. at offset 65`

**Comment by roberthusak** [comment]
There are two things which need to be implemented for this regex to work:
- [x] Relative subroutine calls (e.g. `(?-1)`) - done in https://github.com/peachpiecompiler/peachpie-perlregex/commit/bab7adac4bbb0a0f07a6cd12f10687ac7f569c9c
- [ ] Backtracking control verbs (at least `(*SKIP)` and `(*F)`) - in progress

**Comment by roberthusak** [comment]
It should work now, @jakubmisek can you please bump the version and reference it?

**Comment by jakubmisek** [comment]
done, thank you @roberthusak !
