### ISSUE TITLE
Feature request: HTMLpurifier 

### ISSUE THREAD

**Issue by bfistein** [peachpiecompiler/peachpie#697]
Can we please check whether [HTMLpurifier](https://github.com/ezyang/htmlpurifier) works? According to the source below, it currently doesn't.

Source:
https://twitter.com/liebesprinz/status/1235609585718898689

**Comment by jakubmisek** [comment]
HTMLpurifier builds without any issue, didn't try to run it yet

**Comment by jakubmisek** [comment]
seems to work, we can add it to 
- https://github.com/jakubmisek/php-dotnet-projects
- run its tests
