### ISSUE TITLE
Feature request: PhpFastCache

### ISSUE THREAD

**Issue by bfistein** [peachpiecompiler/peachpie#698]
Can we please check whether [PhpFastCache](https://github.com/PHPSocialNetwork/phpfastcache) works? According to the source below, it currently doesn't.

Source:
https://twitter.com/liebesprinz/status/1235609585718898689

**Comment by jakubmisek** [comment]
compiles allright

**Comment by jakubmisek** [comment]
checked, please comment or add a new issue in case of an ... issue
