### ISSUE TITLE
Method 'get_ReferenceDirectiveMap' does not have an implementation

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#705]
when building a peachpie based project, getting following error:
```
Peachpie.NET.Core.Sdk.targets(223,5): error : Method 'get_ReferenceDirectiveMap' in type 'Pchp.CodeAnalysis.PhpCompilation' from assembly 'Peachpie.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5b4bee2bf1f98593' does not have an implementation.
```

This is caused by updates to .NET Core SDK **3.1.200** (shipped with VS 2019 16.5) which makes peachpie sdk (up to 0.9.910) incompatible.

**Workaround** for now is to use .NET Core SDK < 3.1.200 by adding following `global.json` to the root of project (assuming you have an older SDK installed):

```json
{
   "sdk": {
        "version": "3.0.0",
        "rollForward": "minor",
        "allowPrerelease": true
    }
}
```

---

Requires:

- [x] https://github.com/peachpiecompiler/Peachpie.Microsoft.CodeAnalysis/issues/2

**Comment by jakubmisek** [comment]
ref https://github.com/peachpiecompiler/Peachpie.Microsoft.CodeAnalysis/issues/2

**Comment by roberthusak** [comment]
Fixed in [Peachpie.Microsoft.CodeAnalysis](https://github.com/peachpiecompiler/Peachpie.Microsoft.CodeAnalysis), publishing the new version `0.9.3` and referencing it from Peachpie should fix it.

**Comment by jakubmisek** [comment]
thank you, Robert! uploaded (https://www.nuget.org/packages/Peachpie.Microsoft.CodeAnalysis/0.9.3) and project will be updated
