### ISSUE TITLE
Website blog RSS feed

### ISSUE THREAD

**Issue by akraines** [peachpiecompiler/peachpie#706]
The website [blog](https://www.peachpie.io/blog)'s RSS feed is not set up properly. Can this be fixed easily?
It should work as it is built into Wordpress:
https://www.peachpie.io/blog/feed

Thanks

**Comment by jakubmisek** [comment]
The correct feed URL is https://www.peachpie.io/feed 

We should probably put a link somewhere :)

**Comment by akraines** [comment]
Thanks
