### ISSUE TITLE
Selecting wrong overload of method containing func_get_args in dynamic binding

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#709]
Test case (the full file is [attached here](https://github.com/peachpiecompiler/peachpie/files/4361969/index.php.txt)):
```php
class A
{
  function foo($a, $b = null) {
    print_r(func_get_args());
  }

  // ... a lot of other methods
}

function test($a, $fn, $args) {
  return $a->{$fn}(...$args);
}

test(new A, "foo", ["bar"]);
```

Expected:
```
Array
(
    [0] => bar
)
```

Actual:
```
Array
(
    [0] => bar
    [1] =>
)
```

I wasn't able to reduce the test case to a smaller size, because by removing some of the other methods the problem disappears. The root cause seems to be in `OverloadBinder.BindOverloadCall` - when it receives the overloads of `foo` in the order `[foo(PhpValue, PhpValue), foo(PhpValue, PhpValue[])]` instead of the reversed one (the order in which are the methods defined in the class<sup>1</sup>), it causes `foo(PhpValue, PhpValue)` to be called even for a single argument. It then calls the latter `foo(arg, [null])`, resulting in the extra `null`.

<sup>1</sup>This order is more common, but it's not ensured - given a certain constellation of methods (such as the one given in the file) it can differ.

**Comment by jakubmisek** [comment]
thanks Robert! I'll try to find a smaller test case :)
