### ISSUE TITLE
is_numeric() with a string containing hex-formatted number

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#712]
### Test case
```php
$test = "0xcaffe"; // = 831486 in decimal

var_dump($test, is_numeric($test));
exit;

```

### PHP
```
λ php program.php
string(7) "0xcaffe"
bool(false)
```

### Peach Pie
```
λ dotnet run
string(7) "0xcaffe"
bool(true)
```

### Notes
I would think that `is_numeric("0xcaffe")` should be `true`, but apparently the PHP team thinks otherwise.  An unfortunate inconsistency!

**Comment by smx-smx** [comment]
is_numeric no longer returns true for hexadecimal strings since PHP 7. It's documented here (Changelog section): https://www.php.net/manual/en/function.is-numeric.php
