### ISSUE TITLE
How to solve namespace containing class and subnamespace of the same name?

### ISSUE THREAD

**Issue by Alexander882** [peachpiecompiler/peachpie#716]
PHP allows namespaces containing subnamespaces and classes of the same name, which C# doesn't.
It seems that PeachPie handles this when the classes are defined in PHP, although it seems that the subnamespaces are not accessible from C#.
I'm trying to replace the PHP classes with C# classes, is that possible at all?
I've tried defining the classes in the subnamespace as nested classes, but they're not available in PHP this way. I also tried to annotate the classes with `[PhpType("NamespaceName\SubnamespaceName\ClassName, null)]` but that also did not work.

**Comment by jakubmisek** [comment]
an interesting issue;

Your approach using `[PhpType]` attribute is correct (and the only possible) although it was never designed for regular C# class libraries.

If you annotate the C# class library with the following attribute, PeachPie compiler and runtime will treat the assembly differently, and will respect the `[PhpType]` attribute. It has one side-effect: public static methods within public static classes will become PHP functions. (https://docs.peachpie.io/api/Libraries-Architecture/#extension-library)

```C#
[assembly: Pchp.Core.PhpExtension] 
```

**Comment by Alexander882** [comment]
I was missing the PhpExtension attribute, it works now. Thanks! and thank you for the quick response!

**Comment by jakubmisek** [comment]
glad it works!
