### ISSUE TITLE
PHP -> PHP project references

### ISSUE THREAD

**Issue by Alexander882** [peachpiecompiler/peachpie#717]
Hi, I'm using PeachPie to migrate a PHP solution to .NET, and in the progress I've come up with the following project structure:
```
Main PHP project
    |      |
    |      v
    |    .NET project
    |      |
    v      v
PHP interface project
```
The Main PHP project contains the bulk of the code including core logic
The .NET project contains integrations to other systems, such as database, file system, etc.
The PHP interface project contains the interfaces of the integrations in the .NET project, along with the classes they're dependent on (there are quite a few, so I would prefer to keep this as PHP for now)

The issue I'm having is that the PHP -> PHP reference does not work. While it compiles successfully, I get runtimes errors like `Pchp.Library.Spl.Error: 'Class 'PhpInterfaces\SomeInterface' not found'`. The .NET project resolves the references without issues.

Is referencing PHP projects from PHP projects possible?

Also, I was wondering; is using PeachPie to migrate a PHP codebase to a .NET one a god idea? or am I using PeachPie to do something it was not intended for? :)

**Comment by jakubmisek** [comment]
it is intended to do so

My first guess would be that containing PHP file defining the interface has to be included/required first (either from within PHP code or using Context.Include from C#).

**Comment by Alexander882** [comment]
Great to hear!

The interface file is included in the autoloader file in the main PHP project - the main project and interface project are both referencing files in the same directory, though never the same files.

I had a look at including the files via Context.Include, I set the working directory to `null` and the path to the absolute path of the interface.php file, also set `throwOnError` to `true`. The include call succeeds, but I see that the the interface is not included in the `ctx.GetDeclaredTypes()` immediately afterwards. I also noted that the `ctx.GetIncludedScripts()` does not contain the script file that I've just included. Am I missing something here?

**Comment by bfistein** [comment]
> Also, I was wondering; is using PeachPie to migrate a PHP codebase to a .NET one a god idea? or am I using PeachPie to do something it was not intended for? :)

*Exactly* what it was intended for. We're gonna make this a little bit more clear when we do a revamp of our website :)

**Comment by jakubmisek** [comment]
It seems all correct.

Is `Context.RootPath` set?

If you put a breakpoint onto the interface header, does it hit?

**Comment by Alexander882** [comment]
`Context.RootPath` is set to `C:\...\PhpTest\Server\wwwroot` (In the all-containing ASP.NET Core project).

I've added breakpoints everywhere in the interface file, but none of them are reached.

I've made a minimal replication of the issue here https://github.com/Alexander882/PeachPieTest 
I'm using an autoloader in the real example, but for the replication I've just `require_once`'d the interface file, in which case the import actually fails.
The question I have for the replication is maybe rather; what path to require when the file is only in the compilation of a different project? (the file exists in the PhpMain project but is not included in the list of compiled files there)

**Comment by jakubmisek** [comment]
@Alexander882 thanks for the test case - will take a look.

For the inclusion, full path of the compiled script is `RootPath` + `compiled script relative path`. So the compiled script is always relative to the Context root, as it was to the Project root.

**Comment by jakubmisek** [comment]
Seems following is an issue:
```xml
<Compile Include="../PhpMain/SomeInterface.php" />
```
It's out of the project directory which makes it literally "non-includable".

`require_once` throws `InvalidOperationException` since it cannot find `{Root}/SomeInterface.php`.

---

If you need to have all the PHP files in the same folder while having two projects, you can create two project files in the same folder.

**Comment by Alexander882** [comment]
Ah, okay. Moving the Interface project into the same folder as the main project fixed the issue, as you said. Thanks for the help!

**Comment by jakubmisek** [comment]
good! probably the compiler can treat the relative paths better, in this case, it generates something that is not usable.
