### ISSUE TITLE
How to Emit C# code to a File

### ISSUE THREAD

**Issue by weedkiller** [peachpiecompiler/peachpie#723]
Hello, I am trying to debug something. 

More specifically, I am trying to emit/Observe some of the PHP code to Converted C# code.

Where would I set a break point to view the C# code.
Would it be possible to emit C# code

thanks

**Comment by jakubmisek** [comment]
the compiler does not emit C# code

You can play around and decompile the compiled code to C#-like syntax at https://try.peachpie.io/
