### ISSUE TITLE
filter_var with FILTER_SANITIZE_STRING doesnt work properly

### ISSUE THREAD

**Issue by allex10l** [peachpiecompiler/peachpie#728]
We tried it on xammp and works fine

please refer to the sample loaded [ricerca_su_json_metodo_get.zip](https://github.com/peachpiecompiler/peachpie/files/4516608/ricerca_su_json_metodo_get.zip)

**Comment by jakubmisek** [comment]
thank you Alex! will be implemented

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/a16382adb23034b67af39c052aaf774e61d45037

available in the next release
