### ISSUE TITLE
Wrong behaviour of mb_strlen($s, "8bit")

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#732]
Consider the following snippet when `Context.StringEncoding` is UTF-8 (`c599` is `"ř"`):
```php
echo mb_strlen(hex2bin("c599"), "8bit");
```
Expected: `2`
Actual: `1`

The problem is that `8bit` encoding is not supported so UTF-8 is used instead. The easiest way to fix this is to retrieve `Encoding.ASCII` from `PhpEncodingProvider.GetEncoding` for `8bit` (it's not exactly the same, but suitable for these uses). Or we can implement a custom .NET encoding for that (not sure how to properly handle the conversion from 16-bit chars to bytes though). Or we can check for `8bit` option explicitly in functions like, but that would go against readability. @jakubmisek What do you think is the best way? (or the least wrong)

**Comment by jakubmisek** [comment]
this is commented in https://github.com/peachpiecompiler/peachpie/blob/e361ab2d1be628329a16a9f803313d8fbfd0b7dc/src/Peachpie.Library/MultiByteString.cs#L185

we should provide a corresponding encoding implementation here.

**Comment by roberthusak** [comment]
OK, how should we handle the conversion from .NET string in this encoding? Delegate it to UTF-16? We might delegate it to `Context.StringEncoding`, but `PhpEncodingProvider` doesn't have access to the current `Context`.

**Comment by jakubmisek** [comment]
we can make it a special case in mb_strlen(); '8bit' => Encoding.UTF8.GetBytesCount( str )
would it work?

**Comment by roberthusak** [comment]
I don't think that's necessary, at least for now - the mentioned error is caused by `PhpString`. In particular, this condition is not sometimes true on Linux (it seems the random bytes were there more likely to produce certain characters than on Windows):
```php
mb_strlen(random_bytes(16)) == 16
```
I created a PR with `8bit` implementation as a .NET encoding, falling back to UTF-8 in conversion from chars to bytes, should it ever be necessary.

**Comment by jakubmisek** [comment]
Thanks. Where is the error in PhpString?

The PR for purposes of `mb_strlen` and `hex2bin` works but I'd still rather handle `8bit` separately. We have all the other Unicode cases which won't work with this PR, for example:
```
mb_strlen( "ř" ) // actual 1 vs. expected 2 (on UTF8) or 1 (on Windows-1252) or ...
```

**Comment by roberthusak** [comment]
Thanks, nicely done :+1: I meant that the problem I was facing here wasn't connected with counting the length of `System.String` under certain encodings, but with incorrectly counting the length of binary data in `PhpString` due to the missing `8bit` encoding. But now it should work both, so it's certainly better.
