### ISSUE TITLE
MySQL PDO does not handle named parameters for stored procedures

### ISSUE THREAD

**Issue by tcostin** [peachpiecompiler/peachpie#748]
The following code does not run in PeachPie:

```
// login keys are created via stored procedure login_user (username/email, password, IP)
$db = create_pdo();
$query = "CALL login_user(:user, :pass, :ip)";
$stmt = $db->prepare($query);
$result = $stmt->execute(array('user' => trim($user), 'pass' => trim($pass), 'ip' => get_client_ip()));
```

With the PHP interpreter, this works fine. With PeachPie, the MySQL procedure does not run; the server raises a syntax error. Digging deeper, it seems that named parameters may not be handled by the query rewriter.

The above snippet _can_ be made to work by rewriting as follows:

```
// login keys are created via stored procedure login_user (username/email, password, IP)
$db = create_pdo();
$query = "CALL login_user(?, ?, ?);";
$stmt = $db->prepare($query);
$stmt->bindValue(1, trim($user));
$stmt->bindValue(2, trim($pass));
$stmt->bindValue(3, get_client_ip());
$result = $stmt->execute();
```

**Comment by jakubmisek** [comment]
seems the MySql connector we use (https://github.com/mysql-net/MySqlConnector) supports following named parameters:
`@name`, `?name`

Maybe we can implement support for `:name` by parsing the query, or we can make a pull request to the library above, if `:name` should be supported by the library in general.

**Comment by jakubmisek** [comment]
According to the documentation (https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-parameters.html), named parameters for MySql statements should be prefixed with `@`. 

Does anybody know if `:name` syntax is PHP specific, or it is quietly supported by a wide range of connectors? I remember it works with official MySql Connector/Net tho (https://dev.mysql.com/downloads/connector/net/)

**Comment by tcostin** [comment]
Unfortunately, .Net and PHP use different conventions. I do use the '@' prefix for query parameters in .Net code (not just MySQL), but for PHP it is different:

https://www.php.net/manual/en/pdo.prepared-statements.php
https://www.php.net/manual/en/pdostatement.execute.php

**Comment by jakubmisek** [comment]
I see, so when binding parameters, the `:` prefix is persisted?

```php
$stms->bindParam(':name', $name);
```
or
```php
$stms->bindParam('name', $name);
```
or both ?

**Comment by tcostin** [comment]
... from what I can tell, both might work? My [original] PHP code doesn't use bindParam; it uses execute(array) to set the parameters. Within that array, I don't prefix the parameter names, but I've seen other sample code that does.

**Comment by jakubmisek** [comment]
ok let's make both working :) why not
