### ISSUE TITLE
can I commit a new xmlwriter

### ISSUE THREAD

**Issue by mindfocus** [peachpiecompiler/peachpie#755]
like this -> https://github.com/mindfocus/sabre.net/blob/master/libxml2.net/NewXmlWriter.cs

use native libxml2

**Comment by jakubmisek** [comment]
Peachpie is all a safe managed cross-platform project. This seems to make use of unsafe and P/Invoke, right?

**Comment by mindfocus** [comment]
yes, but libxml2 can do what system.xml can't do, like [this test](https://github.com/mindfocus/sabre.net/blob/2142e0f0d21d76a888eb1cf78d246cac24e83ced/sabre.net.tests/sabre/Xml/WriterTest.cs#L43)，first thing I thought was replaced system.xml with libxml2, I didn't know xml well, I will keep trying. Thanks

**Comment by jakubmisek** [comment]
`XMLWriter` is implemented in [PeachPie](https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library.XmlDom/XmlWriter.cs), so I'm sure it can be fixed to handle whatever is needed. Do you know what functions behave incorrectly?

**Comment by mindfocus** [comment]
sabre project's [test case ](https://github.com/sabre-io/xml/blob/41c6ba148966b10cafd31d1a4e5feb1e2138d95c/tests/Sabre/Xml/WriterTest.php#L30)
```
<?xml version=\"1.0\"?>
<s:root xmlns:s="http://sabredav.org/ns">text</s:root>
```

so the problems are:

1. this test case will first call `XMLWriter` function **startElementNS**,  that is equivalent to `_writer.WriteStartElement("s", "root", null);` and this cause an exception **Cannot use a prefix with an empty namespace.**
2. setIntent throw exception "not allowed"

**Comment by mindfocus** [comment]
startElementNs call from [here](https://github.com/sabre-io/xml/blob/41c6ba148966b10cafd31d1a4e5feb1e2138d95c/lib/Writer.php#L130)

**Comment by jakubmisek** [comment]
so the test case is something like
```php
$xmlwriter->startElementNS("s", "root", null);
$wmlwriter->setIndent(true);
```
causing PeachPie to throw an exception while in regular PHP it works?

This can be fixed once we'll have a test case.

**Comment by mindfocus** [comment]
That would be very nice, thank you 
and 
case 1 is 
```
$xmlwriter->startElementNS("s", "root", null);
```
case 2 is
```
$wmlwriter->setIndent(true);
```
