### ISSUE TITLE
Configuration to auto-start session (session.autostart=1)

### ISSUE THREAD

**Issue by itpleb** [peachpiecompiler/peachpie#756]

**Comment by jakubmisek** [comment]
good question;

there is no configuration to auto-start session yet

todo: https://github.com/peachpiecompiler/peachpie/blob/6652d48ce9d1911bd80da6fd73a2ad5ba45777e6/src/Peachpie.AspNetCore.Web/RequestContextCore.cs#L350

The current way is to start session from the C# code by altering the `UsePhp()` middleware:

```c#
app.UsePhp(
  new PhpRequestOptions {
    BeforeRequest = (ctx) => Pchp.Library.session_start(ctx),
});
```

**Comment by itpleb** [comment]
> good question;
> 
> there is no configuration to auto-start session yet
> 
> todo:
> 
> https://github.com/peachpiecompiler/peachpie/blob/6652d48ce9d1911bd80da6fd73a2ad5ba45777e6/src/Peachpie.AspNetCore.Web/RequestContextCore.cs#L350
> 
> The current way is to start session from the C# code by altering the `UsePhp()` middleware:
> 
> ```cs
> app.UsePhp(
>   new PhpRequestOptions {
>     BeforeRequest = (ctx) => Pchp.Library.session_start(ctx),
> });
> ```

thanks,it's work well.

**Comment by jakubmisek** [comment]
since `v0.9.990` following is recommended:

```c#
    class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddPhp(options =>
            {
                options.Session.AutoStart = true;
            });
```
