### ISSUE TITLE
Need to talk to an existing dll using peach pie

### ISSUE THREAD

**Issue by mordechaihorowitz** [peachpiecompiler/peachpie#757]
Is there documentation how to connect to an existing dll using peach pie.  I have not been able to find any yet

**Comment by jakubmisek** [comment]
do you mean the DLL compiled by PeachPie?

**Comment by jakubmisek** [comment]
referencing assemblies and packages are the same as in C# project
- https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
- https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2017#projectreference
- https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2017#reference

**Comment by mordechaihorowitz** [comment]
I mean an external dll while using Peach Pie.  This is my first time trying to use Peach Pie.  I have added the dll as a dependency in Peach Pie itself.  I can see it in the object browser.  The methods I need to connect to is in a Interface not a class.

**Comment by jakubmisek** [comment]
Definitely don't modify peachpie and don't compile it by yourself just to add an assembly reference.

References to PHP project are added the same way as any other C# project - `<PackageReference>`, `<ProjectReference>`, or `<Reference>`

like you can see in this example
https://github.com/iolevel/peachpie-samples/blob/aa206bd66ff33f3e5749e08aac316959d6d4c400/mvc/php-library/php-library.msbuildproj#L14
or see the links above.

or use the add reference in Visual Studio 
![image](https://user-images.githubusercontent.com/842150/82906348-67310300-9f65-11ea-8412-ecd8cd473a05.png)

**Comment by mordechaihorowitz** [comment]
I have added an assemby reference and that appears to work but I'm not sure how to access interface methods from PHP in the dll .  I can view everything in the object explorer.  I'm not sure how I would actually have the PHP code communicate with the methods in the dll.  I am not sure how to access the classes and methods now

**Comment by jakubmisek** [comment]
All the classes and interfaces are just there. Use them using PHP syntax.

```php
echo \System\DateTime::$Now;
```

**Comment by jakubmisek** [comment]
There you have a sample where classes from "UrhoSharp.dll" are used
https://github.com/iolevel/peachpie-samples/blob/master/urho-sample/main.php

**Comment by jakubmisek** [comment]
Here is a use of generic types and methods https://docs.peachpie.io/net/generics/
