### ISSUE TITLE
Waiting for intellisense to finish initializing

### ISSUE THREAD

**Issue by mordechaihorowitz** [peachpiecompiler/peachpie#759]
When creating a new project I receive the message Waiting for intellisense to finish initializing
Using Windows 10

Visual Studio 16.6.0

**Comment by jakubmisek** [comment]
This seems not related to PeachPie as we don't contribute to Visual Studio editor, IntelliSense, nor other language or project features.

Are you using the PeachPie for Visual Studio extension? (http://github.com/iolevel/peachpie-vs) 

AFAIK; I've noticed this behavior on regular C# projects, closing and reopening the code editor should (https://developercommunity.visualstudio.com/content/problem/885594/waiting-for-intellisense-to-finish-initializing-1.html)

**Comment by jakubmisek** [comment]
ok; still this is rather a Visual Studio issue. **Does closing the code editor and reopening it solve the problem?** Sadly, there is nothing we can do since PeachPie simply does not do anything with Visual Studio Editor.
