### ISSUE TITLE
PCRE pattern parse error: Invalid  unsupported or ill-formed backtracking verb 'BSR'

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#760]
following PCRE gives compile-time error:

```php
preg_match('((*BSR_ANYCRLF)(*ANYCRLF)^.*(?:\R\s+\*.*)+$)', $text);
```

```
PCRE pattern parse error: Invalid  unsupported or ill-formed backtracking verb 'BSR'
```

Seems following two backreferences should be defined:
-  (*BSR_ANYCRLF)   CR, LF, or CRLF only
-  (*BSR_UNICODE)   any Unicode newline sequence

according to https://www.pcre.org/original/doc/html/pcrepattern.html

EDIT: those are parse-time modifiers altering newline behavior

**Comment by roberthusak** [comment]
I fixed the semantics of `\R` and added support for `(*BSR_ANYCRLF)` and `(*BSR_UNICODE)`. Now I'm working on `(*ANYCRLF)` and related options.

**Comment by roberthusak** [comment]
It should work now with the latest commit of [Peachpie.Library.RegularExpressions](https://github.com/peachpiecompiler/peachpie-perlregex).
