### ISSUE TITLE
How to set/change the target .net framework when using peachpie

### ISSUE THREAD

**Issue by mordechaihorowitz** [peachpiecompiler/peachpie#762]
Thanks for your previous help.    Using peachpie currently I am getting an error HTTP Error 500.0 - ANCM In-Process Handler Load Failure.  It looks like I might be targeting the wrong framework versions.   Mine appears to need .net version 3.5  However when I check the documentation how to change it it doesn't give me the options that I see in https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2019

when I am using peachpie.  Thank you for any help.

**Comment by jakubmisek** [comment]
right, in Visual Studio, there is no property page with framework selection.

you have to edit project manually:

![image](https://user-images.githubusercontent.com/842150/83519237-e5e4ed80-a4db-11ea-8bc3-5c81e301aff9.png)

![image](https://user-images.githubusercontent.com/842150/83519259-f1d0af80-a4db-11ea-9dbf-895a1b660ea9.png)

**Comment by jakubmisek** [comment]
Note, you cannot build your project for `net35`, .NET Framework 4.7.2 is the minimum requirement, or .NET Core 3.0

Also "error HTTP Error 500.0 - ANCM In-Process Handler Load Failure" might have tons of causes, suggesting to get the log file and check what is the real issue - it might be an exception during program startup, or a missing aspnet core runtime or its dependency
