### ISSUE TITLE
Feature Request:  DOMNode::C14N() support

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#772]
Feature Request:  DOMNode::C14N() support

If necessary, we can provide a simple test case and extensive testing.

**Comment by kripper** [comment]
Implemented here: https://github.com/kripper/peachpie/commit/79c054f89a7e96e4430bd3a5ee2685aeeddf3e85

**Comment by jakubmisek** [comment]
thanks, can we have a pull request for this? without the other changes and reverted changes

**Comment by kripper** [comment]
Here: https://github.com/peachpiecompiler/peachpie/pull/783
