### ISSUE TITLE
chr(161) == chr(160)

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#775]
```php
echo chr(161) == chr(160); // Should return false
```

**Comment by kripper** [comment]
More tests:

```
$ansi = "á"; // Source code is in ISO-8859-1 encoding (!)

$f = fopen("test.txt", 'w');
fwrite($f, $ansi);	// Writes chr(160) as expected.
fclose($f);

echo ord($ansi); // Returns 225! Shuld be 160.

echo "á" == chr(160); // Returns false
```

**Comment by kripper** [comment]
See: https://github.com/peachpiecompiler/peachpie/issues/780

**Comment by jakubmisek** [comment]
seems string comparison always converts single-byte strings to Unicode representation, causing similar issues

**Comment by jakubmisek** [comment]
the test case works for me (returns false as expected)

closing

**Comment by kripper** [comment]
Is this test correct?
https://github.com/peachpiecompiler/peachpie/commit/b44f92aa796472c24a9b684c7bfde0d9ccca4c1b

Shouldn't it be the opposite?
`echo chr(161) == chr(160) ? "161 = 160 fail" : "ok", PHP_EOL;`

**Comment by jakubmisek** [comment]
@kripper oh you're right! thanks

**Comment by jakubmisek** [comment]
Lets continue in #910
