### ISSUE TITLE
Encoding Compatibility Mode (discussion about PeachPie's Unicode semantic)

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#780]
I have been chasing compatibility problems related with encodings recently, and finally came across [this document](https://docs.peachpie.io/php/unicode) explaining that this problems are by design probably because of performance reasons.

I'm a bit worried about this design because it will break compatibility with PHP applications that operate with external data (databases, files, network resources, etc) or deal with encodings.

Maybe Peachpie could have a setting to enable an "encoding compatibility mode"?
Maybe enabled by default to improve compatibility over performance?
Or maybe enabled automatically if the compiler detects references to encoding functions (chr, ord, utf8_*code, etc)?

I created this issue to link here other encoding related issues and discuss what could be the best solution.

**Comment by jakubmisek** [comment]
basically strings that are already as `System.String` (UTF16 encoded) are kept in Unicode (conversion to UTF8, or encoding **from** any encoding does not make any sense, so it is kept without allocating and decoding anything)

General rule is, when a PHP function specifically outputs string in a specific non-Unicode encoding, it should result in `PhpString` (byte array). So functions like `utf8_decode` should output byte array, `utf8_encode` should output `System.String` and moreover it may keep the original string if it was already in Unicode.

**Comment by kripper** [comment]
Well, it's not exactly what Zend's PHP does, but I think it could work.
I reverted [my utf8_encode() "fix"](https://github.com/peachpiecompiler/peachpie/pull/777) and will try to adopt this design.

Now, I have the following question:s

```
// Let's say we receive an ISO-8859-1 string from an external source (DB, file, etc)
$ansi = (binary)chr(225); // chr(225) = 'á'

// And we need to output XML encoded in ISO-8859-1
$xml = <<<XML
<?xml version="1.0" encoding="ISO-8859-1"?>
<test>
	<str>$ansi</str>
</test>
XML;

$x = new DomDocument();
$x->loadXML($xml);

echo "1) Should return 'á' in UTF-8:\n";
echo $x->getElementsByTagName("str")->item(0)->nodeValue;
echo "\n\n";

echo "2) saveXML(element) always returns UTF-8, so we should see 'á' in UTF-8:\n";
echo $x->saveXML($x->documentElement);
echo "\n\n";

echo "3) saveXML() always returns XML in the encoding defined by the XML header tag, so we should see 'á' in ISO-8859-1:\n";
echo $x->saveXML();
echo "\n\n";

echo "4) Should return 'á' in UTF-8:\n";
echo utf8_encode($ansi);
echo "\n\n";
```

Peachpie fails all tests.
Since $ansi is binary, are all this assumptions correct?

How can we generate a ISO-8859-1 XML file with Peachpie?

**Comment by kripper** [comment]
After https://github.com/peachpiecompiler/peachpie/commit/e20ac99456511a47401bf2c7b7dce1291f2e3490 test 4 is working now.

**Comment by jakubmisek** [comment]
The test case is actually one issue - that `DomDocument::loadXml()` converts input string to Unicode before it parses the XML declaration.

**Comment by kripper** [comment]
Is there any workarround to correctly load an ISO-8859-1 XML in Peachpie?
I tried casting with `(binary)` but it doesn't work.

**Comment by jakubmisek** [comment]
so we are now at https://github.com/peachpiecompiler/peachpie/issues/797

**Comment by kripper** [comment]
Since we needed to use Peachpie to process input and output data from different sources (files, external databases, source code. etc) in different text encodings, we noticed that Peachpie [is designed](https://docs.peachpie.io/php/unicode/) to support strings in 1) one specific text encoding or 2) binary data.

Peachpie has some other limitations. For example, array keys must be compatible with the selected text encoding or [will get corrupted](https://github.com/peachpiecompiler/peachpie/issues/802). Arrays with binary keys will not be supported by design, so scripts that use arrays to map binary keys (e.g. binary encoders) will probably not work with Peachpie.

One solution (workaround) to be able to work with data (XML, JSON, text, source code, etc) in other encodings, was to add an auxiliary method to change the encoding used internally for strings:

```
public static void peachpie_set_string_encoding(string str) {
	Console.OutputEncoding = Encoding.GetEncoding(str);
}
```

In case of Peachpie console applications for Windows, one could also use the `@chpc` command to set the encoding used for strings, but since the application would output incorrect results without setting the correct encoding, we preferred to set it explicitly from inside our application.

Now, even when this workaround makes it possible to work with other encodings, it will probably still be necessary to review the whole application to check that no other encodings are used internally since this would probably lead to data corruption.

**Comment by jakubmisek** [comment]
Or you can just change the `Context.StringEncoding` (https://docs.peachpie.io/api/ref/context/#properties) as noted in one of those Unicode issues

**Comment by kripper** [comment]
> Or you can just change the `Context.StringEncoding` (https://docs.peachpie.io/api/ref/context/#properties) as noted in one of those Unicode issues

How can you set the `Context.StringEncoding` directly from PHP?

**Comment by kripper** [comment]
I think `Context.StringEncoding` was a readonly getter returning `Console.OutputEncoding`.

**Comment by jakubmisek** [comment]
It depends on what kind of application you are targeting. Executable, library, web application, executable drove from a C# executable?

Currently, StringEncoding is read-only because nobody needed to modify it yet. Although Console and Context should have both the same encoding, otherwise `echo` and other outputting constructs will get corrupted text. Also changing context encoding after the app starts is a bad idea, because some strings may be already encoded using the previous encoding ...

**Comment by kripper** [comment]
Right. It would be ideal to set the encoding before initialization starts, but we didn't experience issues, probably because initialized strings are compatible with our encoding (ISO-8859-1).

We wrote a windows console app.

**Comment by jakubmisek** [comment]
I suppose we might introduce support to `appsettings.json` file. Because currently there is no way configuring selfconytained executable php app

**Comment by kripper** [comment]
This .json file needs to be deployed together with the .exe file right?
I can also perfectly imagine a use case where you will need to set the encoding during runtime or e.g. you need to process data in more than one encoding (change the encoding).
What happens if Peachpie operates strings in different encodings? For example, `echo $utf8 . $latin;` ?

**Comment by jakubmisek** [comment]
in case Context.StringEncoding != Console.OutputEncoding, you will see corrupted text.

**Comment by NolikTop** [comment]
> I suppose we might introduce support to `appsettings.json` file. Because currently there is no way configuring selfcontained executable php app

when will it be?

**Comment by kripper** [comment]
> > I suppose we might introduce support to `appsettings.json` file. Because currently there is no way configuring selfcontained executable php app
> 
> when will it be?

What's your use case or requirement. Maybe I can share my experience dealing with different encodings.

**Comment by NolikTop** [comment]
> > > I suppose we might introduce support to `appsettings.json` file. Because currently there is no way configuring selfcontained executable php app
> > 
> > 
> > when will it be?
> 
> What's your use case or requirement. Maybe I can share my experience dealing with different encodings.

i have php-cli app which works with lots of binary strings. I wanna run it on peachpie to speed it up but because of encoding my application fails on run. I use Linux so i cant use something like ```@chpc``` to set encoding.

**Comment by kripper** [comment]
PeachPie can deal with binary strings, but has problems dealing with different encodings.
I managed to do it with some hacks.
Please try to be very specific with the problems your are having and provide a minimal test case.

**Comment by jakubmisek** [comment]
Basically, PeachPie respects single-byte strings but whenever it decides to convert them to Unicode string (array key, console output, a Unicode library function), it uses the "Encoding" which cannot be configured in a nice way yet.

In the case of a CLI application, the "Encoding" PeachPie uses for such conversions is [Console.OutputEncoding](https://docs.microsoft.com/en-us/dotnet/api/system.console.outputencoding?view=net-5.0).

Changing the console output encoding effectively changes the "Encoding".
