### ISSUE TITLE
error on activate after install elementor plugin

### ISSUE THREAD

**Issue by mammadkoma** [peachpiecompiler/peachpie#787]
hi
I have the peachpie-wordpress project getting from github and installed xampp 3.2.4 and add its php folder to the path environment variables (php 7.4.7). after create a database on php myadmin and start the project , I installed wordpress wizard correctly. Now I want to install the latest version of Elementor , it installed but after active , it get error : 

**=' ) ) { add_action( 'admin_notices', 'elementor_fail_php_version' ); } elseif ( ! version_compare( get_bloginfo( 'version' ), '5.0', '>=' ) ) { add_action( 'admin_notices', 'elementor_fail_wp_version' ); } else { require ELEMENTOR_PATH . 'includes/plugin.php'; } /** * Load Elementor textdomain. * * Load gettext translate for Elementor text domain. * * @since 1.0.0 * * @return void */ function elementor_load_plugin_textdomain() { load_plugin_textdomain( 'elementor' ); } /** * Elementor admin notice for minimum PHP version. * * Warning when the site doesn't have the minimum required PHP version. * * @since 1.0.0 * * @return void */ function elementor_fail_php_version() { /* translators: %s: PHP version */ $message = sprintf( esc_html__( 'Elementor requires PHP version %s+, plugin is currently NOT RUNNING.', 'elementor' ), '5.6' ); $html_message = sprintf( '', wpautop( $message ) ); echo wp_kses_post( $html_message ); } /** * Elementor admin notice for minimum WordPress version. * * Warning when the site doesn't have the minimum required WordPress version. * * @since 1.5.0 * * @return void */ function elementor_fail_wp_version() { /* translators: %s: WordPress version */ $message = sprintf( esc_html__( 'Elementor requires WordPress version %s+. Because you are using an earlier version, the plugin is currently NOT RUNNING.', 'elementor' ), '5.0' ); $html_message = sprintf( '', wpautop( $message ) ); echo wp_kses_post( $html_message ); }**

How we can active Elementor plugin?

**Comment by jakubmisek** [comment]
You definitely don't need to install xampp or PHP, which is the whole point of PeachPie.

How do you install the plugins? Plugins and themes must be compiled; most of them are already available and can be added as you are used to. Additionally, they can be added during development (https://docs.peachpie.io/scenarios/wordpress/add-plugin-theme/) or from sources (https://docs.peachpie.io/scenarios/wordpress/build-php-plugin/).

**Comment by mammadkoma** [comment]
I get error without start xampp for mysql:
![image](https://user-images.githubusercontent.com/17564001/87340493-624c0100-c55d-11ea-8a02-dd0671e00637.png)
I install plugin regularly in wordpress menus : Plugins > Add New :
![image](https://user-images.githubusercontent.com/17564001/87340774-c969b580-c55d-11ea-9e52-af7c764c1fd5.png)

**Comment by jakubmisek** [comment]
I see, so you use xampp for its MySql server.

The screenshot is weird, it looks like a regular WordPress, but peachpie-wordpress has a slightly different layout:
![image](https://user-images.githubusercontent.com/842150/87350592-6590be00-c558-11ea-87bb-677a227d0442.png)

How did you get the WooCommerce there?

**Comment by mammadkoma** [comment]
hi
based on your first link , I added a nuget source to VS 2019
![image](https://user-images.githubusercontent.com/17564001/87697384-4471dc80-c7a7-11ea-9dd2-7f8d07ccc7d6.png)
then right click on app and select manage nuget packaes:
![image](https://user-images.githubusercontent.com/17564001/87697572-7be08900-c7a7-11ea-91ee-4f9325145b2c.png)
select elementor then click install but get error : Package 'elementor 2.9.13' has a package type 'wpdotnet-plugins 0.9.960.0' that is not supported by project 'app'.
![image](https://user-images.githubusercontent.com/17564001/87697843-e98cb500-c7a7-11ea-949a-44b08cac193a.png)
How we can install pluggins? Could you give us a video link?

**Comment by jakubmisek** [comment]
A video is good idea. The empty page might be caused by mismatching versions, current version is `990` and the plugin is `960` (since we are in development, version are usually not backward compatible)

**Comment by mammadkoma** [comment]
what should we do for mismatching versions and install elementor?

**Comment by jakubmisek** [comment]
You either use the WordPress dashboard OR you install the dependency into your project file. You don't have to do both.

- WordPress dashboard supposes to work.

- Or the following command should work:
```
dotnet add package elementor -v 2.9.12-beta0990
```

Seems there are some issues with the Visual Studio Nuget package manager.
