### ISSUE TITLE
error sprintf($echo, $delay, $url);

### ISSUE THREAD

**Issue by itpleb** [peachpiecompiler/peachpie#790]
```php
<?php

function f()
{
    $echo = '<html>' .
            '<head>' .
            '<meta http-equiv="refresh" content="%d;url=%s"/>' .
            '</head>' .
            '</html>';

    $echo = sprintf($echo, 0, "www.example.org");
}

f();
```
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”

**Comment by jakubmisek** [comment]
thank you @itpleb , I have just slightly minified the test code. Will try to fix this.
