### ISSUE TITLE
SimpleXMLElement::addAttribute results differs between (standard) PHP and PeachPie if nameSpace = null is used

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#792]
The following call (in our code)

`	$Amt->InstdAmt->addAttribute ('Ccy', $PaymentInfo['CURRENCY']);           `     

results in 

```
PHP: <InstdAmt Ccy="EUR">120.30</InstdAmt>

PeachPie: <InstdAmt p6:Ccy="EUR" xmlns:p6="urn:iso:std:iso:20022:tech:xsd:pain.008.003.02">120.30</InstdAmt>
```
While in general the XML format might be okay, we have a problem with the recipient of the XMLs as they don't accept those XMLs anymore

I suggest that the following code in Peachpie.Library.XmlDom/SimpleXml.cs

```
public void addAttribute(string qualifiedName, string value, string namespaceUri = null)
        {
            try
            {
                if (namespaceUri == null) namespaceUri = iterationNamespace.namespaceUri;// this.namespaceUri;
                XmlAttribute attr = XmlElement.OwnerDocument.CreateAttribute(qualifiedName, namespaceUri);

```

should be changed to 

```
            try
            {
                XmlAttribute attr;

                if (namespaceUri == null) 
                {
                    attr = XmlElement.OwnerDocument.CreateAttribute(qualifiedName);
                } else {
                    attr = XmlElement.OwnerDocument.CreateAttribute(qualifiedName, namespaceUri);
                }

```

or as one line

```
                XmlAttribute attr = (namespaceUri == null 
                    ? XmlElement.OwnerDocument.CreateAttribute(qualifiedName) 
                    : XmlElement.OwnerDocument.CreateAttribute(qualifiedName, namespaceUri));

```
as this reflects the intention of the caller to not supply a name space.

**Comment by jakubmisek** [comment]
thanks for the issue @jan-ai , and for the fix. Makes sense.

Did you test the code? A pull request would be great since it would run the automated tests, automatically :)

**Comment by jakubmisek** [comment]
If you'd have a standalone test case, I'd be happy to include it.

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/a4b1261fe591df6e318818c7753cd252c441854d

**Comment by jan-ai** [comment]
After setting up everything to compile PeachPie instead of just using the nuget packages, I can confirm that the changes fixed the problem for us.

**Comment by jakubmisek** [comment]
@jan-ai you can use the latest version of PeachPie from NuGet feed at https://ci.appveyor.com/nuget/peachpie
