### ISSUE TITLE
gzencode() giving different result

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#793]
`base64_encode(gzencode(chr(128)));` returns different results.

Peachpie returns: `H4sIAAAAAAAAA2sAAKWg+9gBAAAA`

PHP (Zend) returns: `H4sIAAAAAAAAA2sAAK1suj8BAAAA`

See: https://sandbox.onlinephpfunctions.com/code/5f53d69205911db787be71bb61d036b9e01e09ee

**Comment by kripper** [comment]
Only the CRC bytes are different, which are computed in zlib.cs [1]:

```
                    byte[] crc = new PhpHash.HashPhpResource.CRC32().ComputeHash(data);

                    output[output_length - 8] = crc[0];
                    output[output_length - 7] = crc[1];
                    output[output_length - 6] = crc[2];
                    output[output_length - 5] = crc[3];
```

[1] : https://github.com/peachpiecompiler/peachpie/blob/9126794f52e41238b03988c0899b510ef9924d3d/src/Peachpie.Library/zlib.cs

**Comment by kripper** [comment]
The problem is in crc32., because `crc32(chr(128))` is also giving a different result.

**Comment by kripper** [comment]
Fixed here: https://github.com/kripper/peachpie/commit/b0bb4727c47f7b7f32b6d8eb8023ad66785ffdcd

**Comment by jakubmisek** [comment]
thanks! I see, maybe we'll take a look at the code first and remove all the unnecessary allocations.

**Comment by jakubmisek** [comment]
Can we used this package https://www.nuget.org/packages/Crc32.NET/ ?

**Comment by kripper** [comment]
Yes, looks good.

**Comment by jakubmisek** [comment]
I just realized, PeachPie has it already implemented in the `CRC32B` class.

**Comment by jakubmisek** [comment]
also there is `OS_CODE` constant, which differs in various PHP version.

https://github.com/peachpiecompiler/peachpie/blob/a44ccc3c93a61fd2e6c38ed3adee66dd3bfc32d6/src/Peachpie.Library/zlib.cs#L680

It used to be `0x3`, newer PHP versions use `0xA`
