### ISSUE TITLE
openssl_encrypt() returns different result

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#794]
Peachpie and Zend return different results for openssl_encrypt().
Here is a test case:

```
	$key = '123';
	$iv = '0123456789ABCDEF';
	$tmp = chr(128);
	$tmp = openssl_encrypt($tmp, 'AES-128-CBC', $key, $options=OPENSSL_RAW_DATA, $iv);
	die(base64_encode($tmp));
```

**Comment by kripper** [comment]
When using `$tmp = 'Hello';` instead of `$tmp = chr(128)` it works fine, so it may be related with Unicode/binary encoding problems.

**Comment by kripper** [comment]
Fixed here: https://github.com/kripper/peachpie/commit/615d1ff0bfb3e0b1bcbec681d0ef05896cf8f9d2

**Comment by kripper** [comment]
This issue was similar to https://github.com/peachpiecompiler/peachpie/commit/ce3b9a671df18a00c4fe0c9b7441a94a1da2e9ab
Should we maybe check and fix similar issues for all functions?

**Comment by jakubmisek** [comment]
thanks for the issue, the fix would be much simpler - `openssl_encrypt` should accept first argument of type `byte[]` instead of `string`.

**Comment by kripper** [comment]
I think I tried this before, and it wasn't working.

**Comment by kripper** [comment]
Works.
Plase also note that openssl_decrypt() must also be fixed.
See: https://github.com/kripper/peachpie/commit/a91bbd69959e230b7b82efe656f2a61a1195674d

**Comment by jakubmisek** [comment]
from what I see, `openssl_decrypt` does not corrupt the input single-byte string (`PhpString data`), do you have a test case?
