### ISSUE TITLE
saveXML() doesn't output self-closed tags

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#799]
Peachpie saveXML() outputs `<a></a>` while Zend's PHP generates `<a/>` (self-closed tags for empty tags).

Test code:

```
$xml = <<<EOB
<?xml version="1.0" encoding="ISO-8859-1"?>
<test>
	<a></a>
</test>
EOB;

$doc = new DomDocument();
$doc->loadXML($xml);
die($doc->saveXML());
```

**Comment by jakubmisek** [comment]
duplicate to https://github.com/peachpiecompiler/peachpie/issues/651

**Comment by DRSDavidSoft** [comment]
@kripper Interesting, as you've said, this issue with `saveXML()` is in opposite to the `saveHTML()` that I was having in our project.

**Comment by kripper** [comment]
@DRSDavidSoft indeed. Maybe Microsoft changed the default behavior in newer versions. Actually, I saw comments saying that by default .NET was writing self-closing tags, while I was getting the opposite. Can you please confirm if you get different results with saveXML and saveHTML?

**Comment by DRSDavidSoft** [comment]
@kripper Definitely.

Using your [test case](https://github.com/peachpiecompiler/peachpie/issues/799#issue-664143696):

### PHP
```
// $doc->saveXML():

<?xml version="1.0" encoding="ISO-8859-1"?>
<test>
        <a/>
</test>

// $doc->saveHTML():

<test>
        <a></a>
</test>
```

### Peach Pie
```
// $doc->saveXML():

<?xml version="1.0" encoding="ISO-8859-1"?>
<test>
        <a></a>
</test>

// $doc->saveHTML():

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">

<test>
        <a></a>
</test>
```

I'm not sure regarding .NET's default behavior, but in this case, the following issues are apparent:

- Feeding `<a></a>` as input:

    |              | php          | Peach Pie |
    | ------------ | ------------ | --------- |
    | `saveXML()`  | self-closing | empty tag |
    | `saveHTML()` | empty tag    | empty tag |

   It's clear that `saveXML()` **should** result in self-closing tags in Peach Pie, the same as it does in php.

- Also, regarding DTD, the `saveXML()` implementation is correctly outputting the XML declaration, while Peach Pie's `saveHTML()` is returning this DTS when Zend's PHP is not:

    ```HTML
    <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
    ```

Unfortunately, I lack the time to dig further into this rn, but I'm looking forward to see this issue getting fixed. 
 Previously, [there were](https://github.com/peachpiecompiler/peachpie/issues?q=author%3ADRSDavidSoft+DOMDocument) some inconsistencies between the DOM implementation in PHP and Peach Pie, and it seems that there is still some effort required before the method calls for DOM are completely consistent and match each other.

@jakubmisek I'd like to suggest re-opening this issue, as while it is related to #651 by extension, it's also a separate one by itself, that may need some additional work.

**Comment by kripper** [comment]
Thanks. Your results are consistent with mines.
I believe https://github.com/peachpiecompiler/peachpie/issues/651 is confusing and should be edited:
- The second issue should make clear that `<i class="icon i7"></i>` (empty tag) is being returned **in Peachpie** using **saveXML()** and **is wrong**.
- https://github.com/peachpiecompiler/peachpie/issues/651#issuecomment-581145896 shuld be checked, because it says that Peachpie always returns self-closing tags (wrong) and that PHP **always** returns full-closing tags (wrong, it depends).

**Comment by DRSDavidSoft** [comment]
@kripper I edited #651 according to this.  Hopefully, it'll be sufficiently clear now.

**Comment by kripper** [comment]
Ok, but issue 2 still says "With saveHTML(), elements such as ... (empty tags) are automatically returned as **self-closing tags**" and according to your https://github.com/peachpiecompiler/peachpie/issues/799#issuecomment-663201186 Peachpie is returning empty tags.
Is it a issue with the issue :-) or was Peachpie really returning self-closing tags in a previous version?

**Comment by DRSDavidSoft** [comment]
@kripper I think it's an issue with what is being loaded, since this is actually the correct behavior:

|              | php          | Peach Pie |
| ------------ | ------------ | --------- |
| `saveHTML()` | empty tag    | empty tag |

(i.e. `<i class="icon i7"></i>` correctly results in `<i class="icon i7"></i>`)

However, in #651 I was getting the erroneous result, i.e. `<i class="icon i7" />`.

Please see my test runs:

### Test 1
```php
<?php

$html = <<<EOB
<div>
	<i class="icon i7" />
</div>
EOB;

$doc = new DomDocument();
$doc->loadHTML($html);

echo '// $doc->saveXML():' . "\n\n";
echo $doc->saveXML();

echo "\n" . str_repeat('=', 25) . "\n\n";

echo '// $doc->saveHTML():' . "\n\n";
echo $doc->saveHTML();

exit;
```

#### Results:
```
C:\Users\David\AppData\Local\Temp\peachpie-test1
λ php program.php
// $doc->saveXML():

<?xml version="1.0" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div>
        <i class="icon i7"/>
</div></body></html>

=========================

// $doc->saveHTML():

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div>
        <i class="icon i7"></i>
</div></body></html>

C:\Users\David\AppData\Local\Temp\peachpie-test1
λ dotnet run
// $doc->saveXML():

<?xml version="1.0" encoding="Codepage - 437"?><div>
        <i class="icon i7" />
</div>
=========================

// $doc->saveHTML():

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<div>
        <i class="icon i7" />
</div>
```

### Test 2
```php
<?php

$xml = <<<EOB
<?xml version="1.0" encoding="ISO-8859-1"?>
<test>
	<a></a>
</test>
EOB;

$doc = new DomDocument();
$doc->loadXML($xml);

echo '// $doc->saveXML():' . "\n\n";
echo $doc->saveXML();

echo "\n" . str_repeat('=', 25) . "\n\n";

echo '// $doc->saveHTML():' . "\n\n";
echo $doc->saveHTML();

exit;
```

#### Results:
```
C:\Users\David\AppData\Local\Temp\peachpie-test1
λ php program.php
// $doc->saveXML():

<?xml version="1.0" encoding="ISO-8859-1"?>
<test>
        <a/>
</test>

=========================

// $doc->saveHTML():

<test>
        <a></a>
</test>

C:\Users\David\AppData\Local\Temp\peachpie-test1
λ dotnet run
// $doc->saveXML():

<?xml version="1.0" encoding="ISO-8859-1"?>
<test>
        <a></a>
</test>

=========================

// $doc->saveHTML():

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">

<test>
        <a></a>
</test>
```

I think you can see the pattern now:

| Test Case No. |                        | php          | Peach Pie    | Verdict                |
| ------------: | ---------------------- | ------------ | ------------ | ---------------------- |
|             1 | HTML with  `saveXML()` | self-closing | self-closing | ✔ Correct behavior    |
|             1 | HTML with `saveHTML()` | empty tag    | self-closing | ❌ Unexpected behavior |
|             2 |  XML with  `saveXML()` | self-closing | empty tag    | ❌ Unexpected behavior |
|             2 |  XML with `saveHTML()` | empty tag    | empty tag    | ✔ Correct behavior    |

In **Peach Pie**, all documents loaded in XML will result in **empty tags** (wrong), while all documents loaded in HTML will result in **self-closing tag** (also wrong).

The correct implementation (consistent to PHP), is it _depends_, as you've said.  It should always return **empty tags** for `saveHTML()`, and always return **self-closing tags** for `saveXML()`.

Hopefully, this is now super clear :)

**Comment by kripper** [comment]
Cool. You confirmed my guess:
Peachpie is loading the XML/HTML and conserving the original `XmlNode.isEmpty` attributes, ie. Peachpie writes the output in the same way it parsed the input, while Zend's PHP is changing this attribute depending on the function and libxml options.
