### ISSUE TITLE
call_user_func() fails when function is defined in referenced library

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#801]
`call_user_func(MyFunc, NULL)` fails to return a value when `MyFunc()` is defined in a referenced library.

Works fine if `MyFunc()` is defined in the same project.

Here is a simple test-case (only 2 lines of code) with .msbuildproj files:
[peachpie-bug.zip](https://github.com/peachpiecompiler/peachpie/files/4970039/peachpie-bug.zip)

Expected result: output should be 'test'

**Comment by kripper** [comment]
I consider this issue of low prio and probably complex to solve. I just wanted to comment and provide an atomic test case to avoid struggling again in the future with similar issues.

**Comment by jakubmisek** [comment]
should be working, let me check it. Thank you for the test case

**Comment by jakubmisek** [comment]
You haven't included the `"lib/library.php"` script.

Also `MyFunc` is not a string, it should be `call_user_func("MyFunc", NULL)`

**Comment by kripper** [comment]
Confirmed. Thanks!

It's a little confusing that:
1. `call_user_func("MyFunc", NULL)` just returns NULL without throwing an error when the script is not included.
2. functions defined in referenced libraries can be called without including the script, but they need to be included to call them with `call_user_func()`
