### ISSUE TITLE
iconv adds a tab character when converting characters

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#803]
When using iconv an string like _**Kündigung**_ results in _**K"u\tndigung**_ (while \t is just to show the tab character here; it's coded as 0009). 

expected behaviour: the string should be converted to _**K"undigung**_ (without the tab character)

Also I would be great to have a culture related conversion, which would lead to **_Kuendigung_** in this case.

**Comment by jan-ai** [comment]
I tried to create a pull request or push the necessary changes to a new branch, but without success (403 - forbidden). 

So here is the fix that should be applied in src\Peachpie.Library\iconv.cs line 264

`
                           str = line.Substring(t1 + 1, t2 - t1 - 1);
`

**Comment by jakubmisek** [comment]
I think you have to fork the project and make the changes in your fork. Anyways; I'll apply the fix and try to create a test case for it. Thank you!
