### ISSUE TITLE
Update Themes - Checksum Mismatch

### ISSUE THREAD

**Issue by user905** [peachpiecompiler/peachpie#805]
Receiving the following error when updating themes:

> Updating Theme Coming Soon Lite (1/3)
> Downloading update from https://downloads.wordpress.org/theme/coming-soon-lite.0.2.2.zip…

> An error occurred while updating Coming Soon Lite: Download failed. The checksum of the file (fdd8e8058dc886895cfce8e0f0203c43) does not match the expected checksum value (fdd8e8058dc886895cfce8e0f0203c43).

Happens for any theme I try to update. Not sure this is WP-specific, or PeachPie. Please advise.

**Comment by jakubmisek** [comment]
thank for the issue,  it seems like a duplicate issue to https://github.com/iolevel/wpdotnet-sdk/issues/79

In general this is handled by the https://github.com/iolevel/wpdotnet-sdk/ project, and probably updating is not yet handled well.
