### ISSUE TITLE
CodePage ignored

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#807]
We are trying Peachpie with an external project with sources encoded in iso-8859-1.
The PHP application outputs files by concatenating strings defined in the source code with binary chars.

Example:
$output = 'áéíóú' . chr(128);

We added `<CodePage>iso-8859-1</CodePage>` to the .msbuildproj file, but the original encoding is not respected (or maybe Peachpie is doing some other conversions).

Any way, the output is not as expected.

We attached a sample project.
[encoding-test.zip](https://github.com/peachpiecompiler/peachpie/files/5081398/encoding-test.zip)

**Comment by jakubmisek** [comment]
And what is expected output?

**Comment by jakubmisek** [comment]
`CodePage` works as expected - in this case, it is even detected by the compiler and it does not have to be specified using `<CodePage>` at all. The string literal `'áéíóú'` is stored as Unicode string. 

Your test and the issue differ, so not sure what's the problem here; either `md5` function or string concatenation?

**Comment by kripper** [comment]
The value of md5( ) doesn't change even when you change the CodePage.
So how do you generate Esc/Pos output for a printer in iso-8859-1 with Peachpie?
In Zend's PHP you would simply do `echo "á" . chr(225);` and the output would be `chr(225) . chr(225)`.

**Comment by kripper** [comment]
How can I get Peachpie generate iso-8859-1 output correctly having the following source code:
`echo "País";`

(expected output is `País` in iso-8859-1)

**Comment by kripper** [comment]
Should we change Context.StringEncoding?
Is there any way to change Context.StringEncoding from the PHP source?

**Comment by jakubmisek** [comment]
In Zend you simply do `echo "á";` and you never know what happens .. I'm glad I don't see such code in any framework we're testing. That's just wrong on so many levels, and we just don't handle that by purpose.

Anyways; the string literal `"áéíóú"` is encoded into Unicode string as you see it. Output is also in Unicode, so there is no conversion. The string won't get messed up.

`md5()` expect a byte array, so PeachPie decodes that Unicode string (UTF-16) into `byte[]` using [`Context.StringEncoding`](https://docs.peachpie.io/php/unicode/#stringencoding).

**Comment by jakubmisek** [comment]
`Context.StringEncoding` is set by you. In ASP.NET Core using configuration (https://docs.peachpie.io/net/hosting/aspnetcore/#configuration). In console app, it is set to the encoding of your terminal (mostly local code page, and it does not make much sense, but there is no configuration for that yet)

**Comment by jakubmisek** [comment]
`<CodePage>` is not ignored, and works as expected. We might start a new issue on how to configure internal Unicode<->byte[] conversions, which is not handled using `Context.StringEncoding`.

**Comment by kripper** [comment]
Thanks. I managed to change Context.StringEncoding by changing the console charset with command `@chcp 852`, and md5( ) is now treating the source code correctly (as iso-8859-1). I must say that **it is very counterintuitive that changing the console code page has an effect on how the source code or variables are treated internally**. IMO this is a bug or a serious problem with Peachpie's design.

> In Zend you simply do echo "á"; and you never know what happens 

That's not correct. PHP respects the original encoding. When you do `echo "á"` or `echo chr(225) ` it outputs exactly that without doing any conversion. **If you change the charset of your console, this has no effect in how PHP processes strings or writes to files. It only has an effect in how the output is presented in the console**.

> I'm glad I don't see such code in any framework we're testing

That's because you are not yet testing PHP applications that are receiving binary input, generating binary output or dealing with different text encodings.
Believe me it's a nightmare and you will probably feel frustrated when you notice someday that we have [a design problem here](https://docs.peachpie.io/php/unicode/) and that at some point a lot of code will have to be rewritten and retested if we want to make Peachpie really a PHP compatible compiler.

I would really suggest to reevaluate the design, because I'm sure there are better options that don't involve doing more conversions nor sacrificing performance, since Peachpie is currently doing a lot of unnecessary encoding conversions internally and even corrupting data when it doesn't fit into Unicode.

Besides that, Peachpie is a masterpiece.

**Comment by jakubmisek** [comment]
But do you realize, `á` is not always the value of 225? ... if you want 225, write 225, not 'á'. One day, your teammate or a contributor opens the file in his text editor and he saves the file in his encoding. The commit and the pull request will look the same, but you'll be screwed up.

I agree it is different in PeachPie, and a few features are not designed well yet. Sadly, we have to be compatible as much as possible while reasonably interoperable with .NET and reasonably efficient.

**Comment by kripper** [comment]
Yes, it is important to keep the encoding of source files. This has never been an issue.

The sources consist of thousand of lines like `echo "País" . $binaryCode . "África"` which are shared with other systems running on Zend. Compatibility with Zend is important.

Replacing all international characters by `chr(x)` would be insane. Maintainability and readability of the sources is also important.

You will see this use cases with the majority of applications that generate binary output.

BTW, we solved the problem with a hack by setting Console.OutputEncoding from PHP, so the application won't crash if somebody runs it from a console with other code page.

Actually, when running inside the visual code debugger, it was crashing because the debugger was probably using a different code page than inside a console.

Whatever is the design, I'm 100% sure that the console code page (Context.StringEncoding) should have no effect on the way strings are processed internally. If your app reads, processes and writes binary files, the console code page must have no effect here.

To port our code, we are introducing hundred of hacks and executing alternative code when Peachpie is detected. The biggest problem is the insane enormous time involved in debugging, comparing results and fixing this unpredictable incompatibilities. At this point, we have no option to go back because of deadlines, but **we consider Peachpie to be binary incompatible with PHP and strongly discourage anybody to use Peachpie if his application is working with binary strings or with other encodings outside Unicode or UTF-8**.

**Comment by jakubmisek** [comment]
Yes, as I mentioned before, console code page was taken as the internal encoding for no good reason, we're focusing on ASP.NET Core primarily.

Anyways; depending on your source code encoding is insane :) but that's where PHP and .NET developers differ. Logic, data, and design should not be mixed up, and that's also what PeachPie enforces to do - mostly in order to work properly on .NET with Unicode and it's underlaying runtime, also because of mature frameworks are well designed and it's not an issue with them.

**Comment by kripper** [comment]
Well...yes, **maybe** the original PHP design should't respect the original source code encoding and force developers to use UTF-8 for the source code all the time. I remember not all libraries and editors were supporting UTF-8 back at that time. **Maybe** we should also break backwards compatibility and force developers to migrate all their code to UTF-8 (personally I wouldn't do it because I'm pragmatical and time is precious) and then rewrite their code from `echo "País ${binaryCode} África"` to `echo encode_to("iso-88591-1", "País") . $binaryCode . encode_to("iso-88591-1", "África")` where those string literals in the source code would be "encoding agnostic" or use a fixed encoding like Unicode or UTF-8. **Maybe** this is all acceptable even when this "good .NET practices" go against PHP's simplicity or break compatibility with long working stable PHP applications. I guess this can all be considered subjective. That's why I was thinking in adding a [PHP encoding compatibility flag](https://github.com/peachpiecompiler/peachpie/issues/780) to avoid developers have to adapt their source code in order to migrate to Peachpie.

It seems we both agree that Code Page and Context.StingEncoding (or Context _ctx) should not be considered in many of the current PHP function implementations in Peachpie. Maybe a good **starting point** is to search and remove all this references and rewrite the related code. The sooner, the better, because this is a structural change.

I guess a rule of thumb is: **if you are not reading/writing from/to Console/ASP.NET Response Object, then don't encode/decode strings nor reference Context.StringEncoding at all.**

**Comment by jakubmisek** [comment]
No, you shouldn't have localized text as a part of your source code

**Comment by kripper** [comment]
Remember we are generating binary files which have to be in a specific encoding.

Use cases: write esc/pos to a receipt printer, write xml in certain encoding, write to sockets, etc.

**Comment by kripper** [comment]
Well, as I wrote above, maybe it's acceptable to not expect the string literals to have a certain encoding and rewrite the code to `$output = encode_to("iso-88591-1", "País") . $binaryCode . encode_to("iso-88591-1", "África")`.

**Comment by jakubmisek** [comment]
If those files are generated, then it's pretty much ok. Also, that's even easier to change it for a different platform. 

The code above is much safer now. Moreover; it is obvious what is the `$output` and it is much cleaner to read such code.

**Comment by kripper** [comment]
Or do you mean we shouldn't use international characters at all in our PHP source code?

Example:
`echo "¿De que país vienes?";`

**Comment by jakubmisek** [comment]
it's up to you :) more magic configuration, variable environments and various encodings in various files mean more problems you have to be solving all the time .. I'm only a heartsome observer

**Comment by kripper** [comment]
See workaround here: https://github.com/peachpiecompiler/peachpie/issues/780#issuecomment-683473862
