### ISSUE TITLE
Compiler bug "Call to a member function drawimage() on boolean|null|resource"

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#808]
Seems like a compiler optimization related bug.

Compiler fails when running `dotnet build --configuration Release`.
Compiler works fine when running `dotnet build`.

Test case:
[test-case.zip](https://github.com/peachpiecompiler/peachpie/files/5088187/test-case.zip)

**Comment by kripper** [comment]
Workaround / Hint:

The code works fine when rewritten as follows:

```
class Test {
	function test($var) {
		$extLoaded = extension_loaded('imagick'); <--------------  Define a aux variable here

		if ($var == 1) {
			$png = imagecreate($width, $height);

		} else if ($extLoaded) { <------------------ Use the variable here
			$png = new Imagick();
		}

		$png->drawimage($bar);
	}
}
```

**Comment by jakubmisek** [comment]
thanks @kripper , we'll take a look on that. 

What if you update from `0.9.981` to the latest `0.9.990`?

**Comment by jakubmisek** [comment]
@kripper sorry, but isn't the compiler right?

This is a correct behavior - you have an error in the code and compiler reports it as error.

**Comment by kripper** [comment]
No,

1. the compiler is assuming erroneously that the variable will be a boolean, but it will depend on the value of $var.
2. the behavior differs when compiling in debug vs release configuration...but this may be fine if there is a reason to apply additional optimizations when compiling a release mode.

**Comment by jakubmisek** [comment]
the compiler is right, sorry.

- `extension_loaded('imagick');` is `FALSE`
- variable `$png` will be NULL or FALSE or resource
- your code will fail

**Comment by kripper** [comment]
No.
If `$var == 1`, then `$png = imagecreate($width, $height);` and `$png->drawimage($bar);` is valid.

**Comment by jakubmisek** [comment]
Imagecreate returns false or resource, and you cannot call methods on variables of type resource or scalars. At least that's how it is afaik

**Comment by kripper** [comment]
Oops, please consider the other case:

If `$var != 1`, then `$png = new Imagick();` and `$png->drawimage($bar);` is valid.

**Comment by jakubmisek** [comment]
yes, but that won't happen in your test case

**Comment by kripper** [comment]
Ok, basically you are saying that [extension_loaded()](https://www.php.net/manual/en/function.extension-loaded.php) will always be false in Peachpie, right?

**Comment by jakubmisek** [comment]
the compiler knows what extensions you are referencing in your project, so "extension_loaded" gets evaluated in compile time.

**Comment by kripper** [comment]
I see. That probably means that the assembly is missing. Nice!

**Comment by kripper** [comment]
> Workaround / Hint:
> 
> The code works fine when rewritten as follows:
> 
> ```
> class Test {
> 	function test($var) {
> 		$extLoaded = extension_loaded('imagick'); <--------------  Define a aux variable here
> 
> 		if ($var == 1) {
> 			$png = imagecreate($width, $height);
> 
> 		} else if ($extLoaded) { <------------------ Use the variable here
> 			$png = new Imagick();
> 		}
> 
> 		$png->drawimage($bar);
> 	}
> }
> ```

Well, then at least we discovered a case where the optimization is not working ($extLoaded should be false here too).

**Comment by jakubmisek** [comment]
right, "imagick" extension is not implemented in PeachPie. Also if it would, it would probably not be referenced by the project by default.

The optimization does not propagate variable values, that's right. This case is further optimized by JIT.

**Comment by kripper** [comment]
Anyway, I have to say it's really awesome how Peachpie and the .NET compiler architecture behind is doing all this analysis and optimizations.
Thanks for commenting.

**Comment by jakubmisek** [comment]
We're glad you like it! and happy for all the comments and issues. We're aware a lot of things are confusing so we can adjust and improve docs and API correspondingly.
