### ISSUE TITLE
PDO.SqlSrv does not includes specifics PDO constants

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#813]
Hello,

I am trying to run our legacy app on PeachPie (sweet project by the way :smile:), and there are some issues.

When creating the PDO object, we pass some options, mainly:
```
$option = array( PDO::SQLSRV_ATTR_ENCODING => PDO::SQLSRV_ENCODING_SYSTEM );
```
And we are greeted with an exception: `System.InvalidOperationException : 'PDO::SQLSRV_ATTR_ENCODING could not be resolved.'`

It seems that the library `Peachpie.Library.PDO.SqlSrv` does not add the relevant constant specific to this driver.

See here: https://docs.microsoft.com/en-us/sql/connect/php/constants-microsoft-drivers-for-php-for-sql-server?view=sql-server-ver15#pdo_sqlsrv-driver-constants

I would have love to help with a PR, but I have no idea where to put these constants so PeachPie can make them available to the PHP code...

Thank you.

**Comment by jakubmisek** [comment]
Glad you're trying PeachPie!

For now we are declaring all the driver specific constants directly to the PDO class at PDO.ATTR.cs, after
https://github.com/peachpiecompiler/peachpie/blob/a57de76abbb8c986ceb72be057b4810b236724f5/src/PDO/Peachpie.Library.PDO/PDO.ATTR.cs#L289

We'd be happy for your PR. Let me know if you need any help.

**Comment by Indigo744** [comment]
Alright, if I find the time I'll try and submit a PR, thanks.

**Comment by jakubmisek** [comment]
thank you!
