### ISSUE TITLE
session_set_cookie_params is not supported

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#815]
Hello,

I am trying to run our legacy app on PeachPie (sweet project by the way 😄), and there are some issues.

We have the following error:
`PHP (Warning): Function 'session_set_cookie_params' is not supported`

However, looking at the [compatibility status page](https://docs.peachpie.io/compatibility-status/) the `Session` lib should be completely supported.

And indeed, this method raise an exception: https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library/Session.cs#L809
Even though there is code after the exception to handle the function.

Are we missing something obvious? What could we do?

Thanks.

**Comment by jakubmisek** [comment]
It seems the configuration itself is implemented, so the functions session_set_cookie_params, session_get_cookie_params, ini_get, ini_set, .. work.

However, the configured params (like CookieLifetime) are not used by the actual session handler.

If you are running on ASP.NET Core sessions (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1#configure-session-state), those settings are configured there.

**Comment by Indigo744** [comment]
Ah I understand, thank you.

Maybe adding a page in the documentation explaining these subtleties would be good 😺

**Comment by jakubmisek** [comment]
@Indigo744 updating docs is a good idea
