### ISSUE TITLE
empty() on a variable that may exists in a function but does not throws NullReferenceException

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#816]
Hello,

I came across a strange bug.

Sometimes, when a variable **in a function** _could_ be defined **but is not** (due to a conditional jump for instance), then calling `empty()` on it will throw a `System.NullReferenceException` (`Object reference not set to an instance of an object`).

After some searching, I managed to make a minimal script:
```php
<?php
function ___test_in_function___() {
    /* Test inside a function */
    if (isset($somethingelse)) {
        $bar2 = array();
    }

    echo empty($foo2); // OK
    echo empty($bar2); // <--  throw NullReferenceException
}

/* Test not inside a function */
if (isset($something)) {
    $bar1 = array();
}

echo empty($foo1); // OK
echo empty($bar1); // OK

___test_in_function___();
```

Looking in the debugger, `bar1` is defined as `NULL` whereas `bar2` is defined as `Pchp.Core.PhpArray` (which I suppose is not instantiated somewhere).

Of course, there is no issue if `$bar2` is initialized outside the conditional statement, which it _should_ be in a clean code. But you know how it goes...

**Comment by jakubmisek** [comment]
@Indigo744 great test case! thanks, will be fixed

**Comment by jakubmisek** [comment]
Note this happened only in debug mode. In release mode, this code fragment was effectively removed by compiled.

**Comment by Indigo744** [comment]
> 
> 
> Note this happened only in debug mode. In release mode, this code fragment was effectively removed by compiled.

I don't understand how the code fragment could be removed by compiler?
Maybe if `$somethingelse` is a local variable I guess, but what about with globals like `$_SERVER` et al.? I hope it will not be removed by the compiler!

**Comment by jakubmisek** [comment]
@Indigo744 In Release, compiler replaces following
```php
echo empty($bar2);
```
with
```php
echo 1;
```

because it knows the variable is never initialized.

**Comment by Indigo744** [comment]
I guess you are talking about this very contrived example. 

But you agree that in a more complex scenario, `$bar2` could be very well initialized and full of stuff, depending on a global variable content that is only known at runtime (which is exactly what we had in our code). So it won't be optimized, I hope?

**Comment by jakubmisek** [comment]
@Indigo744 sure, don't worry, the compiler just won't delete the code if there is no good reason :)
