### ISSUE TITLE
PDO::FETCH_GROUP is not taken into account

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#817]
Hello,

We use extensively the option [`PDO::FETCH_GROUP`](https://phpdelusions.net/pdo/fetch_modes#FETCH_GROUP) in our code base.

But it seems that it is not supported:
```php
$a = $statement->fetchAll( PDO::FETCH_ASSOC );
$b = $statement->fetchAll( PDO::FETCH_GROUP | PDO::FETCH_ASSOC);
```

Expected:
```
$a = array(1) {
  [0]=> array(32) { ... }
}
$b = array(1) {
  [1] => array(1) {
    [0] => array(31) { ... }
  }
}
```

Instead, `$b` is the same as `$a`.

The thing is that:
1. there is no warning
1. the [compat matrix](https://docs.peachpie.io/compatibility-status/) doesn't show this constant

I know this lib is a work in progress, but there should be a reliable way to tell what is actually implemented, and what isn't.

Thank you.

**Comment by jakubmisek** [comment]
you are right, it should definitely throw a warning in case an unexpected/unimplemented argument is used. Currently there are two places in PDO that are not handled

https://github.com/peachpiecompiler/peachpie/blob/fc98fdeeab0b9d489fd4f643ddba01a9808f898c/src/PDO/Peachpie.Library.PDO/PDOStatement.cs#L372

https://github.com/peachpiecompiler/peachpie/blob/fc98fdeeab0b9d489fd4f643ddba01a9808f898c/src/PDO/Peachpie.Library.PDO/PDOStatement.cs#L447

**Comment by Indigo744** [comment]
I am working on a PR for this one. Will let you know!

**Comment by jakubmisek** [comment]
@Indigo744 that would be great, I'm personally not sure how to make it nice and efficient
