### ISSUE TITLE
array_* functions throw exceptions if used with object derived from ArrayObject

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#818]
Hello,

Object extending `ArrayObject` should not really be used with `array_xxx` functions.
However, using them will not trigger any error in PHP, and actually there is one which works: `array_key_exists`.

But all methods fail with Peachpie.

Here is a minimal code:
```php

class Foo extends ArrayObject { }

$foo = new Foo();
$foo["foo"] = "bar";

/* For the following:
 * - in PHP : actually does nothing ($foo is not modified), no warning
 * - in Peachpie : System.InvalidCastException 
 *    'Unable to cast object of type 'ArrayAccessAsPhpArray' to type 'Pchp.Core.PhpArray'.'
 */
array_push($foo, "bar");
array_pop($foo);
array_shift($foo);

/* For the following:
 * - in PHP : actually return nothing, no warning
 * - in Peachpie : Pchp.Library.Spl.TypeError
 */
array_keys($foo);
array_values($foo);

/* For the following:
 * - in PHP : should work (return 1)
 * - in Peachpie : Pchp.Library.Spl.TypeError
 */
array_key_exists("foo", $foo);
```

I would expect no error from the first functions, and the last to work like in PHP.
I know this is very weird, but PHP is full of inconsistent stuff like this...

What do you think?

**Comment by jakubmisek** [comment]
Seems we've tried to be a bit more strict. In case the code is wrong, and it's not supposed to work, PeachPie usually throws an exception. 

Anyways; I get warnings in PHP when I tried the sample above.

**Comment by jakubmisek** [comment]
I'm also afraid, PHP is going to unify the behavior; and since 8.0 it will throw `TypeError` as well .. who knows :))

**Comment by Indigo744** [comment]
In the mean time, what about failing silently and logging a warning?

**Comment by jakubmisek** [comment]
well, but you don't want it in your code, seems like a bug to me

**Comment by jakubmisek** [comment]
The problem is, functions like `array_push` can be strongly typed in .NET, which leads to a vast array of optimizations.

In order to report the same error as in PHP and silently continue, the method would have to be untyped, and then it would have to dynamically resolve the type inside the function (even it was already known in compile-time).

So that's the question we're dealing with - if it's worth it to properly handle the faulty case, or if it isn't better to throw an exception when we see there is something wrong with the code ..

**Comment by Indigo744** [comment]
I understand. It's a tight rope to walk on.

A _won't fix_ would be acceptable in that case, as it is really not recommended.

**Comment by jakubmisek** [comment]
I'd be interested in your actual usage. Is it by design to provide the `ArrayObject` instance and silently continue?

**Comment by Indigo744** [comment]
Here is the culprit: https://github.com/zendframework/zf1/blob/master/library/Zend/Registry.php#L206
Looks like a workaround for an old bug.

**Comment by jakubmisek** [comment]
@Indigo744 interesting, according to PHP docs, this should not work, it's a regular type mismatch.

**Comment by Indigo744** [comment]
Sometimes, PHP makes you wonder...

I think this issue can be closed 😅 
At least, if someone search for this issue, it will have some information!

**Comment by jakubmisek** [comment]
makes sense it's a workaround for old Zend's bug :) 

Anyways, at least in PHP 8.0, this feature was removed (https://github.com/php/php-src/blob/e6044d4455d7fbaced7f3a6ac28172d963017e51/UPGRADING#L47). `array_key_exists` can be only used with `array` now. Our compile-time diagnostics should be able to report the compile-time warning.

**Comment by jakubmisek** [comment]
Noting for readers - PeachPie is more strict about function arguments, instead of silently outputting a warning somewhere, it throws a CLR exception.
