### ISSUE TITLE
DateTime::createFromFormat with NULL value throws ArgumentNullException

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#820]
Hello,

I guess the title _DateTime::createFromFormat with NULL parameters throws ArgumentNullException_ should make sense, but, well, not in the PHP world!

With value NULL:
```php
$a = DateTime::createFromFormat("Ymd", NULL);
var_dump($a); 
// bool(false)
var_dump(DateTime::getLastErrors());
/* array(4) {
  ["warning_count"]=>
  int(0)
  ["warnings"]=>
  array(0) {
  }
  ["error_count"]=>
  int(1)
  ["errors"]=>
  array(1) {
    [0]=>
    string(12) "Data missing"
  }
}
*/
```

With format NULL:
```php
$a = DateTime::createFromFormat(NULL, "20200812");
var_dump($a);
// bool(false)
var_dump(DateTime::getLastErrors());
/* array(4) {
  ["warning_count"]=>
  int(0)
  ["warnings"]=>
  array(0) {
  }
  ["error_count"]=>
  int(1)
  ["errors"]=>
  array(1) {
    [0]=>
    string(13) "Trailing data"
  }
}
*/
```

With both value and format NULL (yes, really, it works):
```php
$a = DateTime::createFromFormat(NULL, NULL);
var_dump($a);
/* object(DateTime)#1 (3) {
  ["date"]=>
  string(26) "2020-08-30 13:04:35.887719"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(12) "Europe/Paris"
}
*/
```

PHP still baffles me to no end!

I'm not sure about your stances regarding these NULL values. Should Peachpie strives to duplicate exactly the way PHP works, or should it add some common-sense checks? First option is best to reduce the issue with legacy code, but will be harder to maintain.

**Comment by Indigo744** [comment]
And I found the culprit here: https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library/DateTime/DateTimeParsing.cs#L1557

**Comment by jakubmisek** [comment]
Nice.

PeachPie should get the same results in this case.

Sometimes for performance and sanity reasons, it is better to throw an exception, usually if the value suggests the program is terribly wrong and should not continue :)

**Comment by jakubmisek** [comment]
Ok, PHP interprets `NULL` as `""` (empty string). Will be fixed.
