### ISSUE TITLE
Missing 'Title' metadata

### ISSUE THREAD

**Issue by free9ja** [peachpiecompiler/peachpie#830]
running dotnet build on a Theme produces the error "error : Not a valid theme. Missing 'Title' metadata"

**Comment by jakubmisek** [comment]
I think you are referring to https://docs.peachpie.io/scenarios/wordpress/build-php-theme/ ?

The "Title" is taken from theme's readme.txt or readme.md file. It requires the theme name, in case of .txt file:
```txt
=== Twenty Seventeen ===
Contributors: ...
Version: ..
```

for .md file:
```markdown
# Twenty Seventeen
...
```

May I ask for your `readme` file header? If the build process parses it correctly.

**Comment by free9ja** [comment]
Yes. Thank you. It attempted to build but generated another error "error PHP4044: Type name 'WPBakeryShortCodesContainer' could not be resolved"

**Comment by jakubmisek** [comment]
seems the theme depends on WPBakery plugin?

**Comment by free9ja** [comment]
Yes it does. Do i need to install that plugin differently? I appreciate your guidance

**Comment by jakubmisek** [comment]
The theme you are building need to reference the WPBakery plugin.

I'm not sure the plugin is built somewhere as a NuGet package already. Do you know what is its ID?

Then in your theme project file, add wither `<PackageReference ... />` or `<ProjectReference ... />` in case you are building the plugin as a project by yourself.

**Comment by free9ja** [comment]
Yes. It's called startit. I can share the url if you require. I am not building it. I bought it off the shelve.

**Comment by jakubmisek** [comment]
And what's the ID of the WPBakery plugin?

**Comment by free9ja** [comment]
=== WPBakery Page Builder Simple All Responsive ===
Plugin Name: VC Simple All Responsive

**Comment by jakubmisek** [comment]
so the ID is `vc-simple-all-responsive` :)

You would have to build the plugin as well, or remove uses of `WPBakeryShortCodesContainer` from your theme code.

**Comment by free9ja** [comment]
okay. I don't think that is the ID. Because i tried to build the plugin and it still came back with that same error. I will either remove the dependency on that plugin or find out the name of the plugin so i can add it. I will keep you posted.

**Comment by jakubmisek** [comment]
I think the plugin is not available as a NuGet package yet. So you would have to build it first, or remove the use of the class.

**Comment by jakubmisek** [comment]
Closing this issue, 'Title' needs to be in the theme's readme file.
