### ISSUE TITLE
Peachpie.AspNetCore.* targets .Net Standard 2.1

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#832]
Hello,

**PeachPie itself targets .Net Standard 2.0** and it's a good thing, since it allows to be compiled to a wide variety of targets, including the .Net Framework.

However, **Peachpie.AspNetCore.Web** (and Peachpie.AspNetCore.MVC) **targets .Net Standard 2.1**, which I believe to target .Net Core 3.x branch and benefits from the performance improvement.

This is problematic, since a lot of project (legacy, but not so!) are stuck with ASPNet Core 2.1 which is needed when targeting the full .Net Framework.

Targeting .Net Standrard 2.0 would enable more people to integrate PeachPie in their existing code base. It would also put all PeachPie packages on the same compatibility level.

.Net Standard compatibility page: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

__Would it be possible to target .Net Standard 2.0 for Peachpie.AspNetCore.* packages instead of 2.1?__
What would be needed in order to do so? I am more than wiling to work on a PR, should you agree 😉 

Thank you for your consideration and have a nice day!

**Comment by jakubmisek** [comment]
For legacy ASP.NET applications on .NET Framework (not Core), there is the `Peachpie.RequestHandler` library.

Of course if you create a PR that targets the project for both - netstandard2.0 and netstandard2.1, we can take a look if it would be reasonably clean :)

**Comment by Indigo744** [comment]
> Edit: .NET Framework 4.7.2 or higher should be compatible with netstandard2.1

Sadly no... Oh I wish!

https://dotnet.microsoft.com/platform/dotnet-standard#versions
https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

I'll try and submit a PR and we'll see where it leads us 😉

**Comment by Indigo744** [comment]
Just to be clear:

> For legacy ASP.NET applications on .NET Framework (not Core), there is the Peachpie.RequestHandler library.

You are talking about ASP.Net on .Net Framework. 

I am actually talking about ASP.Net Core on .Net Framework (which is possible up to ASP.Net Core 2.2, see https://dotnet.microsoft.com/platform/support/policy/dotnet-core)
