### ISSUE TITLE
Implements bcmath

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#836]
Tracks implementation for [BCMath Arbitrary Precision Mathematics](https://www.php.net/manual/en/book.bc.php)

 - [x] `bcadd`
 - [x] `bcsub`
 - [x] `bcmul`
 - [x] `bcdiv`
 - [x] `bcmod`
 - [x] `bcpow`
 - [x] `bcsqrt`
 - [x] `bcscale`
 - [x] `bccomp`
 - [x] `bcpowmod`

**Comment by jakubmisek** [comment]
noting, there is a kind of initial stub in https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library/BCMath.cs
