### ISSUE TITLE
number_format issue with NULL value

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#839]
Hello,

I have found a weird inconsistent behavior.

```php
echo number_format(4242.01).PHP_EOL; // OK : 4,242
echo number_format("4242.01").PHP_EOL; // OK (string converted to double) : 4,242
echo number_format(NULL).PHP_EOL; // OK : 0
$var = null;
echo number_format($var).PHP_EOL; // throws Pchp.Library.Spl.TypeError (0 in PHP, like above)
```

I would expect the last line to output 0 like the one with NULL directly in it.

**Comment by jakubmisek** [comment]
seems, `NULL` -> `double` in compile-time gets resolved without a warning to `0.0`
In run-time, it throws TypeError

There is an inconsistency in type conversion in compile-time and run-time, although all of them should use the semantic defined in `Conversions.cs`

**Comment by jakubmisek** [comment]
It's a kind of inconsistency in PHP itself. Any user function with `float` type hint would throw `TypeError` but "some" extension functions shows warning, some throws, and some just silently convert it to zero.

**Comment by Indigo744** [comment]
> 
> 
> It's a kind of inconsistency in PHP itself. Any user function with `float` type hint would throw `TypeError` but "some" extension functions shows warning, some throws, and some just silently convert it to zero.

The thing is, PHP is full of inconsistencies like these that developers uses as "features"...

Why bother adding checks and null guards when PHP allows you to write code that fails silently... 😞 

Would it be possible for PeachPie to match PHP behavior for these specific functions?

**Comment by jakubmisek** [comment]
yes, we have to :) ... maybe some kind of attribute like `([AllowNull] double number)` that would tell the runtime to implicitly convert `NULL` to `.0` in PHP. When called from C#, it would be still nicely type-safe.

**Comment by Indigo744** [comment]
Is it possible to put an attribute directly on a parameter? That would be nicer indeed and would scale well.
