### ISSUE TITLE
ini_set("max_execution_time") and set_time_limit() are ignored

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#842]
Even though the option "max_execution_time" is supported in Peachpie.Library\options.cs

`Register("max_execution_time", IniFlags.Supported | IniFlags.Local, s_emptyGsr);`

Neither a set nor a get will work, as `s_emptyGsr `will becalled (doing nothing)

From my point of view a call to ini_set("max_execution_time",xxx) (maybe in function GsrCore?) should lead to 

`return (PhpValue)GetSet(ref ctx.Configuration.Core.ExecutionTimeout, "", value, action);`

as `ctx.Configuration.Core.ExecutionTimeout` will be used in function `GetRequestTimeoutSeconds `in class PhpHandlerMiddleware to calculate the timeout to stop any script execution.

Also function `Invoke `in PhpHandlerMiddleware will need a loop around

```
                    var timeout = GetRequestTimeoutSeconds(phpctx);
                    if (timeout > 0)
                    {
                        await Task.WhenAny(completion.Task, Task.Delay(timeout * 1000));
                    }
                    else
                    {
                        await completion.Task;
                    }
```

to verfiy that the current timeout is really reached. This is needed because any ini_set("max_execution_time",xxx) can only be called from within the currently executing script itself and is not available before the script is started. This gives any script 30 seconds (the default configuration) to increase the timeout by calling ini_set("max_execution_time",xxx). There would be no way to reduce the timeout below 30 seconds, but I guess this should be done by providing a useful way to replace the initial timeout of 30 seconds for all scripts.

**Comment by jakubmisek** [comment]
you are right, the option seems to be ignored. 

The workaround, for now, is to set the global `ExecutionTimeout` in the aspnet core application, within `ConfigureServices` method https://docs.peachpie.io/net/hosting/aspnetcore/#configuration

**Comment by jakubmisek** [comment]
Also we do not have implementation for `set_time_limit()` function

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/d48b73efbf22822c45184920465bea17f5363f07, https://github.com/peachpiecompiler/peachpie/commit/a39223801faa3611cb784ac6ef6ca2c414d8836d, https://github.com/peachpiecompiler/peachpie/commit/21c21f60bfd62903ecc174a7206b214a2f957b88
