### ISSUE TITLE
difference of dates is incorrect when one of the dates is the last day of the month

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#843]
The function `CalculateDifference` in PeachPie.Library\DateTime\DateInterval.cs is returning wrong results in some cases.

E.g. the difference of 31/08/2020 and 22/10/2015 should be 4 years, **10 months** and 9 days, but `CalculateDifference` returns
4 years, **9 month** and 9 days

  | Name | Wert | Typ
-- | -- | -- | --
◢ | diff | DateInterval | object
  | d | 9 | int
  | days | 1775 | int
  | f | 0 | double
  | h | 0 | int
  | i | 0 | int
  | invert | 0 | int
  | m | 9 | int
  | s | 0 | int
  | y | 4 | int

I believe a `month++;` should be added to the second case shown below.

```
                else if (fromMonthDays == date1.Day)
                {
                    days += date2.Day;
                }
                else if (toMonthDays == date2.Day)
                {
                    days += fromMonthDays - date1.Day;
                }
```

In addition as DateTime includes a time component which is not checked as part of the `CalculateDifference` function, it's obviously that the correctness of the calculation depends on the time component.

**Comment by jakubmisek** [comment]
thanks! would you have a test case please?

**Comment by jan-ai** [comment]
```
$sdate = new DateTime("2015-10-22 21:25:32");
$after = new DateTime("2020-08-31 21:25:32");
 
$diff = $after - $sdate
```

should be 4 years, 10 months, 9 days

`$diff->d == 9 && $diff->m == 10 && $diff->y == 4`
