### ISSUE TITLE
random_int should NOT use mt_rand()

### ISSUE THREAD

**Issue by diddledan** [peachpiecompiler/peachpie#856]
`random_int` is supposed to be cryptographically secure. `mt_rand` is not cryptographically secure. `random_int` in PP uses `mt_rand` therefore is not cryptographically secure.

See https://github.com/paragonie/random_compat if you need a secure implementation in pure PHP or alternatively use the .net Core cryptography API to provide the backend so you don't have to write the implementation yourselves.

**Comment by jakubmisek** [comment]
thanks Daniel, we already have a note in the source code https://github.com/peachpiecompiler/peachpie/blob/4105a60c5b47c1dbcc0c89bf1907ace46c0e9efa/src/Peachpie.Library/Math.cs#L242 but better to track it as an issue here

**Comment by jakubmisek** [comment]
the same for `random_bytes()` :)
