### ISSUE TITLE
fstat returns incorrect mode for /dev/urandom and other character device files

### ISSUE THREAD

**Issue by diddledan** [peachpiecompiler/peachpie#857]
In Linux, `/dev/urandom` is a character device node, which is indicated by the partial mode `020000`. This is testable using a binary AND operator to compare with the actual file mode. `fstat` as written in PP does not show this permission/mode setting and so testing with the following code fails:

```php
$fp = fopen('/dev/urandom', 'rb');
if (is_resource($fp)) {
    $st = fstat($fp);
    if (($st['mode'] & 0170000) === 020000) {
        echo 'SUCCESS'; // the mode includes the correct character device indicator
    } else {
        echo 'FAIL'; // the mode does not include the correct character device indicator
    }
}
```

Presumably this also extends to other extended permission bits, such as: socket, symbolic link(?), block device, fifo, setuid, setgid, and sticky (ref: https://man7.org/linux/man-pages/man7/inode.7.html)

**Comment by jakubmisek** [comment]
@diddledan may I ask if it's working fine now?

**Comment by diddledan** [comment]
It looks like that PP correctly sets the mode now. so this is good :-)
