### ISSUE TITLE
Conceptual Equivalence

### ISSUE THREAD

**Issue by TensorTom** [peachpiecompiler/peachpie#858]
A quick conceptual question about peachpie as I'm not that familiar with its inner-workings. Hypothetically, could the same be done for libpython as was done with PHP to create Peachpie?

**Comment by jakubmisek** [comment]
PeachPie is a compiler and runtime, so it translates the PHP code the same way as the C# compiler does.

In the case of Python, there is https://ironpython.net/ already. 

Although, I'm not familiar with "libpython" specifically.
