### ISSUE TITLE
`json_encode()` of SimpleXMLElement should be custom serialized

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#863]
Please consider the following test case:  
```php
<?php

	$str = file_get_contents('test.xml');
	$xml = simplexml_load_string($str);
	$json = json_encode($xml);
	print_r($json);
```

This throws a `CLR/System.NullReferenceException` exception `json_encode()` tries to access `$xml`.  Here's the content of `test.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<databaseConfig>
		<database dsn="mysql:host=127.0.0.1;port=3306;charset=utf8">
			<name>peachpie</name>
			<username>foo</username>
			<password>bar</password>
		</database>
	</databaseConfig>
</configuration>
```

I can confirm that the `$xml` variable is getting populated correctly with an instance of `SimpleXMKElement` and indeed contains the XML data:

![SimpleXMLElement](https://user-images.githubusercontent.com/4673812/95790872-12f8a680-0ced-11eb-8291-e0d9c5412dad.png)

Expected `$json` value:
```json
{"databaseConfig":{"database":{"@attributes":{"dsn":"mysql:host=127.0.0.1;port=3306;charset=utf8"},"name":"peachpie","username":"foo","password":"bar"}}}
```

**Comment by DRSDavidSoft** [comment]
Here's the expected results (`php file.php`):
```json
{"databaseConfig":{"database":{"@attributes":{"dsn":"mysql:host=127.0.0.1;port=3306;charset=utf8"},"name":"peachpie","username":"foo","password":"bar"}}}
```

(The same thing, formatted:)
```json
{
	"databaseConfig": {
		"database": {
			"@attributes": {
				"dsn": "mysql:host=127.0.0.1;port=3306;charset=utf8"
			},
			"name": "peachpie",
			"username": "foo",
			"password": "bar"
		}
	}
}
```

**Comment by jakubmisek** [comment]
thanks, it is a bug in `json_encode` trying to access some internal SimpleXmlElement properties which should be hidden.

**Comment by DRSDavidSoft** [comment]
@jakubmisek 👍 Any fix that I can apply, or should there be a patch made for this?

**Comment by jakubmisek** [comment]
seems PHP treats SimpleXMLElement differently, resulting in XML being transformed into JSON rather then SimpleXMLElement class just serialized .. 

this one has to be implemented in PeachPie

**Comment by DRSDavidSoft** [comment]
Nice job, thanks! 👍
