### ISSUE TITLE
Bug: ArgumentCountError is not being thrown

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#864]
### Test case:

```php
<?php

function foo($a, $b) { return $a + $b; }

try {
	$ret = call_user_func_array('foo', [3]); // instead of [3, 7] for example
	echo "result: " . $ret;
}
catch (ArgumentCountError $e) {
	echo "ArgumentCountError: " . $e->getMessage();
}
```

### Expected behavior (PHP):
```
ArgumentCountError: Too few arguments to function foo(), 1 passed in program.php on line 10 and exactly 2 expected
```

### Actual behavior (PeachPie)
```
result: 3
```

i.e., `ArgumentCountError` is not thrown

The current behavior is that NULL is being passed to the missing required arguments.  This should only happen on optional parameters (i.e. `$arg = 0`) not the required ones such as outlined above

**Comment by DRSDavidSoft** [comment]
@jakubmisek Is there a way to implement this in PeachPie? I have no idea on how it would work, maybe use reflections, or .NET has a similar exception that can be thrown?

**Comment by jakubmisek** [comment]
It can be surely implemented, just currently we have ignored it by purpose and passing a NULL values instead.

Working on it.
