### ISSUE TITLE
Test case: INF to string, inconsistency

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#865]
### case
```php
echo INF;
```

- PHP: `INF`
- PeachPie: `Infinity`

This is important when the app does something like this:
```
$var = INF;

$concat = "value: $var";
if ( $concat === 'value: INF' ) { ... } else { ... }
```

or, if we cast the variable to string: `(string) INF` or `(string) $var`

Since PeachPie returns `Infinity` instead, it breaks the program. `¯\_(ツ)_/¯`

**Comment by jakubmisek** [comment]
thanks!
