### ISSUE TITLE
how to run Slim Framework 3 and Eloquent 5.2 on PeachPie

### ISSUE THREAD

**Issue by insinfo** [peachpiecompiler/peachpie#866]
how to run Slim Framework 3 and Eloquent 5.2 on PeachPie, I'm trying to create a new project using PeachPie, but I can not get it to work, it's giving exception 

The project is hosted on github
https://github.com/insinfo/testeSlimPeachPie

```php
<?php

require 'vendor/autoload.php';

$app = new Slim\App();

$app->get('/', function ($request, $response, $args) {
    return $response->getBody()->write("Hello ");
});

$app->get('/teste/t', function ($request, $response, $args) {
    return $response->getBody()->write("Hello word");
});

$app->run();



```
```console
dotnet run -p app
c:\MyProjectsSharp\peachpie-samples\web-application\website\vendor\slim\slim\Slim\Http\Response.php(359,13): warning PHP5011: Unreachable code detected [c:\MyProjectsSharp\peachpie-samples\web-application\website\website.msbuildproj]
c:\MyProjectsSharp\peachpie-samples\web-application\website\vendor\composer\ClassLoader.php(345,21): warning PHP5006: Call to undefined function: 'apcu_fetch' [c:\MyProjectsSharp\peachpie-samples\web-application\website\website.msbuildproj]
c:\MyProjectsSharp\peachpie-samples\web-application\website\vendor\composer\autoload_real.php(26,133): warning PHP5006: Call to undefined function: 'zend_loader_file_encoded' [c:\MyProjectsSharp\peachpie-samples\web-application\website\website.msbuildproj]
c:\MyProjectsSharp\peachpie-samples\web-application\website\vendor\composer\ClassLoader.php(345,58): warning PHP5007: Undefined variable: $hit [c:\MyProjectsSharp\peachpie-samples\web-application\website\website.msbuildproj]
c:\MyProjectsSharp\peachpie-samples\web-application\website\vendor\composer\ClassLoader.php(359,13): warning PHP5006: Call to undefined function: 'apcu_add' [c:\MyProjectsSharp\peachpie-samples\web-application\website\website.msbuildproj]
```

![image](https://user-images.githubusercontent.com/12227024/95935966-d0959f00-0daa-11eb-85ce-0f13b3405149.png)

Works normally with php PHP 5.6 - 7.3
![image](https://user-images.githubusercontent.com/12227024/95936514-21f25e00-0dac-11eb-8667-d53d288cc22f.png)

c:\MyProjectsSharp\testeSlimPeachPie\testeSlimPeachPie\testeSlimPeachPie>php -S localhost:8080 -t ./

**Comment by jakubmisek** [comment]
Thanks for the test case, but it seems it's working for me.

I've updated the PeachPie version used in your sample tho - https://github.com/insinfo/testeSlimPeachPie/pull/2

![image](https://user-images.githubusercontent.com/842150/95981670-4e938d80-0e1f-11eb-9cd9-424e21b0bf52.png)

![image](https://user-images.githubusercontent.com/842150/95981527-13915a00-0e1f-11eb-861d-6a1e18b00093.png)

**Comment by insinfo** [comment]
Thanks for the quick answer, Yes it is actually working now, I did a simple test comparing the performance on the built-in php server, Apache and PeachPie, I will do more tests to test the feasibility of porting an application of mine made with Slim Framework for PeachPie. Now I have to test Eloquent 5.2

![image](https://user-images.githubusercontent.com/12227024/96009632-4172a080-0e17-11eb-9f71-277760f1a801.png)

**Comment by jakubmisek** [comment]
Good it works. We can improve the performance in the future version (planned for 1.1.0).

I'm closing the issue now, please open a new one if there would be anything else.
