### ISSUE TITLE
`yield from` construct not supported

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#87]
implement support for `yield from` construct

**Comment by benjaminhowarth1** [comment]
I'm getting "yield from exception handling construct (try, catch, finally) not supported" in VS2019, PeachPie 0.9.36. Any chance of this being added?

**Comment by bfistein** [comment]
Referring back to this question via #604 - sorry @benjaminhowarth1, we missed your question.

**Comment by jakubmisek** [comment]
@benjaminhowarth1 this will get implemented for `yield` in `try` block. There are no plans for supporting `yield` in `catch` or `finally` yet.
