### ISSUE TITLE
Clarify where to find .Net Core 1.1

### ISSUE THREAD

**Issue by mastacheata** [peachpiecompiler/peachpie#88]
Hello,

in your getting started guide you refer to the main landing page of .NET Core from Microsoft.
However that page does it's best to hide the download for the old/LTS 1.1 release ever since they released 2.0 in early august.

Maybe you could just point directly to the old releases section of the MS website from the Getting Started page at least until Peachpie drops its hard requirement for the 1.0.4 version of the SDK.

**Comment by bfistein** [comment]
Hi @mastacheata, 

Thank you for this very reasonable suggestion. I will either create a second button for older releases or link to the archive until Peachpie will run with 2.0.

Thanks for your advice and for contributing to the project.
