### ISSUE TITLE
aspnet core - requesting /index.php returns 404

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#880]
I just tried building the `web-application` sample using either of `1.0.0-preview3` or `1.0.0-preview2`:

https://github.com/iolevel/peachpie-samples/tree/master/web-application

A request to `localhost:5004` returns 200 OK, while `localhost:5004/index.php` results in 404.

Is this intentional, or a bug?

**Comment by jakubmisek** [comment]
seems like a bug!

**Comment by jakubmisek** [comment]
found out, this was fixed in [1.0.0-preview3](https://github.com/peachpiecompiler/peachpie/releases/tag/v1.0.0-preview3)

we'll update the samples accordingly
