### ISSUE TITLE
Accessing files outside of ".exe" package? 

### ISSUE THREAD

**Issue by Michal-Mikolas** [peachpiecompiler/peachpie#881]
Hello, 
when I create .exe file using this tool, can PHP scripts inside access files "outside" of the EXE package? 

My idea is to create application configurable by .ini file: 

```
my_app/
    config.ini
    app.exe
```

Can PHP scripts in compiled `app.exe` package anyhow access the `config.ini` file? 

Thank you very much.

**Comment by jakubmisek** [comment]
yes, all the file system functions like `file_get_content()` or `parse_ini_file()` will work

**Comment by Michal-Mikolas** [comment]
So do I just have to run `file_get_contents("../config.ini")` ? 

Is it like `index.php` was inside of "app.exe" folder? Like this from the PHP script point of view: 

```
my_app/
    config.ini
    app.exe/
        index.php
```

**Comment by jakubmisek** [comment]
good question!

`index.php` is at `/my_app`, or more precisely at the current working directory where you started the app.

The following should just work, if the `app.exe` is executed from within `my_app` directory:

```php
file_get_contents('config.ini');
```

**Comment by Michal-Mikolas** [comment]
Nice :-) PeachPie looks so cool! I can't wait to try it! 

Thank you.

**Comment by jakubmisek** [comment]
glad you like it :)
