### ISSUE TITLE
PCRE pattern parse error: Incomplete \\p{X} character escape.

### ISSUE THREAD

**Issue by matbech** [peachpiecompiler/peachpie#886]
The following PCRE syntax is correct but PeachPie does not recognize it because of the missing curly brackets:
preg_match('/\pL/u', 'a')

The curly brackets are optional in some cases. From the PCRE specification:
```
If only one letter is specified with \p or \P, it includes all the general category properties that start with that letter. In this case, in the absence of negation, the curly brackets in the escape sequence are optional; these two examples have the same effect:

  \p{L}
  \pL
```
Reference:
https://www.pcre.org/original/doc/html/pcrepattern.html

**Comment by jakubmisek** [comment]
thanks for noticing!
