### ISSUE TITLE
C# Interoperability and $GLOBALS

### ISSUE THREAD

**Issue by kripper** [peachpiecompiler/peachpie#888]
I'm having fun compiling PHP -> .NET -> WebAssembly (running inside Chrome :-) ) and came across this situation:

I'm calling PHP from C# using:

```c#
using (var context = Pchp.Core.Context.CreateEmpty())
{
	var x = new MyClass(context);
	output = x.Test();
}
```

In the php file, I have:

```php
$GLOBALS['myVar'] = "some value";

class MyClass
{
	function Test() : string {
		return $GLOBALS['myVar'];
	}
}
```

The problem is that `Test()` is returning an empty value, even when I set the global var in the same file.
I believe this happens because Test() is executed inside an empty context (created with`Pchp.Core.Context.CreateEmpty()`) where the global var has not been set because the script is not executed.

How can I use C# Interoperability and access the global variables defined outside the class?

Note: I know that in this simple example above I could just define the global variables inside the class constructor, but in the real case I have hundred of includes defining global variables everywhere.

**Comment by kripper** [comment]
I tried to include the php script with:
```
using (var context = Pchp.Core.Context.CreateEmpty())
    Pchp.Core.Context.AddScriptReference(typeof(MyClass).Assembly);
    context.Include("", "test.php");
    ...
}
```
The assembly seems to load, but the include fails:
```
blazor.webassembly.js:1 Note: file 'test.php' has not been compiled.
blazor.webassembly.js:1 PHP (Warning): The specified file does not exist (/test.php)
```
What is the correct way to get the `Pchp.Core.Context` from a Blazor WebAssembly and to include a script?

**Comment by jakubmisek** [comment]
The file test.php does not get autoloaded, you basically just instantiate the class "MyClass" even it is not actually "declared" in the context.

As you suggested, `context.Include("", "test.php");` should work. Isn't it compiled in some subdirectory?

**Comment by jakubmisek** [comment]
@kripper Do you have a sample repo with this project? We can take a look if there is something we can fix or improve!

Maybe it would be for a blog post about PHP in WebAssembly.

**Comment by kripper** [comment]
Yes, I was thinkng the same.
Since all this new stuff is so interesting and powerfull I'm going to write a little blog.

**Comment by jakubmisek** [comment]
awesome!

**Comment by kripper** [comment]
@jakubmisek Here is the tutorial:
https://docs.google.com/document/d/14x5MRVgruGRNM1EaaJg6aJE4_EEw3AoI7YlzvO9NY2E

**Comment by kripper** [comment]
Now, back to the question...

Let's say we have this code in `Test\MyPhpClass\lib.php`:

```
<?php
global $TEST_GLOBAL;
$TEST_GLOBAL = "Hello from PHP!!!";

class MyPhpClass
{
	function HelloWorld() : string {
		global $TEST_GLOBAL;
		return $TEST_GLOBAL;
	}
}
```

How can we get Peachpie to run the "global code"?

**Comment by bfistein** [comment]
> @jakubmisek Here is the tutorial:
> https://docs.google.com/document/d/14x5MRVgruGRNM1EaaJg6aJE4_EEw3AoI7YlzvO9NY2E

@kripper that's great! Would you be ok with us publishing this (maybe with a few minor modifications) on our blog and citing you as the author?

**Comment by kripper** [comment]
Sure, please feel free to make modifications.

**Comment by jakubmisek** [comment]
@kripper the code file is actually a method called `<Main>` which you can call as noted above:

```c#
context.Include("", "Test\MyPhpClass\lib.php");
```
or - this is what request handler does:
```c#
var script = Context.TryGetDeclaredScript("Test\MyPhpClass\lib.php");
script.Evaluate(context, context.Globals, null);
```

**Comment by kripper** [comment]
@jakubmisek ok, it's not working: `Script 'lib.php' inclusion failed. Cause: Script file 'lib.php' not found. Search paths: include_path is '.', working directory is ''`.

We can instantiate the PHP class and call its method (which means the assembly is loaded), but for some reason, the compiled PHP files cannot be included.

**Comment by jakubmisek** [comment]
@kripper just use the right path .. "lib.php" is not correct:

```c#
var script = Context.TryGetDeclaredScript("sub\\lib.php"); // <-- the same path as ScriptsMap.s_scripts[0].Path
script.Evaluate(context, context.Globals, null);
```

Add to `ResolveInclude` or `Include` - please see https://docs.peachpie.io/api/ref/context/#construction - and initialize context..RootPath and context.WorkingDirectory so the function will work properly.

**Comment by kripper** [comment]
Nope. I tried to compile the script with path "lib.php" and "sub\\lib.php" (moving the file into a sub folder just in case Peachpie doesn't support scripts in the root path).
I'm calling Include() **with the same path stored in `ScriptsMap.s_scripts[0].Path`** and it doesn't work.
Something is different on the Webassembly environment and `ResolveInclude()` fails to find the script by the path (the same as `ScriptsMap.s_scripts[0].Path`).

**Comment by jakubmisek** [comment]
@kripper please see my answer above:

> Note to `ResolveInclude` or `Include` - please see https://docs.peachpie.io/api/ref/context/#construction - and initialize `context.RootPath` and `context.WorkingDirectory` so the functions will work properly.

**Comment by kripper** [comment]
@jakubmisek Yes, Include() now works fine:

```
        using (var context = Pchp.Core.Context.CreateEmpty())
        {
            var x = new MyPhpClass(context);
            context.WorkingDirectory = System.IO.Directory.GetCurrentDirectory();
            context.Include("", "lib.php");
            output = x.HelloWorld();
        }
```

**Comment by jakubmisek** [comment]
great, closing :)
