### ISSUE TITLE
sscanf fails to return more than one parameter by reference

### ISSUE THREAD

**Issue by josephdfoley** [peachpiecompiler/peachpie#889]
Taken from codeigniter's Router.php, roughly:

```php
$controller = 'user/login';

$returnVal = sscanf($controller, "%[^/]/%s", $c, $m);
```

$returnVal is 2, $c is user, but $m is null.  Internally, ParseString() internally seems to be working properly, with $result[1] being login, but the assignment to $arguments[0] doesn't survive to the caller.

**Comment by jakubmisek** [comment]
thank you @josephdfoley!
