### ISSUE TITLE
session_set_cookie_params doesn't support PHP 7.3.0+ array parameters

### ISSUE THREAD

**Issue by josephdfoley** [peachpiecompiler/peachpie#893]
As described at https://www.php.net/manual/en/function.session-set-cookie-params.php
session_set_cookie_params in php 7.3+ can take an array of parameters, rather than individual params.  This leads to weirdness when the peachpie version is set to 7.3.0:
3>  C:\Users\jfoley\.nuget\packages\peachpie.net.sdk\1.0.0-preview5\build\Peachpie.NET.Core.Sdk.targets(245,5): error : Conversion from 'PhpArray' to 'Int32' not implemented at C:\...\vendor\simplesamlphp\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php(82, 17)
Code in question:

        if (!headers_sent()) {
            if (version_compare(PHP_VERSION, '7.3.0', '>=')) {
                /** @psalm-suppress InvalidArgument  This annotation may be removed in Psalm >=3.0.15 */
                session_set_cookie_params([
                    'lifetime' => $params['lifetime'],
                    'path' => $params['path'],
                    'domain' => $params['domain'],
                    'secure' => $params['secure'],
                    'httponly' => $params['httponly'],
                    'samesite' => $params['samesite'],
                ]);
            } else {
                session_set_cookie_params(
                    $params['lifetime'],
                    $params['path'],
                    is_null($params['domain']) ? '' : $params['domain'],
                    $params['secure'],
                    $params['httponly']
                );
            }
        }

It also doesn't get reported as a PHPXXXX error, so Visual Studio doesn't let you double click on it to go to the line.  

This also applies to setcookie and setcookieraw

**Comment by jakubmisek** [comment]
thank you, it was 

- a bug/feature in the compiler which does not allow to compile implicit conversion array->int
- unimplemented session_set_cookie_params() function

Although session cookie parameters have to be set in your ASP.NET Core application, this function won't have the desired effect.
