### ISSUE TITLE
DateInterval::createFromDateString creates TimeSpan of zero

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#897]
an call to `DateInterval::createFromDateString` with "P24M" or "24 months" does create a `TimeSpan `with zero months (in fact all values are zero).

if `DateInterval` is created using its constructor `new DateInterval('P24M')` the correct `TimeSpan` is created.

As I side note: I used a peachpie version dated 11th November 2020 c11c81098926988c3cebb36f8472fba226ef8e56, but as far as I can see there has been no substantial changes made to DateInterval since then.

**Comment by jakubmisek** [comment]
From the PHP manual - `DateInterval::createFromDateString()` - Uses the normal date parsers and sets up a DateInterval from the relative parts of the parsed string.

And when running in PHP, I'm getting `FALSE` and a warning - so we should return `FALSE` instead of empty TimeSpan, right?
```
Warning: DateInterval::createFromDateString(): Unknown or bad format (P24M) at position 1 (2): Unexpected character
```

**Comment by jan-ai** [comment]
Sorry for misleading into the wrong direction. We are using "24 months" in our code, but I also tried "P24M" as an alternative (as I've seen that from code in peachpie).

I believe the documentation for what should be possible can be found here https://www.php.net/manual/en/datetime.formats.relative.php

> And when running in PHP, I'm getting FALSE and a warning - so we should return FALSE instead of empty TimeSpan, right?

So yes for "P24M" peachpie should return false, but for "24 months" it should return a valid TimeSpan.

**Comment by jakubmisek** [comment]
great! thanks for confirming, it should be fixed now

**Comment by jan-ai** [comment]
As far as I can see from the commit 69999a07773d5d3be30b077ac6a8480d11e51d7f it should solve the "P24M" problem, but not the problem that "24 months" returns an TimeSpan of Zero (not null). Have you tried this?

**Comment by jakubmisek** [comment]
`DateInterval::createFromDateString` returns false, it does not return zero anymore

**Comment by jan-ai** [comment]
I agree, but I'm trying to say that **DateInterval::createFromDateString('24 months')** should return

```
DateInterval Object
(
    [y] => 0
    [m] => 24
    [invert] => 0
    [d] => 0
    [h] => 0
    [i] => 0
    [s] => 0
    [f] => 0
    [days] =>
)
```

but returns

```
DateInterval Object
(
    [y] => 0
    [m] => 0
    [invert] => 0
    [d] => 0
    [h] => 0
    [i] => 0
    [s] => 0
    [f] => 0
    [days] =>
)
```

**Comment by jakubmisek** [comment]
@jan-ai oh I see now
`date_parse`, `strtotime`, and `DateInterval::createFromDateString` does not parse well string `'24 months'`
