### ISSUE TITLE
Alternative signature available as of PHP 7.3.0 for "setcookie" is not supported

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#898]
Using `setcookie` like this ...

`setcookie ( string $name , string $value = "" , array $options = [] )`

throws an error of type `Conversion from 'PhpArray' to 'Int32' not implemented` because PeachPie expects an `int` according to this ...

`setcookie ( string $name , string $value = "" , int $expires = 0 , string $path = "" , string $domain = "" , bool $secure = false , bool $httponly = false ) 
`

**Comment by menturion** [comment]
Just saw ... similar to this issue report https://github.com/peachpiecompiler/peachpie/issues/893

**Comment by jakubmisek** [comment]
thanks @menturion !
