### ISSUE TITLE
[Question] How to consume a .nuget packed vendor lib in a web app?

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#900]
I am trying to reduce the complexity of a large PHP web app by packing separable parts into several NuGet packages. 

A useful first approach to test this might be to ...

1. put all vendor libs into a separate .net project and then to reference the local NuGet package (e.g. by `<PackageReference Include="vendorLib" Version="1.0.0-*" />` with corresponding entry `<add key="local-packages" value="../venderlib/bin/Debug" />` in the `NuGet.Config` file),
2. build a `.nupkg` file and 
3. reference it in the web app project.      _<-- This is the challenge_

(1) and (2) are done but I am not able to reference the lib and to run the app finally.

1st approach was to reference it within the server's `.csproj` file by ...
```
  <ItemGroup>
    <PackageReference Include="vendorLib" Version="1.0.0-*" />
  </ItemGroup>
```

RESULT: VS shows that the `vendorLib` is available. Building the app, however, fails due to the vendor libs are not known in the web app. 

So I tried to reference the `vendorLib` within the `.msbuildproj` of the app. 
RESULT: Build process succeeded but the browser displays now that `the page can't be found`. 

What am I doing wrong? 
Is there any article of how to consume (a) .nuget package(s) (based on PHP, e..g. vendor libs) within a `netstandard2.1` _WEB APP_?

**Comment by jakubmisek** [comment]
That's what we do in most projects. Either build an entire vendor folder or single composer packages individually; Although we reference the project, not the resulting NuGet package.

Our project file for the /vendor folder, **inside the vendor folder** (that's why we set **`<PhpRelativePath>`** property):
```xml
<Project Sdk=""Peachpie.NET.Sdk"">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PhpRelativePath>vendor</PhpRelativePath>
  </PropertyGroup>

  <ItemGroup>
    <Compile
        Include='**/*.php;**/*.inc;**/*.php5;'
        Exclude='**/tests/**;**/test/**;'
    />
    <Content Include='**' Exclude='
obj/**;bin/**;.vs/**;
**/*.php;
**/composer.json;**/composer.lock;
*.manifest;*.msbuildproj;**/tests/**;'
        CopyToOutputDirectory='PreserveNewest'>
        <PackagePath>contentFiles/any/$(TargetFramework)/$(PhpRelativePath)/</PackagePath>
        <Link>$(PhpRelativePath)/%(RecursiveDir)%(Filename)%(Extension)</Link>
        <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

</Project>
```

This produces either a NuGet with the content files or what's easier is to reference it as a `<ProjectReference>`.

The **PackageReference**: (`PrivateAssets` is important)
```xml
<PackageReference Include='vendor' Version='0.0.0-*' PrivateAssets='none' />
```

Or the **ProjectReference**
```xml
<ProjectReferenceInclude='vendor/vendor.msbuildproj' />
<Compile Remove="vendor/**" />
```

**Comment by menturion** [comment]
@jakubmisek 

Many many thanks! 

I got it running (with the `PackageReference`). 
I will try referencing the project via `ProjectReferenceInclude` later after some further tests. 

Now I will be able to sleep well today :)

**Comment by menturion** [comment]
Cont'd.

Unfortunately, I was not able to get it to work using the project reference (`<ProjectReference Include="..." />`) instead.
RESULT: `The page can't be found`

Anyway, it would be great if you could add a working web-app-vendor-template (ProjectReference/ PackageReference) to your repo sometime.  This could also be very useful for others.

**Comment by menturion** [comment]
I now got it also wokring with referencing subparts inside the main project structure (e.g. `vendor` folder etc.) using `ProjectReference`.

**Comment by jakubmisek** [comment]
@menturion great! Good idea making a sample project, I'll try to create one.
