### ISSUE TITLE
pcre pattern not parsed

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#901]
- [x] https://github.com/peachpiecompiler/peachpie-perlregex/issues/5 
- [x] https://github.com/peachpiecompiler/peachpie-perlregex/issues/6
- [x] https://github.com/peachpiecompiler/peachpie-perlregex/issues/7 (to prevent future problems with character class subtractions)

---

the following pattern is correct, although it throws `A subtraction must be the last element in a character class.`

```
/^[ !#-[\]-~]*\z/
```
and
```
{\(([^()]|(?R))*\)}A
```

Example:

```php
var_dump(preg_match('/^[ !#-[\]-~]*\z/', $subject));
```

**Comment by roberthusak** [comment]
Fixed in [peachpie-perlregex](https://github.com/peachpiecompiler/peachpie-perlregex). @jakubmisek Will you bump the version, publish it and update the reference, please?
