### ISSUE TITLE
Function 'openssl_get_cipher_methods' does not exist

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#902]
Test whether function `openssl_get_cipher_methods` (https://www.php.net/manual/de/function.openssl-get-cipher-methods.php) exists returns `false`:

```
if (!function_exists('openssl_get_cipher_methods')) {
// TRUE
}
```

I would like to add function `openssl_get_cipher_methods `to the OpenSSL functions which should be supported: https://docs.peachpie.io/compatibility-status/

**Comment by jakubmisek** [comment]
Thanks. I don't know why it's not listed on the compatibility-status page, it should be there.

**Comment by menturion** [comment]
Libraries like ...

--  paragonie / sodium_compat 
https://github.com/paragonie/sodium_compat

--  defuse / php-encryption 
https://github.com/defuse/php-encryption

are using this function.

**Comment by jakubmisek** [comment]
I see, thank you; it shouldn't be difficult to implement that.

**Comment by jakubmisek** [comment]
Seems the function is already implemented since 2019. https://github.com/peachpiecompiler/peachpie/blob/8629bbb68946968a122631dba686520a0d45340b/src/Peachpie.Library/OpenSSL.cs#L391 

Can you please debug it again?

**Comment by menturion** [comment]
You are absolutely right.
I have done separate tests and the result was that the function does not exist.

I have no explanation for the different behavior now. ... Obviously my mistake.


`openssl_get_cipher_methods` returns 10 cipher methods. Unfortunately, the needed cipher method `aes-256-ctr` isn't supported.

**Comment by jakubmisek** [comment]
I see, so we need to add `aes-256-ctr`.

Note for me - CTR cipher mode is not in .NET but it can be easily implemented as in https://gist.github.com/hanswolff/8809275 within our `PrepareCipher` method
