### ISSUE TITLE
A CONST isn't processed correctly within a trait

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#903]
Please have a look at ...

https://github.com/PHPSocialNetwork/phpfastcache/blob/3c888d901e7b84025274682cc7ae18130ca76f7c/lib/Phpfastcache/Config/IOConfigurationOptionTrait.php#L21

where the const `SAFE_FILE_EXTENSIONS` is declared and 

https://github.com/PHPSocialNetwork/phpfastcache/blob/3c888d901e7b84025274682cc7ae18130ca76f7c/lib/Phpfastcache/Config/IOConfigurationOptionTrait.php#L121

where method `setCacheFileExtension` is using the const `SAFE_FILE_EXTENSIONS`.

Method `setCacheFileExtension` is called with `$cacheFileExtension = 'txt'`.

The value of `$safeFileExtensions` is shown below after exploding const `SAFE_FILE_EXTENSIONS` at line 121:
```
		Pchp.Core.PhpValue.AsString returned	"SAFE_FILE_EXTENSIONS"	string
+		Pchp.Library.Strings.explode returned	array (length = 1)	array
+		this	{Phpfastcache.Config.IOConfigurationOptionTrait<Phpfastcache.Drivers.Files.Config>}	Phpfastcache.Config.IOConfigurationOptionTrait<Phpfastcache.Drivers.Files.Config>
		cacheFileExtension	"txt"	string
-		safeFileExtensions	array (length = 1)	array
		[0]	"SAFE_FILE_EXTENSIONS"	string
```

Consequence is that condition `if (!\in_array($cacheFileExtension, $safeFileExtensions, true)) {` is true, which of course is wrong.

When I define SAFE_FILE_EXTENSIONS as `protected $SAFE_FILE_EXTENSIONS = 'txt|cache|db|pfc';` it works.

The title of this bug report is probably wrong because I am not aware of the exact reason for the issue.

`phpfastcache` will work (with 'files' driver) when this issue gets fixed.

**Comment by jakubmisek** [comment]
thank you for finding the issue!

Seems the `SAFE_FILE_EXTENSIONS` as a global constant won't get declared. I assume the whole file didn't get autoloaded for some reason. I'll take a look on that.

**Comment by jakubmisek** [comment]
note for me - this TODO needs to be implemented https://github.com/peachpiecompiler/peachpie/blob/47894d7bb4904175c3194ff12398d08d55f999d2/src/Peachpie.CodeAnalysis/Symbols/Php/PhpTypeSymbolExtensions.cs#L190

**Comment by menturion** [comment]
Is this fixed by https://github.com/peachpiecompiler/peachpie/commit/51e491ba5913156a6a9b1f086518637e8ec4a4d3? 
Does a test already make sense?

**Comment by jakubmisek** [comment]
it is fixed, and we should add some tests as well. At least I'll add a note in https://github.com/peachpiecompiler/peachpie/issues/752

**Comment by menturion** [comment]
As you mentioned that this issue is fixed I tested it with v1.0.0-appv4532.

Still getting ...

```
PHP (Notice): Use of undefined constant SAFE_FILE_EXTENSIONS - assumed 'SAFE_FILE_EXTENSIONS'
PHP: Information: Use of undefined constant SAFE_FILE_EXTENSIONS - assumed 'SAFE_FILE_EXTENSIONS'
```

for using the global constant SAFE_FILE_EXTENSIONS within the trait here https://github.com/PHPSocialNetwork/phpfastcache/blob/3c888d901e7b84025274682cc7ae18130ca76f7c/lib/Phpfastcache/Config/IOConfigurationOptionTrait.php#L121.

**Comment by jakubmisek** [comment]
note for me: and this to-do https://github.com/peachpiecompiler/peachpie/blob/444ccaf4292196122d9a1376dcf1383dc3b7f573/src/Peachpie.CodeAnalysis/CodeGen/CodeGenerator.Emit.cs#L3114

**Comment by jakubmisek** [comment]
Thank you @menturion for checking it again, it has been implemented now and checked.

**Comment by menturion** [comment]
Just test with `1.0.0-appv4539`. 
It works 👍
