### ISSUE TITLE
implement "aes-256-ctr" cipher

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#904]
I see, so we need to add `aes-256-ctr`.

Note for me - CTR cipher mode is not in .NET but it can be easily implemented as in https://gist.github.com/hanswolff/8809275 within our `PrepareCipher` method

_Originally posted by @jakubmisek in https://github.com/peachpiecompiler/peachpie/issues/902#issuecomment-774071520_

**Comment by menturion** [comment]
In my case, this issue blocks further testing due to relevant data is encrypted based on the `aes-256-ctr` cipher method.

**Comment by menturion** [comment]
@jakubmisek 

Thanks. I just tested it.

`defuse / php-encryption`  performs runtime tests. Among others it tests whether the AES CTR mode is working correctly, see https://github.com/defuse/php-encryption/blob/b4e6e8035118de6cffd4c131ad886a9f12b34f84/src/RuntimeTests.php#L201-L227. For this purpose Defuse encrypts (see line 222) resp. decrypts (see line 225) a test vector from NIST SP 800-38A ...

    private static function AESTestVector()
    {
        // AES CTR mode test vector from NIST SP 800-38A
        $key = Encoding::hexToBin(
            '603deb1015ca71be2b73aef0857d7781' .
            '1f352c073b6108d72d9810a30914dff4'
        );
        $iv        = Encoding::hexToBin('f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff');
        $plaintext = Encoding::hexToBin(
            '6bc1bee22e409f96e93d7e117393172a' .
            'ae2d8a571e03ac9c9eb76fac45af8e51' .
            '30c81c46a35ce411e5fbc1191a0a52ef' .
            'f69f2445df4f9b17ad2b417be66c3710'
        );
        $ciphertext = Encoding::hexToBin(
            '601ec313775789a5b7a7f504bbf3d228' .
            'f443e3ca4d62b59aca84e990cacaf5c5' .
            '2b0930daa23de94ce87017ba2d84988d' .
            'dfc9c58db67aada613c2dd08457941a6'
        );


        $computed_ciphertext = Crypto::plainEncrypt($plaintext, $key, $iv);
        Core::ensureTrue($computed_ciphertext === $ciphertext);


        $computed_plaintext = Crypto::plainDecrypt($ciphertext, $key, $iv, Core::CIPHER_METHOD);
        Core::ensureTrue($computed_plaintext === $plaintext);
    }

... and compares the computed outcome with the expected one.

This test fails (here: encryption, line 222).

**Comment by roberthusak** [comment]
@menturion Thanks for the test case, I'll look into that. AES CTR works in our tests, but they might miss certain circumstances.

**Comment by roberthusak** [comment]
AES CTR indeed works well, but we have problems comparing the resulting strings (you can check that by replacing `$computed_ciphertext === $ciphertext` with `bin2hex($computed_ciphertext) === bin2hex($ciphertext)`). I created #910 specially to track that, I'll close this issue as `aes-256-ctr` is implemented.

**Comment by menturion** [comment]
Thanks for the info. 
I see. According to #775 this seems to be a long-standing issue.
