### ISSUE TITLE
 stream_socket_server

### ISSUE THREAD

**Issue by Arkantium** [peachpiecompiler/peachpie#909]
Have planned to implement the php stream class ?

- [x] stream_socket_server
- [x] stream_socket_client
- [x] stream_set_blocking
- [x] stream_socket_accept

I need that for my project ;)

**Comment by jakubmisek** [comment]
@Arkantium seems the functions are implemented already; please check you are running the latest PeachPie (at least `1.0.0-preview5`)

If there is any misbehavior, please comment

**Comment by Arkantium** [comment]
Hi,
```
 if (!$this->serverSocket = stream_socket_server("tcp://0.0.0.0:{$this->serverPort}", $err, $errstr))
        {
            throw new \RuntimeException("Failed to listen on the port {$this->serverPort}");
        }
```
I go to my throw.

**Comment by jakubmisek** [comment]
This means the function `stream_socket_server` exists but returns `FALSE`. 

An additional error message will be in the Debug Output - do you see anything there?


Thanks

**Comment by jakubmisek** [comment]
you're right! the core functionality is actually not implemented and outputs an error message.

**Comment by Arkantium** [comment]
Exception levée : 'Pchp.Library.Spl.RuntimeException' dans AvayaCeicom.dll
PHP (Warning): Error connecting '0.0.0.0': 0.0.0.0

**Comment by Arkantium** [comment]
Ha ok :) send me an update when it will be available Thanks !

**Comment by jakubmisek** [comment]
@Arkantium Implemented, but not tested yet. 

Available since `1.0.0-appv4546`, NuGet feed https://ci.appveyor.com/nuget/peachpie

**Comment by Arkantium** [comment]
Same, my steam_socket_server return null

**Comment by jakubmisek** [comment]
![image](https://user-images.githubusercontent.com/842150/108641752-546e3f00-74a1-11eb-82fb-69e570912aac.png)

Are you sure you reference the latest version 1.0.0-appv4546 ? 
What message is in the Debug Output?

**Comment by Arkantium** [comment]
Yzah:
    <PackageReference Update="Peachpie.App" Version="1.0.0-appv4546" />
And samle Output:

Exception levée : 'Pchp.Library.Spl.RuntimeException' dans AvayaCeicom.dll
PHP (Warning): Error connecting '0.0.0.0': 0.0.0.0

**Comment by jakubmisek** [comment]
this is probably an old version, this error message is no longer there since `1.0.0-appv4546`

**Comment by jakubmisek** [comment]
nuget feed can be added using the following command:
```
dotnet nuget add source https://ci.appveyor.com/nuget/peachpie -n appveyor-peachpie
```

then change the version in your project file (`.msbuildproj`) or `global.asax` if you have it.

**Comment by Arkantium** [comment]
1):
I think u have problem on the garbage collector, if my socket crash (exception) my soft has a function for relaunch the socket and at this time i got error because ur framework say the port is taked (by the broken socket ?)

2) the unpack php function create a "full packet" and he fill all blank (0) by 1:

I wait this packet: 2150236161
the packet returner by unpack: -2144731135)

My waiting packet:  802A0001
the packet "unpack" : FFFFFFFF802A0001

(No problem with my code in real php server)

**Comment by jakubmisek** [comment]
1/ You are right. There is different behavior in garbage collection since in .NET it is indeterministic unlike in PHP.

It is always recommended to `fclose()` the socket resource.

2/ what is the log in the debug output?

**Comment by Arkantium** [comment]
No output, it's a bug :) (not an exception)
My first received packet is "altered" in peachpie (same code on php has functional) (after test it, it's not due to pack / unpack function) It's the interpretation of the C# socket i think (on 4 packet only the first does not match the real packet send)

**Comment by jakubmisek** [comment]
We would need a test case for that.

**Comment by Arkantium** [comment]
Yeah i work on in ;) (I create a client in php for send what i need to the socket in peachpie for have more information about this bug)

**Comment by Arkantium** [comment]
the byte order received by peachpie is not good...

Try with this code:


// SERVER (executed by PHP)

```
<?php

if (!$server = stream_socket_server("tcp://0.0.0.0:7777"))
{
    throw new \RuntimeException("Failed to listen on the port 7777");
}

if (!$client = stream_socket_accept($server))
{
    throw new \RuntimeException("Failed to accept client socket");
}

$message = pack('NNNN', 0x802A0001, 123456, 0, 0);

fwrite($client, $message, strlen($message));



```

// CLIENT (executed by PHP work well) but (C# compiled) wrong reading packet
// Reading: 11000111 00101010 00000000 00000001 00000000 00000001 11010100 01000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
// Instead: 10000000 00101010 00000000 00000001 00000000 00000001 11100010 01000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
```

if (!$client = stream_socket_client('tcp://127.0.0.1:7777'))
{
    echo ("Failed to connect on tcp://127.0.0.1:7777");
}

$buffer = fread($socket, 1024);

foreach (str_split($buffer) as $c)
{
    echo str_pad(decbin(ord($c)), 8, "0", STR_PAD_LEFT) . ' ';
}


```

**Comment by jakubmisek** [comment]
I see; `fread` actually returns the correct set of bytes, but `str_split` corrupts them (decodes to Unicode string). Will be fixed.

**Comment by Arkantium** [comment]
Yeah, ok for the str_split but same on unpack:

`var_dump( unpack('N2int', $buffer) );
`
Reading: -2144731135 , 123456
Instead:  2150236161 , 123456

**Comment by jakubmisek** [comment]
test case please :)

Also if you'd have a test case for the `unpack()` with `N`, I'd create a separate issue for that

**Comment by Arkantium** [comment]
Yeah,

That the code:

http://sandbox.onlinephpfunctions.com/code/c520d060fb077bc264fefedb05b18784736c45a9

```
$buffer = hex2bin('802A00010001E2400000000000000000');

var_dump( unpack('Nint', $buffer) );

// Wanted: 2150236161
// Result: -2144731135
```

**Comment by aaurizon** [comment]
@jakubmisek the bug stems from the fact that a 64 bit integer is returned instead of 32

-2144731135 is the 64 bits version of 2150236161, the calcul is right, but the type of variable is wrong

**Comment by jakubmisek** [comment]
alright! thanks @aaurizon. I guess there is no difference between 64bit and 32bit php

**Comment by jakubmisek** [comment]
@aaurizon `Convert.ToUInt32()` just throws an exception on overflow (negative value or > Uint32.MaxValue). I Guess `unchecked( (uint)(whole_value) )` is what we want here.

**Comment by jakubmisek** [comment]
ok, stream_socket functions have been implemented.

Please start a new issue if there would be anything else, either related to `pack` or other single-byte string issues.
