### ISSUE TITLE
Comparison of binary strings is not correct

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#910]
Test case:
```php
function test() {
  $a = hex2bin('ca') . hex2bin('84');
  $b = hex2bin('ca84');
  echo (int)($a === $b);
}

test();
```
PHP outputs `1`, whereas Peachpie `0`.

The problem arises in https://github.com/peachpiecompiler/peachpie/issues/904#issuecomment-781203859 and it's also mentioned in https://github.com/peachpiecompiler/peachpie/issues/775#issuecomment-651799340.

**Comment by jakubmisek** [comment]
Notes for me:
- [ ] `PhpString.Blob.ToString()` needs to glue byte array segments together before decoding them to Unicode string.
- [ ] implement `Comparison.Compare(PhpString, PhpString)`

**Comment by menturion** [comment]
Any progress on fixing this basic issue?
