### ISSUE TITLE
[PDO] Executing a prepared statement with "LIMIT ?" turns into a syntax error

### ISSUE THREAD

**Issue by dirant** [peachpiecompiler/peachpie#914]
Hi,
I was testing peachpie with a small project and found out that the following code throws a syntax error at runtime:
```PHP
// PDO created with PDO::ATTR_EMULATE_PREPARES  => true
$prepared = $pdo->prepare("SELECT * FROM users LIMIT ?, ?");
$prepared->execute([0, 10]);
```
The resulting statement turns out to be `SELECT * FROM users LIMIT '0', '10'` because the `BindParameters` method assumes that all parameters can be bound as strings without problems.

I'm not sure how to contribute (plus I know less than 0 in terms of C#), but I tried looking around and I think the problem is here:

https://github.com/peachpiecompiler/peachpie/blob/506dfb98f54fea05304a66761849f4dec36cc0c7/src/PDO/Peachpie.Library.PDO/PDOStatement.cs#L996

I think there should be another condition checking if `current.Value.TypeCode` is an integer or a float and bind accordingly

At the moment the only way around this is binding numbers separately but if a project makes heavy use of this pattern it becomes a little cumbersome

**Comment by dirant** [comment]
Another temporary patch can be extending PDOStatement:
```PHP
class AutoBindingPDOStatement extends PDOStatement {
	public function execute($input_parameters) : bool {
		foreach ($input_parameters as $name => $value) {
			$this->bindValue(is_int($name) ? ($name + 1) : (':'.$name), $value, is_int($value) ? PDO::PARAM_INT : PDO::PARAM_STR);
		}
		return parent::execute();
	}
}
```

and then setting the ATTR_STATEMENT_CLASS attribute `$pdoInstance->setAttribute(PDO::ATTR_STATEMENT_CLASS, [AutoBindingPDOStatement::class]);`

**Comment by jakubmisek** [comment]
@dirant thanks for the issue. You are right - the parameter may be bound as integer exactly where you found it.

We need to check if we can do it in general, I'm not aware of all the side effects this might have.

**Comment by jakubmisek** [comment]
@dirant should be implemented now (the same problem was with bool values)

Please let me know if that worked.

**Comment by dirant** [comment]
Quick question, I cloned the repo locally but I'm not sure how to build/test the local version.
I tried adding to the Website project created with `dotnet new web -lang PHP`  the following
```
<ProjectReference Include="..\..\peachpie-master\src\PDO\Peachpie.Library.PDO\Peachpie.Library.PDO.csproj" />
```
I don't know if there is a better way to do it

**Comment by jakubmisek** [comment]
the steps can be found at https://github.com/peachpiecompiler/peachpie/blob/master/docs/Building-Peachpie.md#developing-with-peachpie-from-sources 

- build peachpie solution
- use the script to deploy `1.0.0-dev` version of peachpie to your local nuget store
- use the `1.0.0-dev` version in your project

**Comment by dirant** [comment]
Great thank you!

**Comment by dirant** [comment]
Ok, it worked

**Comment by jakubmisek** [comment]
@dirant thanks for the confirmation!
