### ISSUE TITLE
stream_set_blocking -  // Unimplemented in Win32 PHP.

### ISSUE THREAD

**Issue by Arkantium** [peachpiecompiler/peachpie#915]
Hi,

stream_set_blocking is not functional and i see on PhpStream.cs :
```
 case StreamParameterOptions.BlockingMode:
                    // Unimplemented in Win32 PHP.
                    return false;
```

Possible to implement it ? 

https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Library/Streams/PhpStream.cs#L570

**Comment by jakubmisek** [comment]
socket streams may have it implemented; I guess you'd like to set this value to `false`?

**Comment by Arkantium** [comment]
Yes, i need the value to false for "Non Blocking Socket"

**Comment by jakubmisek** [comment]
should be implemented now, but not tested
