### ISSUE TITLE
StartupObject does not appear to be complete.

### ISSUE THREAD

**Issue by Adahel** [peachpiecompiler/peachpie#917]
For PHP programmers, desktop applications are generally not the priority, but times are changing. I cannot implement a full Main method in console applications. I'm horrible to describe, so I'm going to show you a self-explanatory code:

`<StartupObject>Namespace\program::main</StartupObject>` -> It works perfectly.

```
<?php

namespace Namespace;

class program
{
    public static function main(String ...$args) //Does not work, alternative: Environment::GetCommandLineArgs();
    {
        echo "Hello .NET World!";
        return 0;  //Does not work, alternative: Environment::Exit(0);
    }
}
?>
```
All major .NET programming languages support the full constructor (for example, C#, VB.NET, F#) and implementation shouldn't be difficult. I would be happy with a workaround on the compiler for version 1.0, unless it is too late for version 1.0.
If I made a mistake, feel free to edit my comment!

**Comment by jakubmisek** [comment]
In PHP, you suppose to use `$argv`, `$argc` global variables. Although you're right, the ExitCode is ignored, and the program always exits with code `0`.

Also, the compiler crashes if the `main` function is not static - should either instantiate the containing class or reports a readable error message.

**Comment by jakubmisek** [comment]
@Adahel Thanks again for the issue. The exit code will be handled now. It will work for global code as well (e.g. `<StartupObject>program.php</StartupObject>`).

To workaround the command-line arguments, I would do the following:

```php
class program
{
    static function main() {
        global $argv, $argc;

        print_r($argv);
        return 1;
    }
}
```
