### ISSUE TITLE
Plugin didnt activate correctly

### ISSUE THREAD

**Issue by sorindavid99** [peachpiecompiler/peachpie#920]
![image](https://user-images.githubusercontent.com/78214084/110103839-116c6f80-7daf-11eb-8aef-b869ba16ecb5.png)
this is what i see when i press activate on the plugin.

**Comment by jakubmisek** [comment]
This is related to the following project: https://github.com/iolevel/wpdotnet-sdk/issues

Please provide the steps to reproduce the issue, version of wpdotnet, and - the steps to reproduce the issue. Plugin copied from sources or installed from dashboard?
