### ISSUE TITLE
Plugin Elementor  from Elementor is failing

### ISSUE THREAD

**Issue by hlynnerup** [peachpiecompiler/peachpie#924]
Hi Peachpie

I have downloaded the plugin Elementor to .\wordpress\wp-content\plugins (I'm using .Net core 5.0).
After download I debug WP, enter plugins and activates the plugin.
After the activation a lot of PHP (I think) is written in the top of the dashboard, the website (any page!)

Should I expect that Elementor is working in .NET?

TIA
Henrik

<img width="1784" alt="WP 2021-03-21_11-39-25" src="https://user-images.githubusercontent.com/34379969/111901860-b8513c80-8a3a-11eb-84a6-6253bba3e3ae.png">

**Comment by jakubmisek** [comment]
This means the plugin has not been compiled. 

See the example project at https://github.com/iolevel/peachpie-wordpress. Plugins and themes have to be placed separately into MyContent which gets compiled.

**Comment by jakubmisek** [comment]
duplicate https://github.com/peachpiecompiler/peachpie/issues/925
