### ISSUE TITLE
Build classlib for other platforms (Linux, Mac, etc.)

### ISSUE THREAD

**Issue by anggara-ts** [peachpiecompiler/peachpie#926]
Hi, is it possible to generate classlib in format other than `.dll`?
I have tried to run tutorial about [Building Class Library](https://docs.peachpie.io/get-started/#class-library) and it generated dll file successfully.

```bash
$ dotnet new -i "Peachpie.Templates::*"
$ dotnet new classlib -lang PHP
$ dotnet build

Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/johndoe/___dotnet/lib/lib.msbuildproj (in 1.89 min).
  PeachPie PHP Compiler version 1.0.0+f0385564026b8b791ed633547b348f049f51f18a
  lib -> /Users/johndoe/___dotnet/lib/bin/Debug/netstandard2.0/PhpLib1.dll
  Successfully created package '/Users/johndoe/___dotnet/lib/bin/Debug/PhpLib1.1.0.0.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:01.37
```
But it can not be loaded when I'm trying to run it from Mac.
Tried to publish it using `dotnet publish -c Release -r osx-x64` but it still generating dll file and can not be loaded.

```bash
$ php -dextension=/Users/johndoe/___dotnet/lib/bin/Release/netstandard2.0/osx-x64/publish/PhpLib1.dll  -r 'echo "Hello";'
PHP Warning:  PHP Startup: Unable to load dynamic library '/Users/johndoe/___dotnet/lib/bin/Release/netstandard2.0/osx-x64/publish/PhpLib1.dll' (tried: /Users/johndoe/___dotnet/lib/bin/Release/netstandard2.0/osx-x64/publish/PhpLib1.dll (dlopen(/Users/johndoe/___dotnet/lib/bin/Release/netstandard2.0/osx-x64/publish/PhpLib1.dll, 9): no suitable image found.  Did find:
	/Users/johndoe/___dotnet/lib/bin/Release/netstandard2.0/osx-x64/publish/PhpLib1.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
	/Users/johndoe/___dotnet/lib/bin/Release/netstandard2.0/osx-x64/publish/PhpLib1.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00), /opt/local/lib/php74/extensions/no-debug-non-zts-20190902//Users/johndoe/___dotnet/lib/bin/Release/netstandard2.0/osx-x64/publish/PhpLib1.dll.so (d in Unknown on line 0
Hello 
```

**Comment by jakubmisek** [comment]
Hi,

The file extension is always `.dll`, but it runs everywhere where .NET is supported (win, linux, osx, some IoT devices, mobile phones, ...).

You can eventually publish a self-contained application (which does not require the .NET runtime to be installed on the target machine) (https://stackoverflow.com/questions/46829860/how-to-distribute-a-net-core-2-0-console-application-on-osx)

We have a short docs also at https://docs.peachpie.io/scenarios/intermediate/self-contained-exe/

**Comment by anggara-ts** [comment]
Thanks! I think I misunderstood about the concept and tried to load generate library file directly using PHP, while it should be run under .NET framework.

So after quick searching, I had to create new "PHP CLI" project and add generated DLL file as reference.
```xml
<ItemGroup>
  <Reference Include="../lib/bin/Release/netstandard2.0/osx-x64/publish/*.dll" />
</ItemGroup>
```
Tried to run it. No error for DLL file, but the referenced PHP Class in DLL file is not detected
```bash
$ dotnet restore && dotnet run                                                                                                  
  Determining projects to restore...
  All projects are up-to-date for restore.
Unhandled exception. Error: Class 'Library\Greeter' not found in /Users/johndoe/___dotnet/cli/program.php(9,4)
Stack trace:
#0 /Users/johndoe/___dotnet/cli/program.php(12,0): main()
#1 : {main}
```

Main program:
```php
function main()
{
    echo "___dotnet says: \"Hello World!\"";
    (new Library\Greeter)->Greet();    
}

main();
```

PHP libclass source:
```php
<?php
namespace Library {

	/** A greeter class. */
	class Greeter {
		/** A method that outputs hello. */
		public function Greet(){
			echo "lib says \"Hello world!\"";
		}
	}
}
```

**Comment by jakubmisek** [comment]
you don't have to `<Reference>` the publish dll. Within your C# project either reference a project (`.msbuildproj`) or a nuget package.

You may look at https://github.com/iolevel/peachpie-samples/tree/master/php-library
Or https://github.com/iolevel/peachpie-samples/tree/master/using-csharp-from-php
