### ISSUE TITLE
Malfunction in string operations

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#929]
PeachPie still seems to be buggy with respect to string operations. 
This can be tested via the following simple test scenario, using the paragonie encryption lib https://github.com/paragonie/halite (https://packagist.org/packages/paragonie/halite): 

```
use ParagonIE\Halite\{
    File,
    KeyFactory,
    Symmetric\Crypto as Symmetric,
    Asymmetric\Crypto as Asymmetric
};
use ParagonIE\HiddenString\HiddenString as HiddenString;

$encKey = KeyFactory::generateEncryptionKey();
```

`KeyFactory::generateEncryptionKey()` instantiates a new `EncryptionKey` here https://github.com/paragonie/halite/blob/1fc48289b3759191c4f912d532b3691bf42a1eb4/src/KeyFactory.php#L87-L89
which invokes a key (i.e. string) check here https://github.com/paragonie/halite/blob/1fc48289b3759191c4f912d532b3691bf42a1eb4/src/Symmetric/EncryptionKey.php#L27

The if condition in line 27 throws the exception ('Encryption key must be CRYPTO_STREAM_KEYBYTES (32) bytes long'). 

The same malfunction can be seen in `defuse/php-encryption` lib (https://packagist.org/packages/defuse/php-encryption).

**Comment by jakubmisek** [comment]
right, sometimes string contains single-byte characters, and sometimes Unicode characters ... the recent fix (https://github.com/peachpiecompiler/peachpie/issues/928) solves the comparison of such strings, however, there is still this issue with comparing their lengths. We have to find an efficient way of doing so.

**Comment by jakubmisek** [comment]
@menturion do you have a link to `Binary::safeStrlen()` implementation please?

**Comment by menturion** [comment]
The implementation can be found here:
https://github.com/paragonie/constant_time_encoding/blob/f34c2b11eb9d2c9318e13540a1dbc2a3afbd939c/src/Binary.php#L46-L53

    /**
     * Safe string length
     *
     * @ref mbstring.func_overload
     *
     * @param string $str
     * @return int
     */
    public static function safeStrlen(string $str): int
    {
        if (\function_exists('mb_strlen')) {
            return (int) \mb_strlen($str, '8bit');
        } else {
            return \strlen($str);
        }
    }

**Comment by jakubmisek** [comment]
@menturion we have fixed a few related issues; would you be able to try the nightly build `1.0.0-appv4625` (or newer) from the nuget feed `https://ci.appveyor.com/nuget/peachpie`?

**Comment by menturion** [comment]
@jakubmisek 

I was trying to test it. However, I am getting a huge number of `Conversion from 'Nullable' to '[type]' not implemented at ... ` errors., also in vendor libs.

**Comment by jakubmisek** [comment]
@menturion thanks! yes we have to fix that first. Any examples of those `[type]`s ?

**Comment by menturion** [comment]
@jakubmisek 

I already fixed many of these issues in own codebase because it improves the quality of the code. However, when it comes to vendor libs it males less sense to fix them.

Due to errors are thrown and compilation is stopped I am only able to post the current issue. Otherwise I would have to fix all of them to give you the whole bunch of examples.

The current error is `.nuget\packages\peachpie.net.sdk\1.0.0-appv4625\build\Peachpie.NET.Core.Sdk.targets(245,5): error : Conversion from 'Nullable' to 'Double' not implemented at getid3\getid3\module.audio-video.riff.php(444, 8)` .

Although I am using an older version of getID3 the issue would be thrown here https://github.com/JamesHeinrich/getID3/blob/e54782d655120e5993ceeca9fb0e01895255ed07/getid3/module.audio-video.riff.php#L456.

`$thisfile_riff_WAVE['iXML'][0]['timecode_string_round'] = sprintf('%02d:%02d:%02d:%02d',   $h, $m, $s, round($f));`

**Comment by jakubmisek** [comment]
@menturion with https://github.com/peachpiecompiler/peachpie/issues/938 just fixed, the version `1.0.0-appv4628` should be alright (as far as we tested)

**Comment by menturion** [comment]
@jakubmisek 

Thanks, I replied here https://github.com/peachpiecompiler/peachpie/issues/938#issuecomment-819585305

**Comment by menturion** [comment]
@jakubmisek 

> 
> 
> @menturion we have fixed a few related issues; would you be able to try the nightly build `1.0.0-appv4625` (or newer) from the nuget feed `https://ci.appveyor.com/nuget/peachpie`?

I tested it with  `paragonie/halite` and got an `Checksum validation fail` exception here https://github.com/paragonie/halite/blob/1fc48289b3759191c4f912d532b3691bf42a1eb4/src/KeyFactory.php#L865

Did you test `paragonie/halite` or `defuse/php-encryption` locally? These authenticated encryption libraries perform a lot of string conversions and checks to ensure integrity. I think that PeachPie's string operations will work correctly if these libraries will work correctly on PeachPie.

**Comment by jakubmisek** [comment]
@menturion thanks for testing the latest update. So it progressed from the last time, right?

I'll test the `paragonie/halite` and `defuse/php-encryption` packages. Running tests will be enough?

**Comment by menturion** [comment]
Yes, I tested it with PeachPie version 4631.

**Comment by jakubmisek** [comment]
I have first string-related issue in https://github.com/amphp/byte-stream/blob/7a64a9ad336fc5e1e70b1c1fc1e9618a7027332e/lib/functions.php#L12 
```php
if (\strlen('…') !== 3) throw new \Error();
```

Since "`…`" is really a single character in UTF.

**Comment by jakubmisek** [comment]
As of https://github.com/peachpiecompiler/peachpie/commit/efd50bfec0a78e36950cb6e629fbd871100cb5ca, `paragonie-halite` tests report:
```
Tests: 84, Assertions: 96, Errors: 5, Failures: 1, Skipped: 51.
```

**Comment by menturion** [comment]
@jakubmisek 

I just retested it using PeachPie v4646. It seems to work now, right?

**Comment by menturion** [comment]
Halite is a high-level wrapper for Sodium requiring `paragonie/sodium_compat` which `is a pure PHP polyfill for the Sodium cryptography library and will opportunistically and transparently use the PHP extension instead of the PHP implementation, if the PECL is installed` (https://packagist.org/packages/paragonie/sodium_compat). 

Sodium `is cross-platforms and cross-languages and runs on a variety of compilers and operating systems, including Windows (with MinGW or Visual Studio, x86 and x86_64), iOS and Android` (https://doc.libsodium.org/). As far as I know Sodium encryption and decryption is part of PHP since 7.2 (https://www.php.net/manual/en/book.sodium.php) and is considered the "gold standard" for encryption in PHP. 

This said Sodium seems to be the perfect encryption/decryption library to be supported by PeachPie by default(?).

**Comment by jakubmisek** [comment]
@menturion once someone implements sodium as a .NET library, we can use it and include it by default.

**Comment by jakubmisek** [comment]
> I just retested it using PeachPie v4646. Sodium seems to work now, right?

the major issues have been fixed; the halite tests report:
```
Tests: 84, Assertions: 101, Errors: 4, Failures: 2, Skipped: 51.
```

**Comment by jakubmisek** [comment]
The last issue - string literals even when containing byte sequences (like `"\x7f\x8a"`) are ALWAYS encoded to Unicode strings in compile time. This corrupts 8bit data (unless they are not UTF8)

**Comment by jakubmisek** [comment]
with the respected 8bit string literals, there are just 3 errors left

```
Tests: 84, Assertions: 103, Errors: 3, Skipped: 51.
```

**Comment by jakubmisek** [comment]
```
Tests: 84, Assertions: 108, Errors: 1, Skipped: 51.
```

last one is issue with stat() and streams, working on a test case yet

**Comment by jakubmisek** [comment]
ok so now we have the following tests results:

```
OK, but incomplete, skipped, or risky tests!
Tests: 84, Assertions: 114, Skipped: 51.
```

Closing the issue, we'll write a few more tests for string-related operations, but so far this resolved a lot of similar issues already!

**Comment by menturion** [comment]
Great!

**Comment by menturion** [comment]
> 
> 
> @menturion once someone implements sodium as a .NET library, we can use it and include it by default.

A Sodium .NET library is provided here...
https://www.nuget.org/packages/Sodium.Core
https://github.com/tabrath/libsodium-core/
