### ISSUE TITLE
 No executable found matching command "dotnet-compile-php"

### ISSUE THREAD

**Issue by jstacoder** [peachpiecompiler/peachpie#93]
after pulling latest updates and attempting to run the basic web example with aspnetcore updated to 2.0.0 getting this error:

```
Peachpie PHP Compiler. 
Website ->C:\Users\jstac\git\newpeachweb\Website\bin\Debug\netcoreapp2.0\newpeachweb.dll

No executable found matching command "dotnet-compile-php"
```

im sure you dont officially support aspnetcore2.0 yet but any help would be awesome, im really waiting for aspnetcore2.0/php apps

**Comment by jstacoder** [comment]
n/m spoke too soon, had old dependencies in that project, new project fixed it,

**Comment by jakubmisek** [comment]
Hi, just for the info, we have just moved targets to .netstandard  2.0 so there might be other simillar issues ... official annoucement is coming.

With this change, it is finally possible to compile PHP projects without having dotnet SDK 1.0.

Please keep us informed if you run into anything. Thanks : )

asp.net core 2.0 support is already working, samples will be updated accordingly.
