### ISSUE TITLE
Stylesheet missing in compiled version

### ISSUE THREAD

**Issue by BajanGerry** [peachpiecompiler/peachpie#933]
Hi Guys,

First off thanks for creating this, I have been wanting to find a way to compile my PHP for simple desktop apps for ages.

I do have a problem with my current application though in that when I compile and run the app from the executable I do not get the stylesheet applied to the application. If I run the app in Visual Studio everything works and looks perfect but the compiled application doesn't seem to have the .css information. What do i do to fix this?

Thanks,
Gerry

**Comment by BajanGerry** [comment]
I manually copied the style.css file to the "\bin\Release\net5.0\wwwroot\" directory and it resolved the problem but I should have expected that that would have been down during the Build process?

**Comment by jakubmisek** [comment]
Hi! I'm glad you like our tools.

I understand the compilation is a bit complex process. Producing the `.dll` is one thing, packing it with content files is another.

In .NET project, the content files are usually treated separately, and then copied over during the `dotnet publish` process.

If you edit the project file (`.msbuildproj` file), you can see there are two item groups `<Compile>` and `<Content>`. Modify the `<Content>` element with `CopyToOutputDirectory="Always"` to get your content (stylesheets etc.) copied together with the binaries. More information can be found at https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#content
