### ISSUE TITLE
Executable optimization and dependencies

### ISSUE THREAD

**Issue by Jammmmm** [peachpiecompiler/peachpie#94]
A couple of questions:

1. Is it possible to minimize the size and number of DLL's that I have to include with my generated executable? With a minimal Hello World PHP script, compiled as Release, I found I needed the following:

> 	 83,456 helloworld.exe
> 	851,456 Peachpie.Library.dll
> 	 19,456 Peachpie.Library.MsSql.dll
> 	 22,016 Peachpie.Library.MySql.dll
> 	 16,896 Peachpie.Library.Scripting.dll
> 	 78,336 Peachpie.Library.XmlDom.dll
> 	371,712 Peachpie.Runtime.dll
> 	 33,256 System.Runtime.InteropServices.RuntimeInformation.dll
> 	 79,208 System.ValueTuple.dll

The total size being 1,555,792 bytes, which is pretty big for something that does nothing more than print Hello World. I understand that Peachpie needs to be as generic as possible, but I'd love to cut things down to the absolute minimum.

2. Is it possible to integrate any required DLL's into "helloworld.exe" so I only need to distribute a single file as opposed to the executable and every accompanying DLL?

3. Is it possible to use PHP extensions with Peachpie? I'm not sure what's already integrated, but assuming I needed to use something like "php_gd2" and it wasn't already integrated, how would I do that?

If it matters, I'm compiling entirely from the command line (no IDE/Visual Studio) using:

> 	peach.exe /target:exe /debug- /optimize+ /out:helloworld.exe helloworld.php

**Comment by jakubmisek** [comment]
1. currently all these `Peachpie.Library.*` dependencies are hardcoded in `peach.exe` at https://github.com/peachpiecompiler/peachpie/blob/d9707549b5da524fa43a1f0ba2107a64aa914b80/src/Compiler/peach/peach.cs#L41 It is possible to get rid of them and specify only required references via `/r:..` parameter.

2. It should be possible to merge all the DLLs into one using `ILMerge` tool.

3. It is not possible to use native PHP extensions, but only safe managed code. Most of the extensions (including `gd2` and `image`) are implemented. See `Peachpie.Library.*` projects, namely `Peachpie.Library.Graphics`. Add a reference to this library to get support for gd2. Still a lot of extensions are missing, so please create an issue if you would need some.

**Comment by Jammmmm** [comment]
Thanks Jakub!

**Comment by jakubmisek** [comment]
I hope it helps. Additionally suggesting to compile all PHP files using `**/*.php` pattern:
`peach.exe /target:exe /debug- /optimize+ /out:helloworld.exe **/*.php`

The same can be achieved using MSBuild file https://github.com/peachpiecompiler/peachpie/wiki/msbuild if you'd like to (it automatically downloads compiler and you can maintain all the properties in a declarative way).
