### ISSUE TITLE
Problem with aliases stored in array indexed by variable

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#95]
See the following test case:
```php
<?php
function test() {
  $arr = [ true ];
  $i = 0;

  $first_ref =& $arr[$i];
  $first = $arr[$i];
  $arr[$i] = false;
  
  echo (int)$first_ref ." ";
  echo (int)$first ."\n";
  print_r($arr);
}
test();
```
The output of PHP starts with ```0 1``` whereas Peachpie produces ```0 0```. The problem is that the alias is not dereferenced (```PhpValue.GetValue()```) during ```$first = $arr[$i]```. If we replace all the usages of ```$i``` by ```0```, the dereferencing is added, though and the program correctly outputs ```0 1```.

**Comment by jakubmisek** [comment]
fixed in https://github.com/peachpiecompiler/peachpie/commit/082b4a1d9066c10e042bde6028fd20fd3e05aa8a
