### ISSUE TITLE
Warnings regarding "memory_limit" and "display_startup_errors"

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#953]
The following warnings are shown: 

```
PHP (Warning): Value 'Set' of argument 'memory_limit' is not supported
PHP: Warning: Value 'Set' of argument 'memory_limit' is not supported
```

```
PHP (Warning): Configuration option 'display_startup_errors' is not supported
PHP: Warning: Configuration option 'display_startup_errors' is not supported
```

**Comment by jakubmisek** [comment]
they are both expected since on .NET we can't change both the memory limit and startup errors

**Comment by menturion** [comment]
Maybe this kind of warnings should be supptessed then.

**Comment by jakubmisek** [comment]
Well, the warning is shown to point out the implementation behaves differently on PHP and on .NET. Anyways they won't be supported since it does not make much sense, so they might be suppressed.
