### ISSUE TITLE
setcookie $expires NotImplementedException

### ISSUE THREAD

**Issue by brnanders** [peachpiecompiler/peachpie#955]
PHP setcookie fails when using the $expires parameter as a number.  The function time() and a number returns NotImplementedException with either System.Int64 or Pchp.Core.PhpNumber.  setcookie succeeds when the parameter is ignored.

`setcookie("name", "value", time() + 1000);`

System.NotImplementedException
  HResult=0x80004001
  Message=System.Int64
  Source=Peachpie.Runtime
  StackTrace:
   at Pchp.Core.Dynamic.ConvertExpression.BindAsArray(Expression expr, Type target)

System.NotImplementedException
  HResult=0x80004001
  Message=Pchp.Core.PhpNumber
  Source=Peachpie.Runtime
  StackTrace:
   at Pchp.Core.Dynamic.ConvertExpression.BindAsArray(Expression expr, Type target)

**Comment by jakubmisek** [comment]
I see. The compiler chooses a wrong `setcookie` overload.

Thanks!
