### ISSUE TITLE
PHP ArrayObject internal storage is null

### ISSUE THREAD

**Issue by brnanders** [peachpiecompiler/peachpie#963]
When instantiating an object that extends ArrayObject the internal storage seems to be null.  When setting a key/value (integer or string) on the object, a null error is thrown.

```php
class Obj extends ArrayObject{

}

$obj = new Obj();
$obj['id'] = 'value';
$obj[0] = 250;
```

System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Comment by jakubmisek** [comment]
Cannot repro the issue, isn't there anything else? May I ask for the exception stack trace?

thank you

**Comment by brnanders** [comment]
I'll set up more tests and respond in a bit, this comes from an abstract base class.  When I do var_dump on the extended object it returns these 4 properties:

["_underlayingArray":"ArrayObject":private]=> NULL
["_underlayingObject":"ArrayObject":private]=> NULL
["_flags":"ArrayObject":private]=> int(0)
["UnderlayingValue":"ArrayObject":private]=> NULL

Thanks

**Comment by jakubmisek** [comment]
I see! It might happen in extended object if you override `__construct` and do not call `parent::__construct()`:
```php
class Obj extends ArrayObject{
  function __construct() {} // not calling parent::__construct
}
```

**Comment by brnanders** [comment]
Yes, that is the issue.  That's a simple fix for me, is that something that should be fixed in PeachPie?

Thanks for the quick responses!

**Comment by jakubmisek** [comment]
yes, will be fixed in peachpie library as well!

**Comment by brnanders** [comment]
I also get an exception when using the ArrayObject in a foreach loop:

System.NotImplementedException
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=Peachpie.Library
  StackTrace:
   at Pchp.Library.Spl.ArrayObject.Pchp.Core.IPhpEnumerable.GetForeachEnumerator(Boolean aliasedValues, RuntimeTypeHandle caller)

Probably should not have used ArrayObjects in the way that I did...

**Comment by brnanders** [comment]
`$keys = [];
foreach ($obj as $key => $value){
      $keys[] = $key;
}`

**Comment by jakubmisek** [comment]
seems `foreach` on ArrayObject is not implemented yet
