### ISSUE TITLE
[QUESTION] Example of a published ASP.NET Core Web App 

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#964]
Hi, 

Currently, I'm trying to publish a net5.0 Web App to a Jelastic (https://jelastic.com/, https://docs.jelastic.com/net-core/) .Net environment.

In order to test different publishing options I started with the simple "ASP.NET Core Web App" template created by the PeachPie VS extension. 

Result: The app (net5.0, framework dependent, linux-x64...) starts w/o issues, listening on port 5000. No issues shown in the logs. However, a simple request isn't processed correctly resulting in a 404 error. 

Is there any published package of a simple "ASP.NET Core Web" App available (.e.g. self-contained, targeting PIDs "linux-x64/-arm") in any repo that should work out of the box. I searched a lot but didn't find any (PeachPie) example.

**Comment by jakubmisek** [comment]
There is our simplest web app - https://github.com/iolevel/peachpie-samples/tree/master/web-application . 

`netcoreapp3.1` can be safely changed to `net5.0` there.

Have you tried requesting `/index.php` directly, or can you provide your sample repo if we can find what's wrong

**Comment by menturion** [comment]
Right, I already browsed through all the samples and repos. This web app example (https://github.com/iolevel/peachpie-samples/tree/master/web-application) seems to be almost identical to the "ASP.NET Core Web App" template net5.0 app. 

I was looking for a pre-published example to sort out what might be wrong or to identify the missing link. 

> 
> Have you tried requesting `/index.php` directly, or can you provide your sample repo if we can find what's wrong

Just tested. Same 404 issue.

**Comment by jakubmisek** [comment]
I guess it's working on localhost.

The way the request pipeline finds the "index.php" is by looking into `app.deps.json` to find dependencies with your compiled PHP scripts.

So I'd just check the reference to the "website" assembly (might be a different name in your solution) is there, and the actual DLL is there as well.

**Comment by menturion** [comment]
> 
> 
> I guess it's working on localhost.

Right, on locally everything works fine.

**Comment by jakubmisek** [comment]
If you're using something like `<PublishTrimmed>` property, it might actually remove the compiled PHP scripts from the assembly since they are not directly referenced anywhere in the code.

**Comment by menturion** [comment]
I haven't used this property.

**Comment by menturion** [comment]
CONT'D

I now noticed that the published app does't write data to the app's cache folder locally (-> localhost). 

For instance, according to the sample web app (https://github.com/iolevel/peachpie-samples/tree/master/web-application) the condition in `Program.cs` line 78 (see https://github.com/iolevel/peachpie-samples/blob/c03363b9062086c79fb4127ac11341c5be082cae/web-application/app/Program.cs#L78) is true due to the folder `../website` exists. 

In case of the published web app the folder structure changed so that the above mentioned condition is false (because folder `../website` does not exist) and line 83 (see https://github.com/iolevel/peachpie-samples/blob/c03363b9062086c79fb4127ac11341c5be082cae/web-application/app/Program.cs#L83) should be executed, returning the root directory of the published app instead. 

While debugging, the ASP:NET (net5.0) web app correctly writes cache data into the corresponding folders whereas the published app doesn't. 

Is the `Directory.GetCurrentDirectory()` statement in line 83 still valid for net5.0 and returns the root directory where the published app is located and where the folders of the app has been copied to?
