### ISSUE TITLE
Comprehensive fix of misspellings/typos

### ISSUE THREAD

**Issue by JosefPihrt** [peachpiecompiler/peachpie#966]
Hi,

I would like to contribute with a comprehensive fix of misspellings/typos in this project.

I developed tools specially for this purpose: [Roslynator](https://www.nuget.org/packages/Roslynator.CommandLine) (for code files), [Orang](https://www.nuget.org/packages/Orang.DotNet.Cli) (for text files), [Wordb](https://github.com/josefpihrt/wordb) (wordlists)

I can fix following parts of the solution:
* Non-code files (Markdown and similar text files)
* Code files (C# files)
  * Comments
  * Symbols (type/member names)
    * Symbols that can be renamed without causing a breaking change
    * Symbols that have been shipped as a part of public API/library

### Questions
* Are you interested?
* Should US or British (or both) English be preferred?
* Which parts mentioned above should be included?
* Which projects are part of public API/library? (This question is relevant if the symbols should be spellchecked)
  * Should publicly visible symbols be spellchecked anyway but in the separate PR?

**Comment by jakubmisek** [comment]
advertising -> closing
