### ISSUE TITLE
Unable to upgrade to 1.0.6 in UWP project due to Mono.Posix

### ISSUE THREAD

**Issue by siggi90** [peachpiecompiler/peachpie#967]
When trying to upgrade the NuGet package in my UWP project i get the following error:

Failed to add reference. The package 'Mono.Posix.NETStandard' tried to add a framework reference to 'Mono.Posix' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.

**Comment by jakubmisek** [comment]
the workaround is to add package reference to "Mono.Posix"

**Comment by jakubmisek** [comment]
How do you upgrade?

The upgrade process means changing the version number in the project file header. The rest of the packages remain the same. There were no changes in the referenced packages neither.

**Comment by siggi90** [comment]
I upgrade by updating the nugets then by changing the number in the msbuild file, (possibly i'm doing it the wrong way?) Although it worked when i updated both nugets at the same time, PeachPie.Library and PeachPie.Runtime. So i guess that was the culprit.
