### ISSUE TITLE
.NET core 2.0 and .NET Standard 2.0  support

### ISSUE THREAD

**Issue by ktngoykalolo** [peachpiecompiler/peachpie#97]
Hello,
this is a great initiative, bringing PHP and dotnet communities together! keep up the good work!
is there any plan to bring support for .net standard and dotnet core version 2.0 ?

**Comment by jakubmisek** [comment]
Thanks! .net core 2.0 and netstandard 2.0 are fully supported already.

**Comment by bfistein** [comment]
See [this post](https://www.peachpie.io/2017/11/php-netstandard-2-0.html) for more information.
