### ISSUE TITLE
Problem installing PeachPie 

### ISSUE THREAD

**Issue by fabestine1** [peachpiecompiler/peachpie#971]
I have tried serval ways to install PeachPie but no success. I have tried these ways: I can't find the extension in the Visual Studio marketplace. I browsed to PeachPie Official site to follow getting started. I used the command line to download it. I got the message it was successfully installed. I am using visual studio 2019. If I try to create a project I won't see PHP as one of the languages neither will I see anything related to Peachpie. I then installed Visual Studio 2021 preview. I also can't find the extension in the Marketplace. I installed it through the command line. I can see PHP as one of the installed languages, I can also see PeachPie ClassLibrary but when I create a project the PHP files won't load. It shows Not Compatible. I have also tried to install PeachPie Extension directly on my system I got an error:- This extension is not installable on any currently installed product. When I opened the error log, below is what I saw.

7/30/2021 12:11:08 PM - Microsoft VSIX Installer
7/30/2021 12:11:08 PM - -------------------------------------------
7/30/2021 12:11:08 PM - vsixinstaller.exe version:
7/30/2021 12:11:08 PM - 17.0.2145-preview2
7/30/2021 12:11:08 PM - -------------------------------------------
7/30/2021 12:11:08 PM - Command line parameters:
7/30/2021 12:11:08 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ifion\Desktop\Peachpie.VisualStudio.Extension.vsix
7/30/2021 12:11:08 PM - -------------------------------------------
7/30/2021 12:11:08 PM - Microsoft VSIX Installer
7/30/2021 12:11:08 PM - -------------------------------------------
7/30/2021 12:11:09 PM - Initializing Install...
7/30/2021 12:11:09 PM - Extension Details...
7/30/2021 12:11:09 PM - Identifier : iolevel.peachpie-vs
7/30/2021 12:11:09 PM - Name : PeachPie Visual Studio Extension
7/30/2021 12:11:09 PM - Author : iolevel
7/30/2021 12:11:09 PM - Version : 1.0.8
7/30/2021 12:11:09 PM - Description : PeachPie is the PHP language compiler for .NET and .NET Core. It allows for building, integrating, running and debugging of legacy PHP code base to .NET platform. PeachPie outputs regular .NET assemblies not relying on the native PHP runtime.

This extension provides project templates and other development tools for the PeachPie platform.
7/30/2021 12:11:09 PM - Locale : en-US
7/30/2021 12:11:09 PM - MoreInfoURL :
7/30/2021 12:11:09 PM - InstalledByMSI : False
7/30/2021 12:11:09 PM - SupportedFrameworkVersionRange : [4.5,)
7/30/2021 12:11:09 PM -
7/30/2021 12:11:09 PM - SignatureState : Unsigned
7/30/2021 12:11:09 PM - Supported Products :
7/30/2021 12:11:09 PM - Microsoft.VisualStudio.Community
7/30/2021 12:11:09 PM - Version : [15.0,18.0)
7/30/2021 12:11:09 PM - ProductArchitecture : notSpecified
7/30/2021 12:11:09 PM -
7/30/2021 12:11:09 PM - References :
7/30/2021 12:11:09 PM - Prerequisites :
7/30/2021 12:11:09 PM - -------------------------------------------------------
7/30/2021 12:11:09 PM - Identifier : Microsoft.VisualStudio.Component.CoreEditor
7/30/2021 12:11:09 PM - Name : Visual Studio core editor
7/30/2021 12:11:09 PM - Version : [15.0,18.0)
7/30/2021 12:11:09 PM -
7/30/2021 12:11:10 PM - Signature Details...
7/30/2021 12:11:10 PM - Extension is not signed.
7/30/2021 12:11:10 PM -
7/30/2021 12:11:10 PM - Searching for applicable products...
7/30/2021 12:11:10 PM - Found installed product - Global Location
7/30/2021 12:11:10 PM - Found installed product - Visual Studio Community 2022 Preview
7/30/2021 12:11:10 PM - Found installed product - Visual Studio Community 2019
7/30/2021 12:11:10 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable1& skuData) at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable1& skuData)
at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
at VSIXInstaller.App.Initialize()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by jakubmisek** [comment]
thank you for reporting the issue!

fixed in 1.0.10 at https://marketplace.visualstudio.com/items?itemName=iolevel.peachpie-vs
