### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by Firensis** [peachpiecompiler/peachpie#977]
Hello,
I checked PeachPie using a static analyzer and found something interesting. I described the results of the check (fragments that seemed to be the most interesting) in the article: [Is PHP compilable?! PVS-Studio searches for errors in PeachPie](https://pvs-studio.com/en/blog/posts/csharp/0855/). Hopefully, this article will help you make the code a bit better. :)

**Comment by jakubmisek** [comment]
omg

**Comment by jakubmisek** [comment]
@Firensis thank you for the detailed summary; we have fixed the issues pointed in the article. If you'd have more, feel free to let us know!

**Comment by Firensis** [comment]
@jakubmisek, the article only reviews a part of warnings the analyzer issued. To see the other ones, follow the [link](https://pvs-studio.com/en/pvs-studio/download/) and download the analyzer's trial version. This way you will be able to study the complete report :)
