### ISSUE TITLE
Help with themes and/or plugins

### ISSUE THREAD

**Issue by hendi330** [peachpiecompiler/peachpie#987]
Hello, 
I am new to peachpie and I have problems with plugins and maybe with themes too. 
I want to add a custom theme from my already (only on wp ) running website. The theme has a parent and needs the woocommerece and elementor plugin. 
First I downloaded the plugins via dashboard. -> but errors (php code in header). 
Then I tried it with compiling. But didnt work either. 
(well it worked with like 3-4 plugins at a time, then i tried to activate theme -> error
then I started with theme and activated some plugins one at a time -> error )

I already discovered that I have to compile them together so that they work (-> first mistake was to compile each theme one at a time)
But yeah I tried almost everything. (copy past in wp-content, download from dashboard, download and compile each one at a time, compile everything together).

This is my folder structure:
![image](https://user-images.githubusercontent.com/63050066/140339991-565a0eae-119b-4719-8747-516aba7af983.png)
This is the content of "themes" -folder
![image](https://user-images.githubusercontent.com/63050066/140339175-8a106cf2-9818-4bdd-b4ee-9fe3c51cf913.png)
This is the content of theme.msbuildproj:
![image](https://user-images.githubusercontent.com/63050066/140339104-6c0667a0-6679-4f3c-b4b1-a5b15a079ce4.png)

After I created the msbuildproj files, I ran the dotnet build command. After that dotnet add reference and then dotnet restore. 
But all the time I either receive code in my header or a blank page. After a lot of searching I came to the conclusion that I am basically to dumb to compile, right? 
So can you give me some tips? :)

Thanks in advance
Hendrik :)

**Comment by hendi330** [comment]
okay found out how, 
if someone is as stupid as I am, here is what i have done:
first of all I put both (parent and child) theme in one folder (called "example"). 
On the same level as the folder "example" I made the msbuildproj file. 
thats the file: 
![image](https://user-images.githubusercontent.com/63050066/140536543-73d0e140-59f6-435b-8d12-587b259e5e37.png)

-> dotnet build, dotnet add reference and dotnet restore  
there were a lot of errors after dotnet build (error php 4044). 
Each error was excluded like so :
![image](https://user-images.githubusercontent.com/63050066/140536150-b483c379-a4fb-432e-83c1-7a8bd7ca9a2a.png)
(my first bug fix attempt was to use eval(); but that was like putting pertrol to a fire.)
I kinda did the same for plugins.msbuildproj (but only one plugin at a time).

**Comment by tharlab** [comment]
> okay found out how, if someone is as stupid as I am, here is what i have done: first of all I put both (parent and child) theme in one folder (called "example"). On the same level as the folder "example" I made the msbuildproj file. thats the file: ![image](https://user-images.githubusercontent.com/63050066/140536543-73d0e140-59f6-435b-8d12-587b259e5e37.png)
> 
> -> dotnet build, dotnet add reference and dotnet restore there were a lot of errors after dotnet build (error php 4044). Each error was excluded like so : ![image](https://user-images.githubusercontent.com/63050066/140536150-b483c379-a4fb-432e-83c1-7a8bd7ca9a2a.png) (my first bug fix attempt was to use eval(); but that was like putting pertrol to a fire.) I kinda did the same for plugins.msbuildproj (but only one plugin at a time).

so the woocommerce & elementor plugin work well? with no issue?
